spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:Fka43N/e0Rxc2q8+pxmh9E9BOD5ct/XsqQsgvj3I8GQWHeBGfw==,iv:92jDxhe/vhzwxGGthmRll1LjyFM5nZa+VwcydLE5z0E=,tag:6ocuwVIEa/ddNPY2W8AGUQ==,type:str]
        username: ENC[AES256_GCM,data:pLZBPZT4,iv:/Cc2srzIBRCBuN6onOf+ruXB9uOCGE5cDedYIC4QMbM=,tag:mSKls2B9TSClEqOje2tQrA==,type:str]
        password: ENC[AES256_GCM,data:UCoTF7YwwvSojPw=,iv:6h2kwZteOkBZi9gkb8Md68NFvmTgY0H6HUca4jXHwN4=,tag:MIFiQKD5Wk46YM2btRvImA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:sVX9f3/5ypag/YcXMhSXCTlRLS8=,iv:FhwFOlEGdaV9SjRIWY2zclVz9ncfmN0NP6DZR8BcFl4=,tag:hv+Y33rWmTZAdlGRJuFkyA==,type:str]
            password: ENC[AES256_GCM,data:sxvKWmx3STjGvQI=,iv:GfN4iI8vVffyF//6ElU5MwxpReaHDRwU/ehrPwA4sBk=,tag:t21etq3i2QdBnKxugMvDtQ==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:LxkjevI=,iv:sgK3RP5ZYZ3x7Shqz2U5pA51pyDrDn7a6iG2Lc+WG3U=,tag:RjrQtW4UnOG+V1bcDZanOw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:tED/dbd6pIfNKOee1rSON3HMbot46Oh06paqudBm,iv:nDmGUo4w31nFnI+9oPMAv9BYJKyagNmhhxlS1Fh+X3E=,tag:O0AbwbAbdEauNSUtL6KXow==,type:str]
        cookie: ENC[AES256_GCM,data:O2uRbNv+IqAI8ebz7yGu5A==,iv:qrwgst224orjByE5Nj8euJAO4Do1JYp73jIGo78AUnI=,tag:8VZOoBh9d66psSIqf5He4Q==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:etTuotVjrzm0FkQpkGU23ieZ5lm8Dl6XJaAoJfPargxlPuiR9yh2t3mbXsx9j15kkk5FXfFUwcY=,iv:L8MeARI87onaDqiGDJ1miDl/CJSIKpwsGq32QRiL1MY=,tag:r2mJLBQ6zCpEQ9XSDjxa8g==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:VxOESZBgxd1FugXAbrlSsytT276r1nJhTSaT9/QvRmS/b+qron5tGnM3hXDXk6AKaFo6Pe5a7L1B,iv:E8cpTL8IMzn8f96MMh5fEdBvfVnVX8bSwVQHgeSQ4Hk=,tag:eZqJDrlk4+hfDGYsm62aDw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:d84zXDORvgH4X0BNVh3LD29B3GrSjugYMJJ1v6WmjfNAT8IKKNOD8Kdd7+Mx/BjP3Osh0WqYFlk=,iv:fnH2oqqFAS00DH6lg1D/STbwc7pWgjg8cilovAs/+IY=,tag:D8Q2cxdvguLqaMWUqoOIOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-27T08:38:17Z"
    mac: ENC[AES256_GCM,data:5bKmgGksIfN0QSUh/WQdSuPsIXHCaYvmk96sVJLGz5j1k2iCvinW6SflAIiNWpXyBc5vJn1X/l5fO1MdAWIWqRB6s9ZjAzI0MFGKvF7kdnfOYCMN1QzxZGGYVhlJX/1xtGTj18G8OWBctfB2I+z1EGsYYcnw1VIYIgf8vcequZA=,iv:yAAz7k9bEWzDITqPElHv/OtXVyfQnp21ukwrcXKV4PY=,tag:TROYCpkJYyKU23BsXFfXfA==,type:str]
    pgp:
        - created_at: "2025-04-27T08:38:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA2BCINmX014Pl54aKGfNreKskA5jTsUoofI5VgEfEL0VD
            oe6raVLrUp849+0xsgZFkkne3AMl1WY9UxS7NYdPTwyX9edBa2fyWVp3iuxUImZB
            4zlj/Zw9m96mpn31ZGbm+WcLKBSkz4FBpviNf4oifyxgeLyttUSEP2xkSolosjv1
            P0wtOdQ2bR5WJfmSo8ud4OMbiSkLMM5y9Y0jO7BEP3jEolg61fINplxuPAX66IIn
            /0MHQXIvC6r042AayyF5oveWYRWAAE29fgTfATWr0RPp2Ws6UtFakE+X97G9oqjz
            P4L0CgZ1W1lhxcNXb+TBviU7iHxvNXK9JM3tgSqrb6i7jd3n25FGbYaceQEIre1i
            QSBFQJwI3KtuaZ2EHjLoyPg+AYKFMVAQeHq9VSVO9Hh6lgHLIq3SdwaeK16rixId
            KStBeuEcOuKcGgZ1ixcAvlr7lVBA9w7gue50OJ1gg1V/1lNcn5qBarURGmICJEGl
            VgIT/TUr9xGzc2u8EJKo5nlDFtrTRLvO1wIcGcVkFEl5Czc/Y1KWqIv3H5ojMe75
            9v3PLVMmq6ZjxRMX+Obxy/3LW4ENF5ce6AJI8VpypYTyYDGqjD7s8vifmoDh1Iz0
            I64b/uXLjW+QXrhWsX3H+zmu00u34wqRlmj+7eoWLSNjs8ZyCIjKyGvqArFri1HS
            XgFtH4YG9JxwF2l2aYWO0dteDUginhivtG/N27DZwFQCs1+fHPeXN7xxmOqfR6vN
            9Mc05YnWL23ctqusXsbOEZVS3OOg2UIWj4DudEf/ZDbSC5WmG/xeZfJx9kx/zjQ=
            =76nO
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
