server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:jw+zYJMIjRb7ZJh1r5vaAWV7Fw==,iv:GLxKyxYIPMeLGVchx3+dSzkeYk1/yBzIXt6E+smXDsE=,tag:fVQWIDuiFfNOX885ykUQyg==,type:str]
        key-store-password: ENC[AES256_GCM,data:P9WjmVdNHX2Poxc=,iv:Z/DE5Dx/GSgOWfeM3LXwjufGeXyD0TZa3Q8o6yXLyXQ=,tag:WiFgRHtiPG+lLfabtDADpg==,type:str]
        key-store-type: ENC[AES256_GCM,data:vnyKQ3EW,iv:DjvB1dW42hDZOEQz0aD2O9hPps5hZ1TmWQJlD3sVDss=,tag:P99ERo5V3L75Xqs5m2lC1A==,type:str]
        key-alias: ENC[AES256_GCM,data:KsOBUYcOhSYJ6A==,iv:pVaSAHoe1TIo0G3yKakjzBLKZRcRjuEqGZHEf1owhEk=,tag:Yu8D5BSwV8dgaYD50RNYYw==,type:str]
spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/h2
    datasource:
        driver-class-name: org.h2.Driver
        url: ENC[AES256_GCM,data:TbMIcTkmESzcHzsnvgeYEg==,iv:xXz4ICK9PwQklPcCKwyh0W9JsM9507fu0Dy22zxrQ1c=,tag:8R8tIPMg8mBQvx4S9S62Jw==,type:str]
        username: ENC[AES256_GCM,data:0pK9G6N7,iv:j3wq/TFcGxDdZkhPlbW7Qp4ztYK0FuCUAozZmUKRS20=,tag:xurf+TUKVUklK21dOcI5pQ==,type:str]
        password: ENC[AES256_GCM,data:Za5AFkE/S93pslI=,iv:zeFXUsHG+dkt3jLNhhuhIPi3m5Ei+F+fnBToUpFoZ8A=,tag:sWLUxGpPt2SbuMhoxhAOmg==,type:str]
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:x0j0XA3WehTE89DRKEA4iUWnAQwK,iv:D6XVsJU7YjqWM1+TjBpeNx64sfyWfi0ppqtXcengGVE=,tag:QoA9+XpDZfI9mVuNobpBxA==,type:str]
            password: ENC[AES256_GCM,data:RR85JHNaJYXygM4=,iv:IdFAx+qxdZdbk2HdEftTfUzZyff+vXV3kP/xi8kvSCg=,tag:5c3NqOSt7Bi6rkEYr9Nsxg==,type:str]
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:we+MotI=,iv:owdaiFyiy7o22OTB0NHAmgX0LqERug1ZpnXWSgQsKs4=,tag:OV1tTb8vPI/E2QxmnHwOkw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:15Fnaac6UrfmAi8+2sEPSL6cT3ImYXnYwz9bSZxe,iv:Uqoh7py8Hd+UodIVYL6ioQ5lM+9lSihc/nkMjydOBSU=,tag:R7wnj723kLev9qtMYCre+g==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:9my7kTFMdf9iW+nVH4bdfEQbmCxP,iv:D+O07R40Vs8/2Ruz+2/M1Ue3fkSohW1Gq+k3rHVj20U=,tag:/mzPz3zxsQGmcG7cr9Ua1A==,type:str]
        cookie: ENC[AES256_GCM,data:7Mf4M6sLR6MN,iv:0O9gpVBXxLLHc9dGr900t47xFw2HKGnwrG1bOpuqBFE=,tag:A1EpHryDpa9e+azlGOHynA==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:MMNo60wIztOotG3KUgZrU+nm+a/KLyKdjQSvjtsFv6X+mP2RMP/tZDniWIdzdh6qWXGGzhyz,iv:2flqidGE+Ew/2atSwVjEyJh5nSDGK5H5Z7Y4TC1Huuc=,tag:enoiGzbsKcoATZMJyFDkKw==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:4NhFna+m07LV6K8RLjSF9QvFeboKVLmHzJpjHF53K527iX2K+O6VxhtBqyh/kgNmnzl4rPHKtQ==,iv:MPZcn7v7BBj6Zn1VjdbjTaUawa90Th+8abn1o//+2PM=,tag:vISPJkOETEOktJoVGmyfXQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:uhcTKYLSzedv1UzssruXd/eqneO8kWxuBFeYqwWCGxolr04GWIir5bBJXtytPZCdw3Rf2UoD,iv:0QaxIY5Yq606yhLVxT9H5lhe11c1jzcJWbLHJnisEaw=,tag:P/QMqcopAcDFIUPowfwTHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T14:01:10Z"
    mac: ENC[AES256_GCM,data:AbYrAkwqfFUIkxrpenYfEU66QXuM0OaVyDAhmrfOxOnkC9xDTtFPL0b79uNLk2zQPwM9y4eseqcjGEy6kgHvi9h6MPMLxu0LOaQtanI3xfcJnXBPmtFqltu9A3rjiWex0FST1YJ16uZ2OVBXq24X3oo31adIiW5IJzfKbr7xcjc=,iv:/UlvPwDEaHwSelhbRtGMtQvilIpklqigbUfAW7D/w1I=,tag:nt8oDsX85oN2eyy1xpcYlQ==,type:str]
    pgp:
        - created_at: "2025-05-09T14:01:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAhm7z441AwHwkrTs6m0WMQs+bP9Hp3iiL2oMvNLS+ivAX
            TXBBz46bTPhFaSPjAOCkNQ6PqZvvpBpb1Np5tKtPKFUv4TGR0oW6pl6aOAD7HwFW
            wAHvW/6txKfkPP+/J3CDc5biDx+ysi6txrD1/JtawD7RQZ81LKXDlMEQBcfzm2JP
            kZAex+ZWgjv/mzAt0kihm1HWInr2ri32WRIhmSdkJxBTwqo53CRHwIvXHnRI2wzY
            u1ngOh4rTDAJkQOQBSRqOqf/EiCucG6+z6/L1GZiCVClnIsXziVbLMBM+K14C/+8
            7ivpGPcXscPw8MQIWQAblJcW14IHivszz+FD24RIJjkr0cprad1i6C+ElWNN8AzH
            vdHG88LJ406dEkDlVms/yHnDoKXuJnmGUSOvtGFUUkPl3lkawJ9h+qppIbOi5fjO
            1iCxZSaRFY0RCMY6yE5Fx3EuQ1InG/2PEP4DXpswNIpufcUPJEL9o6D7ahnvpQI5
            rCLYGBicASy7HJ4a3F+r+KO9jIroPSQ4M/oQf7NlSm7MhQwcOwNzjHxtIXi7ldcD
            f4hEMADpreSDrXRsuwic/T5nj5mFSiY7AYPRVeeDHFvQS/lr7GYKb6pwsfP0IVtJ
            BojoTNmd+yrvKilvhmbDlLZf68GhZ+0zzCkffs1LHYpVCad+NsuO5JCnZDBT3f/S
            XAGzM83I08d8rFiKUrTm1+Opq64baC0Qjj85E7SNyXBoAoagj06qYWdlz6UDX6aZ
            6KAq13M0qOT35SYQbOmz+QcOonNaLkaOu69vOxUh9Nd0KybUWULMh7rwZ13F
            =0LkI
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
