spring:
    application:
        name: Replay
    profiles:
        active: local
    jackson:
        serialization:
            write-dates-as-timestamps: false
    sql:
        init:
            mode: always
            schema-locations:
                - classpath:db/migration/postgresql/V1__create_table.sql
                - classpath:db/migration/postgresql/V2__create_view.sql
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
jwt:
    secret: ENC[AES256_GCM,data:nU7rSQvzWTZjgVaatxIvIC3C8vwzQ8Z7Is8wQsoSDJX2XCQJ1+k4/WeuK/8=,iv:wIzJ5giiQWr3UwgQSyzaVFI0heuYOEYMSSPAx8+AT10=,tag:j5AmA0YNu5P09cIY21VHYA==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:ecOZ,iv:ya0PVWJSjRGlcBeRCrCzyA22BO6rbZ7UbKiLeyhPgfI=,tag:EHUKy0i1J/E778vZGuF6Kw==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:qEg=,iv:DF3NJ/dEWQ4qIr0wals8veZAGY+ujxYmNcKzdZiox+Y=,tag:X5jwCjTBdY6SeLWey0RXjA==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:0wcRV2jxy7DQdZQ8/IuWWQhUDOU=,iv:KCVOCns+3CV9Mp5ZTY8hAcNwQ60idHk384gRMyu6oi4=,tag:pFAlZ7SoO7U8Tr7a+tGikA==,type:str]
        client-secret: ENC[AES256_GCM,data:l+EWAmOi0ABmSA==,iv:BiBUPPh3U/uekkom9tyWTfwy/deeuns4cuGIKPQGJM4=,tag:fDsaDl9FtalF+pO3ril2DA==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:s2XetH38NfI67Eftio9gNCW1Q4+St0/dYx9X8il8oJbk7NXXpXnQrwlxmXShpHWjwH+sKXHBlYziZK518jnrEyI5+lN17Jpg,iv:PS8UiIc/TGwMYkv0xc2Bn0Rb6rS5sIfJGejHiMStvqE=,tag:7JRd8JFvFRre/Nh/kZtcCA==,type:str]
        client-secret: ENC[AES256_GCM,data:zjuO8KSsz/lKp3ZNEbOR3M5IoIvwY0bl4sd+5bRH0edgm+g=,iv:x+fjwFNlGknTcpc5L9yhoHmi6BdwKkdgXFOp5OtwOyI=,tag:gHXSxWxImiPLibTe4xtFyw==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:cn4xSjRLpeLulmAalVQcO2h6NzdfJF/7eRx4JpAaMsU=,iv:Jvi+6TRKjiQaChjCDz+1sED6x7g+IcLZxzncm5MQ4wE=,tag:EQYF98O6MbhrKKcCgf7qJA==,type:str]
        client-secret: ENC[AES256_GCM,data:K4TCi5SaAEw2IYZT0KGOsnwKqHJ+88Gybs//YH5PKjo=,iv:esxSwIk0pI3sfHVvpy+NCYu27m3toirFwclQYO2ekzc=,tag:URyis06r1TWnslfvplSvfw==,type:str]
s3:
    bucket: replay
    endpoint: ENC[AES256_GCM,data:MhUz6DKpovtoMvGiieRyo327wqNQCwTJRAB/02CGkJJG,iv:FIp10ccZCDE2TsbuuGTkyaL8L9p3iX2cM/UA3MeZ5vA=,tag:3n8fTmW7BdtqYO2djERPmQ==,type:str]
    access-key: ENC[AES256_GCM,data:IbyMkeH3OuMbUuk3zKQ3Y5ZLjiQ=,iv:jXVa8zWFuYYJXAKS/ZfufqoAKRdWry7M7mFkWOIEjFc=,tag:/xw9ZfEOjafDz3fvghTLcA==,type:str]
    secret-key: ENC[AES256_GCM,data:AyO4pQrJvgkcSIfKXqu5YZWkuPsViAMEAFWvADUWlUmPQGk/m7Im3A==,iv:vuI1ImgwRPW7eL/NL9asUKxcPKHf9dJBcH1eclMdm3Y=,tag:yBFQ3VF4tRC1fHQSYV4KxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-03T11:58:52Z"
    mac: ENC[AES256_GCM,data:dRDDVAKgrWO8m59Ov1aWcL8rjuCEzdrbhvPUiexEtPFMQ//WHWEK11PzHKdO//3jseZxVePNx8VYgjJPijISXuqRCDAufRKfEOHAgWYODrAkx6t7Ik5OIZhh++lSkCOhGnsin3ClLG61ROj9hNEZBkXmHEC3AOI7MbxMjkKyApo=,iv:NeBdxRpzfUM2W2j5TwF5J/LndW74RpcUCNkUIjwNWHc=,tag:7krHfEOKrlfXbNVu0toNCw==,type:str]
    pgp:
        - created_at: "2025-07-03T11:58:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//d5+/Et7GfzrQ2pivb1bUQAMXcvDKlzBjW8ff0oFF88bZ
            ObrpkluqQDsN28XRGCVt5TSfJ6os60XE7Ro9TgEfAQICRS2ckG5EytT+PZvxsVwy
            iaIWFtRCXHGYMiDAAzjPI7W30HkujpWbj193ypuLsg62pNhha5HlIwd6ASOqOjei
            gMoxRnPKEyYf5abPjTgGNeUpoeH5VWFEwbuwa9fc1SfL/zlNcunlvWa8T+Uad5ib
            oTV/sryPcORRDj5TZmUyUCOUM2a2gyirFj/mLhJLIM+kPnGPaPIT/9QTEEIcyExu
            Rt4DO7hW3YyLqeAl6wjpXULSz5eqiNWJsROMKfQWhLtdsHbHBE8zW+/MFow2KSrN
            zOfWj4OsiNMjs6k2u/xHxNa1++6Zpwgew8Qz/s/HlEjz+R3L/M6hwPm4Dum0V9jE
            eKtz7mNHLWQwamRzXOOEIBxCw0qWpZRqbprIGXQgIPtl5lhpRmeq3evsnLx9yK6W
            yxWn/JehD94fyV8IydR0guqQozErowdwdDgK3vCYh2a/RpEILixkelybKxBMoRZ8
            zB8mE7Pn1jFwNyOGwXx5CF5U9NcuQq+mRYgX6XxASXFuKLokqPbD6EHhJva4VgKN
            kvr7zN4dcHaIXWA725niQnH+8KWmPkpSPGTs5OG+DRgIIlNJQdOHXNP4iiI+zsPS
            XAFqw0MLCq7ORusrt93ci8fuhz5z0sMIBbyQLzJZyUoVS50dCbrNmcnlR6j1Gxk4
            xQhIRzsp73cMolhBvpbHNUVEHOZJFIhP4Knrh/ePS2TKhvDBA8pVfa1l5GgM
            =OZbW
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
