spring:
    profiles:
        active: local
jwt:
    secret: ENC[AES256_GCM,data:bmDNLd9TBtpnG4O6ZoWqKwu/sgEMePJsEfZFByDgtlmb0bsYFvvkDfORaoc=,iv:RyBN+j4UMphokwcXWMbtKexMIRKI9s5MxxQ+g73YIKA=,tag:VGiweqbO/FyqnOYgRVQGMw==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:UEsL,iv:UcnZKmrWGr4wBzVo169CgNmSrUVzFp2USgS3H2M1Jwc=,tag:evlNGiE7/DTpAqRPReBL/A==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:uL8=,iv:z78p3cjPNi1PiloHCkWXEealWjlvDsmYv+gIQJILVkE=,tag:48jp2Ky6b6IZB4j68YIYDQ==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:33V45GSnWYfDciT+ybSMGBdz8fU=,iv:0fgZYZEPe0nKBs5gEDpj80WDY+xa5o9VfJYwqWYCLTA=,tag:Eps/4KwtG0GWyx1gjRRzqA==,type:str]
        client-secret: ENC[AES256_GCM,data:nMDddCPnzlGRQw==,iv:tuepbue86FPc7l0cld45+UkHKngxTwYgcp6Man51xaI=,tag:mpLLrvu5iaFowhLGbG7+Sg==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:Nu4Rm7Q6ofUvOadBxmkDQIMx/73qjX2fzq6aFlInLwvVRH98HX4SUSFdznnXEBUlMQMRy+88fGWhXxuZf4iY/YVWJnE1IMnZ,iv:ULyaf4GdhmkT/UMFjTJwRluAbxcIwerFOmKquWSHYc4=,tag:REbstp02kszFgM8J0bKsnA==,type:str]
        client-secret: ENC[AES256_GCM,data:yLYtIlrLjrg8RZR94HosNKeTL7/3r9RbqvLNERrtfKQXmnw=,iv:1KgGOiZ0rD9uyNJVtYrqQjrj/hMF9QTf+336ZwHnVxM=,tag:M8oqxJCi2lPpcHTNWCF5wQ==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:X2eNgmYiRCwzfYciRF6nuB719UycXLPBHeqx1sozPcg=,iv:QrmgnLD4ulk/hMukiDhrgT3FnODtSTRAi7A7Ikjy3XU=,tag:FY/PFsAxqULBixsZzDtvtQ==,type:str]
        client-secret: ENC[AES256_GCM,data:yycFCkTbEo881p3iFx+u5RRGZ4PknXNYbKcaqu03Wqo=,iv:abPpWpsXrqU9rHWtSDQ5oHBrkQxjUxwV+LiOCLoQjx4=,tag:vWvWtEhNDvV2Dur2fN6clg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-29T07:46:28Z"
    mac: ENC[AES256_GCM,data:mYNqLwNpW8EP/xsXX6HO8hHA9Fi5droawETijKkwqjSSYwnCGAcSt5eO+x7BqSC3xCgdSuyrUj4y4hfzVnJPDEyt/Y1CoRfBPRCoIfvOjnsFTXLyI/wMkKeKvN23fKH3yT1FJP2hKEt/r44/2C2pmKxHLlIlONYsDgCmQug74xU=,iv:8z5U7FYzkddHC9wpoqUO2Q5/mEvntJ5D0TGB86A63iI=,tag:vLCEL+N8ioXREmDs1q4UfQ==,type:str]
    pgp:
        - created_at: "2025-04-29T07:46:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//XKJzhb2ALGV0BeWGZB9v8BA6fSiqm2rupB6gOnBVr6C4
            n8RW6dB3rfM9pzSjRSoSNZ/J0DgVtcMIkBk1catQlkzho8h91MEl5yagR/QHmYhd
            Dx1ah9inJEV5gZC8p4Qa9VoJrqh2NtayXW/aOUovqHoRt4sFC6WdctNVzzGkv6DL
            FYCgVIoqx9wAHYL7vn/Vr28X8vwHUALCKH8V2ux+xZjDwTJGYZpIJMscmz1YO4cF
            XI4J+RlMKD48ipO/ctcylsPsUesLqjcDDEhWbP5YHE1LclJDtFq9eSErEzJ4aTsR
            P0XgVrirlCp3ExaRncjDr8nWOS8KRYA07YtDtWzazJZbmFd/OTOSGR1qY8AghlOx
            jnM+wN5X8lU42tAvM8PhA4C6wTa4dZPrubpKjq7HBYFtyMuTHOKOPlzGYOLuF1G7
            MC4vEP3n1CfcwjFcDNhCB/d+Pse/c9xtm0z9UKHn+3RRt6sLp5L4wevXbgjT1vtZ
            TVErfN899hee7DgAfmubV1MXpZoJLbV02OSzJF70KJn9m6HA+z377w2cxAp0w1GT
            QpKkTYLnXYftyISUU3e0IsoWN9ZQk9b/dMriZtdNYV8m8KyXGH8yy97oMbBas9AX
            Q14ILzCA9kVozqPE/S1pIdMfPJWMzcE/VEYRULfAAESI2sQfpkVftGcVo796vJ7U
            aAEJAhDw2crYNPgZj9E7vXnq6PsJwNxx0TgviH+P92o+sv3NF5qOkDtu2hS0m31J
            snQ7kFd5CP7IfIwMRJVbVSMyFSZo5r5P066l68XpMHnYZWtSNo9Dfj8jS79n0AvN
            hL/YChX3eU69
            =Qp5w
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
