spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:MwzCqHoz1XUyzLeajMjg0lrZpIVID8PZxP7AaX260m4ZBJAI0tzSHoPwrQ==,iv:watCEVKRhTFWJSXZf06u9Ln+3xxUHZuYGRULokNo3H0=,tag:rwgNgX+DJaD19mQX8RgU7w==,type:str]
        username: ENC[AES256_GCM,data:dloWBNvH,iv:HlZgG5254SUMpMiIbs3UBD2+cVxEdbDlwPX4s5z5tlw=,tag:+QtgjuMsdYbDE3z6DLyVEw==,type:str]
        password: ENC[AES256_GCM,data:2u1u6aGjTqrjoGY=,iv:O7AXVpvHqB0H7nZhqIibdCvdRhLz9LcrbwyfZk3sgZA=,tag:aK8s3w2FopbVEw+dVmEQEA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:CfBPIn8xd4X8zsnMSfyUfx2R9+M=,iv:1U6Tp5KrxpNnnarTIToutigSnyAAmGuosUmUJg427Vw=,tag:w/bhpipNQsxaPjUQeAAhSw==,type:str]
            password: ENC[AES256_GCM,data:bdgeOP4tUZn16aY=,iv:wS1gtuHE3JAmsCm0WXecEB0eiYYeOj39w6OfK7yR5d4=,tag:uykNofubEfm7gNeEaDZc8w==,type:str]
logging:
    level:
        org.springframework.security: ENC[AES256_GCM,data:+PGMWtk=,iv:1eZg3/PoKRpyazJ31hRa5SbTokWR8C3WD7ziqvwX1fA=,tag:eBTK1xkbF8/GN3NEaxubIA==,type:str]
        org.springframework.security.web: ENC[AES256_GCM,data:xcMdK5s=,iv:xm/UGTv6dWXl2YfOMfOh1hSehXCfmcQWFrj9735wTX8=,tag:s6mWZm29Y8T3ggxFp7gwIA==,type:str]
        org.springframework.security.oauth2: ENC[AES256_GCM,data:eJD65Yo=,iv:3S1xywDJsfmNq1DnyOrRoOyaaosSzd4PDuuj8TLJ/Do=,tag:uUqoq1Wm/sHszPTSPL3Fyg==,type:str]
app:
    domain:
        frontend: ENC[AES256_GCM,data:pQEjoQhKXzIin935ROOf4J3QZQ7LSD7LLg7PkMLx,iv:pcVLQ3hWY5//YJJPlK42m5E4PokIQBa4hvmg7Spr8f0=,tag:aRkn9kIS7EkANt48K+iFwA==,type:str]
        cookie: ENC[AES256_GCM,data:eOtsQk6bi2y4gO5yeMQySA==,iv:75grXSF9khV3ajHnxzU2sm37ilPAf+Q4Tnwtmi28ITI=,tag:FSJyW7ChWm6vv306urhpqg==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:/AN1bf30O0CdMmb4HslXoV1mPa37hF+amCJxn90ZZe4RL1on29qSAFSrh1a3FpBCNrJkxqwWoki6,iv:f4+vMUyh/SLTrKpNvOs1oFeolQqYfTooQpycwANqAQA=,tag:uI7xslDP/ymZkbPSLK9ZTw==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:G8kVhPhJ2pcUb06wt4gOPhwsgJGiOhe62xwVODuzhdmivjkQU+KO+eTwn4/md/ZIbhrwbbqJHCxNcg==,iv:KU+eV3iWQ06UHD8LGGPnVkJ9wpdN6pECZNZNQQuPYco=,tag:HnF48CDwo6rQOWw8B2443A==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:B0sD9rtgsayUQEfiL3f3uzoA3ESKEDql1mcTfAvDlhc+GgMc8r2CCQredr7xLjFAYixYYUHLUTpO,iv:djPXDNrcVMTex9bNTQWK4C4ljvLG48EgsKQaPdoPi64=,tag:1MKFXvoIKnqQt3gOD83xVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-28T16:16:00Z"
    mac: ENC[AES256_GCM,data:ebFKL2QqUV9ZfcleWL1+AFZzsXPP4ZTZsbGLsc1ZNjufS0YEn+YimTvvzjcuBpa/4vw9q+HgJelGoq5o9wtUzV7FCrd8jkPnN8K+yZxDf8ocMN1naG9OQUjKp8wqiWWGv1DjyszmO0BMazSTP1i5R63pQ2OWIBqgvKyqm1mPn4I=,iv:Lh1xhGJ4tOOR1bWPvU1BmPOKg7Pt6NnhrHBVY85bgpY=,tag:pGzuHNGJCiu6txf0v9sjNQ==,type:str]
    pgp:
        - created_at: "2025-06-28T16:16:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAy8cqeJi54ajVoI0dXKNwi6KcpwvcFxqrPjQq/Qmu9Tzj
            h4VNLbCzjHg/xlWyzvotOtMUtq0+clJQrHSd2Kyw6at1NBlMqgNhWcRvRhHNA1pA
            twir72Zr2JGKnAU9TqrLReJ2Zd4qes3FMwcJ/5WYuU1iVLxRWxltvikoumjjm6YV
            wmlSiKNDRaQmIJu4foTV9oipUp0P8ZpIkg32lKpEcuFF9+KykVQoCKhGx2DX1xDr
            C2q3kApwxYEga6VY8WL9Bu028LSCGzP2axhLp9Mq2P1mCwyz4P+p+LkngwVDR1uC
            zx8lrSVO6UTEzldBj0TpZ+4X7gwsMP/lZNOT8kdTU0EUd/dks+2WtXpgaox275S0
            utGbptAveKDkUxirtL8uMCmo/9PgDPQsGFZVX2WZmaj+Not0sLnuezIfagUHX8Oo
            hIJV7+jraHdQDU1++3pjt0tbO+Glap3C/qW/JvDCmoW0rrhFgxcV+1Bm/pslFnZm
            6kTgu/ZjyG1CrVuiQnjqEypx7ucC+yWMD7JKG9Mcn06GMo6JdFdywtbZKRBKGDBD
            eOd0fXgz66kOdYJAKdGEV/95x41+KnR5IOpqKOTle4NBthZRoGGcQ/HNLrKYHdGq
            X6Z/R1Qc+PVYmqjnQQVAVk7Y8vFrg7bcS1dQW9WMT2xUP/xRXFIyjK1zdcSkXDHS
            XgHGysiVWWRdtsml6lz/QWnjeYZtmbYuInzsNQZ0h3LeRL68pJsr1fA1gblT1lkf
            KJhlscKoneJpjomGxVqKuF7Gqrqt7aBO+odgpooHOab38vK+q2KDpUu4qdX8Jlk=
            =IDtr
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
