spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:CESDXNMlnCzlEZ68fJ4duocwDcGtaUAQYA1WiBXEZ8Nxj+8WLyKiau4eSA==,iv:UCZSanNg971V1JBBs0I7MNJ8rFWbFfk6q7DzQ2crWL4=,tag:smyQO+1cxUf9w32UDmifRg==,type:str]
        username: ENC[AES256_GCM,data:hHSRdg7y,iv:CMWATcb9Ft9tJb0sw9Bwzfr8FjFfRH0TQ2S1TQmuATw=,tag:Yc/aTnB7zKMLzuk/r1gu9A==,type:str]
        password: ENC[AES256_GCM,data:tkjkjSDomqkPlgA=,iv:Y2THSdx2yuVsnrgvMWgGFs8vP/hNWkaXqoLrYHJKevk=,tag:xOJWsM592aDojafEHwG+FA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:9RZuvoVvCck2oMeCtUKQ0qSFd7s=,iv:R6jPzG5xtM4QJGVio5Dw4yIg8whRS3NG3+ActTL8cWo=,tag:3mHmDNlaedHE0KDCtZpyFg==,type:str]
            password: ENC[AES256_GCM,data:gHHHC95djMdu6tM=,iv:7jOl/tv+7SwCnWb5RnzC1rUXseuiNK5fIFWzZOjSPeY=,tag:djozgBH9K5LWxo1yxoBS7Q==,type:str]
    flyway:
        locations: classpath:db/migration/postgresql
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:p3zon0s=,iv:g/RVNLh1AKKs1BV6GhBXg3VWtHREw7ixwngQE62Yoys=,tag:dwraqhbnKNQhwgrliu9Z3w==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:UjijPJJfQon+b4DPaQTg7M4hrzuCHH4pREcxQZ0/,iv:GM1S93yzBXbZXhtg6f2SaZ3mbnC1MPPaNA9/27r/EOE=,tag:Cy5lsGoKHqEZsgL76j8mGg==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:KImIJjTb18SVhRSfZ9x/ih+j9X3tUsdRYl7xZPbr,iv:ADq6iAGgYErS7rCArvCWsEx9O4Ut4JF2cf35bxFdYY0=,tag:h/k+Q1L7KFrZ2zQQj6FnvA==,type:str]
        cookie: ENC[AES256_GCM,data:r1rIy2XgPr+hL3KeQRwOtg==,iv:wWY+28bdUi54mUFw8YkqMC60ATzNX8PV9u+jwdUwmFY=,tag:viV3do/bEWkIh6QozV1htg==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:hzzv8iNh4cKXWIsswfFnuqhvAhZ3Fu7SCoyhATHFsLBZ75Psgv0sZW2jiQKV8nU30dxEllk=,iv:8IpIG/qjYujiq55fIfycH5B2/sNdUjT6Z/v40DZfJuo=,tag:Q6lBtuFnMQOa8qB0f+Gy6w==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:TummJHEVqaL9xubSE2gdivxQDoglcCget0f4mAzkIp+Kwkw4AhxOHDNPoTa1aybIZg3YdtE4,iv:5GsV2uYHiot4puEs+gVFms1AEy79Mmt9moREH7Km4Lg=,tag:9/qyi2J1gtQ3Xm4twZYZeQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:jpmOmG55D1VZPcdQ0izVPaTZh9iUdGRZfLnNxzclJeNC8YOwa+Q9d7p4urHlpJOad+AQKvk=,iv:gPEzkhO5JmtAsJIYEPd6G8IugWyvASL3T/kYUU/U3qY=,tag:xqpmV/C6E24gYoNfZiJbTQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:O8sbj0+h/j+YuRL0NjW595B8pAJ/GVYOKwVCVo7Xk2EG,iv:rctBuPgD6QJsL3kH8a96XbzyDkfF+9VM/u2qljkK35A=,tag:oOyYQbJiERy9xVxp7yf1RQ==,type:str]
    access-key: ENC[AES256_GCM,data:Qsv+GaeDLFcEgasx+MxeQp6IeaI=,iv:lnzNC6vpYHco658qpEB9wtESiRWOHuGm1QzPorh1etE=,tag:SnD9ttiX8zTLHGJ6UuEgJg==,type:str]
    secret-key: ENC[AES256_GCM,data:NHdqoDIr5ieRY3Vk1VW5H9d84Vwa7MuAmgNjAbv6vzYu4zOlPpDwVg==,iv:uj4sgX/+46nPCYYqERUE+7fUyFBQZs2LD3lpo8GGdZc=,tag:6X9fBjdQaBmJarU9j0+X1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-08T14:23:10Z"
    mac: ENC[AES256_GCM,data:lYCjK287hDgw3cYCpiuXJEcVtbOzdzADDU7alpO0meeUpFDM9jNtNty2NHADGVkyl8/AufqzGpRWn+oPxFy7k5Z2qjN3rvyMjA1c5ZWw97nDVAOv2KPY3QvbMhCwSd6N6taJAZEYldANAey8ggGKrT0PWG/+6FTKGjW8c0iBC2U=,iv:U9PhzAVI/XUvdcob44SzvhBSr56QkAbIppZcvlgBdvs=,tag:PPJGwZeaHncuEWhiSxQGkQ==,type:str]
    pgp:
        - created_at: "2025-05-08T14:23:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA5GEWSWROdCmCIG4wJFGKnhCfzSEZcnrbnxYsQogyMyXs
            S4p9qRpnwHqL4yku7Ama1CZtHsCFgGT7YE6HiZJ4ofVoY8Bol1RFVmvaLPBOiIVt
            YJm89WJE+7uhhw4iwYVS0q+MEPb8zoMvvugpHWdt47p/h599ZxYf+OzRhWOj51lz
            BKUGYlFA133DMGfSFVu+Om3HArHQYVeWljaPT5nDoOZu5Ur1n/RJbkAUJNkDljws
            3axp35IbpxOoBrELize9E1dIe6n7CIGfE++TSpKp8CjL2253DqRNOPUt2RbsR36w
            kEQ4tbOYdKiKBviyLpdpuOHH0kXQ0h8yr4d74uUoeHE8laiLtNV4W6ICc/ly8bry
            N4nLKglPIuptRe9rYFAoPVlh7DFWcZY+2/IzevtT32sfWuPueyeLRrOnhJMug8PL
            rgnAvRsn5jpOYXaKv1NrT6dRnnWqkZN7IFFoLKfdLUDQt3avKAbVObTgBTJSQmxB
            QMR5+Puhzg9uV4e9HfhIepAEj/sXcBq53zSjxFNmUhbi4nR4PbbJcAmxAMoZtRfV
            bAYST5X06lYBu1kkXEReLzf/BYhxBUDVW3IOR22hUEmxok4tesv2kT5NTChE+mB9
            agrDnjH8M0j7YS8HnwkXMIaq1uqbuGEl9DK46X7+C39n7sY+D89eKwsmis8+WFLS
            XgHwR3ckqms6geVoONObbfyj3M+F5o1M6hUPIx+GE6mWNW9pV7hzN3LjxzsTWlrR
            MLStT9izHw4dzR9r2o6bnxkQLvECdTuWGOsOePkvutHAFPKg1e/XR5F7qczsdPU=
            =BgLV
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
