spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:aiduz9Z/gMS1VrFKhnjlc3diCaWla032S2zNi9d3nm/vsp8vqw==,iv:1HNS4Aqk3GsI9fZxyWY60xCj5rFyrTUjTaZvt8VKzns=,tag:DlmfWBv1ffLy3cjtqQuyLQ==,type:str]
        username: ENC[AES256_GCM,data:D9+HSKCN,iv:FWOkI12QxR+m+fcdAowYhah4X2QoQkB852drBPkSlh8=,tag:oKqrtZIMML0uR5lDqr2Mvw==,type:str]
        password: ENC[AES256_GCM,data:7tCOtGca5SUx8GI=,iv:uicgWbWGGx6bnyIT66O+j32DL5jRrCikuRODuGTxCL8=,tag:D0+k196IQvCvGPjY8EMDMg==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:saa5Y+Tx9FcwJdilX1jlwHOQ3PM=,iv:Thb7fudv/hCYGVdP6rPCuEemerBtXrgg60PbMiaeg9I=,tag:L5AEAKkFBu5D8rX7/0vHkg==,type:str]
            password: ENC[AES256_GCM,data:pQpgUOFYWkKTgNg=,iv:gz4dM82r0+Zi0GPyTl5oofNZJHHnymtCXGrN1xHlttg=,tag:QyoVrW56rp5IJTei5b3Rdw==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:9CPed+4=,iv:d9Bk2tUc3rWVovcia8QM7i9LwrDO/lmG1szhTno60Yw=,tag:MM9hSsnnsfkor4Y2W/9WyA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:kSYChfmEwAmxdWm3vA/dDs79lnvTlPYlFLm2Zzw7xn0as/Bn,iv:oGA/r+jgJ/il6QBdC3Iyc9iDeDf4aUV6+f2PH/6YI9Q=,tag:okxCYRh890WMvmt2nQ3QlQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:hlUdZWPFUQlFEsTrx9EHIIvOxs/8cu7AXXk5KZv1y/Tc6urlNFX07Qh7PMC9vgoqGPu4fCFcyog=,iv:pTQSuyaRoVf5a+bReKrndFXAJhIXSLA4KHUZFn82xew=,tag:buh3nOjR5m7InVWLGh9iQA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:s+wRnnIlesCpTyaGmkAGUVXG6rIbDXsqDAef8WDLtwRNUUmQhR6bXSr3cUFRy6FdQuUMw1pIVn1Y,iv:XEzU2QQXzx4V/Op3np/GCjeQLRk6paLJ9elQHzpjGu8=,tag:rouRih9pG9TxLsg3h0TINA==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:KP8vwDGlieR+czHPxTCLHB0+CQOp0YLRfvNx2g671DjTaY/YP4T4eZZmm7sHkobFMA0M/NyQh3E=,iv:MQ445tpGiBUZJTmALhZqrZeANsCcYLDraF61fifFetQ=,tag:5VSjEbTURuHCJB0Kl3aJrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-26T16:18:58Z"
    mac: ENC[AES256_GCM,data:MUs7p618HXuAMP4W4Rn8ZjjnliQ7tm3FiKqmBn/Rq2locCXPEjgiXluDBLMJue6TPmmoDPtLxMTsD7r8lorwuLFH9jQWmSuqyAc/OG1+uVxPhEFS6YoYi5mo7nb7VkbysEqNb3Xn7ttDLub3LthnC9X1bZa7+QFlb+p+31yietQ=,iv:LTdittJk2x4gbGsOiSePUhUXtYFQeF+VN/KuhA2951Q=,tag:MBJeLmUV15lMaQyxPYg2ww==,type:str]
    pgp:
        - created_at: "2025-04-26T16:18:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA2poDDjRjRObxd/XheWRw5/vWVA3Np4CtSQJKQQqbDAav
            rujJYHWuwS7EbBrd0BXEDKtdk9IbfzgH9HhUmvIvsO4hxWKdXsCmx75U7N94vhUv
            LuOGiVCQcskjO63urd8JaQFdPs2T1TQeT3j1LuCNCYbs7UqV1imGL/kqeqIoAlll
            ML/2PefpMw1ymd7c+Q3WtyRUaTZCYE0mkp3EEcz6bJNklSINvnsGMf6e30iPYCqH
            KqzOHCIBgSalby1SMbQhfCjsNQtEOVD9DRJVmIqMhkP/QuKiCRYbbPyqBa9pWjzh
            bF0+bTfo38HR2Yzqh36lI+X3CoWxpemiZjq1LVQuxSQ9k+mxUD5BgcCy7/oFp9gy
            89VCdEfw+okmd7nyuGXGX0uHXssMW5DDOY+zeWTCjUQr2OW9w7MsT6d7JxfNH+L9
            ylY8MffAdZXm4jtNZxw74pUdmsXTHRelFvpnvRT7J19dpDKjOUobO6Kbz8vcG2xR
            0N0aJSFxyMLw1gj3YetiYV19L/PHlgdVnNge8fVjqvY1VmtzGK45n6nDWkJSQGdf
            LNj5FsRgGa8iOq+rAu+pQ1pTmRgPRntNrkSmjPZcpxQs7xSgGuu/zR+AtqfA6gBW
            6rU2mcFD18C3z0sSHcXmlRpMK3SevUz3n/Lj/gRP54+BnSCL2Rzm+aD1vXDXDr3S
            XgFH+t3M5j0HxEww6UXCxyT2CtSQxSSr/eA55M263YHyVDi8tW99M9UWupGNGydr
            3f2BU0qAgpL5Sa9JcFBKd0H+hshak9Xdo/CIDo9HzsHD5APlp1N8d6d/guLL8xE=
            =IpdW
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
