spring:
    application:
        name: Replay
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:78JpFvZJAHmBuqxBjy7JvrY2hPCQYrW1W9Jlp7TPBHyn77hW3A==,iv:+hZZpJj6q9eSH+Kvot5hRsHBMnT9QgT1DIKKsZUcv3I=,tag:vGHLo1oEnJWlvaO4FY55Tw==,type:str]
        username: ENC[AES256_GCM,data:FSXbeu3+,iv:bVa38kDPWFADFYS6l9oYzc+af8Ikmgy97njsLzK4ZlU=,tag:NxOwZ9knzMpIvhlYK/eJ+w==,type:str]
        password: ENC[AES256_GCM,data:51ulNfxtB574hMU=,iv:UPg/PeaXIUpzb0fOqCZ/I/HB84ka/sO/m7C6xzCdLC4=,tag:ZEbRO06AY0DJi+Ntg8QC3A==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:iv50lH5JhZuPCCdxnINIqaDapI4=,iv:04ebv0e+WMrnncDzSEVpnrEV0JB1gYds9UmRHPEO5ac=,tag:3qGF4oXjRjPlXYEndfsgaw==,type:str]
            password: ENC[AES256_GCM,data:4cf0AXF37KWsdAw=,iv:cGcMq3sgz/UljIQslxADRsnf9UkVtA6n4ouCOTCzFjk=,tag:hDOsJOY+U1xDO3tQYz2bgQ==,type:str]
    # 잭슨 타임스탬프 ISO-8601 형식의 문자열 직렬화
    jackson:
        serialization:
            write-dates-as-timestamps: false
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:sDk9erY=,iv:d9Pfdcu7wsCXeupPEtmBpY+CDxN57H1IRehJlQ2v9Yk=,tag:f/K1dAcD04/J9Hsal9wKJA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    servlet:
        encoding:
            force-response: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:Fqy2txmTHx7eoYUtya5vN2wSKhbI5i8JJmBGXxR2,iv:oR5Xl7Yiv0Dsz5+uHKRLYOuJflKrfUKoaqoRpu8D3cs=,tag:5lEZCrcaTdNto5SyueuMsA==,type:str]
        cookie: ENC[AES256_GCM,data:GGjP67rNGn6y8JnB5Cm5pA==,iv:82PyXvWL5szv92aU16cbfkxs/m3PNuHbkIL2p2NKBBI=,tag:2eB6jgZDsCLPNIV7DMQPAQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:4fZCysl4QKk04VWJ0njFtIrUpKCJzoaJ6ddGXJ9hPy5m4+Eaxk9bhiuhLxVz+BnOoIgNfVI=,iv:+FM31fhAoTJtZvx59+y//VUIk8DiJQpeExBBeOKDsUE=,tag:k71xhL7RoBu8MvfSDRQw1g==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:7PM3XjIdizC/WhrK+VN0J7XWS8ZRZvpst+laKfA0Rqi4yGkBo0eqzQsbhp0IF5aoW5BmVgZi,iv:kb/vcv3Bk947h9G/KQyjdCaLG/LqAmwRIW49M3OTkjw=,tag:mjHBG4Yhp6cgQxb8gTWXuw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:GNubycFutyEbzADk0XJ14jJmS4Ek5d6HQwn615UWr79VZQjOMzaAd7LP3joeffAxQvxrj9U=,iv:XaWYQYX46/exuyzfsFWiILLUT48PbGjRMGJDBguD8ys=,tag:iQSNzrAos8JrOoBjyc0Rlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-29T06:06:22Z"
    mac: ENC[AES256_GCM,data:U8v67eWikXYAFk5TztxCqHxL1rnDhr6M0Q8Kidos/zV54KgzXMwOtXrNYB58yVhb8+zto3LScs+g135djFJH6ANb4fviJWwjP0WNOTXwrScxfiLkEXFdOpUqbUzP+CZ4FEB0hqkZKJceYz+LtRNqD35mAynPSEO431IiKSmh/GA=,iv:Vl4eHB3ZU4R2mWGdlJVW1LdH90E9i/NP2W4EOYCrbEI=,tag:tsO+qBmoW8VUMt/V6rCfPA==,type:str]
    pgp:
        - created_at: "2025-04-29T06:06:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAhxUeJNL9P88ol8JfgicOnICZypqJ7htIgWg1/8v32kzV
            REp74i8jtzkE9aKOZWZneVSrk/jn1LcSEF5s+LS3pKGkgeSwSGT7vKhW4cLIdmuL
            yHTMknNE34+GISMAoyCwJ/a/95urDc89rOr6SXgPCFcLKvGbsF/CMaQkSE3TG0un
            Dp7MLh42e1WW7j8E6hXr6+0m/Sm5fl2Xd/bWUO4S9LjsWjcJ1DbMUtv2yEeC7BlW
            BXSvEg5rlOHhstTfMHAo7CyotolZZ2qO6RKIKcabwXTWscz3YPCs0DYgCy9gHt6/
            Tv+pTXUsnnHyc53tJgm+KyEAN3q4HSogLLRb2hmNE48G7wwLDJ/XkPYZAI9nBES9
            xLVWIl1j3nj0QUTfZwuFzKDw7tHPoIyBYqP2aFi/PnsIM7jUG9232AxmWIyCPwEu
            vjDMajxfIlQPcRYAq+Y685SIHUcWOsWIU7RAR9d7rRI8RYPwFrWknaWeFecgGZqE
            /rNesBm+DVGczyTXY+osa4O4p4X/pl2Q9KRvIvAQ6qWlVEn4mZ+3mldJmxCnk8Qx
            h48fOdX84tJz1qmT2lV7w9F9jCHTQvoMHrP17x1TW/TfQRqxhkF4xuLzRB3ZbBgv
            dpfu+KCZWQT7/YX0eUxGxc2KVbDIDjRT8Io0OdkQOhapDz/TvfwD2c4kbSUWSOHU
            ZgEJAhAx2JHyfmOGN6jHM6EtI7fmAcQJcs8j8SP2RRssJXk6HmUQf96UzAneA4bV
            7KWJoSWDR+Mi+8W97dln7jujXyRu9Fkmpe3JILoPH/Z69sI57tgSwr9heaoZ/249
            PcVBC7bmyg==
            =P1Hm
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
