spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:tArbju+eW7d0P8yzlY6w1pJmtHeE5PF8Fc1cdd/6plB0Szdg8A==,iv:dHsyPItpgYvrgtJHPmTB7LF1fIxLYkUkZZRDUnVTMdQ=,tag:h66Y0wY1kalGMPf7nqC5Yw==,type:str]
        username: ENC[AES256_GCM,data:dCjkJ3//,iv:jbMzku3XUFQkeTAQcNAlkTSsobLm+ReVPTrZX1Z4+fQ=,tag:vXu/EvEt+zvy9hmb4RdB4g==,type:str]
        password: ENC[AES256_GCM,data:PowhlSPMJfpQkYQ=,iv:/0MLZg/db1wtUlcJJTFEtNUnUeE8zKp4QHnwcvI8Fds=,tag:mIRV8n8sXRaolPGzMVdxYA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:iCwKEP7m63qAUOZSOAn0VoRj+Vc=,iv:yIUWuq7Ym/Wd+y8Goe9dn/uPRrGp1fERIbmvgyrMuD4=,tag:bM0oHShlH6ijGuwb5OihHQ==,type:str]
            password: ENC[AES256_GCM,data:6ev/VYYIucwV/pE=,iv:xvGm3bvdFWL6Bri5BvGoIdmidrQNQg9potUvGd3Ml9A=,tag:HZdDjekwNPgqtNZ7PeEatw==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:rxQMFaA=,iv:CRnUO31FW+P4TVVC9a2H1Czc4XrvCUG1SCmg8B5oaBg=,tag:dl2gn8QQ5LLzDpcRmDsthQ==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:Imedj7ScLTMH9YtmQqP5a3k4OVj2Ood2f+B0I31s,iv:MZs+sGsjbU3lyp2wGevOpkZcox/8/ZWsugtAOhgvKOA=,tag:r6I+8AIrRWxf/HXlmP4lqA==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:ec7JFBofjWR/aR0797J6EHNUIk6fpMVub79WpysU,iv:ysQN7eO/1mwXSYmr5hqfrHh3M+zJhJOPekNES2Yg2mY=,tag:61PWGie8WG8VxMuMjYr8lw==,type:str]
        cookie: ENC[AES256_GCM,data:Cramc2vutTjzQpm7c/C60A==,iv:TAL8yRtArAtobGHB9KUTBK4hp2oOOqBub+IT+A7Vfvo=,tag:Z4SDOfQCHYYfcYIq1k40pQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:w3bRNxXjYdAIFnt1VO11FB91ApQSFEvMA2vN6jd+Rt8QrGhfEzIQgMLXasgz+t4FnBXlDZQ=,iv:qbIx+ov+74dmuRzMqwQJEQj6vfov1AXbUkU3jkpZNpE=,tag:SDS2uWNIWQowtqHVN2BOnA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:UMqDofj2gRyOAPugdvuL+b3vxupnCrUzFJbNGsUJXAvMor3y1QjFbwuHhNRWLD8f9pLM98NR,iv:9Q8ed3UZL9HR4GMohBpgYabo0qjYoV7kBcuwjdQWS7g=,tag:HTrV2O7JaUTgS2KAoWsqnA==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:a83FNd+aiIeeCbzZlXWxeKg+iOnIPiX2UT5pIcZz/oCMH3+VxCCRi+nSqTGpPBzFl+MwQWk=,iv:PoD2wHHMkBqm6LrlF+BtAfszvoYYqI54P0/fo1iivfs=,tag:kTt823cuv4GfOl7jr/rqVw==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:SDuaBwlsPvP5an4Y93gY2YcG4kYqCU3Y9NbjWmUIJSOh,iv:/eeXLoSVdN3WlPSZjvKSdMKq6QAU5hA244FKrpq1yGc=,tag:Z3/p1Vc3J8lLWJb3tHTbYg==,type:str]
    access-key: ENC[AES256_GCM,data:E/tWsL8eWfaSk0ztY5IQc+hMgWs=,iv:pdnoOOvXx+VkzUE+d4mBrBvJgkapuSmaUwZF+FAEUfA=,tag:qcfIS6qU7wl6pQLEEdIZlA==,type:str]
    secret-key: ENC[AES256_GCM,data:rpUCFAisMtkznqDL8WRYdu2x4T8V8VG0w5Z4rlzor65ubVedoMueyg==,iv:KOz7VU8AWmvDFml5Yq0IS4B8C5+e/0Kjy60S/4OJKBQ=,tag:qYgNxAGewErJ9fcM21IEow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-30T10:43:29Z"
    mac: ENC[AES256_GCM,data:C2NfczF9AzIXRzb5BAWnsKJveLMpIV0iGNM0+PuSbVkwNPCXcC/eL7kU/7irHYZzqMlKAC5vqq2gi0sW37wDMQclalnAivyvp1XyVoutRqtgAxZyGeqW6/2Tb2AYwHnqjzqMHnxp6bvpLNI9z65EWCbVr8cT7icb6W6akTHYFv0=,iv:7XRToB1OYF6K9A+40MW8hF/M1sM6Wdm0Qz7c7SjRz3Y=,tag:TTbOI3B3FJcI1h28k6qIwA==,type:str]
    pgp:
        - created_at: "2025-04-30T10:43:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAvhVvwOzyR/AoInUHDvQSXDmQrvg/Re2rW47WOlzI1Oaj
            8qZldiNJG9i18ovBct1OM8yAIrVLljxIneWQuRkIr9GQ80uYyhlEu/SP+czW75g+
            iK2VoYKm1hyF5gwiUl6S8vx3oKKVl/d+PHrJgMoORW1hVZuoDUGHxVu5xkBl4VMQ
            deEe6X1Pb1TZdmkhtSCrxEWYGiwIjKro1EWk8m+3suVp60VU8N0wazBJ5K+SYhu/
            jdkXo9fbJaEkIPdnD+1HHKOeBieweJXYibO6aGSwLU956zUvntZDmV3hZLToPCNZ
            D+BijGA0MzFW6v1aBjkmALnsj+UeDjRawF7fGZCeEdZoceZ/J8/1kiIRhvmNm6Fl
            hDcY/X7sinHBdcMZzI1/tu3wyTaXgEneilZS8Y9zEik3Q0CqB2UnQrNsO/gocxyv
            R4zmEYtdeiZ9hCcS4ktgpwzflG5mZDIncgX6QRvWTGEZls6D1GKvK0MmfPWHh2kv
            hflHCmX1Q5RybCzq2z0qjXB8DnpoMkOgbHRgjLLHLmnk1kylMT/Elt4n/Df7sCv0
            EKd5RgGxItsKJoYfZrivlK0TaOSwfYbO9wQnclVZR29jlkePWOX+C+vzqVlGh7U+
            1UNEGo3TYAGsFD2kfz6rzht05tUMlsWLLb+083vuEbSvxOfZ0K6fC60jXs1tt8bS
            XgHX/hlwudC0b3JfSkgV9s1DeiPuF3WiMLUwQOcLHUzmpBjmWomnSbKTkfCdJjUN
            /WMaW9UO1Y0HCdYOjvNZW3NgE2p61o7pCEsV19EOEMXAG0kYlcjLqXusqYQDk5o=
            =OkxZ
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
