spring:
    application:
        name: Replay
    profiles:
        active: local
    flyway:
        enabled: true
    jackson:
        serialization:
            write-dates-as-timestamps: false
jwt:
    secret: ENC[AES256_GCM,data:3w5tX2zuPLlGSndQp/JyoZztWES7Wz3OnWqr58IC9Q/gg1tQxdpkvpIh02E=,iv:w1/zGXUN90yJzeN2JsGVIpW9zVK31Wh3XrHOANJX0/E=,tag:d1GBKvgTs30Ktkx2K3OcpQ==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:je8l,iv:hcS92Kfs9GY/DwwLbL+7DrfBL/QTrHroCAiTSrbu/hg=,tag:A+CVyH1ej+c14G4FdjIZaQ==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:9jg=,iv:TNvvgrW+TI276EPJeSIHWYjf3WV+DVfxunvvDd2w2pA=,tag:SdcHm9vC7NtpU3dHXB/3TA==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:wPjmOyzenV5xoYJqQSwhIOA67z4=,iv:SjT1bLhF1BRqU/zd9yNLl9dL92VBo6Bj7HLsJQWvSvQ=,tag:3Pz5qa9juPSGzyKsm/LuDg==,type:str]
        client-secret: ENC[AES256_GCM,data:dPcz7kZSh4sAsg==,iv:GpUXxcFE2qNRq/HbUoGJPVnLHbDXWA2HY5yrbBDo7ME=,tag:ng7tzrEw3skwpgCHs1Kkvw==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:ubQ7QvTcKYk1jLNlf5+WtXHHV59fM0m5DDQHhIYKa29I5xMeKBodEbRNypIlAbWT5P91YnT9T6f73eZ93zN96lsov3VqVcP1,iv:SwtoGTzyOCxDRp/SyrE4R1V4skiD72JLWwT8mLyDnnI=,tag:rjW9o4ikkse/B019hs1x+Q==,type:str]
        client-secret: ENC[AES256_GCM,data:IO4uipXx4nOVMa7/LUdwYFXuSbgvk5h6KYc+gR2VeltsjuY=,iv:KmIDbAbBKC0Ynr2/fROl2JVXIM+EkL/vSBMokVSvw/U=,tag:QNSygAfGtTBepw9IEtNe9g==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:t89Yis4ox7DDfVMdn638tRSE0GmgRbK78I7r6z6AnGk=,iv:d66LtXsiH5nR5E8n0Fy8xEhVBGEIvCH498KKfKNesec=,tag:UeC9oSQwSdzatmQFVTqZRw==,type:str]
        client-secret: ENC[AES256_GCM,data:8grDKIINFPInxN3WQqSnP51GNDeIWzeQzLqBtwnCQkM=,iv:XlN1eSTG0S/DjSrz7MRA59hw55H9tP6/nH2idG+6PSQ=,tag:BN/P/y8/P/X24UxvJ7UzZQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:mEiVUeNDaVXd0nyZ48LTvbqRW+XQ+mht6M5J1Yd5llzj,iv:WOnUeL63z+Yjcsc+kj5jqNtIYSlr0D5YUNhZatjZ3OM=,tag:ZLczeM4c6deIOXeLZYyGfg==,type:str]
    access-key: ENC[AES256_GCM,data:XvDcgkkoVz4/NF6lrxA159JcFAc=,iv:xesoQeAi5Zubsru8cAx+Kg7LqP0GJKlE/xW4FTJuvUw=,tag:dVVlBGof5U+GSX7rgGguKw==,type:str]
    secret-key: ENC[AES256_GCM,data:gWv5Lm9p/E7vm5y4ngG91az4jguN05/1G5owHswysbJOHYrsMlNb5A==,iv:aQe0X+Zc7vHMKb0+EIFs/yuqBaCLF/xvFlyTHzygbyI=,tag:VjRhGKyTq2lBApRA/kgdlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T14:02:23Z"
    mac: ENC[AES256_GCM,data:tFQ7I4Wah9naPBsWVBbEjZvvUsxv8pmHUFF2Nkuu52qBF6ySURoyldhgxPFYurxyYVU76VqUDCqVyW0nTBx14J1FbBL2ZILZ7eaKSV/pMtyVinuyj9h+8Y3B92tJz6TGXeVVh9hKT8cc4ZYy1fcTvUO/A5WV3Bkv3noWCGi6Rjg=,iv:hptt3rBN4/Pm2OVUAxASXzfZjMLh/8zXi+NVuC5rhPc=,tag:C3FWO+bBFpOQh5mgPuhoHQ==,type:str]
    pgp:
        - created_at: "2025-05-09T14:02:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAkXK4rzVZSiZkIgEQ5b8tTuNfPIDyuetdexhWkffhYvJG
            DIiUoIw1hQZCUmbdadFJ/k1zDFWVd9CiQOnhjA+mu5qQtQ1RhEuNZBfuXFiDaVGU
            LRij/ZljZmkFTcNGPWycBnHXTtZgqUlA/uZJyu5lgUh2QhLoQxanaIWDWJsApmXH
            oLfphanDgQmsHuIolPhowWhJzTLZn23mq70+UvhAHhBDEFlqRT9pZRdlOoS8hgF7
            2EkKHjHUwdDtpD1wRJHHLiLAr1PoP1XKjO4V1n5eehULigih0cussJ8RBbdDj/sQ
            VY3rs/ppZoVEsmjEf57BcKpEDZHC8YH7Y0lZHiC3g6bqH7UQqOdH54sseb2BS4s1
            KcqJPWyK1ZWEYsItbsHAq47Xsx0i40m75IiRpj63kInGUXAKuETKO42tuIFoSCxb
            Zal0z+It1S6S6yzjU+xIR3G5nBac7ctdvPW4QHRzfae4sXslz/ibS9wSrWNUPcR1
            hR9ajnJr2e2AQR39ILA08xXjj9FGPexrePAr7oJ8IvbFlWeebwc6LvKfRZcFa4iC
            BozU86yA/V30eU8iHm2steCL8Jt1f+C7wRL5j78fQQgy/4KVpQ51dr8Cq3vCCA8r
            1PenmhCuzvvWu5xz2K236hs4H/KoBMUk3Mt60nOfVpiaqf2xTIdo9lWfdzNggIXS
            XAFNQx8UruS50bLgKKICHqcmmYNMT5pf8zxDs1ObEObjW9qMWxkNfgHVvQo24drV
            TfKHIaQ0DRlDgoZKyulLJOFIaI41GGM4+9RdqDN6EYaa0Nh9p38z9gB60k4X
            =qWt9
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
