spring:
    profiles:
        active: local
    flyway:
        enabled: true
    jackson:
        serialization:
            write-dates-as-timestamps: false
jwt:
    secret: ENC[AES256_GCM,data:g351W3ISSbj1LjegLaQr/g8LrG4xaU/TfujkLZHn8S+19Owjb1bJZsCmjBI=,iv:4RWLm7mrJyGSWoTWg/OSaqJd9Galo/HF5R0w3Q7lH/I=,tag:Yh4AfF2P3MMZKnuM5UOPqA==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:CVwr,iv:SSZyAN3u6by0Dn5dTVgBtsoOj8zKHQLbe10bQvww6mo=,tag:b/Rc2w1KQxcq3t64VwZQyQ==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:YKs=,iv:zP/dwel5OUPG1RB0NANGJcScSYnRRgZ1/9xVZOXyWMU=,tag:UoVM/ppcwXWso/WY2EpncQ==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:zyTc8gchNh2zIVaHQ5BauTTiEao=,iv:adVquaxoLbbQOzGNdccoYAnh7xkgP6WXWHvYUxICc9s=,tag:dMYVkmilI3368fRvpcAOtw==,type:str]
        client-secret: ENC[AES256_GCM,data:PcDvlwg2jpxgBA==,iv:5svKQOaSmQFn9QYXh96vD31rGulTO9Kcf4cRLWG9WaI=,tag:ZEzCPVuBbBlK8MKicYHf8g==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:mPurhtmZDY51gRdanCR4/PypCp46GPfXb0Vt0T00mkFIKF2ZiXcm6r8Qq7XVTKfEe19yxeM6GqCvuX73TKc4i006kP3nziOj,iv:Kuydsu2HWq07c6cCA0fVXQdAj1rqqD95LM0NW71B3Z8=,tag:0d2Wvk3/coL2EZ4Vpu4hNQ==,type:str]
        client-secret: ENC[AES256_GCM,data:W/OgfJPXbcZn69JfE9xFX+ReVujCteWm5gXNbMZnB3f8Nrg=,iv:NPpxaovzsC0t+qthvzpV/MzYbO0kBwcsFtPBGTIuEtU=,tag:wMQnZJaYqYxLcZxmYR+LNA==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:jclZDRexJQz0AZcgBBFrpdOEVUnnyl+L2YTjzACjLXo=,iv:BNTnxbX86zVYY00pukdNdY8YdyZRqbCWoNuUxh4D4RI=,tag:RcaopnsE7UycW6WER9BbCA==,type:str]
        client-secret: ENC[AES256_GCM,data:jo1gO8WsYyBjoFRZc+iyaXFZmjZ7WT15uxND0/klnB8=,iv:6aZ7OQrTGVO/4Qb1XTAoXozGptJn+vonAw+VB1cH5+I=,tag:4jsf9UwTOAYzuGpQoV4+LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T13:15:34Z"
    mac: ENC[AES256_GCM,data:ewXjQNKxRqjKG3oOfIwL0Um8kIkHc+i4SL75kJuj0Nho9S4CvUf02n5rsB+IVHDtoAMKFsUMEVVcldhjdn915zJGT6vpGglmkvHTkU4ig6bvrFCU/pzSmE6iGC+Bkdp/5pYXEG9+QBSwfoKpaAxwl3WLOcALmtdArs23xkfWHjU=,iv:ZbeEYp9FA6m7fJ5v8lewN8qn87ryDfKPyJ4GrOCTUVM=,tag:ndnZG2hsRLhrvJT/0y7l2A==,type:str]
    pgp:
        - created_at: "2025-05-09T13:15:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA8lO26BklP/k32JmEM310dB+sO9KxJViwcCF6NzVyR3B9
            qfXJ5V7G5y/6uVPUUjm/Mh0oiNBwFV3FBOzO95mwaKPkk1R6+u/F1aChnejnMnRH
            gDweaRPBDL5O9JDpJzSmCLujXF7R7r0dWYedLIqg/xA93OPmFkB4BniNBaZYocHa
            tTtCpP++XtrlnKZQixlaE5vX36r1I4i82eeFY3YtgNg6Kn1nYJESR41Q9XFPNehP
            JdghvR4XKCNI3fxvIuxN1HEkCfVW+NM8FOto2GgkDcoGbESVj6vhWDoUPdEpyv6J
            zEEPy05hOArZP+CYcmg39QbwUqL2UXdehN6xaDiEjNhSK4REf+BO73rKtTUGqOqY
            RDdC9OKMiBV1CGjbkfZIuzMG1DpKa0Z0+5XeYr4+c3VtLIJGStJou0V3NQ+KJWWV
            V8rNwed3Cvqf6/l3YVPWamK1PTJ3cUNVxZ4K5efD66JlaH6nmw9NDkEEXSya7T3U
            f4lkGhFzaLY6VizHCNskaEhk3AuIH+kBQfHrup1SmfNWS30CSG8CPodS7Hfd74Bg
            mn9eih40vsTi2/kj2XVdHhKsFDUUfwJQTO5y9Uz03hYumlqgLUv1vhtcLe9CtT8H
            1nYosvJXw/0+AisYu+3uFdP7phktn07ZtkZz+Y/VaxvqSdM9Xb+w4Cyx2cEUJbTS
            XgED1V6vV8WA8ty9xTSkZWtPDUIt9qUE6dhAMOHTyZnHpeQ/CbsBuPXXGQveue6g
            30mhBjkC3maFxsKTEBK2ROYasQp1d7wvu3+pyXVn6eq5LReG/tF29whfjWfTL7Q=
            =x44V
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
