spring:
    application:
        name: Replay
    profiles:
        active: local
    jackson:
        serialization:
            write-dates-as-timestamps: false
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: phanes.replay.user.dto.user.query
jwt:
    secret: ENC[AES256_GCM,data:oVzzMXcxXuFieRzwaGY9nyiZpDBswaTouyf56KZvEMPo6Zzi59Kg5uRvxaw=,iv:lC95Pj0X09izYdQoLu7tPFOIQmS8T+WYC4WsxrGh5yU=,tag:JT7Rnreb0NHdwhsw5rd3TQ==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:8OHJ,iv:pp77hJpw1W/UGQKFEyQ2U7nZL8THNGszm+RWXQyWqBA=,tag:4d/WAkqPdJCK5Zy1smsHFA==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:OB4=,iv:j4AdVLgpZApDybJARUt47hCrVS03r6J9b3xWfzsfJo8=,tag:25BH7kr2vUklX6X8sJMjOg==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:Pqvwapb1ZRrCvVwRiZDsatxKnvY=,iv:6w3vIgKSo3XjFJgh+EenOvvw6p1uY3Lyr6b01icpWjg=,tag:VsxMJiJR0kQvHvkNhQI1hg==,type:str]
        client-secret: ENC[AES256_GCM,data:CUhVYMBxXxg4zw==,iv:CxGwMfMZomK2y/LBkwf7Hjxpq7eYXsfPbQfr0xAKTy8=,tag:N/CY3VVumWhvRFrv250V0Q==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:TYvF+WwAkcIB9XTumqXRW9EzkGuvNDKDMvzixVYoAOk9Na7Vr9m5Vnrofbawvjg9/d1AliH8tfQhZLBw4xtbuDycGoahqftO,iv:4RZAj5qJf6sAn7rmWA4i/GZrqQyxiZI3y+BL/uG6zrQ=,tag:PyRmdJODkQAPUm5J400ZNg==,type:str]
        client-secret: ENC[AES256_GCM,data:3MNIxHSgdzv5CJSJ74jPjZn4mY6DUqvh74ucKZeLcKFKA3U=,iv:A9OYarzXChicGgCF3kRi7IUeHy6cep82N59no98Ss8k=,tag:nEMt7gOCUAQDHAu+WAU3EQ==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:/O0pyYaTo967yOY7VDIVZp7pkTgn6JwYfG5+bcDFu4U=,iv:pbVqMI0xkH/54BfXqneRNcD+HTmbUy6Z2foqTqiI4Fw=,tag:ls/UTZZmyQNv9CERUG9KpQ==,type:str]
        client-secret: ENC[AES256_GCM,data:XaDxwiR1k6CFWUhN9Thz8a/5LjF+CKj2UQl3YfGhCFw=,iv:NWLlVB1gobQ9WztwqYxlhg2CRrjtorPzVuSiyczmamU=,tag:h3u9Z9xKVKf6bu3vAHPOrA==,type:str]
s3:
    bucket: replay
    endpoint: ENC[AES256_GCM,data:+izbxNXNCiy3J9ExpjCMjkavgNgDRnTM168O9YPDjjev,iv:KZsxFVwwqsAGdHAz3kvu8z6EQxqF2jK/CI1m3YCokE8=,tag:mZOEa0UxgxAl9kIcdB5BOQ==,type:str]
    access-key: ENC[AES256_GCM,data:OzbUrEUtRDimSqAbAegoFCmrXws=,iv:YiBcsBFVk20evpgeNIN6jBgzouUSVMp0APFVrbWkYDI=,tag:PPMNwRoSg1Bg2gmUrRBDPA==,type:str]
    secret-key: ENC[AES256_GCM,data:alMqnkqEE+O6Mn/kc2SPzBAxinLqevckL7KhvwlczNECmGQZrIoKPQ==,iv:Bnyz6zHFe7aH+EGbKDaZynBb2wOErvgBykTKtJ4sw4Y=,tag:TcCpghT5Sco+5qBr/VsY7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T11:06:15Z"
    mac: ENC[AES256_GCM,data:br9xobicwE5sjYK2LcEubPDswIgJyXT1hPHRFCrqeynrkQ7tELnqC0A4mH9BAPbM9pSCuFNQrXQ7Vv5PkPt62n5A7kaxbnYXPYICVI9cUH6SGQjlb0jb0DhfOlxgxk6y0WBGLJA/Wdk9pu3tUGCtseHMWxqJbpFGVMJVSdlcsjY=,iv:7e/mCTq8l80G4WDV5bJlaYyDs8OBubRuLpC/UqfXTrg=,tag:9jcIb2RtHOrsyAU1TgISQg==,type:str]
    pgp:
        - created_at: "2025-05-18T11:06:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+LW1WL9OQosAMT4+uv3eBW6myYCbWMqWRbRqgBNkfNSGy
            zvR8UezQCJAltXDztnRJqYY7HpFuNXv+Lj9viTM9Rtix9ImQUSeut07nBGyijfKi
            AcFhIpznmYUlwinhJDmMvL5AOxl3u5eCcaovIY0c06wvUxHoOvtzubgjduHFtyFe
            piy3srkpdbDLVA2uFiCCSOeAiXzmCEgkOQm1mu5iLuMc0OWcLtByD1KKRWNHaKBK
            ppziQTV71oqWt28x/rmeF5QnoVxt0/sannbn3v8i2GW9ReyZVf8sDQ0kI1g0yLmr
            9NrY9YfkfKGF+mt6WXr5dKv9XAkwe62kJ+sqmcjaIMslGrU+iJC3GnyIxy9V+Fgw
            2pvTHKXl5q9GljU/uRGclcb1A4Wfzm2y1ik3BSN29uqEMK84SxltdKr1j8Ztogdb
            2cWRuknd8Qm/3q5B3Rl1atv/Z4BstPk3VgCq3PrNq5j6QEpB97eCBPgwsCDD05CZ
            lKCe/0spbR2/JyKjE/2xFEbfrRBmUtNSwmClExjP0+VKVPGNndL1qvXTG4bKDUg/
            g1TNGVf7DtV14cZM/Xj7vs0SJXI218C5Ce+nPxfaSeytisD9kzZvYsJ4kTdP/bGs
            XHmRK4d/va/AazgLUMlGo1gKwEHVX8v6yTMGrHqofWppgWfqKPXn+IneEZfEaMDS
            XgHw15vjQaMgILRxUYmXct9Qs/6kegl4UN4vnXaY7LkeE9Bmy5uyodgN0Y4Kj5uo
            vcpRFQt2quC89tRVjq2OkHKFZ63V9SAdnRY/jd006OvB4yNhSDrwc6xEEUYb+gc=
            =T9Tm
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
