server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:oAhkUNnGzoNFLbNiR5bj1TeEhg==,iv:lHsan/rGDgx92Ih7umL6sbUFMlotfjkvLlM65VBd4/8=,tag:thcyRrY9Zeze4DB3RjJeCw==,type:str]
        key-store-password: ENC[AES256_GCM,data:IXORUHapB2pqN64=,iv:sIk+X1xJfYqmpNOUePuTnkYEg3Bc0ILZ3jU42vj6kWw=,tag:0ubo//AWkNPVvtBzOeiJXg==,type:str]
        key-store-type: ENC[AES256_GCM,data:sm9/UKZr,iv:ryjw6FzwlTEd/pfsruVP6b4Il0sb3Z6kxlzl3ep2sag=,tag:bDuxyZIlbMclGF4b++ZCfQ==,type:str]
        key-alias: ENC[AES256_GCM,data:uAZ4B1VGzNdpUQ==,iv:P3NkxB9ga3I4C82CnwhAK8YRxzvLUc0MMwvXUdU6wNM=,tag:ZoVYQqHdiZrFczu1XUqWfg==,type:str]
spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:OPrsS3fstuIij/i66rv/+VGfeKT/rZrdqmaQu3rrl5DKA3SZxfXyftzZxHXn7h12RdI=,iv:8nBrxtHSsJTdjjU041XUamQsr1+UUfn5H+4ZOHLq9DA=,tag:bCInOXJu7uaKqn5svSoaJA==,type:str]
        username: ENC[AES256_GCM,data:UTGyfk43,iv:pnXQJEMD5ILZM4rGo7TwVYlWK1eyj7VPNBXQU/qUFkM=,tag:C+MyCdnEDJC6K8x84yhivQ==,type:str]
        password: ENC[AES256_GCM,data:IV0T/XM1be0C5LE=,iv:9DauYy+dhofpxy67uQEBPQEylX8/pKc+EyTF7WIaqKg=,tag:++ZjYk8EDj0PEqh9kSwswg==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:nGbpRieNs3umZJpHCXRK5QOCOdvm,iv:E/q2Y71eg/evakNluwQpDUvhy1j4mRvEQlqCU8tTGL0=,tag:9xFKZ+Q0C9WohKAbu3UVjw==,type:str]
            password: ENC[AES256_GCM,data:tae+4srP0uXi96c=,iv:CNRT4bRUXFls9/JDFstJQsTQfoC/hQgPQONIUULapOA=,tag:9j7ryULHJ03OgXiJL4LsSw==,type:str]
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:IzmQA8c=,iv:U1t22uX9DP1M1h/N4GbF96ZLWCnes95S/l0qZPezQIA=,tag:poni5xbi416lKoiO14Em7A==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:y29qMP51MTWVpiNqP0+0moa6v4hkIQKTbULp,iv:fN+O9FiyyjM2NqwUAZvbuYAs7JGO7LECOE+84hBJL48=,tag:sG+cJg1s437YChD/SkHbRA==,type:str]
        cookie: ENC[AES256_GCM,data:vMSTDw8DIANQ,iv:652ZIjuWNKNKcem9EOo3B1viiFjOdTZY342ecQoGljY=,tag:8dXDiebuDbB/J0Wq8rPBJQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:t9TCmt920nmLW1Prnar4VhyQXN1ZTMB67gvEgtMPuG5DrTvGauyMxW8HuYs5mhO6KU6A2Llx,iv:tH2+apuS5D86ylu0BIFl0PkCmQICAw7t4xqOjjzDS6g=,tag:Uo541NB0FqK5mnpEpF2aCQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:knykXu7OPwx3ezh8j0Z+qwyAFkO47PYJInrnnMBENQFm/xUQiklwbgapWM26BH7h7E5l7BBoZg==,iv:lwVWp9dJvMv9VYAFQ52K0QKRZ4TQUBbuItE/w61dqiA=,tag:r/6PwrQ+IN+tKrlYGqQK7w==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:MnPbOu7CEpceIcnyow+Efn5kBFMWxqojt113qoVIs7llcAN/4QNdux3XCwjDxa+BxBs3CCJo,iv:odZBi8QgZb9sHzzbu9bDq83Ll8/KXoP20Gfc5FKDdLA=,tag:XhHTxiCGN0CFa4VVrLpUyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-27T04:37:25Z"
    mac: ENC[AES256_GCM,data:/fB0UldM4pD5FuJM23LohxQ0AkmAVjQ8KoLd4k2O6tpEv3AapcguHe7mN/CEThSqxRw2jmhWXsLi4IyRemwvYeXNyRabBZuOmZ/V8GvN0jcDho2uup9sdTLrSpifeofxo66c+rArWUxATOxukjkik2AMBWJRNXN5Ab5VHaFQE4k=,iv:wjXFCCFfQtpF54qdnpqFwPHbL/05evSKR88m+gYdnAU=,tag:XUrc49JUO46qn8kTCNPN1w==,type:str]
    pgp:
        - created_at: "2025-04-27T04:37:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+M3f/+JwRbrgee6mLUqeTyRSDuZW0v78iOShBFrfHnk+s
            dJ8aVlM4YMJpw1sjlvaivvi0s9E7SJsrlkPgOorCam7t2og8hS7C0Mlz/9Dqvjtd
            09pi+VIEpXORfGq7UFD9xzy9P2ZHvJkOeqGp6n2K7NhxrTJTc1W81kaqtPDM33Bf
            q0OI5VKxrUQEY/VNAgUEBWdekNXGDkvNZsOZ1eu94q7HiRuOb+D/DLEOv84nb62o
            /8x8p87LM3YXZBTJUHSg+PB072nZuUhprFFvoYJA/h8Rk4riw4LiipNz7qU9C4JI
            f6RXOv5rnL/HFvGeBjZ7LgDtuxvS3la1E1EhKxVvFZnPM8LggHp2OTepyv9kr8cQ
            P1TvmclC9YK9aW6FalXsEJcEBHHTaTb27gkAr/5gd8ZDGi6v/XYryF0gLHGyKpHK
            MuR9uCgQvU7VuSLwYWxZfFvfmT3IDzqKQcqXGnXgsN2laaXD+gbXRZH8hPntfPxY
            Popwobt1pNJJlEPKki61GBQVAN15a5nWNBNn+lfSmd8YqiUk2kMm/1+FK7HU+xjD
            Jxrko4bHqq2DS6sLuLGLL5sYlcqS17oSM066x5UN2e+ndJBE07zK0Y6cpSsF9PQW
            21UcXsUc/79Z4RjgK5DTOFwNggRb1Y49xTdiAYKwh0Bhkh56uR7luJoee3V+BqjS
            XgFb+JzlOk/GHZ1pr0lVrlZQX02fRSQxZzaL45HBmnSi3Od1li//OWCLANVOiJAt
            8bv6ImAG0U/dkeTwEOvoWBg1r5AqRLJzIly92WMrB6Tix65LxAcYOyw/ECeltno=
            =LXVR
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
