spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:AbEZCK/bpJdOj3F8rY7AiCLeRBDX8mZZyxE3/I++OdVQ+ANwMwa3Bl1W1A==,iv:4nZ2FSfRPkmeTJKBGMVe8xiXfrg380dW31FVzNBvAos=,tag:p1FNBhpkmpodCJLNo/qWOw==,type:str]
        username: ENC[AES256_GCM,data:aomiKvqL,iv:WI2qWjplEhhRv18kehnPIAgTCYX8r0j8PaJlWciS/w8=,tag:lgqHG5PUShkt2KMlfAVy0A==,type:str]
        password: ENC[AES256_GCM,data:WOTh0Ug1jQ6celY=,iv:5R66DxRiqtoRwzqUqStRLIvBS1aPXIhptG8tDlFVf3o=,tag:y+CRcH5mj7qbAhJaVRTtEA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:K5eiAhnlOBNUNuaD8j/+FHSJ3ak=,iv:AbwNAfxEixXMyRUOBVvpwJiKvvr3lMcoGv/if/J2LAg=,tag:StEZuT5fB3KrfyTyiGwzKg==,type:str]
            password: ENC[AES256_GCM,data:sIfJaX9EbJ51lUc=,iv:6M5tELDKA4oB6lmjh19eMUa353o7CapekZwagml50wM=,tag:nz94qc9vy+XP1+r5nPAk5Q==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:utujVWE=,iv:xKFK1zRWzRch09L9Y9PzOEBCwq+Rs89lOUbE1Mvb3Vw=,tag:yuRuOxhf15qqEhHMmPotnA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:snDD8iXJ8iqelDVSH94LPBIg1OmbQC0UAuyZXRl3,iv:ZbN/mFsigEwkQ6i0BhflBEB1CurZcqGhY/Z0c5Cz4sc=,tag:aP/Yk9OJHcd9oPxtJQTByA==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:0+Mfk2YXvSyeRnSIVU0sneOxI0+10QcnXAN8myQR,iv:Y9K4sfPGBGMm1gEEX1biol8G7DMKQcKAvPaaD6oZRZk=,tag:ci2fDxdnrfLU7Wm8+jJKSQ==,type:str]
        cookie: ENC[AES256_GCM,data:88SVG9hinQUsewdgnM/VZw==,iv:igpVqDIecN1GFPvmz/Rh9vXwj7kdIIBri3SqAjIK88w=,tag:AZdGielKeHL21NpqfpJZkw==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:+klbZ4fCd0bO1eImEqoB7upmdM6jM+ocuIpKSC2WjEXnNejicddHbRIvsrc3KEHdPmtAlVk=,iv:+NWXs0Id2rapdQYBERp19pZJy/G8SXSNd5x33iUSAeY=,tag:YeuBXdcCcFFZzAssho17WA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:BYuGvuiAt2yzRLbz/nuGbRbQRSTvtxm7g+CP45PRsUswCSJqrSm3drJ/YnHE6ZxQGDhNL0AD,iv:8pSGwni4E+sNa4baNegc5TvFmQdKcIerDTnkrzDAcyw=,tag:77DQFphtJWCSHayKpnZ8PA==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:ZSO9AW7WCNErnFnUP/px3mzPitBUh3ewbe7dHtHpSsKHUeE+hqUSk8oSD3RqxAI+gETLOGA=,iv:ijyfFK30TeNcSPAv1Je1NyoOsY1+ve5PYYXGH1JjOv8=,tag:qaAn01YdJI2+w6ZYGlIUbg==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:7eJmEsSAtRtgmNpkf5GsknH0nQpXRSg++jv67XNiFIYJ,iv:GdxYM74kwCumfRx6uCoNzKpHdxqmmGf2iWqytEQv/YY=,tag:5mSQfk8uRJgHLnOWss4aKg==,type:str]
    access-key: ENC[AES256_GCM,data:GzONNfnf+H6gA++S1KIvxmxXvxU=,iv:A0hCaSoWSMxRAUdXH5JNNLC2VPjLMRXsX6/y7O2B1cM=,tag:DOylMcCzfUtVnshgN/+lrw==,type:str]
    secret-key: ENC[AES256_GCM,data:HNt8svTEjLBKezi2f734SG/F3IDAaBFdIMAa97G/imSbrmXJCBMqXg==,iv:v8ZWJwIw/2SJIkQopqqPlSWU9g2pGCC6L4LgvPu01hE=,tag:FGHkOjAjEytROrehuDk9Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-30T15:29:17Z"
    mac: ENC[AES256_GCM,data:Y6QFbANrgDMzcga8OTub8lIy6HcsngW9ErjHDdBYS3RAYwFoGsP63lLEq4B0Lkr4iT88ZmnYJBrr21WBpJsKjZTtjm8bsHHSQ2LzNWHmJ5ZLomUtk7r9GizqYPGGm982WIx+zLj81HEPL/Sk/uLMvvF0YVjG0nt+2tDgCw57iCc=,iv:4+BGwWdrLmYJcPLsxRk60KCGQmQ7McADv3n6ymn/278=,tag:Yrqlc5hDxIG4WU5vh8am3w==,type:str]
    pgp:
        - created_at: "2025-04-30T15:29:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAhhDKgwGe7p6rLOa1yt98xxEwLG+wNtgdNdcWn104ciyB
            b7LhSOYnOCy5l/cuLsB1vqaQsGy9M52/f2MWJLndh95L76DRJPMytRN6AWcqk8fJ
            xICfEtr7cJXWqPP3gRzUNMUrMj+xGvlXyeQ4w46Trc3ru2VaxB9AHCPCOif8Nz3D
            NaLc5lA5lrWZLa0E2wS6cPrUbJHzyfLWLV383s7fG7B1eyewib5K3b4BXoE+Vt6I
            yaYPsEIWfdOcDfpGVdsih33zrAEXaLeFy/jIsYvcxYeDiVcbbEXXihliyoZHydlX
            PgSUexJfhKM4asV9PZYktbQQ0KQ8Fs7ZDeqog2HSRI7+Yu2uVIO+74alrtB56+ub
            dnqJ5Fr94FhXMrUyNBsdTYyt7FtKOYwf8Nb7GqUzdoFtkUuwJTKIQ21GyBaOsTr2
            DBGD80Co0nPnzaeKCVdGj8oVgyZtc89GpoLquncoEWG63BITxGoat8c13mVPmAP8
            Gm9s8AhR8BIysIwldIikgQTIdRj6i/3/g81vGgwQ+iKab4mSboEpDfHmNSAhY5pc
            6/ustm7SRyLKZweGsWWw1hXDKqc8TZW6IhThlh6+I4rYnfbfuHDkZmwYZFknKdsk
            Q4Kth+hI6joawzWtOCp9xktrrgLqvApho+SmTMesaKYWmgGFBM6HwSxmuhYkY/LS
            XgHpJnCcsgiAsq+zxTZtZrXdz/owQ1J0PZfQuqa+nmBMINK1pF3l3ND4o4ZrYhYB
            OCCZlfShwSuJHCmGhVKyUmr8YkBhL8+dTuwxCrqQEzwbqyyC0DTxUnYPrP5IQ5E=
            =X4VK
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
