server:
    ssl:
        enabled: false
        key-store: ENC[AES256_GCM,data:KGyVGV60xaT1WrTddENhbjB2tw==,iv:6QJO9ZYSj2HVka3b2R6DsHi5agmP2NM1C2r/fGrsgyU=,tag:U7r4qgyhhEtNJkq4+doTfQ==,type:str]
        key-store-password: ENC[AES256_GCM,data:0/Uh9w4T6ccUMN0=,iv:fHhHc1jWU+GCCQQitZiP/EFxz+BKKxq2/jab6smB5wQ=,tag:+ICpXMKSsFCP4+JKyVo1nQ==,type:str]
        key-store-type: ENC[AES256_GCM,data:2hYW3veu,iv:kb2OaoXciQ4IrK3u9xXThwUhvyqmVmS/DIXJT/VNjkk=,tag:Zyhy9sdDXe32tpQWErzLCg==,type:str]
        key-alias: ENC[AES256_GCM,data:AnfUG725hF0IEQ==,iv:QuOUfDcBj+wYm8x1yo7zhQHb6Ig4iqxbHRngBER6730=,tag:T9zNt011GEfJTjrYIXdfZA==,type:str]
spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:YCfR7pO8WPpnWdXAYVGzamuzj1vPU6vFppp1rcw5oiHhAEkzy2W25MF1uw==,iv:VRvnRrna9vzncr/fz9lGe0w6WSAcPCPiKBNQceDcKYY=,tag:l+MDpSbKnK5bSwlpMH/6dg==,type:str]
        username: ENC[AES256_GCM,data:WfjI5iib,iv:Ljw+WWSPFjE+CU1x0DAiXG7dVlNMPmOIHVlKVsn2iUQ=,tag:lzjx3BWbr5T9jeSjMfoMvg==,type:str]
        password: ENC[AES256_GCM,data:/ovOTfWAQRwzYNk=,iv:8I6dpWNR3MUznjS5bGSYz+f+gK2shVl70JPXlWSDKQg=,tag:TajtXmFa3w1+iXo55CuhrA==,type:str]
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:bA2bU16q3foHHYFRLl3VI/f5RLE=,iv:AB0LYpT41oi090VaCRa6h3W+fVAJe2IlJZZ4jM5DSMU=,tag:9sRMJBbtodnHbHlmXkzwIw==,type:str]
            password: ENC[AES256_GCM,data:Fze1zvpQgMkPJKo=,iv:e2B/MYljDMUbVSZFw6HdSXWxCCYvPNEegv/DtJL7s8M=,tag:otz+ej14Mxf1huuC+USiUg==,type:str]
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:iZwsIcU=,iv:1u3Ku223jhvvjmZmDhvXcwZ00I4BlFbVHa9g/ZaaVZY=,tag:XC2e8wYYPqPL7uDOuxDCmg==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:oK4Izg3Mku8js+qLsaZliESkFwAzzSd849FRmINg,iv:pShTdG6Iwl3NB5KzIsJmQ8yKcTox6Mvvers1DjUpz9M=,tag:rz03wPM3iF6mcgEYL6ubHA==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:IOpgnfo9P/BwR0EAePoape+tD0BW,iv:x1oEuFHVCpT5eeEDRPxTrbYhv5pyzoy9xTVsSMntIXI=,tag:AcrwaDVys7us+cht59iwjw==,type:str]
        cookie: ENC[AES256_GCM,data:PRZQoCdS0lkJ,iv:P+N5EDwwbvRiWzzRkaBpWbP/eWfPpfqbsqirqEaJnzo=,tag:xb1a8pf/a1Xbcf8gh0gFhg==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:P4x/KJtiCQr5aPyD4NQw6CjWwoyze3h0oTVbo5OocG9Jrj1XCKBcTnU+2let2qZZH0oJh4BgGiQe7gFZs+ux/g==,iv:wD7zowANYj9f1wIGNWmAM6EeLvvfLYLuWYvVuYWyU/U=,tag:0KXWi5phWsDS+JIspOA9ag==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:AKWBSn96RV20/IdJlcPR6VulFnj5BPJKkU5hWlFZTb6G8tw+bLGynNNRgnF+SPvw7u2dZ/BlVH0t1edY7ce2HDM=,iv:1maam9HHsxM7SNSpuhzG35UKtVaen92REW3bflc/sAg=,tag:s+T9v7KxZq5bSclRGbhuFw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:brctRTXOrK1rhMTypbUWwbaaT6jX2o6hdQTWqF4vjJcfAyNSkeSm78wvm0zo0Tv3Owp8mCE5lD1QZ0EQt+ww2g==,iv:opXOQNTAfB2R/XQMn4mQ5zuOmf9Ip8M4PawPE0fYD3A=,tag:B1QapgjXVy/+6Evp6KfiwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-11T11:37:04Z"
    mac: ENC[AES256_GCM,data:kDnpUlDZt2ouyxeOLSPreayl5xayl2cAY6a7voVs/dLZYiSLFjLyPUsj/GVyGcK6FMsM6yli3HS8CpSep5v+iksuovDd6KJGdmSTcdhb/kUAdzk4vEAbMFGsg87UzdrXBPQqeZz8SIVpPkbxNXn4JlsXWtDHbpCip5K2Oypiwg0=,iv:ViTlwQIltgA+iKkQYawgWesRbB0xXl1yCXn6iT3QHqE=,tag:WaDZkgDh4icL+ypZtXQK/g==,type:str]
    pgp:
        - created_at: "2025-05-11T11:37:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/8DfEb7rgVKcPu+TonBdEZnCGzEsqbPzub+glazSnAljIZ
            cSD33eiGHcHWdTPNwxE2FVV9/zfLeu3ZX+e+i9E8WmkmGOu7/7gRS2f5ABl5IPbw
            D+Ah5nt33zAZtruohQJfhFqT6ID5jk4TWKWH9wb8MuIln/TtdxlOoK3ZP+jzqc67
            glMo0KIcnash9eO49DTf8Tt3LRNcC2Zv/ki2BUMI+nB52yHVox4AT6AYFAaNqm9X
            Pac1yeOue4ubZ/XOCTwEBGtrsb8CoX8y2wDd41IwlhbuSb1Lb+jYo+/AehAYk0CF
            b+bImF2GYJ+06GwBqoetqQb5x7kO63nila+eukIoU96AUB1VZ17xYresjOiIj2Zb
            ntPeJU01THFT/ddkRNygPFmTIBKlIDn6ROPmlwKPZgqSmyfPapHo3d39BWhuOl2x
            DlGzCViq+nKcJqbyE5QIBemfQII/Ca5N+rCAaMErVCb5H9roDNX6Lpq5gPgICxRg
            9Sou3snWc/ZNdOF4Jp6dDnI/vrJQtUZXneWVR1JML5f6sfaatmeOzrzyQaVxWTcT
            eMLBXgjD5ih4/vHJsNjPeP/yQMpOkZ5p3Z68ffKxXhuHIgrr64j4Wjne//14q6Wl
            zgJ+OAJLOUA+mqckFDceVUfI2S3NLBtJGQrucSlkprp5RjWAz2Xz/qGJ6BRgidDS
            XAFtv/2Bp2EPY//xi57jSit9nuMk5FAmgBUNyoOYU8wvqbNquE1m63VenYAWItMZ
            xFoUPLJlrHikAJ0k7IYYmEkYhM3OdPctR0qany7d+zIeRXgWCATkXHXOAhAr
            =uJwr
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
