spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:VhrgbZw6Cqps2OjDUaq1RFuBu8j/vSvACQVC29ko0ybrIZLatGz6k5HKGA==,iv:jdUOCs9fnexPo+MjsTTCqpwVdh6/ycLz3zgOrEsod7M=,tag:0Ywox+boZiEwukmjXmBUSQ==,type:str]
        username: ENC[AES256_GCM,data:MzthMplJ,iv:WtA9Jv0Z4Q0RCCRaEt7/a5oLmTIcgSaY73uNNFSWIX4=,tag:0S3Hkb/lFvaLHt9T2k+bMg==,type:str]
        password: ENC[AES256_GCM,data:Ag/0W4eknKWOFsI=,iv:BqnAt4W/oUgwYrrWKFrWGHtcyFlVmgkaLwi9Lucpg9w=,tag:dnryxcmS3evzrMrkpkxQgA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:XHkWSv3CfE8Aw4Q/8vuXF8R6XMY=,iv:Bnu3sZTPWgjaZ9FyuwkE6NPMF4JZwDOvKOibCs69q8w=,tag:p9latgQFUgl8dcUTBXy9Iw==,type:str]
            password: ENC[AES256_GCM,data:VeLdHq98bHTfyr4=,iv:f9BpPXFKfsfP5lWuh+mGODqe+mqrOMZPop7LuUpLD18=,tag:UkjL6WTvKpOy5+B9ldYkNw==,type:str]
app:
    domain:
        frontend: ENC[AES256_GCM,data:9EajH2M/KWxgoQISGD8agbQocX5ar3anVgMH55+Y,iv:MNaRfZaMzfCof6wtRVRwbSQa/P60W5tUVdLRE6EEATA=,tag:Eo9Y8pGDqi/6sn7WVXUsdA==,type:str]
        cookie: ENC[AES256_GCM,data:ON2isHar3fd7AI15jOHs2g==,iv:G1wMfVSFM40M+nA2BB5DdNH2l8dqdLxCFfoB0h8oMWw=,tag:YOKCzVZ2pHAfTfUiD00rwA==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:ePWN53EJD9Kl65Vd6pQLa75E4X+18si8L2ljsNNcr9SCNd6VrM44uiLhU26hOt94+cfMxA9/vPqh,iv:gHuzevHpjXtYd+spx+F0T2x3cDkWTzcSKqEVi6OdjD4=,tag:b5EyqKRCfvFVGG7Za7srHg==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:ErCRYHHLBnmJFrsZyhFMtX6xHz0HMwsI/eioqEwtrmBMhY2VWzGcgh2/OHbCjJFG6bldlNo/gT/gyg==,iv:3Sq324TpHDwNFLjHbjNPj/sy7f4aXNGo3N9XZ7r0T8U=,tag:22CRWQMLuHeMEiWQp/83iA==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:hzRwmgnNb9/1QoNc4foij4GAQ+cdgA3mgU4GYYz0ohoLOxEQTfekrI2D2w1ERRpX+rckNj2fOse2,iv:xoNaRi5pFpRCa797qqEEQn4RTP3u0ktBWQwW+oO334o=,tag:iWScXU4vzD0RlsUwdeCBig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-11T14:16:42Z"
    mac: ENC[AES256_GCM,data:rlM7/8i+jwLnvD7RYs5CvzdG4Rxbdco/HNS24Da5EM+NTMtiWD9hFKZuOFXI+sCXQrt9Lqo5uZsIxCF2We/1ylkrJvsJqD36tSjw+bCyGyPQMMKqXf3NdUPSqfFRvXBUakyFqDGH2HyYem2JsbQY2g7NqZ+aNSdcp7nT04lkWes=,iv:A6nEi7jH9+Rhz2fkPWUISCAp6OTH10D+c/ufSGowCqo=,tag:n4BbPHj7VC2K769kllhrRw==,type:str]
    pgp:
        - created_at: "2025-06-11T14:16:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//V+Ai6Hw+/pgTiphTcrbA6nfTkTbtO0BsfLE8yYGxotdz
            BTEPJkLo8RPskVbRPUo06Jtu+AM432choQji4zXgDhNJtYf9ykAs5ejO0WETIYtf
            yNzjVKdB4zV7JhPD4kcKIhAh9rj36aGmf5SjDdlY4vtJiTvU6dcvbN7gzUbHa86r
            t7GN8K5Gi2G2YFCKbvir/FgjKB4kji+D0HHlNpVbt9+9zXWmvyYxVbdga3dXBTAN
            GqOgmBE8VG4rgJtBSw8We5F/OPYAJmX+ietCGBd6Y6ozHy4JEDgWkubGwUtV8Ddy
            Ls8gNeJfy5A6mMfbK1VP2z7tv2iz3WSH7Hr2mJB43cLNxJmjA1vy1m4I3VNqlxeO
            A81NJgEGlD7OGKH7FnLyzYH+FLU6KcQhhSNwqIIDUl/JcVDSb4zhXUmLY+DGsago
            1oBTvAoIObR/8u0JKt0NJ0pnFFavh3aR9alskSat51FrtbLSSpHR6s1wb0x5GQNs
            UhEaVL1Wot7Be5WcA47C8KwQqhOxj6Hgy0KxWvaFrEsXKAIshoP4eY3w9oVFsrzb
            /8+j+Sl5XxlQQg319bPFUGJ0vwXHesGyO+y/Y+PYPJG823GPfwnnzqWeFxl5Oafy
            hHTSCT+X7UcCrgSPk4AGDfljEoDZpL0t/Ytr21TRizgFbxCICTFzxwJEHcV8H1fS
            XAFi5ccuVnTvEK0vt3UPjFgTvjHdP3nRXZlZLq5XQTGeOKO0BBIJANIFv2/AI2Ho
            77ySWRudlNOau4X0/fjWYA7OaBHdgv0crNZ1M1VdG0fjSjwS/CkGE8LyqEin
            =HyBG
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
