server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:e0ou2XkI683JSN6OQyADxiaC4A==,iv:Ot2KR4LnTxXDekQ5SV1xhCJO47poBMPCe7cCd2bAkDE=,tag:8XKOhNnJoQ1teCprCdh+ZA==,type:str]
        key-store-password: ENC[AES256_GCM,data:5IIvIvKaisNdzm4=,iv:5yw2Xz3/PiI4JRjujoKblxOSNB8lwX6IaeBkfAhyGeQ=,tag:JpdqKKtHOkAjIz+nSauzPg==,type:str]
        key-store-type: ENC[AES256_GCM,data:N+wxKqvK,iv:Nbz7CQxoKMtl8L1WGqPmmYBUD/nQRkQCFOsWanVAL5U=,tag:lq5h+pASciKPLfpQQnfw3A==,type:str]
        key-alias: ENC[AES256_GCM,data:rKnhA6YGTFEMug==,iv:Wm+HtHdoWaSJuAjpt+qbralN4hmiAETTRY6ksfgBbug=,tag:PstiM0ZNj111GI1MJqOsnw==,type:str]
spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    datasource:
        driver-class-name: org.h2.Driver
        url: ENC[AES256_GCM,data:FYt8TqS7GGJLcVJ3RzkOOg==,iv:w1XB8nJM1UAoGLZ7eW00PR7cWvGX16s2HMOkAaCHWW0=,tag:woTzB0W95JU04bglffP0+Q==,type:str]
        username: ENC[AES256_GCM,data:/TDa70F1,iv:+rVWxtbjXeJOuCJxCeaopfHGw7sjeV010IjyA1wRKZI=,tag:ievM+GojO+QtJ1a47mUpqw==,type:str]
        password: ENC[AES256_GCM,data:HOpxKXqL6EfAVSk=,iv:7I87mPPC9IPc6f47p7JbAH4N94ntDh/00NEhydQSVCY=,tag:yTRtDjaYC/5+CrD8VEzHDA==,type:str]
    h2:
        console:
            enabled: true
    data:
        redis:
            host: ENC[AES256_GCM,data:J735sdayAdxCKDN8I9jOjAGArFXr,iv:bUCwoN9Sufq5yZ+DqU6TOplIuSDECmxV2Z1nqEFFHWs=,tag:wvQ1a/1JesZEaUDnJLq+ww==,type:str]
            password: ENC[AES256_GCM,data:znYNbSqfc/Zov+I=,iv:mviOQMbX+BTCkML0vCSvMdbrxwt963kzeUBfYD1/0F8=,tag:hUzTDX0xlcvOT88n/u+TlA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    flyway:
        locations: classpath:db/migration/h2
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:lSlYPA0=,iv:Vgs0YN4pZJai4rhYlmnSoV6ChtPU8TYKxM4fAcViyJ8=,tag:tDRvQy9ixv2QNwyrb/VA5A==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:UHYz0Ui3tIrhsyxaJLqZsEeXkgiZQ/mIdtUQjZ/c,iv:gF89cBkupmMvfC1dBR88xB5XIEeFl6JVtyyZ1Hce4nc=,tag:FCqTGKXNs2YXE0brWnyBig==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:LQGgHEZhgbB2AtsShyof5Yz5/CIx,iv:GgmaOnbs3j7kpvbGFJv26Ht5wJ07nQNXwxlheGnkRAI=,tag:ZfG6hpf7q/+b3JUk+qOouQ==,type:str]
        cookie: ENC[AES256_GCM,data:bsRSEvK/RZIy,iv:siWXrFvRHuAufMpMm+C7Eom7BDl808OVqGGP1Ok8a74=,tag:u+pChrC/78B6/Jnsun6R7w==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:9JLniWNJx6Q9A8HXNQw5UqGzTp6cqBY9LBRGbqHh6Llu66tF2ouceT7el3ZlKSC4ZJDNcqt/,iv:Db+wqlQbHXlwoTihascYtvrD1U1q7Jjjuu1D+aHlG6o=,tag:+broUdYNm6//rBdUbBzQUQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:PCNMmg7+yn0dSwUgb5ONt5Lr7hkAFrSVQBbdtmlnfnOHNH37b94q9Km0lRJkIrRcnHe7zfT9Bw==,iv:udr7mf9zrF4p+jHsVamXnr5pMz/0Rm+RG/0cZohxxpI=,tag:rULHN+iKRFNY8wJVV8UJbQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:6xR7UwnyiD2y5Ott9/dfx5BrAARGizQT7DcfPUdPKho41HmpckwSzEBbxBKtzqmruls/9dzy,iv:3cWB3BKVW1hdEeXSCsV/0GSxtixqtZshvg5Vc5jGvfo=,tag:JErf8yxBvvoCm+RveHy3YA==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:Zf2xkEJvu6vwXk0Fpoihc8FzmRlwiRq7+/XF0koOsd8p,iv:dqZdHVyiBO4VxzaBOq1BquQVqZXoASaJ2uo+q3Lp3Uk=,tag:5ZLbZoS7TlErb7/KG+eFSw==,type:str]
    access-key: ENC[AES256_GCM,data:bqUeYTefeTRguokcAE6O7GUaqFY=,iv:9QBhbrTuSyTRNxrEvT3LiHPxDJ04JNnzyy2luLgIKlI=,tag:85QauR5JEGoNqe4smSv8LA==,type:str]
    secret-key: ENC[AES256_GCM,data:GH2MHWZQd/cZwmSV7fatPqAtxMHtkZ0GfledsKd/x7CfnQFviMWI2w==,iv:CHvCB2dGX39WMzpGfqTEIWe+huuIvhfWO1l7R702+uc=,tag:qbqTaMj7/hKGqzIZcIsxUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-30T15:47:57Z"
    mac: ENC[AES256_GCM,data:edyd6s2Nl5QHhMd/VyuFGwrqgnyxsSvv46ToAevDdAC29d8al6aVSi8QOyo399RhHfh2At5GLeW9TUlyn97DgCH2hMl7jXSLxZy1K/YxzsHnzY+UtvwFUjjIa7MaiIWSI3RTzPl2yDmsOx7LuoHlubWqDg8onpnJOOOtk1B4PBU=,iv:tg+2Bwzz8iSV0Tv+YdOrpaZyzDrT7pZDv9KX8mOV76k=,tag:S+3qnlwkgvIzcKAJopoYEA==,type:str]
    pgp:
        - created_at: "2025-04-30T15:47:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/9FKSTZ8WqVIXy7wshlUfclTAd+8BHn/QGs3eBeykXnkUR
            pnenieoa3egI3Bgs5YuWnUU+SQKYtahQO+QJnFyDjviGygS/AZ8BCHazRcl+V0MA
            uTYSMvAY1aIEWZVv6V91sfeE6mUc2LeCcioM1Sij2mhgrf8XhwiWmKvZ63y0FsOX
            KrxcyLj+M4i+2nYBktxa08dxNPwmgd7z36aAZgizjPf9P9qe3hvtmHowPVsw2Hdf
            PvmkJ7eV6P600E6xc4JxDALMDHuqr56Qt/CNdw6LwCnTPq8EHgbpSvCsPSxP62xC
            MXs4mA7Xh5X7vNIXpGmWFWvELSyqquDAxnJXZP1XKw8O0y3Vo2Nx17CCmoTkOFuX
            cl/lytoDdadK+gGHmC82Fa05cE9Ov6uqn3+KoMHxr9rFebKnVeKtD/0BICwmQ3Oo
            nY9Pq0aDzpb5e9QSxhIgGlQVPVWyM3OcJ700I0no3oVTNpdFS2X4G4qA7BtLYLB/
            mfyHK7ER55B7WrYHeQOEFFYIseL5VEtUXPJlhpxUGtvhCj8XeONpgbq2atj6+Xey
            7sitYX3KhSAw8tw1B2HYcwet/+WtEZWjP9wXmT/EF+hyGK1tXQO+L+JYBFyouxLe
            nVENIg5gczj3uMgSVPFVW2JO5cq6ra9mnEAEbFUptQcY6IaIYmrMJCu0PFJxD6LS
            XgHSDHonQWiEcaS2/oHyfBT7lpI5DSTkM05XMH3v7EJZnL7m4CFhEdGDZXZWZhD8
            Re1OIlhHaUdMj8zeQPOUeZwnN8pISZQtpsXTx8NFgRNh1+7/2mGH8xPqlaW5DI4=
            =0Y05
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
