server:
    ssl:
        enabled: false
        key-store: ENC[AES256_GCM,data:FvB9A917clpf9Z2itSF40YgN3A==,iv:LICkOwZSPRndIrwBlxL0MCn0jCo6fnl2WeP3sHCxMyk=,tag:xZs1DE07q9CGAVT2sK8ABA==,type:str]
        key-store-password: ENC[AES256_GCM,data:lru0iKLU0YzSs8Q=,iv:LGjGc90Pw/rm+k9D4hGDD19tm5GN0w4nGsQPf/TycDk=,tag:wbe0INIU5sYS+4YWvVbBrg==,type:str]
        key-store-type: ENC[AES256_GCM,data:XkCPiCeI,iv:yRiII1ZKJa3IrJnPgjYYvskEnXtWcehlCjHPcGd+sF0=,tag:J3E5HCtGSlMNPp4ed2Si0A==,type:str]
        key-alias: ENC[AES256_GCM,data:ik0wMwknLGCF9Q==,iv:VRrZu/FAMwPy7RgqWBXtFvjF482My99liZ2NhA6MP/w=,tag:Us/wpYySYwWMkQ5LIPPaxw==,type:str]
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:BfnMmdeseUylC8Q0J8JBwDKdSwaHtKcr8/NErxc3BIqdnXq/JIBa4MWvTfdgJ8GcPcZ4uzKQi3A=,iv:SPoZJ8R82BvnVfEq6+o6yqsHuVpc07rp69E8gQwwmys=,tag:ZgVIgQgM46Yl1vUGRdOhXQ==,type:str]
        username: ENC[AES256_GCM,data:2VsKcGic,iv:USoNssWRjSzg1qTeGduKAPyJ2wEXWIN8xJYpMIdXQoY=,tag:gjiV+m1bnFCfVnlYrMytDg==,type:str]
        password: ENC[AES256_GCM,data:aDAVhkQmdim/Op4=,iv:UlpzZwM2TNvehRYwJh/x4hvVboNgfTdze6mpJoO3pio=,tag:6E4bZXJ5XmFnhFN9xCQD3Q==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:IRwkiVsdhMenQ3VpGZZzFiXKzIPR,iv:BXsXrJheMRtOcfEAIYl3YEv+EH//DHO2Z3Tzdw24jJk=,tag:gZuMOtrw3FGcfJhlYK5zVw==,type:str]
            password: ENC[AES256_GCM,data:6+hQh5/b6zmTv2w=,iv:/PpfzMAkvf8iplemlYlsuurRfyXWzJUeBbxjzOK6ryU=,tag:LX96urqL6GYViDpwz1y6Ww==,type:str]
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:op6MxO4=,iv:xxx/qXfuTGoFSoaaaZkaDaNt74/XniFfP5j5Q+6iC18=,tag:/0j0EPWV2hwd9u0bkuTLLw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:O4+eJc9g0hJwXZ2ESurnOM/s0CbMoPTtQ7iNrHe2,iv:Dzm58mlQPBWpsOxdBuYn5lq7+AQk1aNAk+kXKnDsbig=,tag:65ODjSPP3lKrKe/S5w8LKg==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:l4+it/1vr+7iC24Zh8hdDZvujZpk,iv:b/v7Tjd5Jfq1IlEZIq4JcRzxY3X3k6ugZvPAunz9j6U=,tag:EK4emXsMOTFSxcDmlgqX/Q==,type:str]
        cookie: ENC[AES256_GCM,data:EQAjP+H/H+Ba,iv:1bDumoYQNRmZK13oq8lD5MFKZTmzrmqaiwT/7J543BA=,tag:sDpM2U1FDupLuqYXNhRibQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:JM6JsHTXUW7HcVG6k5bdZ3f7bYbOFfaj0L1F7IC/KkzoIH2OlWnTNhzRNRFgBuHqp2tBGe6cuPVtHY8=,iv:77rtpGlmw4oVmdfS3tw2NGw64UtgOKn5fjDXsII4obw=,tag:RUCyx9M3aVSfiQDi7C65tA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:ZgGnh3mvHnCgPFBzsS0YphuLAq77sJL3EyCZDFnBAb/Pw+V+6v9DuILQzFI06gpX3rzXAS71oviGlSz3,iv:sBjnJXZmoYLKTjFEX6PliZ2MABGQaZkmtwO9UGfFx6I=,tag:QhjFff00cq0l5NqMxMo9gg==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:F5qGi1wG4NMcAUDZYFiVHtWhmNGPebU4jWHfNDZNvsjnOhZsR1zw2dOZgZw76xK1B+fpiWDv4CXLCR4=,iv:D8CKvMPF4xTAFxVxHdl+dNA27CyBdhME238bhZen7UI=,tag:M3JFS+YQYaWTeFlNs7Dmig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T15:12:25Z"
    mac: ENC[AES256_GCM,data:/y+p3znuiAtlYJTQNWFUVHqtfu9z6CV/JRzR3cmA/l4f6CwzNhYzl6ybANaBY4Tdr/8I8put8t2I2hv5O9PJ1bsUJfxocqlmUQM8FkE6eR6LKfeeOjX3rtSRKvg9NlZn1qRyBlHFQphHzWwdJZwApgEKVGqGRXVjZrpmEjJSdw0=,iv:VMVUBNpp4ZiZsr3KqTxEVEjWjyUrsSLt9Oj6hStUUWc=,tag:TiNgHVh58M3vnkicOgcpLg==,type:str]
    pgp:
        - created_at: "2025-05-18T15:12:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+MXQpPqEPUxpKu09MkxGmy7oj1OlLXcYy+o/masCxaKN5
            j83WFllcCIPXNA1m7D7R/yHX9U4beZE52PR1J3/8ZR6Vij6NxgKS+R2B/OkEWHzH
            MSqIjDo9C9np4aImt2K2pa/ZMgvksP9kgfNTdgruA9cPcvRE7tZdUwTFC2WAbOKL
            SAZR/9Ypr5HBhSjBoKnMH8XuDY3ejFPz68njYK4KHjXKVOQEz2yLube8eJSig3/f
            SYPuuY8VsqSqcxTlsvTSmxJpOb+njojiRaPxkbPtZYzUyuLayh+j1XMrmpgcOdWW
            suY5xtYQlZmFnPiWWxJuplRJ8B4rfGa/XcTEUo8x684st8FvDlEfWmubX2BYJuQE
            9Hzld3mQp8WO7dv13q3B1TVpOgqsLPkp2ey+3+OQ3qXQRlsPohEYxlEiIdhzG77I
            J180sDpZJcLSQxLVsXa31OhF6PWRUv1M20/Tsy6LJ3DwReTj+2TBM4AMHuyD4vY0
            ha32cf3reVcjHMctea3PprsyuH6Zwiw9KTPddB9DKv0OVKL4tI/Lh/YQqOjIOIgN
            zHc1/P9fy10deZB9Pk6dcX7mE6niArtStCGc/fg38fI/cz612xsCttTVn+8oSXy1
            olLPuQquyanaLX0XyVV9kGuHTOzz2F6FUkTt+eHERqi2JbNkOyF1ixiWnwTPrjfS
            XAEg9xXV21WOPRDyr3DUd6l87ot/O8NCrzOdp2Qxou+p+J5CcH5sKFK6+xsu08Pv
            Y6pRy7+koMhojBRZPu/htLHp57pcJvJ7av2N4vupwuHLwzMGkXi0FBUPT4I+
            =QDzN
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
