spring:
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:7ZNy8/pYfAjcCGgaNVf6m3pHIK3Ps5RAhjgRF+fugL4V+E/sKa5a4HMYRw==,iv:1t0ipmz/7MDgF073YAcP7+7VIRfbKyo8U12kTF7N/4I=,tag:kZI3Q+cuC2Fhgx4pP7QMew==,type:str]
        username: ENC[AES256_GCM,data:dXyLBSMr,iv:SF9iSsoOc5/nqWIkrGSm8e5cJTSlWJ71DTQ8koF6il0=,tag:eGgwOfQOwMnIBfKf6M1QoQ==,type:str]
        password: ENC[AES256_GCM,data:7e3s9q8T/aha7ss=,iv:nz5Zn/+l3eib3kM5mv567MbMP2JNr+6Hdfs9Dull+F4=,tag:e7MyhXx1KqhpdP92IJP6xA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:dHP44XhYxUdliu8zSww/rV6m5kc=,iv:kTjM5+XS8llc1H0oesECRnkkPWwzEu1KqQBzZJ/QFys=,tag:SfSZ4pn6J/eAMGBfmAcixg==,type:str]
            password: ENC[AES256_GCM,data:tXV2IILZlVOrHkE=,iv:BzvKLd7jVQTWUkd48aDCUQelY9b4FDqmrFhG8+l5vD8=,tag:rMQ6x4Zfj28J8UNHgmDhnA==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:4wlf+aU=,iv:A/AiKjbV7XBw8YKD2qKwWySG0dX1L8Diqypa1+NDjCQ=,tag:nGLy9hsgz/0GSmTLRZzKcQ==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:KhYK+G0pFqrU2ntHpntz4pyLTD74jFUwYmVItJQf,iv:0PxQHHogwR0w4kAAceGYg8h0ejeUNJA1esYA9+OnIBc=,tag:njHW46PsYgWr4w3Wvcso8A==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:RVsQWGYVKR+Avllh+wmyh5XUXJ4XGlKbhFC7fhYQ,iv:i4ukQG0dMUsQtZjkQgKJllY91g7eZZZltYjeVKxnlcU=,tag:iUJYTJJBXDEMoD6P3TpMRw==,type:str]
        cookie: ENC[AES256_GCM,data:ssL2AdMJKO+mOMNqQEUnKA==,iv:GPBJBQZEqMlfWC1rPwqolm5bNNvp5wqcDg2tKOQIBWY=,tag:wOD1zkbrE25Uzl1avQbQvQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:HXUQuKQxEFN4hhapGHOe0XXYViJmc7SYJU25aohqAOm9Fz1NftxkuNqkLJZ10he0NG556CNZlQxS,iv:yiz1M9Sb+AdEi+kwnyFBZ9ZMH4kEiKKwypVciYXogyc=,tag:Tamu76VywuR7epHJ4noC+A==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:TTJ1Qa0YsnollJSA8o6+vUAXCWRokd+GHEzeQHV+uiN4VlQ5JObNH0nUGpIglhIlcJF5jPqL3T/mjQ==,iv:l1uLlq3EJpucRu1ey8LOSYsBnyRBsFX/Mz1ImdtkH2s=,tag:ayuumRu00vOSs/fpEfQ7gQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:iuOD7NMFKdG7TZne/Ag12WGABqHffMCN0PFeHWXM6AMCGaGPih/Mk0tnjljPOVW79IUjEjVjAamH,iv:8/GIUnpZuVtf92ck55usRzeYDrW97j0WfBZALrdqKZ4=,tag:nKep9uhM8ZLcFUaXleVa0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T04:52:34Z"
    mac: ENC[AES256_GCM,data:p1cL8a4elRmF6VDNUz5vMgFecbH9XLXuigBrKOaG6vi+LVqu2q8NYigaYy34mkrPDzKlPz31AnqoD8NZSjnORnr5fY55ZBo5SpIyN1sjWMqHMQEqlLj4xBL8dEVPc2ax+9KpTQGrRYxRHvLgO/jYXX5GJt46iewMgOMIeUVrRPs=,iv:SNcgkmxW6THXHjUFIE2nWZ7TLZNCRT7RMn52Yc4Ebr8=,tag:TA7gz3a7sQ8zEjXLct6PUg==,type:str]
    pgp:
        - created_at: "2025-05-18T04:52:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAmLiY3PNQMPrgcIl2MwIR2n/3arwgNMtUJrO5BuSJtSDs
            or/qerOtSu+/qIXLtc5vZsEB5IkFbEKPmgyrXzXDzQ155d0yoKUjA/LNPvMGrzQ5
            txS3LvgQGixhKe+JUyWAD9TZslXzVE/I4HasrJhOOqj9rc8RUYB81+ouXCexxdZS
            W/nwdfzn1BogcMn+alR63mkgegIFLusm/M9uuolGh3wXfLD7jXgmxA3qeeFhJiE1
            Twy6ctEAUezbdhmZuCYSfaX6oh/cLGcG2rsMT7lt9+pdg52kEEsPMqnJ2zYkv67Q
            8dUuRTeFpNUkztl3gsX3ZT//CnzWxHxQ5dALSLkMb36SOItQD/7ZZcMwzt4Qxsnc
            Hf3qsIzCWdWRWmgNDJt4xq7YTCex0Evg5QTLEgoBuHchLukZM8wA5YWByEWNcs8p
            Biqo8RHwHUIh2z0IBk9fuMtks1M7DdgX5ZzxF2FH7eqQuW1DNL3zu1rftu4sviG+
            nJ6qUYLvZr3gCexnqX4YOVmh+oKaCcNz7CCvY06lORvGBij1mmc6v0Z9gJhqHiPY
            iciThuG6m8VPfmSpll7gF43wuNgZEMft2bC/y6r4NVzK2MOMfhfy1AhxNn9ZkRty
            Tu6CToFZz6oW6srYJ7Cr+gagRliJUr0x34dLqVfjh647CMpvuC4QIOzcDqs8p0fS
            XAESLL6JRjnV/3KDYhcPmbVV70F/MVRyofEkw2OY96MbrMP/8yv7oRIlVLydE6fy
            hXuPuwKU64mwu04R6+G5pV5ILYzpGp9qU1GdkfmmwJJe3USACRusNNuxp7/Q
            =iCty
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
