server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:1Gzwpmy0GUSafTpyo5cKmTfZ5A==,iv:7HavIcQdA9v8Df/8Wzbsl+O4hFlVki/81GQjGD9az5k=,tag:tAjjELZoK05Q5+sYIlX3iA==,type:str]
        key-store-password: ENC[AES256_GCM,data:JISM7GJgw+MPbyQ=,iv:eCf+uaxSW4O8Nm49/fJyqB1Z8c52flDWJgwkXdeayt0=,tag:BwpDz+AfGzhppoxZFL71Ng==,type:str]
        key-store-type: ENC[AES256_GCM,data:oZFj6ba1,iv:UZwIPdn67yX7VR+yrScZkDkyr4BzWDBop56cr7FGsHs=,tag:y6PC+a8fVx2QU9g1CwOTUQ==,type:str]
        key-alias: ENC[AES256_GCM,data:jtqQHuQOURvR2w==,iv:CGu7ZgUMho7MJpWR0+Cu4VmZiYLydkYARgG+K8pi6x4=,tag:0FlBlOUFmpPXWve5vOQQ6w==,type:str]
spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:8tXhblT0ArM5n+pkPu4K0JGyly6Ly+unTb+IUjAXEsWWI+3JtyE35sPqYLhbmb8sDxc=,iv:4PVhd5RNgUwak+vtJnf3+oLG7Fy2Z8p79Frtmr0HbJQ=,tag:zdLRYchit96Yj72/sG0QOA==,type:str]
        username: ENC[AES256_GCM,data:iqFCoj7/,iv:1oucenJBXznSt9YdtYRUcqHOUZO/zi9VVB0v4eInMd0=,tag:NLSVwTjkAid3lMz+FbEgPQ==,type:str]
        password: ENC[AES256_GCM,data:40Yj4J7sbxApg+c=,iv:FtBOhkjbAdjkG5E8ul8TziG7OMTps94xT8HY3BYqakY=,tag:C8Oo5K5zS8YEZLZ7pSr+FA==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:1J/HFo17S5tFg4r1rubBfRsl9qwh,iv:yR3m/2X+nuHDGpraiY1J0ABkvje/BWwBJomPufPqIuU=,tag:QafTwIiw23Bx5FuepCPZbA==,type:str]
            password: ENC[AES256_GCM,data:QBAr+v+L0TKxk2c=,iv:Dbb5EDQWnkqudhq8x1OJDZ3Yjapgmrsz9mJlwpHpLV0=,tag:9feOtERyVs7br8sD8EFvvw==,type:str]
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:R6QYraA=,iv:1k3iHiFabfS7Ro3U5slVLXbEBoMy+Zo3HDriDNTSYFo=,tag:dg/7Ys5GXLVjLz8eemB/4w==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:76Nsg89Ak0sAipmwUHQiTs9Gkfa2,iv:6WFe9F0/mQZYBwd9oEI2vOYDkCdfMQy/kggVEv19bVA=,tag:IYxRETGElMztjCdje2spzQ==,type:str]
        cookie: ENC[AES256_GCM,data:EXsBoLt+AyOq,iv:VeL582g32tqJd9FtulWaOkDy91vr2K2rNGjojZacPu0=,tag:E8H+7JxNyL2FddlfFLNk8A==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:xhL0euOJOkWK7zM6MS+IBRDc/SR9B/vXtD1581n1q5UKgamKhyCmkVp+MEmU1glnfxUueEK2,iv:6MnKRrDiUb2C9tMlenia6Zjocbdi2WsNKajO+VJQvb4=,tag:E1L28EAxn3xrRd8nL3EFTQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:jJVko0IGU1IdRbHrljqlgFFI7uuimH6BqQSYqda5NCCXCHD62ZFtC3x7igVaL1lgB87KiEF2QA==,iv:F6hHvMaH+QlbVlWGmbSN6wGAjIZUxPmIEp0AREnNdNM=,tag:nBlWPeMhxib4duHXSLwHnw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:HtFHb6BS3ZvuP9xRlxc1WGGzrdZRsqdAEHpgNwJSFpyS2XoyPUtQCNDBrFWAY8cAkSYm2FUg,iv:F4p+R6xn3Hmg81JcMomrShyob/iVgehoo5oxsPSBLtU=,tag:TzMxMlqpgQIsovLz+VDGwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-27T08:38:17Z"
    mac: ENC[AES256_GCM,data:YsW+VMArptBZlxC3iOZhCH8Sr/yfokOg/V9C7t37NyfZhlt1oxNRRzdnptzsO7iuIkyiuEiQl23KqKZXHB3YJn8KkSPV2VBuIgjIOjGUNrj/+cT0qikS3WfMGxJD4SQuvpqsY4vp9dDg5kUOIc3ZVWK5elyGUyD2LrmIJ+OJagE=,iv:NH7pA62tssQ4a50qPv2KPwTvLYKLECeOb/ggj3gvoHE=,tag:6L8nggyb1CqXFxyifKyBlA==,type:str]
    pgp:
        - created_at: "2025-04-27T08:38:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA4zPbhTePbTverG+eUIpJNx3tP3eUVVqYZ6YILhPdzQnu
            j7Fq0xe/BFNAr3jBm9DfE2FKoYNahCfbKNsHg7w8EadPyzzFoULWo56AJuS/akmI
            WMoWg2Pmgb1CaJVDeB5wEdy3dyA7bJ0pet12tg3gPI/TTb2c8m4WV0gD0QTO6kXL
            UPnxE0TnewZubXxp6zDdbYjwd3WM77qnJdkOsm4KEEqkGsI1QAQ2hT/wlyts63Be
            oLP7Olaa90ooQxFi0y0de4trQOpqxtGGVm5D1ewXmHHu0Uh2CT48IBDhzymsYrpC
            6Yawh12xJ7WUUn9EkUMuIa0avL1E9n4lVzOeu6/F/8R+VwasP2Sm7LMocqbsu79z
            Ne8R4sDbDg95YIO7T3LdG9YEyoDFvVa04foodZ99Dss4U8lyL8Z2dg6ex9q8/lbO
            +D1Sf536XLjF+APGkN+J1NDdnXqEHN3MP2IsLFBEeTmcUTJigkg7rvtcelcDC3WK
            ePgUPImSCs/ayr+Sp0Sb8fkK+lBPlinYXEmzHRtcaUCD33tX/SPyLaU9HJX9gpW1
            2RGk+oUKohMk18Qowfz3zqbuNgQOwXrrAz0cu8rDmg21lGe2WN+MnlTrnyJuSKeD
            Un9eeo5d/428XLXt2jT6Mufm0U+vtdZhxoy6ZAWtjgEa9lmdYKU8GzAzYdLG81LS
            XgEhJCVnwlwCN+itByKqmUH7w5gAhhHw250U4/p0BtZTAeaDu8/4T+Jr/UrwrK0n
            KqeecTqSqKws4qvvBlRRCt3gD4eH/AN9gM3kB3bRCyeMIciJ1/5f4mgLAme0LrE=
            =dth7
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
