spring:
  application:
    name: Dev

  server:
   servlet:
    encoding:
      force-response: true

  # 데이터베이스 설정
  datasource:
    url:
# JPA 설정
  jpa:
    hibernate:
      ddl-auto: update

# JPA 설정
  cache:
    type: redis

# 로깅 설정
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: debug
    root: info
    org.springframework.web: info

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
server:
  port: 8080