spring:
    application:
        name: Replay
    profiles:
        active: local
    flyway:
        enabled: true
    jackson:
        serialization:
            write-dates-as-timestamps: false
jwt:
    secret: ENC[AES256_GCM,data:FVbxdhT0bYOAQkp05KyRnkQTFR5DcWW/CGCdG8VYqiPSG8bRNEou1W6KhMg=,iv:WDP23ptoGrnnulUjdESNCYr2F1B1WaSb3WD2jsfkd18=,tag:LahxZsjPJFNBXuvAYgHOsg==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:dLH9,iv:h4doACImOCGs+CzGyd4pexaMtrK60N2D7kNWu8+pHnM=,tag:88on0VhE8/hpNZIDCaDEjQ==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:+Lg=,iv:MFzCwau7FJQykUz/UWDr6WhvRcxu52m4bN5ZHVCc3Mw=,tag:6Vktl1Do+ziqZiPuSMhBHg==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:OsbhJKG+J2KWPeVxEq6YW3dKzWE=,iv:YYiuK7CiGxYTCYS/r48WLolSbEr3M4aulJjinBB6i6E=,tag:r3pbOGlToCrY/bliINJmvw==,type:str]
        client-secret: ENC[AES256_GCM,data:SC0rwTmEJJVRGQ==,iv:3R6Y8q7KOBycyLmfYsDiGUOhEcY1IAsiY2q/ABWT0OI=,tag:Fr8naP35U56aaAh+QfrtgQ==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:7X1LjsIysMRfOJJPApYqMIT+PZiO2EBaOvrmnPmdOH5GEgYpzJRWXK9DmclhBQ8oYK44xCy4pyaCI36p/63XOjIyTzerjmUR,iv:4qG1PPLWIxYcVkZfZJEPnVI87rSeLI3BvXbG/IMqrpM=,tag:kJ/XARi1j9+hZmxxVQmsjA==,type:str]
        client-secret: ENC[AES256_GCM,data:1VzArvVa29eswgzQ0jGun2A/bOq1nfyLDPaLOKAWK0gwpbY=,iv:Q8HrR6Bmn5xqhpEbTP1K3ahZZapkRKcgt3vEMg6Cn/o=,tag:i+v67JvpKnUi5+ilQ12OAw==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:6A/+1f0kvnMHTUxlGMOTvMFeMvsLldccxxEmbZznKbU=,iv:DETdsODFlnUk/v+qb6rw9dZmMqm66uoCGgNBA8evQYc=,tag:Pd66cvqmbEFhywc7StBnYA==,type:str]
        client-secret: ENC[AES256_GCM,data:ZoPYQpZD58PhO92HqGnQs5ddaJERnZ3+isJ/j3+i0Vs=,iv:FzISS72P9PuPV7/UkCtIo/sVDtjfCr93GiZ7h3zpxHo=,tag:tAluVmplkOk/f/mHRUFF6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T13:24:06Z"
    mac: ENC[AES256_GCM,data:3ScTAnd5kE0SasJMokUpd+A49sbCgYYpw08djIHYzqUe4IR2cCZNdX8s4WTHTqOFqVJX7sovVazWGjSY8GbjCMT+/6nxztNT3icGEK7Da8PovNLZghMd/Kfw8wx54G14P+O/raUDcMbmm3KjZlnslSjdPTMd8xiG3olaZKeXRkY=,iv:QK7AUEDX7VsNu4/KumOv3ehIQ+ilhHCI6jPKAGRb7mI=,tag:YMv2/AyVMCWPOo/18kFxjA==,type:str]
    pgp:
        - created_at: "2025-05-09T13:24:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+IClSKvWVuPIDPdATu1EA3ZrAVLkbuTZYneHGsxTbaYPZ
            N0AGx+ebj5btPvqMUaTJ/XcStXYhYjoyNUTsFmwpJ4NE90HPRQ6s60eEFPGx8IzL
            swdYYilhfeqfnMywxf3HOtSMlrkLr+ubJ0H238XBM9ttLrm0WHSvS/tzd9983tHD
            +paDMkEUM3VcwKlNpEw50lAwT1TPd0/4pR4kOTWoA+aCGx/MyvLMznCxokPrywfj
            5m3rab/KeDRIqLD544Jm2GT9KjY6Yq6P47BP3fL+Sq+ylKFAWkze3o77FrSqC3+o
            2LpCvHPOVXsnytjMZQ7Qt6f/Zi0Wy836BynlMTpo4Zi4O0NoLAYpNH55vOPEDRqC
            A3cvMB0eyzTL1EjBEJV77Ea6Es81pVd4GhvHBIv9JL53pUIvJhKuYt/p9dbN5Xjj
            /M0PTX+3V3fq0KHEX5ZbA6s3ajyA66NZkHWWLtlnH6k6kTxajvzrwTaj8L++h8iC
            DDPxtx/6Q0MXNzGqDL4mTlyVmVjg9n+FifYFivUHehFJnPlw9EJm2EeLok4so1Ak
            7FRHknCA/IwxxDbhqiJSka/nk6XGkxFYioL5ve4KBHTitbU20xUt2CFcpYrEMsu3
            +6/PcZS2gg5RrgvJgOgc4Gw1pNn4fTMaD5bnxJ3RVdW9NWqYbRc4nUhj6XQS2NLS
            XAH9aZ0001okJh/MrSx43DO1LrarhDM3NLv0N2AfztOxkvY+fA/g35wZnLEHPIys
            DSs+Af0CAVHC8WVe9J357h2kwcJp9N6TmwKd1C3MzzYcomkvdmFKLfO2Xn9V
            =IQK5
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
