spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:zf4V/OEB2bW4Lnli9ZgQK82WKR1l3uf4aLIs+11mxusPe3FD/gpMVSvrR1YvLq+DuZI=,iv:qe13xMMaeT6I4IPBMcuZBaaD27U7Pr7fmE6bLRVw/Nw=,tag:pCUnicV2EfOhopMHATe0Ww==,type:str]
        username: ENC[AES256_GCM,data:U/0l9VFG,iv:Oe3/ajFoewHaPWzqkN8sS/43uWvYkzyq9wmQLf8OC7Y=,tag:QR8YSfRooO8ae46Ti0EsEg==,type:str]
        password: ENC[AES256_GCM,data:C5QSuc4AEn7Zv1Q=,iv:o2fJYBBloLctHsOzhOps7EQ28Y1QUs/W5spkm1Ly9n0=,tag:/+OUpRBBjIbCr0ym0CgCiA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
#    data:
#        redis:
#            host: redis.phanescloud.com
#            password: phanescloud
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-26T15:02:30Z"
    mac: ENC[AES256_GCM,data:K1krlWl6Cj69FFpjc4gD9UxheVausHm+po/ynCkgLL0hJq39jS+j2gbsvOXH71d33LJq+A/D9S3EL5wEC+mkPHeMwgLB0Cc8oyA3Zw8/Z1xSku9QNtBvaUxsJ/NAh8li8YGogysCvugk+zD1WiEBxVPoWVcIyAMHSKBk94blFxQ=,iv:p9gKN+CBGCTHAv8XYBZ7EDKual/dCMQ3zfGGFSZ6F7M=,tag:wyQ8aFDYIoUnSI5Bsyb0XQ==,type:str]
    pgp:
        - created_at: "2025-04-26T15:02:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/9G7GBDhZee+T5oMz0OBAt7V1CsVFg9usP3Ezzqi2aTMD2
            s/Lkv6RksHzySxVBsVtXmdImtmq8PJgSZv5gaKKkdCCH0xY52iJC89bkokie5AGT
            cbE5MmQkv7G6pD4Fusz6/qwxPqDHZ6VGkb83dSs1fOzjXjbjQDBjNBeZCdpVbdCv
            aSTV8mtRMjQ2oCu7XHZQIDQYHL58kwL0jK1t21Pk/5xBxnhHZFfID35fwWA6s+LG
            T2tVHaxRMwaMqFy1uIl6cfIjiOm2BCK5py7D1Je5I8vX1L/FDKBmP6TG00XBhpum
            xHJkrm7tvBl1lM3M+ZC4Rfg/lErQATaALcxn1juTT8WWmUXh73SOO+DGwfyaTht8
            b8KNobtHt4mMGMfSRm20PoaYmxDXPPx5xtW7UBwCp3aB8pNkej1FYJsdlf8ZZtYY
            RWIivAG0oEZFAFEqx6igNhf+Zf/fhE5/1Ixg1tj9ECgES+3y0SAY49EIkZ7DICnF
            vJMpGlq43KJraVjmA45WtNDSky84Tw/Y6UwggfjUDvzUACZr5uRlImq8E0rfkswK
            6jQYYwFiN2S6Bch6H2unO701NmemO9ZfwPXshyrlDLb1RUxI+0O38OrRrE/Q5Hke
            TOYPP6X6zamu5ULX/urvqf05wKEUvQwTV+YAG0ZOYQG5y/9fGkiYcEFAzFFG/p/U
            aAEJAhD4/pkyb61PibK3uFq5EsOhEHYjHBtt7piBEWfwSgwEc7femr93swIWOv3B
            imhls6BUv8oy6Hz6QMqbauxIzJBKX3K1BwIgKQygwwllA8YVmJDw4rAoF/DAMWV5
            I0xNAVt/3xXC
            =HuXt
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(url|username|password|id|secret|uri|host)$
    version: 3.9.3
