spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:ZdComWhLWMAuwYSN71V2doSzY33ZpgbCWwgiMsdMwDxHv+1I7Q==,iv:NxmP8Lc/mLUYHgKIujrSiZ9ELRbGGPFT/MlemgKAvwk=,tag:udvvpmzXiXKbxwLdziIxkw==,type:str]
        username: ENC[AES256_GCM,data:B8rEt+Xi,iv:V3VgLDgchpnZ0KOTLNgtwZgCqByYE5rF22earySBx/8=,tag:2G2SPXkBr18vcOVj97VtJQ==,type:str]
        password: ENC[AES256_GCM,data:jC1ffHfXRzyTP30=,iv:XzkcqhJI0v8iREwkEdIEjt0fzdOgNEygFV3L1IC+lWQ=,tag:Y+jnznOiH6nQgzS4u8S9BA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:pMYifSgS1ZTXRySdeBlSB0v30a8=,iv:jVD2cHfp8606djxErSSO3qJbONjVWeX0341saOkjg8E=,tag:OAx286Bmslwz/tu0K6wA+Q==,type:str]
            password: ENC[AES256_GCM,data:BSGTbMN2wXsBQWQ=,iv:1wD8I7Hysj5z3Cm27JlkJ6xYS762WlgM4KJXBAeOv0o=,tag:AtgX6IaCrG9Dn25UkYTTkw==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:2xfM+Vg=,iv:wXhFh1uyUNoai/B8bChOZw4BK/W/IVmw5YX/EXAuSXQ=,tag:B2JXojaqEDTsJX+9or7EYA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:KsfJiVjQVjdfR5Q/cdsxqZiopmn0ZTwpbL88njLQ,iv:mBzet96nlp8CTt33sreMby8K8/HMAlb7KNxSQ6hAt08=,tag:Y3kgkffvQ0WwT2IeoVjDlg==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:MlnFNb1RQj77qbgITzMmLppKqKb4o0lKATC4YRI3,iv:ps88pReH7HckbbTPYAvfDUYzMmTEKblVZO77ZFd7bOI=,tag:xHK8yAQQsON9+1AYU9/XwQ==,type:str]
        cookie: ENC[AES256_GCM,data:u4IydyD6Z51bQMWReQGDqg==,iv:WW+7GL3I38BssEBlkZoVCGVGyiUOK52koToOtCEuGhM=,tag:uzbb4V6lyFTB5DU8WlD6UQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:90WYt6W9YoJLcLH0LBd55HwPGuXz8XF/LsbhxHJMCrLPEDb03QCUI/fxEs27n7RerjSIlDo=,iv:T0mSovgwY7auBfsCK6Egd+TyuvHtBfM1bOVdStlvbSc=,tag:oHbamVpTevU2wz6X50SSgw==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:UgbGJt3tJmyIM8E1qYS6Js9H+m7HKzyTnHu/ge3By4aeou/XAvRF3++HLA/kwMDzM+SWhQpB,iv:/FgEsKxcyaXPwY8TL+ca/CCKA6/1jJWwK4kttZBT5IQ=,tag:F77wDqTpz83FY5xTndgnZw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:F7MC+85OvDEexWezCyMRpVBjebDuEtpd4r6kva83bX6ChOD7EQyXPdboexnGEaFJWT8v1jY=,iv:1pQ5eJxj7GQyeSdYqqlpGaN246AxPQBUu61safoNlSg=,tag:DidTR8ZrI2VleBU/pmAsyQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:oTXzEktzQuaikz7KCoLLx5Q1eySu27JAtqFSSILAJ2n+,iv:aWeMWV8BUIzmWfjE8H/5ADa6Rpd3CfocmEEqNmQtPJg=,tag:esYQCMkPNXsXA3sbNh4dVQ==,type:str]
    access-key: ENC[AES256_GCM,data:qXvO/0z0Eh7gyAXSycnHu2UpvQ8=,iv:ECbiWy64apaagXtlDtOpXb92MJEObyuZF1386UapKnY=,tag:yyqkhB/I9M7aEvzZplCcZQ==,type:str]
    secret-key: ENC[AES256_GCM,data:ArmQYKvZd2LPIWbsMmVkovrFDhurNjlfTzJru0egmECuHq23UKkywg==,iv:s9UQkvG1HOaf4ylmoOyjJTSDOVr2OmGm9jeBAHKXIFs=,tag:cVyavAAvCAgSRqexdQDJUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-28T15:01:38Z"
    mac: ENC[AES256_GCM,data:zT4thgJOiXQQ6hpjY9HV94JdKQDraEJkHkIsy79a57h5SBUwCI8CG/oe7wV8FcKJE+pq0R7ZYDH402l+IKpaEOXYwsMyUDqNYPFhuiLy4Ig1ngXEomqLCrJqwKgoBmJkXSseBckoIc4CW/LWJu4Z1jcp68YEUso4FbHpUupmQIk=,iv:uWhEs4B0THlqplZrfgYluUqis+oPPugOU4ivhVWg1m8=,tag:9lXEoiQVp9KHylbPRxFJIQ==,type:str]
    pgp:
        - created_at: "2025-04-28T15:01:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+K3Kd6sOhPvKH0RmRJ/bD92GW18sL6puBjyV9tC3ap6Ii
            n+NcIrDIuKhFSyWXT/9Qju9HJzCIUB1MY1blJDII0A1wYldAxO4YxHklaQzwcxWJ
            WkRtcXxk/CWY8uPCwgjblL4/QscMcPokG1IU0hKk/BwDNV2H1BfqKUhbZPSfE0zU
            QY6Xhf9VkWt3w9xMEtETJu9+Uo8cEaSTaTE+XZ3zI1gxItBTn9Q9dUVyPDCHG2BM
            PtR7Ej9iyDeeXMqKs+5Uh7hcri3lS8h2fRW4L6bKIGcq7hF/bWDo09xrioKwUIm6
            11u/QgeI1eOC/5J16KcOhZpSEFyMM9ZCzoT9bKeC7xesnBly+L+chqG1CiNf65By
            2ZcTV7iMEzOOuP5C2+c5qh0iW2yj70cgpAD76KjUqL/QSxWNgHM5/zSLbPoZC2aI
            zrcY/QhcsVRmmCoIkD+uGrJxUEcU2KN2021m2CF2N37KPKIgkLDR0A+oU9V/hRcj
            L3svpAK3d2INNdBwjwg5Y0OpXF659aolNdg+ptj6e4DaxfhY9v8XQd6F8M1LSt3Q
            D0W33kRFH/6UO/3eeQ9POiEiZvQsdlfF0wbyuJ4K0oRJw/DG76oIDzjANT0+tVE7
            t8H04afYYfO6Q8MOnxkDonkg3n7HlpC9RCGNTDkgx6w21FJh76OUZ6+QSCNVsbLS
            XgHsKpculw06OaCsKAgE6ortdIwB0d7+C4eg8TgLuVZ99U8h1MIjnDkFLwnOAZ1f
            K6zb3HjbcyHIZIDZINYWphqxXnFQIbd3O1/wK8BqW8FTbJ1tfYD+xMG5UHnYR+I=
            =e93h
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
