server:
    ssl:
        enabled: true
        key-store-type: ENC[AES256_GCM,data:n8782iLs,iv:C2+gCHRtmO4WN+crrF0MmBbw//9gAmdiPTwyqo41ddQ=,tag:LiEIZLBU4TBlXFOE3ijPxw==,type:str]
    port: 8443
spring:
    application:
        name: Replay
    profiles:
        active: local
    jackson:
        time-zone: Asia/Seoul
        serialization:
            write-dates-as-timestamps: false
    sql:
        init:
            schema-locations: classpath:sql/schema.sql
            mode: always
    data:
        redis:
            repositories:
                enabled: false
    jpa:
        open-in-view: false
jwt:
    secret: ENC[AES256_GCM,data:cSsCZXHtXusdMxnqTum9Qh9lBmIyHAra5AIWgHsTF5sbErBZoCLl7I8DWRA=,iv:8R6jMF1MLUlzeJXn+Uh1cFOFgrMEZdGrK8NG5fMSUU0=,tag:Sfm1CO6DALqbv7KUAXaOeQ==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:xNsF,iv:X5f/ygHSJWzNHRN3jBWI1T7Dpyo9CeW66BBma8JD6Hk=,tag:XKIlzSkS72L18+ulImCjLQ==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:dTw=,iv:eYTHNr5jzP0uDHJK4+uSeTqEfiUGFcIym5aQGx8sNkA=,tag:bDR6M4LQoui8ULAGAQ3U8A==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:JbOKRcFnduSs9nugbYUfWWUQdds=,iv:YI1qraIRMWG+b2AbGQTJnNA3mROPyA7KzYTtsQxYk/k=,tag:ifBC/qTGTq8PnQUNrYGFrg==,type:str]
        client-secret: ENC[AES256_GCM,data:HKUSTPsJUCFApg==,iv:R51S7Q+m985vWxoj8JECZZvmNobLfP+Y+d+JF2qp/Z4=,tag:4VedYTlhDovsBtdmUP5QLA==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:JKJNJSrUwP1nj45rxZgtPJccuCwmhRX8mnMo9ii3sSwNEg18RPTpCIEQ67+IPzEP+BsxbwILKnAU5w9DQttYjB/j9P7Vw1EN,iv:VsB6PYKeFiNcRmXcGFBHMdTYr7mLpCUs+qKfTBPQ8wY=,tag:/kiPGWR7twO/F+qpG9eYYA==,type:str]
        client-secret: ENC[AES256_GCM,data:NH6k0NQtCkAse1SdSpoJGOZVShaXJoUjFCYw3/uxEoS/lq8=,iv:6Kq1u9snl5jwLCcg5YL/wRrB3w/32ViHFKdd8IK0eks=,tag:fCAQc5fHmqJw1377G2VG7w==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:ystA6ApfQ6xCcC+kSdtZJovih9mkM6PeFBkYodcXNh4=,iv:qPSPhyEEmV+QshkkuX2IMPCebte7MWoHNc5ANaXcp3c=,tag:M7o0nKq72why1pMoiVzGIg==,type:str]
        client-secret: ENC[AES256_GCM,data:e4k8wFHC+vXaO0Azq0ie9Gkz8tN/hVEqeDbu8sK0F6E=,iv:8sixdXZaGj6KOvpUCry8PyKFwoSxtSfzHPbHpWVs7WA=,tag:FsfC5x/vxMWtsUQd0dAMfA==,type:str]
s3:
    url: ENC[AES256_GCM,data:CV8Q/15olQCltUcaxFMdiNHBASOtx8gwaWETS8fXSa/N,iv:k2s2eOhfbKLkVlJmG44LsYdiUZ6u5ph1cViKokH+nUY=,tag:bKHmewKVBbit7hii/siT8Q==,type:str]
    bucket: replay
    access-key: ENC[AES256_GCM,data:FDGt35fzxZQpT7AImYKtnPq8/Ns=,iv:iVJN7NhqjfreApYjsyi0suoryIxlFY+n+cB2XKqmR3Y=,tag:jt+pZV2h72MMGwVRvFnb0w==,type:str]
    secret-key: ENC[AES256_GCM,data:V7jhTipbs+utQBPsrpnunODH4bhyfrb6neA+YR6iiyIvnCzyAOQnCQ==,iv:uXk82GA92O1t4b8R9cYY/2nRoS2sqDHKM8Mt983DEAk=,tag:2YASkSrNXVHqedURPEG73g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-08T11:39:23Z"
    mac: ENC[AES256_GCM,data:oR7pS0ZscDYgZoXwTS3Imr3EQ10BH4rwlhb6CUBY/CPt3kRrqow6HIqpDBkA+4Ih+loq6yg0GC8f71PdVOqnrtcVkR+Ok9rZ3Btp2kGw+5s31p3tSXT9Hyh/MkFblTDHxzT//qSB944KGuN9riLc0GVgbquafUHmOUQVbhqaFVs=,iv:BKSSi2r008YPYHbec34x1WqFTDplWgAv75QLQHhBtOE=,tag:eLRpcEsfi8mMkdUqSxayjg==,type:str]
    pgp:
        - created_at: "2026-01-08T11:39:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+LX6XDgDcMSr9WgXZE2p3tx/Kzhu9pWe73/ox593OJuGZ
            gk37OuGFDEFZ3DUx9coZjKl8vKtwnpHuUz5tW7ennhGx8njb7xVy7UlmkDNsjPbu
            +3avG6V0eCx3eb0shDRuuLjlRXC7OF+27cf1/xvzajnjOXlGlwgd3u8psahJi0TQ
            RinIi5542QME3xuXEfmPfD0+PeSxaiyou+GQ8FO+XXPsFoQBR8VoIvfTnGUG2TC5
            TAJOXGyXUZc8SdT8M+44Hazxv+UCNcWvXQyayHykKrI3RARu5GXjLBR6/gH4/kI/
            PeWzMAgeFMvG3wR0R8iNyR8mm66JOwDAY81F+MwhI7g2nCc3C+j1jBffT7p5CV3s
            Ocnq7O2n24Nt4MG3KrKNT3HKR+qxCxFXxjAUEx1/zPlHpxyDfaFexT90Fqph+9/F
            lp1Vk80lt7miBij0onYGC0ox8hWjI01di0CA+lt26QooQq6pccJAR0mwVOGArjeo
            9VuvVPSIUlpBDAshNIMitor9ip3kNdiFHz79oc29qYXJy+mXc01DCDcgaurfqzjx
            I3XVandQQWZP7CfNz3UP03Arf4P73HACqavXVuHNjptrV4hClkwWq0baeWh+uKhG
            A4M1UPLgxKe7o7xQMI4GiqsIdyEF7uNMzw0Ebv+q95sWoY0+Pj6HTxANbXRiqerS
            XgGARcgXbpEn17T7/yi70D6Z1xeeWsA9ncFMb4zw3ykvJMG70KaWfC7ZmH2aGxhj
            pEyYllFa5JzV8p9VJwfAkRbJkAPKMIG60fVVRwJWnfqvuhcllvdMSrWAF+cKlV4=
            =Yp2X
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain|master|node).*)$
    version: 3.9.3
