spring:
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:n8GtUbpj0GpLi8HNhb8bqE6nM5g62OpZYUlfORGAvNwa9sq20GY4T9EosA==,iv:Uaz3qM/KJP6Ixyp1tKu+0WEkUgE564+hLQLOQNjptY4=,tag:HEkuMKXQOO7FTPk5ftqh/g==,type:str]
        username: ENC[AES256_GCM,data:iKhdjVjn,iv:l5AKnKHt4vj97p0jkjVYX4mtfqcbcejIveKUhWp9hlY=,tag:ELpgifSCXqHFhmOs8TkhpA==,type:str]
        password: ENC[AES256_GCM,data:GOowYLxxP+fSUhw=,iv:mwT2FoJ1UAaX4nlSZwBKFm644nSScIOHF/EJtWSG9uA=,tag:xqvtQZJcrynV3pKidVfZHg==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:24JeilvAlVuQxBrdxQ1Ke3XNwFk=,iv:tTAtpxPkEvdRrd4cFUhth9+n3E8kcStqM0C+R/VSxIQ=,tag:/ce51unhnHaUfM17zgqfrQ==,type:str]
            password: ENC[AES256_GCM,data:ulYw3rfRghfhl+M=,iv:5G2wGvuFCcV3Nm4q4viP3qOJ7OudGRAduXb3jjYG9K8=,tag:EgvYPEzyFF4vJknevRpXqQ==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:Y5PNesY=,iv:4gSOylWrYdTsRE0xjozIlnX1Mtmpch5vXNVCbmkZS5A=,tag:ayYuUyI1B1CGmMTmbJzyyw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:V5hoCPpYtYHi0Cb+j/wYOoY9ANINVuG+FVMn3p2S,iv:I2VgzH34/03GaJG2klm3Og9mOXEF/TLkIF9y9BKlZis=,tag:L3jgvdt2vb7Nov08R4jr1w==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:tocbbKqddVeOpaGrisCPfTEW1dS5efsFNucM3yuT,iv:C3LQFxK2B0aKPAC6IZypau4JiagE4OwHnzdtzPxeaDw=,tag:pVXt4Xfj3k7F3hOj9rt9bg==,type:str]
        cookie: ENC[AES256_GCM,data:FA71fyLKvDoHWDnbCiVT2A==,iv:R73vyHbpXfgOm+NKzDF9MNI2J4BkekGSmcu4Ch5JDZE=,tag:lvS3fHrEblszhGrwGNmaBQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:dSDqIM2xfpNdRD9agfC1stPIaTxKBcHEBMF0PXZVS4QfLLUP9gzVoKDdbaLZHvdslhcsVzNDuYVw,iv:qt706jBDA31KN6b6po84I3H1XW1nUmmMyViCkhtH9rU=,tag:evOzN54LAmHUdyDBmn3NLg==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:AXMiep6HR2SWGvyjLTo7cTnGMaUVyURxhEs4Ww5SZtrjFTfUE2tw9Ut2glZLWIhkZUPLgWT46v5yZQ==,iv:ev6Il3x0n11JZCJqRuVHqBAhFSvmuLtAnnMHCyb0uYQ=,tag:29gYSKQitqatE6YvL7Lo1Q==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:7kOSY6FRHR9b+7+EaIWKvnTjcLbyRjy/XqJixKXK07orbe+A0osk9bpwcPC93nUCdyqoIPoJZIS6,iv:mU1YqYgf6x9KglSmysk5rXgMxTe9LglaJLT+9PALdck=,tag:U17+O9CkpUsZyr2QJNlPwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T11:06:15Z"
    mac: ENC[AES256_GCM,data:ucPk43VQ8XBUcKW0kKvx1fpgk7Df/xn4zzimkNBZ3KE62FuXdI2RlYKhOPaxu0G3SbASDFanjm9bbf85Sb6ZHaEvLCke3ntXIWzTA+8/9Qb2Z6HIr5YmnOwKsqDr0pZsgWhYsYBSemZsFCb4+gaKFQpTyWjcvK+YfTRl4MG2MK8=,iv:OzNmrUVJMOGv7hKPdMjUAmE8DL4FizJ2oxchK0A3Gr8=,tag:xuyBF1op0Uzx4hnsltkBuw==,type:str]
    pgp:
        - created_at: "2025-05-18T11:06:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAzra0zy+S8I5aQ5RTZbEC59TcGBI85K0Qj/YwbqocsDRt
            OnAaUjv1NldsnGim5I/yRWzK41Qi1aw32rI4DDHK1dKpWvBQgxTvcezqHe6WFjbg
            UQ449rE7kNKetSrI4e308g4jklM22y/mXnnx/v/ALWltnFbeSRIN9WUTFqzeyjqd
            TmBlK0C1ZRTIIibFu7KaIaMRtk/A6DJTQ+XADkMbaVNnE8flL/pigm759jCDCXaP
            EXtkY8EVkgjLitlwBOkMOYhFbF/1mmMjsq/0YybuYmdeqelMLtpUBo2vTQKQxEmb
            HRWhQafeQA1UuIZqYWliokB6gb3RfBTGcoy2GW8todr2NCTnb4ajo1GwKAcuj5C5
            UXmxfBNx3iyN4CIOWos/bslb3PlfXG/sOaBV0xuAR2ZuNSiyycK9GbI5j8U0PxxI
            FeRSn1xA4tLxGsPxz1G8bK+Yss4W0Q0sMQzRlXOJrbpSaTGDjix/t2cFA1I3cn1r
            ssGVGR7DXTlQ5vOtwsYqgfoLqw15xj8qgWxr/MIbGsw5M2axm4LFIA0hJSDKIgGI
            o/rJj9MDxFwAascqrOULeXgW6EeyFiTOIyOWEOb3TZt/7zpZqzARgGfnXfff7X7Q
            KcmKlv221CcHsZI5emxu5rRIWxIq4mvRZXzoW5//TD2JRxsBbhKaIA0DfBLCTxnS
            XgHyW9a0be8s/o15atCMSKV93yuMmzi/mPV3BsBpvVjSYjoplmD9WldInFubJfMM
            eDfjsjfL4fLHdx/jtVbbvgK2qUkuNeTFE3Xb62dnSv96I2MCiYQ5/92xX0wV40I=
            =+3hA
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
