server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:CoC4o3bPYD+vwX5Qy1WMSvpKvQ==,iv:x4nbfi40qnU3g4CL/cEFoHFZWzbdauF90hgQK8pa6Zs=,tag:6wIXFp6HBCswowgCvhE4AA==,type:str]
        key-store-password: ENC[AES256_GCM,data:CbIxWqCxtw+BeX8=,iv:wZOxdcmFcd9rbmSc8zVKBLNcIWKttOBIZRFzRgUY5ck=,tag:fha2w4r2lUebkvDTLl1hUw==,type:str]
        key-store-type: ENC[AES256_GCM,data:sXE85dft,iv:0uU+tAboBFWGItiyjioiIfArATPflkGyEAae+0JqD94=,tag:G7FZrDO7XtedAfucHF3fnQ==,type:str]
        key-alias: ENC[AES256_GCM,data:gCgZP7HoGynAIQ==,iv:jfRurWNmuLm+cuQC05u5abNQy3FWVTsAHcFTA8kLheI=,tag:aBbvXY8NFmoxSpGGu2qfaw==,type:str]
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:r7nYFA4AajTOWPmWhugG0klUGSYVneGDHI907zKZzTRmqPv7upkZhi7OQE49hpypTFMPS8dRvD0=,iv:JXfC6rRqnXIYM8DlOS1MmUlNdBY48Wcfx9wHLRnFiC0=,tag:FWUir+m+6hHkjn3pd8Ljpg==,type:str]
        username: ENC[AES256_GCM,data:pWWiumNB,iv:rIPVL7yWwxRTGH+2fi9/Agn1Eq/DI9z1Nf5luUXlRRo=,tag:5NM93Bf/aNgZyecXOyHd6A==,type:str]
        password: ENC[AES256_GCM,data:JzElzmGsYjLVCJY=,iv:RptNQ+nvbO0Vah1PdInaQu2WbSf+8QPkuEcbXUuML0M=,tag:hsQK0OJfldUonlSGYkDm3A==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:ZhpyJlwW4yNDN1v/b6MuspoWUEDD,iv:QCxLxJeOaZIhedKX3jBprw81EZAXxxQsY5eRzVs2cyU=,tag:NXytbETPVywhXxe9p2DDgQ==,type:str]
            password: ENC[AES256_GCM,data:IZGgY3cvp/nlhtk=,iv:qNyJLYQczxGhjMTANd1qitg9J6wBx6gKjcBRd1zZbW4=,tag:mtmsRzG04L0Lt3tNmJFIDw==,type:str]
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:XU/m32w=,iv:/uWi1eO9xxoKsUN4vv6Q61PxvveDuittc7D3GvwtD/w=,tag:eHsmLGKwqKPnoozn/CRdAw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:45g719MVnssdON64sGVdG80G8AmX2Axajh45RrWF,iv:KQN9aP31eQ1cQyuC3eJHcLY2XP2SLYNX74oZ7p+CmsA=,tag:6hnUdAViCCjkvO3ESS1B1A==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:Ahae/jW8AOtNebD+xwABC9JZy0e9/l1B7vETyRirCBdB7eUR3EtT0bWvSA==,iv:sjGLAnm8jAwMfOLKw0sYNTDcubOgvLcFKUr0hwTyBm0=,tag:6rtGuvSDA0KEI7rsBO3zog==,type:str]
        cookie: ENC[AES256_GCM,data:igw6PcN8jTSwuwMRE8iAoA==,iv:/480ZHXM00jAVBstHYjtjeHXlwYKANZdY2BzNkM3IVg=,tag:16m2d7wfamS4YpIFDf6knw==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:rxgC4jP6dw1C27Ebc+/sWG8dsA5bqkAIKiAd2zOqq2tbH6zN02LLqezKxp+ou9gNMEcYJON8tQptz4fyXwNtfA==,iv:O7TYBf7ZjzZV3f/lpA73QkORYAijgVXxSC8edPtgykc=,tag:uV9ENF5vFWKw6kaW/9cBUw==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:PGLJY84MeuevJQYnDxNohzjC2HxOgSENQkybfQv1tZ7yQAOW2VvMiKtpIiJw0+7lAfVQ0qBG6WGZhMkGchxRqZA=,iv:pme3XisklFFueVdLvUGPXcMgtyDKrUMEaSkY47iimWQ=,tag:sX4JB6Nd1vYUjF1Vh7/kZA==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:9ua84I3kp07npz7ew6Sk8ddN3saTHRbzOvC8ej1G7lH/soHz5XAj8zEoIUbMQOKTwHvjNigo9wG/Owg9X7XWGw==,iv:eC+yttZh4qDZX575eVZmB3UNRsbXW7cDskOvue6JptQ=,tag:Fzh3Y9sPghWuDBmX1QXdYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T12:28:35Z"
    mac: ENC[AES256_GCM,data:Y8crbT0TYiTOFHPjgWskH4XJP8N2zKDWmonqksGlG2Y5xhRSOuhPMSCRfuWUqbCb7qHdjyk43KUoIC0AuJom46tmsjP5TocUTT1VterDFR7tTQq1Kyn5fNIXNNtYyQ3auk0PGA8J/1ymicBytxcId11rOdtHyAcqU4v342Zif80=,iv:BqeTuC9ky11UMCe+4OTCCqggH2aMgucTqQk3PnNB6ms=,tag:Ke9bQJHzBxcVvI9Cvf6zmg==,type:str]
    pgp:
        - created_at: "2025-05-18T12:28:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAvQTYTx5kldS6nmKvcGerqlHd3STc5VFjs4+Mpe95XM4H
            0iuLSu/6IxHascAMGgQSr2gyEh/1pMPfAEf+VbekQ2Zth7p5UkT+biJZDcdv2hQw
            oC6LgvBN8uKS5SxwXZpy7bI257ygk1E/dnrTf5sA6BFg/g1hRVsPbpllx7H9VK0y
            nuZjHEq5oRICl8E++asZpK8B/klgMlh5VouNToGDCmdKLZagW+T+PKO4Og1M9e9X
            4sx0qL944tFfg8z63Q5NTiAhSB3HSDWFm2OL1omRs9MVpQ9buWrlU+xVAD7Fv0+v
            TZo4TtY3ohhZ0teRoqhDAZ0OycqpuwDURQNN21o6wNKKCrRFeurFaFKRB55fqqu7
            K/tE3cHPWm9PUtZoTezDyYkKdDL3NX7ZQwh60L2lgU9cPMtVYw580yIbpLNSY1e9
            ki9ezWtVXVnJTizYxEMEgCawxZ/AXuXuxGYTD5cHemhgEYUaGYvbu69h4sqc4ZuS
            2pGeEJJd6Hfjr1vu7B1brerZ/++isNvZxSqZnI5XZhkqORok1x0C1AYzcGyP8eLF
            V/C2ntX8ihymSLz5MpS9m36ZMkdyWDbe+FrseMw5qP2dtG/OqtazMjdVA0PRbMAO
            98+FrWv125K7PMdPQbd2kvZkB6qxij5S4USp0Z6xByJ9hJu/ICtpE1wRKgwybbzS
            XAHrO7b4JXlbz/xXdPARPWBT80sBnUdLkyzX2n6MDhievBtS5YoANpL4iHxZeNrl
            nOeyjoRJYB0ne4mYJ8Pwef+GuhYu0+lb16QIsN8LDnlsHmIWSh+Fj2b9rDfZ
            =sbSm
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
