spring:
    application:
        name: Replay
    profiles:
        active: local
    jackson:
        serialization:
            write-dates-as-timestamps: false
    sql:
        init:
            mode: always
            schema-locations:
                - classpath:db/migration/postgresql/V1__create_table.sql
                - classpath:db/migration/postgresql/V2__create_view.sql
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
jwt:
    secret: ENC[AES256_GCM,data:lkco4+AUi2ls+2lpCoJZvx3P+kFMg299uEhmGgSgmGQDuYJmj4DQOzizHWE=,iv:RiIOf8sqaNJOTYKEM+Dh8HpInKK5C1s2SxkmhwYoxbE=,tag:g3TDIDM42lrSAl32B0epQA==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:Vwam,iv:RctXrTaiw5noVuL+wHjUesGItALrlugizsnefPTDsWs=,tag:ol/j6qTsilgSMPns5f+XGg==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:NhY=,iv:lV8KUVyGXg2aGpsFEjsG4bfCX0WN25qNEO1P4wloN8g=,tag:vQ1wMiX1f/WgqSFmIUeFlg==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:7Pv0MqO6ICLai6jh0wGislHIb9o=,iv:LIspyWE1aLIrJkHI6uEeXJqCZWWWJ5Q+h8RiXrpnMNk=,tag:x/Pfh5JOchQIHcm/4w1kfA==,type:str]
        client-secret: ENC[AES256_GCM,data:E6LidZzbApxDKw==,iv:JNDXbeSYPKfbsHg4jkDpzOtaifftWstJ/xUbGGiRUak=,tag:VWwkGfSnq5z3aMzeUqOAug==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:oJOCY6Sq0R2PQ+wO3lmFy84MKXR51CO9vO8wuyvIb5zAe6Y71aPyMPAuQttPaeKG/VGzRpXKNfOFm4hvodeOw3aEmGUjLpHx,iv:zCnr7/i4S9mK/yJP00Gam7z+u9KyCcsd0zZCHZPBESc=,tag:dRkKnMsJPT/IBaNATd1EDg==,type:str]
        client-secret: ENC[AES256_GCM,data:+Ys1NB1HZQO0/sfafpfmeF0ttXJGmAVvV15dRmstGpHBne8=,iv:F06lOt1gt0ASvuJYe9okEq7YTg2bwprR6jpSn1OcV68=,tag:gSvAhnlkziY2A1pzVgclNQ==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:HtRULFSf66a01YefbvsP+btfkFW/OBu9ymvSCuGx4Ws=,iv:LXzEZTb4CXlXnFlGzq9WUcJSNm3fIVFkezzB7/3+Bvw=,tag:sKOuR1JAXvrNUsPKlaQbXg==,type:str]
        client-secret: ENC[AES256_GCM,data:JvLtdVROljlvotfwdXwLciHHF2XYrXufUCudB4MzWR4=,iv:bbyifTcKR9iLvOb2unoBQEnh87dzO4caostJT/h3HcQ=,tag:hw4ckNAGBGMn0kZT9gndYQ==,type:str]
s3:
    bucket: replay
    endpoint: ENC[AES256_GCM,data:6hAg4/pmSmY86uKoutrex98uGBR7gmPIf0jhXVXsAFNQ,iv:81EFXbbFKKIET1uWsi29lYod5KfX4nAaW7TAiIS9dkc=,tag:FHrLrX3yHmO8WpXYT9ftBQ==,type:str]
    access-key: ENC[AES256_GCM,data:U5o3tcJdaSrWnA2dUJAyZrwEDM8=,iv:ySlbcznVXK9QKAccK0E2uV8xRNK41HQfFdOPGR2EouY=,tag:IYYuVjWDp9qEH8CbD8YLSA==,type:str]
    secret-key: ENC[AES256_GCM,data:kbopVIM9PFIfO8S1UbX0DYi8XpHmtfL7SC0XrLppjTlXymvdoX7DOQ==,iv:GBeU40qEvmK4yFrx7M6cFpeMtWeKuGDOpBh6mehYrPU=,tag:4sZZMYwvVbTu/hcr6zHM3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-11T14:16:42Z"
    mac: ENC[AES256_GCM,data:0uZFNi4I2BlK0i79SP9kLAPeyLx0nq6EiyM2nZoHA7C0hilWhWHLq5vR1f9ojvM+mjOd+pL4+cJYdfgsmLILQYkb1qZqZOu3kh7ffgR0KQ00MY9frGGFANPOnIQuYCcPNA676MU5ICJscd5i/RikXidyukBlNgiA6VOhJeAHAPU=,iv:MnTO228i0HsPbym4/q/JwnwO0DlDaYFfitPx3fTfNck=,tag:bmbVs+NTh5RxW0071zXd4A==,type:str]
    pgp:
        - created_at: "2025-06-11T14:16:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA9fvGJ6K8Wfsf5Pgs77ISBGmEP0pynqXAxTA6sjemuFAV
            kxc8dMsGw71ZYS2jT3adIcUBBYcXf/5cLBW+TnWMUjlDu+KfzNF8J9oWbd+4oQKi
            FNTlNPDokPEU8dId0GH5Y7hEciN1tfSTv+5P6+VfI6XeENTNaX/FidLHx1ejapOP
            7xWNQLdAqKmYN2EfkdYfdLUo7HQqlBD3C6BuP2Xqoiav7ytqpfnN9o7ZiFfjndB4
            5ROM3jqWG5Gihia7CKxdeHsuoA1eAebLFtMqKLYpaX/WHcq7YoGeIYuxgqV2UDkN
            1vVMzH/J8PwgP3Jk0DVPe23a3gxaSRV6jLYYzvgm+6Roy+uoEKvG5J3yhnUFhIFP
            BMNFfbuogaxhQ/tVCv1v1ch+710hnLyF4vyhwjJUilLcHbJdHKUcSNDBWaDD5XTf
            6u2FyeZonDarthZzWCMI9GcTlfRe6HW0Lk98UEFnSUlws7Z5KWimoX/xto3/6Ff5
            HoCuBi01+L8Qz7/Cwaks90YXpBFG96XG7IQb8DmSwvJxZW381J3FTjVuXinfb1zF
            dbnngRh7bybUBZHg7kF1XEqsu+qtaGTTGJuNacmGetzYOviSBzj6tcrlBPDUVLPC
            C05Ftuj1voa0H1vSMoS6Ngx7cth9fJkAuNinPIoZiivaGiZkvsIkbtBzQiG3A8bS
            XgHLMqDHICAbzLfG2o5555IRFpk8JdYuMjuT0VLrbSgVS5fabZGE72VhUPCjKvzI
            qtpETnxrUlbhZxbeGxl577Cp6Og+vxQRLMKcEikZ9r0WwkIHa6UWPA7r8QOa4R8=
            =yTlv
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
