spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:Q1TUTIN+bADYdkv7T+erbSnHok67+YCepG1VkgutnwY52njW+I3+HRktKA==,iv:4Nd7fgNMsuI7//J3JRptgB2P2R8NJGn1Obwph0Yc/1Y=,tag:DcqhNwQaPD9jT3oFxpVhNw==,type:str]
        username: ENC[AES256_GCM,data:CkCWP+nb,iv:GTd4FgXRP3PKoJTwD7FwH3cf/N45CMSufFtt357/vKM=,tag:P0O1DGeB3y5v1Ge9OExiKw==,type:str]
        password: ENC[AES256_GCM,data:9vHAL7cjBeFQYQc=,iv:i3I83F8bL5TEQqc+nNnCuUA9vIThUSJ5qWfALF1bPiE=,tag:KJtMJCwxoOFqOesuTto3Rw==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:DaTMULNVOEG9td+rTSWQDJho6Rs=,iv:ZidXs/yNh+ey9YNRiMhnTLX4Uz3iSdcv3vYulnCpC50=,tag:2Xq3dYpjO6QXH7b0Ox7f3Q==,type:str]
            password: ENC[AES256_GCM,data:5/x1wHadHr6gPDU=,iv:ZWBOtVFd2vnxv7rjHHKsf6vIzKmJwGbMgRdBE9RHLo0=,tag:dxRRgyWm6iOBTT1YIFXsJA==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:49ndnac=,iv:CKoK5B0rZ8i0cgIxOyMI2GE0zQbFckqb2W/WPF7mXX4=,tag:+/T3+OKhI2J+omP/f9S4sA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:O35N1DjGFZupOpU5FaMxnnGOKyVPTHX4z8HubJZU,iv:WqRPsRgOe2XaaBN2igywQMjn5RBIeggrN6rTLz6AgGU=,tag:8tEeb/njwGZrz4isr3iKxw==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:u36RpHDwNXFfFfi+Db8IgrP1zeD4K2t+sIYgGEKF,iv:m6PJLg+MEb0r5xixIrm8nSLi54z++8O1zr8xG05+qlo=,tag:0xNSX9t0A5orafrQ7oD8pw==,type:str]
        cookie: ENC[AES256_GCM,data:vV1oA63CWGOFPs/XPJJMeg==,iv:uU83ma/ppy5wxnX4liKOYXFMkTlDtpKHAsA6rUO4ijA=,tag:++447+KJ5tUDRt+ajHHndw==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:u24wpetTs0G7jB62J/ir1yoe5KWMzHix4+W4c6RmvODfSxsCDdAGgunqsjHdyiBVYJoXwpc=,iv:7llEqQAjemfScHJY+sl9xMl3+MG66qGIxecLzAYgeiA=,tag:715NGgiLD5hvS2MI9FPsXQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:YrcXrz6YbGbHCEzLEQjRK2WuKiIB9Lz8H36lIqZHl+LRY//YI7iZyy5JnuFET0vOyibBXBSG,iv:Yk1lD3keJN0DdFhiAExGAQg8hwbkmGawj2VoPD4XojY=,tag:N0gLBFUQO6rR4r/+qhHY3w==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:py6ERxDAQU2QrtaPcW9u6ez90VFtu6TgGq/UovfiZIvdaV0iyE7W7KVTnD3CbwEY1MAt550=,iv:uLeqyOmmP81iXrcdvqDaR2WJOauqldQtGGDADdhFv7E=,tag:VsBkWt4w9T+ZcvEw2ve9Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-10T16:05:02Z"
    mac: ENC[AES256_GCM,data:4U4Hbdi2xqAUvkh71thzKOOlD3KhnOi8Rr/88/Nncz/VmH0CjHqsEesf5HqLOoDMXY2FRLGxs6h59mWkZryujQyRKrqvkbmt87OB9yOntgIhpEt4TsfWmQCE2rdkog2csef0+I0/IFk8lLplVzbDM0lyw8MIu9cadlqQBMPOgPE=,iv:489pEccQPxEDMUuHAz8dOOI2XouunXAz8qEEavzW/hk=,tag:MtKD3agwjdbEnc8fJ1Q9oQ==,type:str]
    pgp:
        - created_at: "2025-05-10T16:05:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//TzxPxPwHt6NDJkV77fO9ZP+bgYFU6DUA1EHVL0AXd1BY
            V9C3euPpdJ1KZB0OlBqm8PseKBQQ8MCJHsmd0c4U/XeScoL1wpgalBvV5PLuYV6X
            If2ZyZj5gkbdJ+YqwSmUHizdNOJCl3NBcA3CbBGLeuOcKwgsv99EatfjM52mzQ+e
            mpt/fcZQQ+D3HN1SHpO+u0alsrYB4V7WOWTWqsmSboCdCyPewex/xKHJylctbBy4
            9O6QfgeVK9PypP6eWRf0VRAVrga9CjDUjX/JT0qrQzVjPJFVTlRV+uoKZBMZRzAl
            IqYcirTMg4eaJHUVgHU8KNQGNmsGQ8kBc1ijJoSQl+HNMPjhkb6Xk8R7O5l4tq6q
            4XUs6Rvbx9jtDMVqITQkVJ+vrXuqtzAoE5aGwC3PCPKOwHoCnXUIl3YlMzlEHV6Z
            ZMPItAd28vMcDSOqNyMCWvNRKMeH4tDNuXVDwuduRzwVE2zj4gCClFUv4FZSb+9l
            lBt76HBJy06N3uh+koWQIHMqc6sFNuoHoeJp6zLBrq+78rwUS33yqHj4eJY/w8Io
            MjZP/zKEC0wrVO5whvgHqddy8u7t28ictoYsKcLOGz8k2NKdtqnzGqL+pqSN61gB
            9ukqhAA6KFyVGorAV5Xumc9+xFXIcOk/eDeDSWdv/mEXQMowgXnQppFdsWgoEWPS
            XAHAhVkRV1zFA40a71RcrIZ1C5DD6UgeKiEodtPf936qKW7GwwOQ0TyFkw1R7E4j
            ovFtQ+CekCmEXmYLtct6URI15CFE+hItIKqSUIT3SCItnwQgNvHYZcEEbqV4
            =li8e
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
