spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:1DDq17RybCKgXb4u2i5LCkTtvvs0BBX5163E1yTKv+3vrHpiD6oL2J9r6A==,iv:6fEnB+zdaDgCyGckrZNW2Ek0BOIslStt7aLetD0UZCk=,tag:lfNDZGBk9e9A8uvgkqYe+Q==,type:str]
        username: ENC[AES256_GCM,data:2oTWaX1N,iv:Ng8tsV2/NiDI18yeA31QIPbEbpwS7geZFiIpTh52p+s=,tag:cSrMyh3ii1nLB7z9zCE5Sw==,type:str]
        password: ENC[AES256_GCM,data:/LkYVE9zrBrKi+c=,iv:yX8jfHTvLQkZIEiEfoeM74hzYLArzgVUD5S+c6tIKg8=,tag:BoBmsK2fsbiY+a936cpI9Q==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:1f5iECsZNhVMvG0zclaCy9aweM8=,iv:+P+PUgCoew0TCfP3xoLWRAGajSu5dSkSaMKOiB6PL0k=,tag:V/sTd3AS05mCjpCYzf9CwA==,type:str]
            password: ENC[AES256_GCM,data:Oqt6by950zf54+8=,iv:1XovWaqBxnD3bMldQ4NCj50Pj5FF83AL+zxhlCdfuws=,tag:03HgTBHiCApwXWM0JsNDLw==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:2KY2pSg=,iv:GzFygxfxoNCUvu7tnWQOnLH1a3YhiJR4a6jQhjxOhss=,tag:zffwdRhdKYozymUGYA1nAw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:3sS5L9bDdxL2eRO5+p1ZPy+VRp/eF4HZvsdOgpvt,iv:91EVEOoFSQ165kP/HWvMeMWiHn+U0jq8GF+3800m/+0=,tag:A1C6YJpVe5V05mVOyKchLQ==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:m8hwKa2IrgJDIwWKSr6wZZoUAK79EzjnNkEW73Ay,iv:mX0Tkbp8dUWnTttZWNUm42/fj2lrY2i2/wU1zTWT86M=,tag:gG/HMefMv3OO2KV3tnAf3Q==,type:str]
        cookie: ENC[AES256_GCM,data:LyAlrXDIV+9RtCyXewbSYg==,iv:920xqSxQJEMkkOKZSORbW4z8WlkOEhr0K4ajmk5x6Zo=,tag:LRdVPvqJP0UzJ1AgXN0HNw==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:uJ1GE+0u7mGJGHyMo+xkV2HSdLs0zrwLYwx00SLaduehPsCYYaaq+bqS/rR+O3UDB3yCOr8=,iv:FYwgvySrvxffxlPciSLSUy03/2//0bajf+S7blXSI0g=,tag:ASTNHN94k8KYBlvGyNDJSQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:fvCXVcjpHFOi51SGpNxhg9NqimXGTUwj9hAxm4g6DQ2QYia1I+KbkkKQSWURK8k2KAni54RG,iv:TZTyk22CLkF+Zmb8NHmyZ8JhQFSmxvWjiqRnbCop9U0=,tag:FRC9mUiAiK6iuClmS0LNEQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:5BTeHJ6I5KPrDjj/z5hzH7uBnQujlUmjsn+AShgIezQsGNbXLHOxAQfnRnYlXq7KLPfKRk8=,iv:7VPtisp4asceqt0IN5uuic24G5rYcDnWeUiNglw0NDs=,tag:FYvyDbc91q4QG9m9AeOkLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T14:02:24Z"
    mac: ENC[AES256_GCM,data:gz7RxFJiL5xFeLge2a8pD/sMya6L/+MysTZC5EHcjU4p+XN+xaiwSpTrgFC9hzxNZcagv1u605wTcmBC4iw/wx5fQox/bctaP0zgCFl1/ZyXK1y+uwofBVggZ5smVFC/vOBk2xaVgBp1E0iUZ6gk2RQlLir0MBMAtcNdBgWgqRg=,iv:xYGTv4/sRYehWKy5xpouC9bd1nFSF+RKAbQMoDMRpcg=,tag:+X8+zLt0qX7sPHE6yqFImQ==,type:str]
    pgp:
        - created_at: "2025-05-09T14:02:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//dCZI13be4eNzI1OYV44LsDo3LKLAKOSWgRiv0v5zuUtA
            j9VFvCKFpBWv+L1ml1tdGrReqZIdpkqIKlg0Ooaa/UVKJEHwFvxmH/mAvd4qjACU
            p64RmU4EQ77XBfyRkAquF8KgSXPlOzzS2CjtO6HhvRJ6lcR/1Frmnc34sfvA2fWG
            nd0aDbMYQCGuFjqX3kN83X+Me6q31RkNbEZJhzDvjVDPMtjO89T1i46HUZnIeBOM
            fzbFCaeYR7njqqG3WG/TBpqd7oYCL2bvenYCpdte3GAjG8PTb+u3QL6ihPwwvliw
            sZNcRu2OMMtmVEETo05fJ3fQHkWn4LK0nCbS7D1U8RifVCshfYh2ronris96Brac
            E/qfFEB0qYvwxSGSkflImQEjJv7FrC6cLTSNwkY9BYK26pmpJYvG97nqEoBlbG8d
            8STECC9zopo1kxCVBHIaQCqeVLapJS8ZLEOf1FAMzr0nEtfl1vhSf7gYqGo/nuyp
            2hjJbnd8yT+5ufO6kvI03p2d224b92kg8lyjdHSEaCjscuAbzUHdCO4nDjIibu6F
            C72WU1fk1wLDDCbOki2l+ngc8uVqXd+sr08rbrC822X+wQfu4YeQnvP4TnHBydVj
            jDkWOU1JwMn+aTLf1P4ejvBFBj7z+dioiZuETWt7OjpPQCqZkQcCPE5Ch1QDnzfS
            XgEAKq7NHcqgt6DZkVp/dngJ30LgoNMOR+pi7ybAfJnA9o1OVf5398jbjWWU8QwN
            CRHU2eaRopN4iBLQinxdpKK3hU9XfxbvnqzYjSWKn2W6mI9WxeVT1RxybEf8Dzs=
            =W5pt
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
