spring:
    application:
        name: Replay
    profiles:
        active: local
    flyway:
        enabled: true
    jackson:
        serialization:
            write-dates-as-timestamps: false
jwt:
    secret: ENC[AES256_GCM,data:4Hs5t4E11FwYz3gefcVQhd/HJNjS7O4qjLkD+VIVfJJW0Ml7lOANaBpp7Gs=,iv:kfi4V11lxgOIX6IGlkvu913R++Sru3XsviQKoTPEGko=,tag:AWdf0/l7ngxqhPCw7NDfiA==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:Juq0,iv:eRlm09hZgs66spYi0U2Eypp2pghOVt2tVytkccd4BfA=,tag:j4k1XT3BOgLo/qhvsI7RvA==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:E2Y=,iv:MMMHIahOUHixbLzOEzz9cciW3hGERDkOFByoK3W/4ck=,tag:hHdxKD6Wf4LfXGlpxxmt5g==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:v9w0UIutehbGsQ0JMRuclhHlkoM=,iv:0jVHiqG97usWZ7LmVr3900IQ1IXzynd3LST46hJ3MfQ=,tag:ReLCTwqGx7cCsJl+qTHp9g==,type:str]
        client-secret: ENC[AES256_GCM,data:hoctjT6LuC+PaA==,iv:/72kyCTHpT1rOIS45oejYURNeYF+5o50qeTciLohN2o=,tag:4g5ZE/Z0aZjHBOHtEVW1dA==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:iO7FkqWMHkrt5jvpVqNqXYxDN3ixgbxsEC3YxkD4g0PhjQey4OpTYrd0XT0smTVGtpfAdVBWihyQVA441GjwOeDsEt8IAEco,iv:XFKi4RlkSzguBxEI0L9vjQDJqeeAEICTuTIw33x+rcY=,tag:91K9rOJC0o3db+Ptf16oQg==,type:str]
        client-secret: ENC[AES256_GCM,data:kJJDjOJbNhuYio2+VfHmeheCWWpWddXyWXYlLoV+yu809bk=,iv:8bVwjHaa0ZAWjVyD9NxEqk5dNO/RbxrK0vumFam41Uc=,tag:/Rmn2qXWoYofF1H0tFwMWg==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:dwHLpjOCFwu6B3QPjlDk4JI4bG2a3ca43PW44oN8afE=,iv:kp1euVf2OSjFVdKEo4dQCIFshZPV88CScn60nh7A6DQ=,tag:m8WOzhAaI6cPcmvunmFN9A==,type:str]
        client-secret: ENC[AES256_GCM,data:9cJi23JTvEjfjrKI+pDe8/T/CKVtJkWZT34IFKH+qT8=,iv:MjWbRyyiC/f5rjp3W69Q3b2Ye/BlsgerdxtCDDy2Udo=,tag:afqvgD4sQznXMnmHM3oCRw==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:TbHZvqCba2ZWRmy3wdJEyMnGxDmCd7qVvAF/UR06972r,iv:3SYt2DqI6p8JCUQy22bJQgwaOdhKxBZ99gU+Cs0l7ww=,tag:gQ6WQgYgBUd1mUAP72zPkA==,type:str]
    access-key: ENC[AES256_GCM,data:f7bTxnEc1vTeCzdl5Z/LwOqNO1Q=,iv:Jaz9HB8KsPhIbQBU0rQRIGFtMOyA7WAgCl/mz0OmP4E=,tag:8oYmub1sCCyGelq3EyFSQQ==,type:str]
    secret-key: ENC[AES256_GCM,data:jm8Vq9rE0Zlzmhxe/9nOOZN3gr29OyYVYLSDZMrvoeGezXUyEJ3zrA==,iv:cTqofG3SHMJIPPHXGvR4BKd9wiLJ3qiHIuw/ktXMLZY=,tag:nFNzveLoXJw3CQ2yLRIg1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T14:01:10Z"
    mac: ENC[AES256_GCM,data:8xn/eQMxET9NAt1IJuPF3QqGFdlQl4kRBNA8sF7ThyccUdlqQW/JEI56vNtxAJ6J8eGB43NOmYijG8eutl4kRyyfd3+87/SVLXStN71RyUoWFIoAN94a2vLfjbgkBBCiYU0m6+I2/OaOJa8I2hywH1PoZuYliL8ikTHXjv/VBuc=,iv:CCfuNQ8KxrGKrPfXvNylSDf9TCgzFP/oe6Fty1bZbbA=,tag:30b2fmn34tGHAnXUesAWbQ==,type:str]
    pgp:
        - created_at: "2025-05-09T14:01:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAArxJNQjb3/1h2Z2Q5GJehhJml2vDPFXc4MaMJJWfI7XCw
            k5DWCni/i+Cd10yPosCJr3oKelrB6fSkOq/ZrWU/wgRYMMhdVNsQ6RSAWW4Yvg+A
            KIzWY4yw2Ft70kfTLnxjxYEjq75IhYHgtqwJUW05PF4c4y972Vl3upbVOsXVWrh1
            CgsyJTZ/tnRxq+ikRt3f4IXBPCyGLFWWt8aveojhcU1Iq48HHof+ISkQJmg1kmrl
            iQ0a9YnXVHi/oBICTqTnLDOxVcMKVGWsJpNDlSzsXQHS9lG1R0oLZoGhxvIEc0cE
            /BVvd0SmfGY9lQ702V5XSg/BfL9PtZ396anFkNGxsyK2Ocg32O3n0arcjP6vnUrR
            a9kq0DFC2tYLT0o+IVhBIoHLjW02G/PMsIgOPV0MvenH6yjHJAG7geKV4mI6mTx4
            0oyqH2r1we6xlS7WGs8xH6i7K4qNmBJPjATV6a4nt9cyDZ80+59fwnvYt3yOEhkC
            37/JLGyf0TLqQEoSVlWUYy3bWGIoc5wKPRLsYQUmH1fkceabY5GoIV6rUijEVvJJ
            7LsdHxbgG66F1ebfJhSWJCINKdjx4ntG9zXQA3ZzqlBB7mEps8DQInpT2j+UTj8F
            5EyvyYwcnUC8CqMKSjDbm1n4J6/Dw1Kp72pKvFZJER7BD7sd3NNQ392XWtQ9L+vS
            XgF+Xi30RHoyGxW2+lGrZirVDhncvtgGa+wygu+A0cZkdHwWkhIW3fTKwZMkSEdW
            gG3cRLkIQ6uHiaJtWHuj9S4Fb9wouBXxiM2n0m5aZdID6zHJOX/NejhCJi3OPvU=
            =lw/t
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
