server:
    ssl:
        key-store: ENC[AES256_GCM,data:UtTNkCEBj/fig122CfNCKfObbA==,iv:9fXPJaCmcG+6k9Rz1Ul2iAr/rdgMkHpxBj2pXx+eRtc=,tag:elULPFfhtHOu7Ad5Ir2FEQ==,type:str]
        key-store-password: ENC[AES256_GCM,data:pp9ar1ATg3zoyUQ=,iv:elrki0a6GdgkuQvocnc/pd9GxQWxt7bn5K+/5M2raLY=,tag:LKBK1AqNsqOdRzXk76wRfQ==,type:str]
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:JOB9zRKpddm5rJcDSy1y9HIOd+mP1/wKVhAskXRsVWf5yIwDdQE=,iv:rlue2lGeewZswwdhm2kbT0wlD5+nDmU/DKsXHFav3k8=,tag:w6YJBWOni3vgRzBU6uG64Q==,type:str]
        username: ENC[AES256_GCM,data:qNJr4iSU,iv:kD7ryVMiEu+bFKDImL7c21je7W1vgXnuEURVkFjjsIs=,tag:RHbdbT9ENRTgqOVk37KXyQ==,type:str]
        password: ENC[AES256_GCM,data:IL9WyC0PCH/ip+A=,iv:4ob6IjZzqErYyA94yfb/+UuKy767wm99oh01zoeNW1c=,tag:WbRsqAUkEFS/JvxDHFbkCg==,type:str]
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:3kJhN//HOljHuA==,iv:kZb5nu6awgRnneCWs4T4p6jaNX3UTWZerJaFAuuYDb4=,tag:k8R0cIIbkTPv5rsoKEx04A==,type:str]
            username: ENC[AES256_GCM,data:IeYTdskUcA==,iv:K3KM/bflsZkHOP07TrPRlmAs3CcaPbBq/vdlOFE/x48=,tag:rb1GlqlM3+wk6zeitrtFiA==,type:str]
            password: ENC[AES256_GCM,data:057dlwpnf0Nj0HQ=,iv:FWtN1Kc7SDMbjlVPtsfQQJcLxdxrXX28MLhrzVSdFi0=,tag:Pyh0Nrh+Qwvcl2pe4yFUZw==,type:str]
logging:
    level:
        org.jooq.tools.LoggerListener: DEBUG
app:
    domain:
        frontend: ENC[AES256_GCM,data:xv2lLc5nlrg/DVb41WM1Ivp7WWvq,iv:ttHvZ6Yl6Rf91jNdKXYUs8yKQlPFBbRKmhgPMfZ2fUA=,tag:guh5lvX5IqsKz2I9h4YKpg==,type:str]
        cookie: ENC[AES256_GCM,data:Q+YCGyq3dmC/,iv:k4/z+kRVvdYYkxDfQAeFjULQnFxOtRM0V4i31oHlc14=,tag:3z5QDMU2+uY+n3FMF2WRtQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:pTzTLFDbVx1xF8SEpmZyubZOW518C4YiiPTQxO/7wpShBd07Ps1X5y40zkNM56owIhMG4BnyASnl+i7FGQTjxg==,iv:8yM+p6J39zNt97SnII12sRTZl9U40vleACtENxV8oPw=,tag:7MRcNSxNOaBTDJAi1EdVGQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:d47NTVGTyOahqo/yuGSzUcJ4Tf5rM9ek/6q5iGFHecQL9+3ftxYMm6RrzpbFFoo8iVqkWHG5lxITGNYIqvPQETM=,iv:L6EZ3oGeXdaP6YPnK7wuLtClNF9T/ZYJ0Liv/jmU2a4=,tag:TBxh48gKAuIBc+G/27kPHw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:GAIiksIp2e5ftLH0nReWO5EbAMpwJ9nE0kIEGbrZ/KCiGRA5e+xj51wyO2cBQWk2P+P/vwkhwX4DK4GcGheO+w==,iv:7COKJFbTPn4cspbODF1x2TKf2TMzLuUZzGaL9Rr5HJE=,tag:IlNaahn4wAELnxm9leLToA==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:QdwKkKefpsynecOTGYMRnXEm5Do6t749ouhBia0qbvwB,iv:JcFeplG6abLeTGApJEdxU9D+/LP9rYOYA/UCU5ARnh0=,tag:sXLLLq3rMyxoprLfdxMFww==,type:str]
opensearch:
    host: ENC[AES256_GCM,data:4eZaDxxp+bO15w==,iv:AjNJ38mRlDa7ATrqFCMHIMsoty27TaU/VIElMheYwZg=,tag:c0e9cvEHGodSPkDVD3LU7w==,type:str]
    port: 31188
    username: ENC[AES256_GCM,data:dDb9g5k=,iv:oqkiMSo/8Zs6iuv+JMqlTqGcfmaRtLPTmyoIDVKzfTg=,tag:xA5R92YSOXsWJUpgKSazWw==,type:str]
    password: ENC[AES256_GCM,data:CrlY9j8/6S7aFFY=,iv:ew35o8j8QP41nPVtYzQkvjYC06M8sjlPbApUrvNSXDg=,tag:3HX9s7dX9wO8PzZFCiPWeg==,type:str]
    truststore:
        path: ./truststore.jks
        password: ENC[AES256_GCM,data:RqCtjo2zdsFsV38=,iv:SodMy09n1Tpk+MVxuYwX8T4WnXW5uKbW9am+kOy+UQg=,tag:F3K7HqegIfoUZ7aS3T8Nzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-08T11:39:23Z"
    mac: ENC[AES256_GCM,data:VGzh30lfxzSXgCc7jRz0RzXjIEbF4WK0ZRT5zaNefvEiFE2Op9uxajqunI0ucpzkWOMFo89l5KGNWdxk3/JXwqQYPEHbnG2iB1f1uJNYFzBdUl/07aqQTFVWOSJacYFuVtvY6YBkxv5wYX6mOWtopB6WeYGdEI1GYzPBtZqEwmw=,iv:25OngD57QdH+TQW+yJbsooBuGyfvPTl5AMeE6gFUhKU=,tag:SI5Rzg1F49Y8LlWNiiG1Og==,type:str]
    pgp:
        - created_at: "2026-01-08T11:39:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAjG8y0xqmn5jzX1q7LpWKPI9C2v1RwYhw5pUMd1lSv88P
            KmtzpRB6gyLNilOosEEhOQKB+UAbEEHJfwSIWLe62IvjDo1IeJXu6cTeDz2Prcte
            S6X1l+rVN+OLDF8PSV9ncccjNQq+R9eDONHAg5D8APh3oNl7qrPYUfdeSsuhXTVG
            6Cis6K6vQwqCqdJjzHEVvrrTD6yZNGUx3bjoBDbvjHvzc7yAwcPUT1iJ4blok/Mv
            QQx7VhWYRxb3xkf1YauPAXlimhu5OTTzEOm19kEz5uEqqEMADm/CWQIaDUwRtWZC
            nznFBKX2n3JEObbkSWlSryyQ9fwYtvM3BxIbPobUVkRwHXuAAFjR72jr0dyQIKN0
            dT7Vgje+JNWFW4kqQEcPo3idYGJlsTsx2XNwp/TqcPMW/W31KFZP9t1ZKiGlsOm4
            btQLyRoFiONPnm0at0mbsCgbnsZa0Tqk09IjDdupCfVvR2ixazAZrKEQ7v7z4E77
            y6NMhMhP3LHW0gSUOjylM1JTFmKMSDxTvM/3nBS+kVsj+j9jnNhRWfEik7/wWTC2
            oW48pXZTE2HR2JCLoabcWv/0y5PUcGvC7KVRO7qP4I5pLz7urt8GqJa1GKO9YlNe
            4VD+EWFvlO7KmTzmqXhjH6vwfDCWOOIIHWepWBX2m2z/4cItL/Kyhry7/xmXBV7S
            XgHE1FHc/2HqWO57iJQjQPk3r5p5BcdtHwNLM8GqS2fQZVF797AIaQimIW/NQ8yb
            NZf3d7nuN5lThKd/brtrBUgpKaX6HJisjJJ3uzgx1lHEoD8tFMoRj5KJ47OlB9Y=
            =PXB7
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain|master|node).*)$
    version: 3.9.3
