spring:
    profiles:
        active: local
    flyway:
        enabled: true
        locations: classpath:db/migration
jwt:
    secret: ENC[AES256_GCM,data:Cpt2+5JQyLiBRmFG+k1+HY5D9GTLrbuu/UhW06G4MB5nybaSDyiQfkUo0m0=,iv:INlKA6djfo2QIMWGkGLHvdSVd1zvGEkllK+3sc4WsP4=,tag:TtfIwEbfy2D6aWgwd+nocw==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:62b8,iv:BFOSP73klLY9ShkCy4a8glpxze5dL6ZQJ1OIaDIqU2g=,tag:9dstTNoPYN3ZrBKNTTm+jA==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:t7c=,iv:mfRrM9rWWOa5IYDR3PV01P3Y/Mul59gHwHjYRFV7Aso=,tag:3oJFWDu6u9gSbwlfbQ1IGw==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:ZCjo+nAzgR/pqjqEgE8IIDHJVPc=,iv:dBVZWLcjHGbNCS/IU+jhmsZAVVKn2rDQgQVTbtvndAU=,tag:R+xpLZX0sj36fg+fXRKwSQ==,type:str]
        client-secret: ENC[AES256_GCM,data:dtLyRxv6P4+CWw==,iv:0mVViU7DOI8Tu4KhFWKUdaNRXzTzp/+0krYyvgve6yE=,tag:W2CClQ3fZwLLC9GsZDbSxg==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:Xx1eSusYqCtUOdbgYTYp+6tAADcPq0bfbih5Fayel7aiKCcp2I7Q5/Ee39brs4AWYDEANETInKJ8++j2wwtNjLsfqf42+hMO,iv:HilWwOgS0P5G+kxPLlWHtlkS8gGqYou0EPQioZVarSA=,tag:aGsmqhM+4O5xrUOkOBoYbw==,type:str]
        client-secret: ENC[AES256_GCM,data:WjgXB1i5wn6IQRR0ageD7fFbIZgCnThdm7y/D1JwbdvAsm8=,iv:zrb9qiurAOK2vFrocgDZLLrmid8OKq5WUoO18ldExOU=,tag:doKJpPJroIDWFB8TiEfrHg==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:doxmD+PklnBs92u6qBaAlzLDg0CugMFcSiQ/vncDI2Y=,iv:/Phr8v9AiKUll/uaQYISZrelghVtbk/M1Yr3YRrbi7E=,tag:g97RpABeRR9LCwQwRcR7Vg==,type:str]
        client-secret: ENC[AES256_GCM,data:QlSPa9QvcnCFg7/K18vLqnBLa6SqU+gzGP2vJScpnu4=,iv:kOZ2UxywB1PjWyXOo29Tjbo2qy3QcVzh0oS4HJbpSZ4=,tag:BnT2MgKL//xD/s5xYL4NEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-30T11:14:48Z"
    mac: ENC[AES256_GCM,data:RpuVDPVe2dHyTHHMz5DfU3hCN6SZn0QDAsL84yq5x6u22CxF3z/zQXbQsM4GqBgsRRbmt0tz/G5UMwQxX+tRSxq86IZWJ88yelNdlZ8Q7EuLtqfFTDPFQly5JXCvKGm7dNnhDDnmMq9GL9IWjTLrlPaTpbosDrrIZe022ItTK+c=,iv:cT6dXYXSMvtLeiYNVVZpf5MEUsTW/KcYPQ3aIv2EAkE=,tag:VqweAjMrxPG8WcLen+7uMA==,type:str]
    pgp:
        - created_at: "2025-04-30T11:14:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//dAX/Wf8lQWFGFDdCng0f+eeXKfB8iIHR1WbG3POSu/Sx
            LMDMEO7FV+MA+toEIW8501v3kJn84P84yf7VkuwgHNiuLBr8UBXnNowWGwujEmXU
            GfcFwz7AENhDQvoC5wCMI6Wkhae4j8uSU15TXpkDJTh+HaBVQbpbD5PjKUmFYYRG
            0K8GDU3G1rfcXjP5w7oT0h4+3hLjXQM62fOKEKMEiPL75aIEbMxqXILh64R/0xQL
            T8g+PEbmO3HP7Qxd3LThRL1nb1krFV37HFRmqnt+khO5yOTaQJPEgF3M+bJsBUMW
            d4xmunbCd42SpI5ISkNiB7qpVZyc6KElBFf7gGSralmUSS1iqoLEmHBzsFfp5PCb
            QfSiumdKZyDNIXD3gTRb57KVBYHcdtohfWSBn3ngkQYnfgklGVsbeME5YHKSns9r
            0jLqKrHvFZq2EN3BAwP5tka6wakf/wcQArix6fcfn81ywmsSKaUSukBkiw4YX+NT
            HGUg3A5K5jBu/LD+NTRy8gjm8AQ7WQKCKu/c+wtcA1yChbtws4mTX8xG7eW115Qm
            uzoK8NE1rpAVMyEsKOGP5AThBwN/FbqwRlGXRu0h3ZJFrJQGZZfGo9AEKsGZc7x6
            uSr3k4EFdgQAmNX/nog7jXRABAx0fzslDC/gto8+PjWX8RMQ5WHE2++O7sp0e3jS
            XgHHHZOpHbsNjj1hDzD6QAZrGZ9IPeXfPUXHLr/kQFxk8OZr042WxGbkggRYtY6p
            TJ+ViTmfEPzncP2n4MZBofEc1LLepETAJlWeNBu9PATooE6wJLgHVXbODFI5K30=
            =Rh9T
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
