server:
    ssl:
        enabled: false
        key-store: ENC[AES256_GCM,data:rZS3CraTSRNODBBoSIRBg0Rzqg==,iv:MPYwZ5/fDxFRQOEUXxAHs7QXPKHdEZ2ir3PTR7UxiTg=,tag:E4CQ/K/ygZ/DE3F3p2AVVw==,type:str]
        key-store-password: ENC[AES256_GCM,data:5nErnpSDDPcZnNE=,iv:6ndo+Kccmv3PN1QFKUB6Fsh6iDM932OPysIPhVgdOgg=,tag:7b4M3oIC0XERDEJypyKtpA==,type:str]
        key-store-type: ENC[AES256_GCM,data:e4w2AWLb,iv:93B+DRf5S9+T61f7VUJAzgN8LOlcbKAaAH8leILeKCw=,tag:kKtSH7UFAEbVb7csef581Q==,type:str]
        key-alias: ENC[AES256_GCM,data:ryNjOoQwt1EenA==,iv:I+uLvox7X8PVsMI0/hVBZAlg4OUVjDY6HMdl1CGp2iU=,tag:q0ls5jz/xJlqoY7MGJN3lg==,type:str]
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:ix3KeJS4m9/fFUemmj/s6p1RcmJZUgXP1axg6GbsRfymtWL2ekdsTjHgWg==,iv:6qTHfmouWwsAWPRtK4L7GeHnndVr7Hw8Os9K0gDNoCk=,tag:5VyWa8peNq5TckjGuVYBXg==,type:str]
        username: ENC[AES256_GCM,data:XleqUM8t,iv:d4P3y4OL8TP9Uj2G7wflBaawfmrimpeVq9JpUfhfyI8=,tag:UzRXvps5o6yDMbJk+1RFLg==,type:str]
        password: ENC[AES256_GCM,data:GZa8GCTZ1Ekeqmg=,iv:s4sDa8ging6FuAChVNtyQzMtuJP4cZ/+KNB13OlOxNk=,tag:BYQM/QFqqcvb6MVZXRPzZA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:laGtbZ5qhxMnUimXqgSfSOwaWAg=,iv:kgug5pRuoQx70LWCB5349tKWPNvr64bH6oDJp/mpkyg=,tag:eEA9PU5vmJNc4J8jJAMZPA==,type:str]
            password: ENC[AES256_GCM,data:Vby2RRttaoLJ8qQ=,iv:NCQwgiFzfAVbLfm57rmrL579TW0BofNNRT/cvGXRuJw=,tag:MWAI/2pIm3aXPZ2yiL2n4g==,type:str]
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:tmPx0pU=,iv:dgFyIycLOzRGZ154gWKXsfLsT9c/P6aK6vUutaAfpaA=,tag:GbL0nD55G0yisEFgw7fWXQ==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:bHMHYd+oOWPbEZ6s+jbX4dwDNLfB20e/eRFXWLbR,iv:TNDBlAOcT8t9MTCzKbxi95SExWAb1ZnviT9dRJjMHI4=,tag:CEYpSMHmMJZWHOrVU1Ta3w==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:ZQzmOHOfkUmgq4Iu3hFsFybAbCrS,iv:mz+cHl4IIyMS5nl4Hx+IfuEoPKt8sNkMWjFEq08yTds=,tag:ZdAWWaLlq45Tbc7r7MRohA==,type:str]
        cookie: ENC[AES256_GCM,data:DfRea/nfblEv,iv:bMCDZNHEY5x7V5Szbns3wW6qJfnPTAf0pS/Aqm8rPUs=,tag:vVHmJpcoBTt1r2l58DLL5w==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:GKZXMiahl3GjGWsymHewmzqj3mqW4rLaWKT0I4TOzQlV4ei4WCqquY+SvPtOhZD7d0EXoO8BS/Drjkk=,iv:NWivLo/MSiy3fqgqFM3+x9/qYPrlYgh/ivBC5gmyEaE=,tag:6GmnEs9wrHOQK0K10bB6cA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:CjkgrJIl7i2ZTQKwXFhttS0CmYhbQenw2PkBaffMGHLIVtn9NTKNMby1OaQyrEwbBN5DA9FYJ2V2f4Uv,iv:2weqculnCh1NK3JEXqQDoafOfLnFVaT/KZobVgfPQ40=,tag:3TNngz2dOoJQA4/oUz8JeQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:PIhPWN/Xf5tvAzhzPDOxvuw3E+PLZLtOyIUdZ2Tjz9RzJDGGBa2NOZfOE070y1dgY1ve14tSst3DdFU=,iv:6jtSRIgi1gxxwZCOWnsnFtBoyoLYFQdR2u5UWjxUfvw=,tag:JXFyW4tYCoaWerNOIuHoLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T04:52:34Z"
    mac: ENC[AES256_GCM,data:C62vJsZKcxMVPc/u+ohHlzjM/TLzOGmvRCYUdnD4VAAaSuY2e2VRoFfa4bPSlCJ3fXGFeulsd0SHzAnYDfRFvlQefJ+Yo/btI1jv/m+iMMSXkwX+ivcx0q9SXS9UJuTQdmgbPGD/YPyQNeegOr2hbnBCgKj4HYDsizR8ROlr2aY=,iv:0FT5a0xeFbZU1HpCT7prv5/vjdlcKY4P8CkTtodFvUg=,tag:ZN147UNWOlNxzZHYo9WWyg==,type:str]
    pgp:
        - created_at: "2025-05-18T04:52:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAsFe++KW5Lqap77hamn6gtCI2dfM5rkc+BOAQCCVZApwX
            ILwcUDEaDF6EM8Rem87KYuyUoKU6ocsJTLwGljAweit60M/hsayP+LUArjgI3NkG
            3EaqatuhNUXFkTof2iyUCF8/FecnrJMui4xrPRosnoe/khmIyQK9oYL9V6BI60DR
            oSV8Fj7kFyIusGZFlMDYZtvSbjZ9RlxVXkofn80TNkYFZRNNcvnwtz7hylE60jwe
            yw0aEhjoeZ4WDC4s+JBS9ajcQTP2DWEmFyyLedCm3uWhccRfJaEFk3LvQL/uNsj5
            OUOPnLHs9IUAxfiXl2K20SDlddl8IkfNQkj7sJtz6hohprnCtXDVpYYdDGFmMRyW
            8U6L6Tq7tjho+tUat5BDQMwTM3Jh7r/M4tnD3Lq0Mx2GmHqcRhOmy06qTKJD+O39
            q+7p3YHfpqngv6l96mg5I2W+96hH30+B7B2wqmg1lsJfQhM+WzUT6d9yD++jCKc4
            B4loOHTGQo3wrBR3edLbszSycM9MJvoqN6mz7VfHyOQSzHBPWZX35hWqNXucYmaU
            llkviwUOOsiok438drig2DOQOZ2/Gc/J9CvmBvk3f7EpM2wrzz7eNBeSTkGdtZem
            h0E1/3TycHeAXL4mCojPaN/0w4an8cJCIryn+u7mIbnP5QG1m8EltDfQd5ucLIjS
            XgGofTQVj7QsqhUBQltUuNe6fgqU8A87C7ljwK2UkfvoH9/sO0t4I86+EIEg0JPN
            kvLw8GuHoOfmQfaaQ9dZbRHQ/fqZorW3sfvb1jJkrR834OtbnsMs7+ZUeiOIJ/Q=
            =uxO+
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
