spring:
    profiles:
        active: local
jwt:
    secret: ENC[AES256_GCM,data:YP2jP3RM2b8W1PLKvQSV1vy4LJGr9a8vuiAATwTEAg6M/ShQo5mpzoqAkwI=,iv:tbRrg3rYtg1G7jNOYIQ2O8i0ZE5CxuMx1mXSmbujn3o=,tag:uHK3MFxBgz2wBowukCzpIA==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:Pc7X,iv:e1Aw+B+LfO7tNhPyzpa1OG6k+s46EWR1+ET1TK3asEo=,tag:OVaGYXDf5bh8x4ehLT5FAQ==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:7vk=,iv:OuhfuqRkv0HSXKeZ0yilsmLRJmiP/WIY1SACVt7uTKw=,tag:3BzEkyGph7634i/LySe++g==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:8eByY8ZDR049qNhMxEKtrfNOvg0=,iv:uacw7b3hle7qeH9ynjgBbU5HzJaq6zjhMbJTAjAoOc8=,tag:VVDbzWu39nqNxqwavSul8w==,type:str]
        client-secret: ENC[AES256_GCM,data:aL3Numwsy/ZHCA==,iv:Ks2XsbScd5ArlcC0URpxRaFsVWreolywcdN0HXEhQTs=,tag:yx9fjF3j2NmEufXByKofjw==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:0x6SKFE2CoDCceq24tsNglqKNJx5SFNd3StP+EGvaDnl6fmkS8bcY/+m3AyLh85+0lppZYpzy9SsWCEnEPfWMhJ1O5q5b2eX,iv:IPUGGlROIZo9aIuqcyjBU145w1COqIjeAT9fHMregc8=,tag:eXnVUlM0/s3/pSJelZfu1Q==,type:str]
        client-secret: ENC[AES256_GCM,data:St8i39EkXVFCDEbdqmooNcLV3yZ5VTboOT/uLtwOatyHytA=,iv:+5n4NRlGITfABnPY3n6CRXrvQX+jm9t4eZYLR6D8hzM=,tag:702o9VHXnwsyKA5+9g4wxA==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:4QPEuAErkFfvXjWpmlq40xFqJgH70/EYSd/yzGrHT98=,iv:hKQdv/XocN+CIoSe99uh4ovaHGHuLuICrtTz5lekUts=,tag:0JYPohjqFXtQ9BepW9pi7A==,type:str]
        client-secret: ENC[AES256_GCM,data:5I7RHaXxY6e+ZruQJ/qFKts1BaWpLxanLEQ1eWXmgEo=,iv:kLCXJ8igWHgkO0ngwDCcF4mnXe1Lp5K5CcYjbE9iz/8=,tag:lvVz25SFPGiSgz2Sj9Pkvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-27T06:42:41Z"
    mac: ENC[AES256_GCM,data:CyO3442wvEgO7sxQ3sbv/2kCFrHn3CR85r08q/cBWXrSXmEkpsbHi43+d5vezEYvGG8G1twyh5tMci70MDwqpjs7mw2BaLRKM1tJaVxU7lJZy3g0JlukqTVhmuHGjBP2LqIgxomw5taTAjn9FY1x3zvmo1iMdr8/R2ecOunVx8U=,iv:mqYLvK7Ra9VgKNOD7wIzETX4e1QheYrAsHkGdRGiBzU=,tag:i0FYyanPtU/0oG33qG7Img==,type:str]
    pgp:
        - created_at: "2025-04-27T06:42:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/9FPrTPcMR13wmEfZ+YzGP1IulmtgmtsQ71adT0EhLsybZ
            6xCorAoZLz3J4I3q8V6etAaRWYjheV396qy3ozKcJSewkopZnfoUDAduMVKFC2B8
            9W+LMFLzVQTGQi3faGjok3nIXu+oqAAB2BGSWWPceSOqKeB9JDW4bab3kzZF0opz
            PomJuKzLktXm+29n0cth97yS79WnDmbEf8xk2/jOOtnzGj2rb5x+eMM+YwCtLU3s
            Cacpv2p+KoUt1HwYPL3vwqDDjKJJ5eAxNUvt8E6Bx0NGNl3eE5b3KJUsmdG+VqJs
            O8jr1McnqZP9goXS+uebo5Bc2fl3iBGu/W0AC5QkXKZOxe8OT/fUgY1TKXNi4oRW
            PH9Acxu6EzRWm+v0hq2BV8rDkcLeZ6IDj0ROOvaQEZ+/19Qf8mAJof2BD1mCcway
            fG5fGDg5a6gQu1gUBfSfLIuwN708lcFpN4lC9hlLEiLw1h/ME7HizbT1FcD6KKcN
            Yw2ah3mAvtrjNxpZ3FVpRXV+plDjXRtrOFp2L2/tZLV7czF1TZAmDq7IrgO1C1v+
            ONpS42Ox+lPLttpQ/3oxf/Nq+uzuFnuIAZgy+Jr0HjiiYUnxefv2Xzh+YHbbTRaZ
            /RiGyCKK1mYi+zsG/4R9N6OVDaz9YKzJhN/Kzx+5gKy+5Sc6w9G909M6mLTjFYvS
            XgExz4bE2Y0JHju9P/diG3v/V3f3RTtjugT+2t4kkNHHg4cManuxCVmbaNVncZV3
            qF2rBNbu5Tun6npdlK+6pl7pNuMm9AK0eJRlUejEdbHl208nznXokMeomSIJXoo=
            =grYK
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
