spring:
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:rgndQt8/WHirPT8nDILT5KVZtrFK0/mvSZzX9s+sz4l89Zme97hVJxyCig==,iv:FL8tpZeFzsThZDusNl0+CwqHE0/Vdlnh91ImH42o1mk=,tag:WeSuYKFkAPbKxRLQuNAYbA==,type:str]
        username: ENC[AES256_GCM,data:F0o/cUVk,iv:1gntDqqjEMweb0L9IKYt9xw4cW6ovzYDNweTBBjABa0=,tag:nbuPlhfTvhTj2AhcU+oyFg==,type:str]
        password: ENC[AES256_GCM,data:crxd9sb34yKKAk4=,iv:lVAybyZh9p4LWw2gSplMOpG8gSsBq8Fw423nlE+6Odo=,tag:9AZOi4dqCxmuZJ88NeyFTQ==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:ERLyAPFHKEhIa+EVCkmeu+GYD7c=,iv:z4EUvvRekISqkim0dGnjlf6gfuBBlFpVX2OcpWPJb0Y=,tag:inmfU+kkr8ANtu5M8Pf3Eg==,type:str]
            password: ENC[AES256_GCM,data:tw2XbQF5Nb1Xevc=,iv:gzKMMvGigFoYCMxI0EtYRqdAqLa3xoqpj4lDKViDzEY=,tag:o1n3ygoOa2p+ElHYFXXzcA==,type:str]
    flyway:
        locations: classpath:db/migration/postgresql
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:KuBdhkE=,iv:S25Qh7fjySIcduVqN/4BDgWHvWglyAX6aET7AWunixI=,tag:JqaQsUJDh9vCD0UKSwxvLw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:A0P5AYY+f1utFzWka4urEN3ZHYFajvTi1IwgMhH7,iv:DTjlP/AO2CR2pFpvYVuR/Sg5riPRmvi0v9J1gfF7+gk=,tag:IDxbYo/Ne4C3uHmtus1j6Q==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:V+sgiXPW8ScImNYMDjW6FWpEbUulKPpv8t1BBj1Q,iv:DJ5Fc8VtfD4YuCyZt4IBibu5IjdQMtu5C6+RZ7lNTgs=,tag:tJ/FGuBuivJm27YQNYMQLg==,type:str]
        cookie: ENC[AES256_GCM,data:uGeqLCk/PXTMzLT1TPmfWA==,iv:0S96Xaql+/WXYrLuoTasjv6dB0SVOAkQSYhysqv6QWw=,tag:kUjYPMb2tA9s30DI+2WUOA==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:JgYXn1nj0FV+neqQuVboYskW/wEb9kmIWjyq+IfawEzHJkJu36Bg9CZbWfZPHN1n4ZphIWI=,iv:F95z3V22NcLYJiEiUhSRgjJRplmNDXAF7QoqTXrTPuo=,tag:/rHh6HfBei5Zb9BVCBpPTQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:jebtKo0XDKS+6oUyNqRxKI1L7q14ey61vhBQFpqOGUUflKFBJo3XjHzGxGglH++kkkTuKuwO,iv:AEwyaCXVP18Ccd5O+KBCfp4rIqlhUkxBqVR4nNKKWk4=,tag:wAHoq+6ymHK1vbK7DJj2aA==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:lUVDgF6rpxozknMO+YFvod9CjFbrvwWjr/8RHzsHZ961bxWiTrnMufvQK2YmQLLPSKZJaVA=,iv:1VfHzjz/mkZa2Ow30Jg2+dTKr2tQgRBu8Xf8TVVn13Y=,tag:vv/z+QhHWQcQ1YRI3Vx1gw==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:GJObmsyQ6Am1+Fka1hGr3174KgVQOH3TdlkYOWDE6P7i,iv:sAEGF/cDsxUN/g9P+F5VL/k7O93muSMOURsk3/MP08A=,tag:FFPPDFDK0kkqLMS227Yi7Q==,type:str]
    access-key: ENC[AES256_GCM,data:HWw2e5tEqY3VJ1FtoLFLAtqnHXo=,iv:AVfxckZXGZ4WBzNeHDHBW5BHAUr1WJXmm0xwV6Eyyfc=,tag:RetZ8Gt9JT7qbqcDHFpd+w==,type:str]
    secret-key: ENC[AES256_GCM,data:8o1MZRA/u00vX2YR+mPN8EjRImIQGjnbZ3gY72l5BkBiVgDAdX99bw==,iv:oeF/E+CVf1G0HrjCyg9v0p4dkArLNBAwC6oD47xY0bU=,tag:BrqLd5+ycM2uleTVkfOILw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T13:24:06Z"
    mac: ENC[AES256_GCM,data:PweEmK9B7A1CKS4uyU9+MML4C8Vi2rvca6ckUZZ2KhuewJJ4jNlgkPVFdy9tO5TSFPXfQB6k7hwaWWYgUCmJCoTqO7Zf0gaEATemJObgX/SuG5arTlZxui8Uc/EDdXI68P1wOux0svM2j0x5Y/bZ6mGDuDTS8wpLaBcr28k772U=,iv:LFu2deLdOWxaQk865T3oPs3uaLzje6qwULTovYsxc1s=,tag:9Yd1RJBKj5XIaPFtxoNxvg==,type:str]
    pgp:
        - created_at: "2025-05-09T13:24:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA405yojGcAdWElmo0HCOQuAFqhKg7p38lmIBAoth6go5f
            2quDrPYAtHuqKDmYSg8xA0PPuv1OFnVc47SSrgQwNUo/GvRnw0B9lKd8Q7b0Sa8U
            AVFB3G/SpcIWDPcjdAGPPW3EmuHM+gQFcjWrNnYHLpnrUTFF6dpV9+F7V0f4pqcM
            unmKXNrTqCUE+o4qI3uKvwiQed3bDDyZSgV4OXi+p0F+0fOK4mknMh/VCaz+f9mM
            T52CiJmr1VpYcejNFc5enHO83NfPtZn0FD41zk449ya7KqX4nHJ4+/SKU0rlT0LQ
            inMlvUGeQMs4q2oVUVPGKIImMkhPjPIyC+rKWHC5CpnVF9Hc2dSmmyBMJFOk7OTS
            sIUf+pgdj4IH04nG3CgCtIUdn6Nbmiu7JAy20Xrlq1Hkmeie+uH6nDAXU4lvHSZ2
            gQJXkjcxqI6IuvuLlQ9EeYzM5MxUhRA0OLk5kpiYtdVtqq1yL+btO1Jj4gphnHog
            JJsfaZWHLtH/iR6ccz2ltB6nvhCyrbVFwq9tKz1jQBb4j8NmBykh5dT9VSYoWa9K
            iWtimhiyKMmEo30J+fmhK37yNaeqCVMBk6H33tFWnb8r7ZG24bFqdMO+Oi7sC+VU
            5A9V45hhJcyBH50gn6hfBDNzxSmrws8zhNbOaqW5flez/9UUnyt2QrZYByZdLf7S
            XAHw0ZFtBXjjiqohD+m2LDkB9cNR6qpH5luBTVUOmwn/N7kMK8Ce6GnzTL5VATh3
            MK97La0Z4tGBS6Uusyig2X2/aiYP7giEm4lJ4PFxult2Vp0k77xRZyxKvA1s
            =KqFC
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
