server:
    ssl:
        key-store: ENC[AES256_GCM,data:Fm9nDS1qK1XlxXREovUMS1rRw+f9eMQ=,iv:tgJgtNAXvfg8RH+PdlwvEiYW8AScYwkwTgt5bODAxN8=,tag:uNYFSNgwKgGeT5k/oF5+fg==,type:str]
        key-store-password: ENC[AES256_GCM,data:P+3J97IlKv+LR8WXbelP7fNqtVc=,iv:cPKWu7PaRBTt/fm3NcRNH2WwnLuaVirGkwnpFgxKmWE=,tag:0yMuwmn+cGYnsdvHtJDthg==,type:str]
spring:
    elasticsearch:
        uris: ENC[AES256_GCM,data:n2/29KKQySc6oDfhj6ccoC5J/JMajXLBUBTW9QpMWGKC,iv:45cZhUmoUQCHvQci3NpaW/3Ms725BpMzdlWYxtygWQM=,tag:D/gGyJri2JQiGIbel/VjMw==,type:str]
        username: ENC[AES256_GCM,data:4kiFlh4=,iv:OfJZ0kFpv/2l35p8D3LhTfg5PoElrQott6ADBgYCgRU=,tag:pQ5//6erP0FGfrRrxCtaTw==,type:str]
        password: ENC[AES256_GCM,data:19lu/Jc=,iv:z+I5lwrg88GC6lUV0NMB5goli4PS49MrmOf7i/OjRLM=,tag:ezy7sWooo/CJRo4PqY/aHw==,type:str]
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:0Dtp2l3RgpmmIHUiFXS75QVm9aMSidWCOJZQpZ+0pb4PVTucANRn,iv:3C10nQQYkkcntYCp4h3nTz+itabWjedJvci0PxXyOpw=,tag:4FPyjI5iPQaxhL8N0xE+1Q==,type:str]
        username: ENC[AES256_GCM,data:Bz6jT/54,iv:EgPzfHuvs5kjn9A5O7+RWpz1AX5MqTxf2hJrd8zF/pw=,tag:eGopAdPw/yaeXZ2Y6zG4MA==,type:str]
        password: ENC[AES256_GCM,data:fvlOIvMZbfj3PLY=,iv:E7fo63USEmn0Du0fMHnsO7FeNwVBCXbW97fOWYOJk7E=,tag:W0HIUCt+Oq0RvVIr7wmQFA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
    data:
        redis:
            sentinel:
                master: ENC[AES256_GCM,data:k0T5kP9u,iv:2bMlPu/lm2tI3+56cJgnT6IA/I60j707gJa5oWasfd8=,tag:KQneb6aLkJqIIWEV6LxDog==,type:str]
                nodes:
                    - ENC[AES256_GCM,data:AhUIyUTxeySy/+LHWhSrtqsqSAl8gJT/aMsypQs2/n0NPFd8u6Xe8uWM31s1YvKyz6Q=,iv:yUmNLxLleOom8TF6HtlQjPLj2Dv2sJQkTiqQdtvc3yY=,tag:jFEABOSI4szODwAQC2w2Zw==,type:str]
                username: ENC[AES256_GCM,data:nAF5E2lW5g==,iv:vFOjVTO7CbpNI3JFlKDwXsnMgglWV0H8R9HWtduRYVc=,tag:CzAbJDovC+19s31roteJ4A==,type:str]
                password: ENC[AES256_GCM,data:osLYp9HL3gqZc84=,iv:fMOgBXJPgDFVbQrydPf6mQ6dRzBk3fgufFLay5N4TRU=,tag:o8H6uOw8665jzlpQVLy6fA==,type:str]
app:
    domain:
        frontend: ENC[AES256_GCM,data:WRo0VJICeDnGCvmO4/2G2HXp5ONkyyc4/8qCQBs7,iv:TwM7KTIdd09muwv505KsCvkVunOY2ffngalSYTVB/QM=,tag:HZEYXram00Y5Xe1METFwKQ==,type:str]
        cookie: ENC[AES256_GCM,data:xLeLzyr/z4cR3cwirMThIA==,iv:+PRiF3SsoCsImeklTHE1S4MPWDewKJUscXpGECmS83Y=,tag:LWiGBlw5NHHv7YJd1+FjDA==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:ecklvIh3ajm6sFYbN73OUuPc+DrXmyN4se0mlrZm0mFtcVquWtRcK8GBcRNGeZiQDlcsXMU731yY,iv:FEBqGedjfotjrHguXn1BZ3FUVPp65sJsspeMLspDs3E=,tag:iM/sv08E79jw/zZxjXxpyA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:dkOtFhZcA4GR/3rAxZoc+VrH9SG2p8xG7vlVhzDCh+6REjP1h97uFn2HoZZdm/x2Jb7d5htQgUtt6A==,iv:5Ud/XZZdglUkaBFAvMFow+ku73U4KEqsLbLTzw7+qm8=,tag:3sjOj6WHEiosQUiQ1ZTzKw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:b/+eYwN3W0Z0Wg9F1BGC95jJAkpzc4WKyREBh+avLU9lm06bj0NBiFoQ/f3bsMYV//ZqJUUpuema,iv:1kUVdEiNjUdRj+kMf43MgFp9pSsZ9it79/3aCLt0z4o=,tag:YyZiyxvlBC/7ewJt49OlvA==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:Ng5/8uC5qnkD2+8aR/55txko0A==,iv:92iahdLQpik3VFa1vB1E7Ifo1EvrpW2UELl7LCeNJ88=,tag:bdSrk+rsI9aSiGnF6BOBGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-12T14:39:12Z"
    mac: ENC[AES256_GCM,data:Fk9qe5RgvThz38DydKSQnbePiKNL0rLHlnoAirKLP15Xbo7H7FFXjmUHcfQKup9Vyvv9e4hCN6zoeECQwrn1jLigOeXHBqUvPylFQFLeFmoWZA35HGBaXiO7Uj/Ll2tiH0CZ7qcTD/jqoTjVUtSNaE/jT+OGkwomOuBrpXkTlIk=,iv:wP4aa8vH7kXr02yaBgAlwXcfXjYD9cnVbcX+IP0y+dM=,tag:a8zzWB7KN4Pb+KYAe54tPg==,type:str]
    pgp:
        - created_at: "2025-11-12T14:39:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//bmmbdJclg2jB2OPNphONmEgJD30cjCsGGuol1yvGAbbN
            8Bilb2xFlOE9CluJ2phvLNCf0+duDjSTaOFDI9h+8ATy6dR9WGUjl8DgvQfBkIeW
            R6cp+vbB77wtfjFrCyFodjscWZFgVVj5V3J14PjPs6xOGqZb7Nk01e1O8ZDILQiv
            gjLqlnTqCqWyOiG06P36d/d1NxovUtqSay0STFyMeLgV2FZaCbuG70ebSASxE4VQ
            K/Gra5ge6NBw/1EEhyr2KLjRvPhmXGdCpVQA8a48K57+x7ZZWv6b332jt/JfVJ1o
            cjdwkD5GcWNof+r0DhSnPl4HmWmMTnza3d+gQRsbg/oDyXrEc1Xf2yx6b7ccLWbX
            RgxLIK5TKu5EWPbTqFnNjdxBgHR7tPvqv7sEW8xO2p4lqeF0Rez/q5C5yuYDN9pt
            AbDUHSU0SuouWRjZl+Drynwsph60RvlAsfDP/EoesopoIC+teazJJ+oj8BCjYbGu
            peT2l5WuPzsMFfHM8vxd3vejSUiw2OUcfgZmKrfSMHXB9KQZpEJydSgZsCueRRVo
            ec71wgpXQq+WaQvXLIjIDq5c74TSjoP5edgmrL5oqkybQ+UlYFMrvdNnVFX4AZKU
            TY/kn5giQnYNgwBQgUFGbb3L4O+s7TsjrICcoUhkK+qXjk0qm4BxmXmWyWMB6/PS
            XAHoLI0b0Bwt7+SNxM2z5/vwEr2qChgcNmLixzMdjTgudAmz3L33OVKAE5rr96U5
            HzkFRQyuILk2mbdPnxFoy5jU3yHplHWFiWfWOG0w628oKBejdJXzAraqDJIQ
            =zoAF
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain|master|node).*)$
    version: 3.9.3
