spring:
    application:
        name: Replay
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:iMYNuQ0I/NH6US2w39clk4UwPy30Vz5QQsis0YMs3ynAXyv8pA==,iv:WSBfLL5RUhc0Q5l7qcZ5mwqV2xbFxG5CLqFtgR+NDN8=,tag:pFmRFbSsU8r9CGHSFOzJcw==,type:str]
        username: ENC[AES256_GCM,data:UkFLI7+H,iv:N5A7ujYLgrJ8PZn8uw2f23KFSbwka1j6jhwzJt3WW+g=,tag:RMhXUW0UVR97ipNX/rDOdw==,type:str]
        password: ENC[AES256_GCM,data:JwTclQYk9ks10mo=,iv:02R6giMlHNmFKZ/D178Bz3ICKJqLLgBYw7171lOmH4Q=,tag:Bo1b5mdSEnYowfiKEKO5Uw==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:Cx4Uz15AEXBOZMtVVC7IQ7Bx+ns=,iv:NJCLMniIt9YPfY5JLT4j3Xg1nwix2aPHIOykmkSW4zI=,tag:z3Trbov1bWWZiGGBdDt/Lg==,type:str]
            password: ENC[AES256_GCM,data:eCXV0AjNzIwvJGM=,iv:j8UXSIBe5lvPkr19nvK2chtJzGun3Op0QbAIZhRz4ac=,tag:GReZ9BXG677nm/zSDKx4EA==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:S448Weg=,iv:18r4dUJKrG51PRXI+CeAndGghJQx/+UlYJ1DPzaNMIA=,tag:gwEwA+l5wMlxbonEeXIeUw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:5FRA74IGsX6YpQsye15oLfjX5nED69gaPExwT5gr,iv:fgcRQHQfpKSX20wMjm6dbO2BOPkDBKeD82L1Cnpflmw=,tag:TPmu71UYzNMtXteDcIcY1w==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    servlet:
        encoding:
            force-response: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:mEjPCj6+p5wTexFVIcWbO59I1TXWJr6DqhOIO3S1,iv:XzAX72ncmvNvlXYIGi+EXWlCDOyhG+E7ReNxyr37b8Q=,tag:Uaf0yGhg9lOLugAG4SIFKA==,type:str]
        cookie: ENC[AES256_GCM,data:SEZIxc+DySc7SNZigiyz/Q==,iv:VcdZDapUHgxhyz1BOzn8IUFX0kSnLZZyiAQHdWXezsw=,tag:NA3D3xPZQrtaJU9aLCgs2Q==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:3z/tqxtV0ZsnbUERfw4GaOIkQQQLl6LRyT2565W7Oue5mS25rPRN4+Xk8C49i/z+nFz9fFg=,iv:JYoVCNowi+OwlPUbLN7oMcjAQ6jGaHhkYr1JwHTlRf4=,tag:wGXRJ+D3MQwdgWkSPPvJ4A==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:FW3pEaU9iGdlZLmXURH7A1qZFX0VMBbHReUbUnTFhMBFOm4Mqd2n4q5RuhqWV+ReBmuZqBBu,iv:JJlqa0e+I7S8FR+/HwnE4r0o5dz38S+7cOePIDfrCu0=,tag:/QJoMq5WBCLS25KYmC0Y0g==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:OrR2NLv+Tpw2n1+P8RZAzNTjE6aK7zQF65I/h2pyUKkReQ1x7EijG51TYEX8FYmd+UnzuZw=,iv:Ys9cF4ZcF8fR+PwuQNJOGcIND3rJ+KSKIAyI5gFsedw=,tag:y0TEsGPvzi1FsZ6DmRcpQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-29T12:35:36Z"
    mac: ENC[AES256_GCM,data:3yFl+dvZjCI+ZqYDffc+cyu0jlGLcFuvKJD6wMdpiqVGil2Szz7X1I/LtWXJOY3+8JpiUS63GMxzZVAqyJKwFvgezWDvNLC17hJmzQiBobp3lhD9FCw0zIKZfcgeDoC/g9T03KFwmctAl5shGszK0crQ1bU5JB0PQ6wtN8C2hBw=,iv:MkgrO32kkujr1EaJ3Fan9YPC6jAYe0c/snoEgUADheQ=,tag:b4eN35tDsqKdt6luLtmJxw==,type:str]
    pgp:
        - created_at: "2025-04-29T12:35:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/9F1hbCLU6cvtX570TNVrHJ4cGMIIQiyE3XTqaOYTHN+DB
            sGSOcRINSPrOAhb8oDkwWhSKmtzY08Pnk62B6gsG3DiJtEmVXM6GHtUQbOOeh+EB
            L4L4Vy9HbTdLz0jwPPj4kH1z8XcNEA+RXGOy5BP2f1BNiN0ECLtYSSsmMK2jxCig
            B2pNTS5vr6nmjmw2Lcj9FavTGdphvoMFhc69zYls3RlHdYGZYXXMwbQK36hNMPDb
            m6kv3cpr1m1jD1MLakF3U+xy4PG7R67uztMN5nPih2V47YL+Clrq8TNGaPLUy7Jh
            zD+9FU2RChagYYvDqFegZ00x5YwFe48GicW3MeBlqhmiNQg7QcD5kb8eE8mNsxlc
            /D+NM3e9pxKG2OM7KZnP5rB7HmDFp0YEk+90teXE2UPqu44SM2YAxbcdwwPc7R/h
            84xqmwXmBQ7t85Fbd84ENPwRHs1f4TvGPRQRn7rQAsOXmFBVAXkCO6oz5wVsjJdx
            duf5Szk80Wojun0hMZqz8Q8m+KBC2MlXEsp24ycqer4LKBzV7WTRXDtqvom1KDiv
            Du32UmT7v2w12C7kZz0hHtgjCK4nZ+KgoOKCW+N+t+5Yxk80AWVJfXjpUbrgRM4n
            iGOwfYuE9kK8D60EKGgguWvbSnOwQpvi+ynwful5NqnFyPWaHGkJyr7uWVDfFX/U
            ZgEJAhDYN+ZLKHBX9X8cXrWzyAihtO52/6brBBYdHMNyFtP3sp8PdXnjuoRi6r7B
            PVcBO9hkCobuC/G1s6J6HlJWJfcWEh63NN5kF1Z5eYIzkBf2d3HDNXvV6/fJfV4Z
            Im+VIRIbFQ==
            =7uxO
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
