server:
    ssl:
        key-store: ENC[AES256_GCM,data:6NjAqpqLaX/d88hXQdqqUbXKGQ==,iv:V7s52cqKQUUPc2FbOpGviWGY3WFMDFDtYS0MSuo7FgM=,tag:w+eSIKJPE6M/Cay1IjtUiQ==,type:str]
        key-store-password: ENC[AES256_GCM,data:3e1W0EkJ6LU6zys=,iv:22OYar/WMHHWsNOzAHLqTgRmwUypFuAPtTDnqhxHViM=,tag:6mc3vB51OeSDyoxTBD+HpA==,type:str]
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:hjJt4tz9LUs1iqYU6vYxcYb2wdvaYk5VzrpTRZbrSL1TVOLK3is=,iv:offLgvgVp+Ffrm3K8p/lOZHXSIxA6o54bsakaw18P14=,tag:XR7SDkvd4Hj5hkTqbLFWYA==,type:str]
        username: ENC[AES256_GCM,data:W+yfSP50,iv:0/gjk4jPihWCI8gTrCmg0NZ0nFzava0JV7mW0ib9n9U=,tag:l1iUKBxJlXsffSJcX4fzLw==,type:str]
        password: ENC[AES256_GCM,data:1ui+3zIMsqfa6NY=,iv:QQbIszMPpcDFt2Tx81XVt5o+B1Uby+GU15dMuXpWBlw=,tag:T5Evf+LpsrIbuKmng1zhHw==,type:str]
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:tygU8Hi5wbckSA==,iv:jps6tJdztz/+LOUF97TEoWpRHhW/swEaseuUrpqFbXw=,tag:2eCb5Exqv0lbuMSwG7kpYA==,type:str]
            port: 30001
            username: ENC[AES256_GCM,data:65nZh4A27w==,iv:m6gv2ybwlYexeGpgExIil6SuLR4OKFIaE6r5mK/I6ss=,tag:2whQz8FJk9RsBbzFJYrUjQ==,type:str]
            password: ENC[AES256_GCM,data:M8UnytfIpv9Wp7c=,iv:VW0c5N3+Co9M8CfnLuVeYEJcpY8QL7ocH+b2EbQsD/M=,tag:nArGHcFc6m2eCxNdIYxe2w==,type:str]
logging:
    level:
        org.jooq.tools.LoggerListener: DEBUG
app:
    domain:
        frontend: ENC[AES256_GCM,data:+4fCSbRfAB5Lp3oHfR6ce5Yr/RoA,iv:Jvusynf/HXno4JNTTDiTcOZFKpcoqeLt4JLtZCArpXE=,tag:UNPzviJ3KKvIFVlsLDUUNw==,type:str]
        cookie: ENC[AES256_GCM,data:fdQyrmNgldxF,iv:NJd7RmcM/mdUKZzYAm3BVEGvcxELt0Uv9E0dJszlrNg=,tag:Fv6dywyRsHCTci6b7Gh7gw==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:aCl58Kuocv9wEupsEOkxXHgR5t/HIJgDQqUjHenpM09kN2HEp384UVDWLdcNjDgafoOrhHgw2wdYXYAlyYvRJg==,iv:Plbeg2QGJGqojvhxiHANxHY0J6kuX7f/ABlfuRfB43o=,tag:l+bBn2wJ0LdKN9743DHxVA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:r0XTHqSKJAeP/vSkp//DQfXLe1k+MVwZBZ99UXvWP7oQc4j3+mIgbpioqQxLt5YlgzGo8YFgQf2s6sskIsf8I5M=,iv:W4d7sG8gW6uMEISWuQmxov0P0sQSLqOyhf02F3lUKX8=,tag:PmwtxC4nYn5Xedo8yE5tqg==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:e+Joyq7nCaX9SQ3opddAdSl0WukaaagNfF1mkS5ZCgrxVbTBwtYKO4JHI8UlzWXhexdSFNHToFkFMJUYVwnUNg==,iv:sHpJI0DdyHpiPpO4ZwshDiLNxaYPdvqqbEVGJh78+Vk=,tag:S9YcTGEcKZZsL7e1/ywN4Q==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:nXfoH+Lh0yGRWho0djMa4DM44RhLRqgCUN+KUc4rrIOf,iv:0p3MAFV+B29EwrSWr8QUgywv8AI76RmeOCswGhzHRr0=,tag:87I61AqBBcWxIL221/ylQg==,type:str]
opensearch:
    host: ENC[AES256_GCM,data:rBuncd+uz9xFwg==,iv:QURVU9bhfbnl5bLASrZ83fZq+LfoShV00AlX3ta/FGk=,tag:pQKYYt+e7Mzn0FmziiK2DA==,type:str]
    port: 31188
    username: ENC[AES256_GCM,data:jAnPnRs=,iv:l9AdqZA3TE4OStpnveikGuC8vkDxnxI+/Y5I3FIvonA=,tag:sgSx5pMaahwudm4Gt6RksQ==,type:str]
    password: ENC[AES256_GCM,data:O5cT21uyf68u6Y8=,iv:0KznY26/VvRFwR9y5ArWwBY5DBUksWnA2ay7ONbXQrE=,tag:cTP52Y5/0N+HewmbnQYK0Q==,type:str]
    truststore:
        path: ./truststore.jks
        password: ENC[AES256_GCM,data:OFz9N+28zskBwSg=,iv:njt4JXTzlo+zDqA1c9PZBme1ie8JQh8MzntoldtjgkI=,tag:wnPI2RLMFEsRkgOX+Ii35g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-08T14:28:00Z"
    mac: ENC[AES256_GCM,data:LvSiqzJugUkn3xvuSHZehPX1VFJ9YSPWNRRJktvgRMN9sQT4PW3LlxDbuXPpwzZi7rdTPTL6N5xH0DPVE17OSShR/uWmvBM+wAVZCaAr6Fsx7DPfE+xul6jb9vkDNo6iOpwtV2ZzZhWJeAYE/zc8PmD/4kvBIKMoaTrilePdyp0=,iv:IahcuLvWQ2NMPYdQd63Ym+qOz6d4vks23VZ92LqVvms=,tag:bRCSJKYho7V97YMjxnS8rA==,type:str]
    pgp:
        - created_at: "2026-01-08T14:28:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAplB8KgOVSoFUebetlxy+qxCYE43P6L6oeb0ra+r840gz
            gZ1b27Munxak8ea0kveKwWJSfg7tk+gujYY4aljAZviBeRoUs4oD8m/SaGgJz1HA
            QeC15pMv4KNL7KCMYHJT+wQu2Dvje6R9IwCam0So7w8S1sam0DE2urtDvQbR6w4M
            rzmQ538ofoMMan0WyyFJgmEG3v0PQh4jSFFGmPyoyEmnRoxLscsIUvFQsjsWwGdF
            E93NzsQr8GAa7shSEHJXg7rsjgdCRYZNwwn1VR3vcN+QiiWeqC7aVs3rDKLG1OmU
            6epCiB42s4JyqlH6gq/r3YXoo7G4xWApVQ1XtKBI5SZWIhhn+UUfmEyUndbCeEgA
            3s2ypHym10ccZwMdr5XkYY5Ndq3H4k41Y5GDBLIIPLaYDgpi1yo+BS9wLbXSafpW
            1Ou5PHjuxbTUjrsf1UJEaJn5Sm9T1nYqboO52krXW3pWNp6sV8qB61SMhpWmO1UR
            AWufFOzdsyNgufXhkEs/6dt4krx7V3E47/j5DsviaNYqIIU6KFSVtkAD3U1R8lLe
            fuuGZC9P+TnLJtTYtE3pI7ZnxYxeHrliTSdmcmwWBc2h3dqNGgxNk1PaS6ZKoa48
            dGLoFqXQ8juPfyzQTsfcjry0OGyEziEAclp66jEtKNsOB7VRIHFjThlUcZH+37nS
            XgER8yKu/kguLQ/S0Ekk+Fwan6TSzX8c/y+4e+nJwbw6Ptp3pPId9Bf9VuESzzh1
            5fWZrYTLDe+j/wf2h9E+TH+S/Sb6IrrUNgDetC9W9a+5AIe1bLa1Em330jsmRfc=
            =MYNT
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain|master|node).*)$
    version: 3.9.3
