server:
    ssl:
        enabled: false
        key-store: ENC[AES256_GCM,data:l9rd0DtVJEr4lum1MQu+pepnSg==,iv:/vBA6q+ls03rgcOwCcQtU1gxUbXXeTx2xjNVlWN5bjM=,tag:htRAZi5ogbfqBWAB6tyjZw==,type:str]
        key-store-password: ENC[AES256_GCM,data:K2BZII7vQcfBmcg=,iv:dRVYj0VVOVNOae6DyFqczyeA0N4dtiB6XRHVHZOSoS4=,tag:niQ+QCAoO0aX+9FUPk4Vcw==,type:str]
        key-store-type: ENC[AES256_GCM,data:jITIqvYV,iv:3qvaRynmApTHhpoMoPIK/1UaiLqbv4LATvJdnNv6OOc=,tag:nuHXKCoEZ6JMKIm8WNI9ew==,type:str]
        key-alias: ENC[AES256_GCM,data:mDoWxMSqJlgNVA==,iv:Alpgx60ZgEamyovhWDTjvM4/VGNa8aNCckGgnnQA1F0=,tag:r2uRfyzpTsvCqz59oeaUhQ==,type:str]
spring:
    server:
        servlet:
            encoding:
                force-response: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:O+QOFJy8lJjQGyaepsozcqF+0mwWzMVcPhj5+oJL0JlbIDc4Az4W2fCw9w==,iv:OXfyH/RMQ7p/J9TKashdxwNtKKipm9gvqjIc4oOE5HE=,tag:3xnodhhzgzU72qDUpE2jkA==,type:str]
        username: ENC[AES256_GCM,data:v65IQw49,iv:hZtSGgmMkHmBk5Bu6vqftccI97NGLUn1RPfLwFqlxhQ=,tag:nn9U7pvPaR7POto57yWvrw==,type:str]
        password: ENC[AES256_GCM,data:3je5ScHce4rLahE=,iv:zBSS1WnxLOp+xUSUwJvxFQwGqjGMdPVWqfyv5qZPVuc=,tag:BoshWBdK68re2ZW7Me5XLg==,type:str]
    h2:
        console:
            enabled: true
    data:
        redis:
            host: ENC[AES256_GCM,data:yHc7u+6LXeUUtN9zSqiWBCStAP6a,iv:FcKHbJFKZZhw7p6ZTXzoyUD1cpWatbitwL35jszdm0M=,tag:6Inz1OanlWDoiN88q7kPwQ==,type:str]
            password: ENC[AES256_GCM,data:Wds1bJWHOUMyO0k=,iv:zeEu5hrIQlMjk++GnQQtEwA0bN2q7w+1i1j+0xCL1NE=,tag:9j9zaXWdTEBbZJQJRi8iGA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    flyway:
        locations: classpath:db/migration/postgresql
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:dB/nAyE=,iv:U2XEpol+9dwWSFtdCQzk90fXxPYhFNvCbMjox8ESnjU=,tag:SD5teHAjnbY+fzGG+ViJRQ==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:KE6n+HA+x7e9MQI6AiOsQ/Sgt3vwMv2VmIUwFhrp,iv:XABEZLBF5No3B0Qnwdc4DwlluqPDkBKR0QPrxq60BWQ=,tag:rWOGIfphjuSZfD8oF/ZWcA==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:dZEXaN260zCp1fIjKTY3L9i3P8GC,iv:DyCwHgNcpX9i4HBdfsnddtP5AqCPfFhfasicxxkKq+c=,tag:5OWqkF8d7yTGhNkqlLvHCw==,type:str]
        cookie: ENC[AES256_GCM,data:1QOj4fuNnaOF,iv:8M5s9AyxzVIvR0AB+E37tB7ZDFDKq+ajF71JvZJJ/jk=,tag:Sihg5TOgUJO9sPEr1FrW5w==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:kOSfBi3Y60qqrb366xMIvcVclJMfMPKsb3MUhg42TcjiTroaKyznuY/ZXHVWixPLK57HjLjw,iv:qgTOEYiwA36rANfKcvjjseCn1D2tL/IMtngDuGzhyHM=,tag:1zsSZPPLibxLFIn68pRj0g==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:6qIcCzWMPwpS0KZldcz3j5AQyYXGAh5OzbHo+2T6gRabBeVhYVdQnifYWZ6izoITlyZh5R6Jjw==,iv:NROFe7p7VSk0fupqQ7UJ95AToNKVIsd90ooRfIeyhjE=,tag:gd98XP71R2iJ6A/C77GbYQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:9X+AkDnD0HfhZL9F/PnGjzL+yYtU0Kuh9Lvvg2klLP8ZJxSmem+zT1ZXqGcY2kiNV1I3963x,iv:MaA/V3/2bfTZvPncfthmWFZXjWSP7Qnl6MWR71KHB24=,tag:3sS4p8dC/7Nox5FVoSzlUw==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:1AjFXTz0RrJQLCoNg0A8KRd+m/LgdwkQG/RmH9a3ikXE,iv:esLG6hWEORn2esTaJhDg7yXA8lyfRm6b+5UpvktZJgg=,tag:IeqtCzpWQ6Lp4XMrfB24uw==,type:str]
    access-key: ENC[AES256_GCM,data:HQSmK+zaD/NoC2AzHKpeV4j4r4o=,iv:Vewo3NzJ1M4gtb39XwmWtG2dgvLBYSN0zHfFBNpcghk=,tag:h0d5mDr6t2Pb/zWoRF9pAQ==,type:str]
    secret-key: ENC[AES256_GCM,data:85AEjL4nLVk6qgi4rE+4JG6KfiSzd5eFKVnmiTKA36XBD2SSktztog==,iv:cagfMpHy2CUSgbIs/JVZTrt0fci8PZzEJhyIEx0XFIQ=,tag:mdGNaRuVRmvwC4+4SJm9Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T13:24:06Z"
    mac: ENC[AES256_GCM,data:Te8lfD4w9bcQ6i4y/MZDg6FOidc9qDdFvcws05WGofk89a7OFBP7RNOpWl/O82k+94TEIofw5mu0biCzh8oUFNTK+LUzh8D6iDK1g/nu/b/xnDqqgx/RVQ5p9EhRsFZxmMO1bMBDxZA+b7D8UFlEjwmRr6ylYSFVat1mR/zDqcw=,iv:tw50a92/v19srdLvTZ6uC75keMWTW1GdPJWRCu0sAaU=,tag:fUyZEaui32OFZZH4l/q+pw==,type:str]
    pgp:
        - created_at: "2025-05-09T13:24:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAhvxZd/hA+tTyNxdpDRASyhoauZxzMlhYKlGropp8rJy4
            oCcQdj5kF7UW4WeOOVlEJ3Ys6WfsWtwHVo0MLvagJvQo7HOzHRZIRJwDB09nXgEQ
            VRnA1cj4bnYxjqAK//T0KY/sK7rEeBSXtEgnvDBnZhyTn8+ITEdR/uFPUc2Ipj4A
            vJNbW1CW3Xrk+tRyrsJO4q6VfP3i6DY1r0yLO2ke+o+AXBULMWRn4QfSLl6q7RHf
            DwqpaeC6ZZXWtXpzO/dJPDoFt+IucFKi1L4axvjnl5RlxwlSKkQZDOT0SSunSB+L
            n2Z+1PmD/GkYAGlriL+07YZ4RRw0cms0QvKOA/S356CopAjKqHqvIC/SFG27wS9r
            PjE6daq9aveCWafyGrh+Wa/QdqONPZ49huGfRydZHh5zzggn79FsNdIW5C6/mFkv
            i0Gs8GlmiKChuXYp3fpCOn1+/7Z3iAhewoKLjvjBgijBK6+aCsrbPtsqyYkMGXxi
            SU9aYzJ5xm08+aVt6sy5LTyEulEd7p7AnqzUTENtbP6nGMS6UN6iaKN4HwmLIW5Q
            wvlE+eJga+WHKJYBxIOBHMOgPaSLemHfLcEuM4pNs9ydQ924RxFSWtPoNaoMajUT
            GkSfszJ6sRnSkCwxOmPe6rfqow7G4vudyMRg+TUSR8d7Xxau5BU5df01oxylwRXS
            XAGld/vnBcH3IhKmKFDV+IHNsUBqh9UYYcFlT49VRc8gcBpcLbsrbNmQ9RiNSeu/
            GPSIJ/UhdrkTjOkH04e/tOsdZ7hkjEeir0gHje+M0PQbFLA0/nFMO4U1qlrO
            =xdbe
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
