spring:
    application:
        name: Replay
    profiles:
        active: local
    flyway:
        enabled: true
    jackson:
        serialization:
            write-dates-as-timestamps: false
jwt:
    secret: ENC[AES256_GCM,data:Ng18FKYAh8x4s5WDadexdCy/PhlDZfsr35Z6H7ucmcNDpZvHxYFAV0QRuFo=,iv:hybRRvu19cVG2XHUkfY27TpCro2oxToshM+dXQnlgEs=,tag:syWnuSAU6IUQdEuGEUWL5Q==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:n35s,iv:+QTJuDN7zoa1HvirYpVuNUBiAaFLBdR5TNEJ9JdxuYY=,tag:++fV5zeU5qfSFjlLTu6mVg==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:itM=,iv:meQzU/yv7T7ftxOE/Cp/XNniInmHCWT6F6vxfBMez5c=,tag:m+MZdlLLnk8grBtozosMOw==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:yJTbrO8m4xMHM72nMwHeS5zkzsc=,iv:nNHG5U48xEuG85ndeav3kkHTot4/flRfU3y8D26PN3Y=,tag:OOrzXsXJx9d+dcSuGVCayg==,type:str]
        client-secret: ENC[AES256_GCM,data:9aI2vEXd5haecQ==,iv:VF+ksPK8LXhsLcVQgAgTTt4L1uadx5O9WD+VQG9ABG0=,tag:H9tro690qtjkEo9CJfR0VQ==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:EEDTdCpKYpX+gqvV/Bv48s3t9iBBlDSl3lOiQCNHBUwbpB0DOenEqBIFy6tHRqYg7H+bQaE18VQfKssH6cxOzB1Q5vNwq3AS,iv:t8t9bE2yHeEbD4AHu7xLTdSXB9uS25zdtB2g02NWs7Y=,tag:aWZVTW8fMwSmrWf3vamvcQ==,type:str]
        client-secret: ENC[AES256_GCM,data:f52ALYA0tmF6/tXSFbqDQxHR8CKTqO719uIJ6PlQjjEWDnA=,iv:YQHtnhHYLCf5rBVi98Nsi8G6QdetYwanG+BrBIuWK/w=,tag:m+2QeUPegbSrQw99ndFkEA==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:M9Ig1o5Dczf8crEOpJfIW76qKwZEMcLRoSsPa61bATQ=,iv:D016ELnpMLlBs0le9NKGjJSQEgi+nDtQO33jjXg3vZ0=,tag:YBVseVk2qNXp91xo+GZ5dA==,type:str]
        client-secret: ENC[AES256_GCM,data:dOHyoT6Q+Ov3DkLLTBO/MrCI3qODIAdzZJrIAStp1k4=,iv:BmqHn1DlLBW11O9hMxR9se0JHMPKuxLUrmE1zxr1Tc8=,tag:2aaHQKHIBRNHBXIHgUVxKg==,type:str]
s3:
    bucket: replay
    endpoint: ENC[AES256_GCM,data:qLoF9DICCm5M613gefxeny9en2PEFPd62FEsAZ+1nfkr,iv:WdbFVRNtcU54mWsxdEQcz1YtqItX1IuI4B6wGmgORkQ=,tag:bOnd4S+lg4YxNvw5rzlp0w==,type:str]
    access-key: ENC[AES256_GCM,data:mzr937urusEJ+JsYL3fkOFS4Tc8=,iv:Z7gJGaxOA1zwp+8W+8RSevj2O188Sdtez0dDE8g/Rik=,tag:y8pPo05d10gQbL717s4k+g==,type:str]
    secret-key: ENC[AES256_GCM,data:8iFkS15kysA2palUYNUBIRcsO0uMzhp86tqjwF2QCcpjppvqRIsShA==,iv:ETTbNg6XF6Nr5blmAtMin2XGikVkYDf87zpI4OOAO2s=,tag:HYBtX401AJpk22DzmFX+Aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-10T16:05:02Z"
    mac: ENC[AES256_GCM,data:81XFztaZtbJVSbEoBZjd1hkDLARyFKZHiUdpS0xHaC1TJUBRHIeRSKPexBf4BCZCuciAabuSoyc4fOCRmozIdbaNWNUkk8I3RlP9KYTFvO2sScRgyp4mMDWZEvoFncG8+qwqxvfJUJsLM1GebldXBzSNTYUGDTeOI1pG0J5oZ8A=,iv:rDYRpFBA5aoP7luKAZG15SUKeCtUAqJ6z+9aKpOowHI=,tag:mjhiqEDhfuha8SB1dd+hag==,type:str]
    pgp:
        - created_at: "2025-05-10T16:05:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA7Xjy5U6wkw/P75BqfrOv50mVYn7UcaZ2OYF0QYxAdVfV
            2YN4YsDUY/YYeOqU0ocew4flMlPSyjgX17CpzuNMaJGFazX1RMB8hcMjO3CT54yJ
            5FlAV4t4x0S2DpYTOPWWyuRWLyAWP7FdNFYaDmhKaiCVCYZLkeV1+5j38cXCs7ys
            sqjmIAUqZdiOKswhQzWxO4CIlYh5liIdZffTREoqZ5xRmENylFpXRKlFUqvjnRIU
            sfEoXQC2N2TaX+1TWpd+cyoL4jlN9uvTe62GYEILIYTT2UNYGnboxj0Xf89JDbPh
            bgEO9A8LdQ6XwMK8KfsPQ53THMoM+6pgQnOBoRMR8arXX5dJnrvRhfXY3XNwswx5
            vaI0AKqfCDYqIMWtVEaGJPQN8wr7bfWSC2B2IifBpriuDOWeFx0ILLt/+Mxt6WXN
            jYj4He+HyYQWsqz+gljVHPZSZDSPdMqPgE8waMNP6RD/u5LD2WmMLaOZGZR8oPKx
            ZdF/ty8wE1iu0KOEgLKuLyFOoLUd9oAjZ2O1G5XHv20pzmcNDHV6o7TC8ohJsr4H
            LwYVQYL/tDPK+05/ddUSIn6GomlSW9wVhopzsbNR9bR6XifSlWgTkKFRYgAhAw9+
            d2iTpke9PvuaSoLxdTf9297ZFai2ek4QWI3Rr7Jii1QA68GZAdEqtYv3fZq/NYjS
            XAF+KcpAEjuk8ot76sN/N+ZQFvvn6+sSg0CeL6cfhx34z1Q7wPDQZCI6CoNXxOo/
            ZUf0iGXdVW1gD+HcT4rUPu9KyQ4FNHlkb42Zsha2C2LFprKZfAmloKs9MMcR
            =Xdt4
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
