server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:N3BxSZwOi3UYfzaiWB6Av6LZIQ==,iv:dgEIx9l+G8BlzKA05WgFhrIVuQKVnjF9lc/WMq6x9YY=,tag:HoVJFT4QAkxqsKpzVZFYLw==,type:str]
        key-store-password: ENC[AES256_GCM,data:ySdbygMc7JTWxAo=,iv:g780l+CgLTPLPND9B+gUxCB4cG9s1fcNcDqEnN+UL8Q=,tag:w0Jay8fn/KPJYcrH+zuYRg==,type:str]
        key-store-type: ENC[AES256_GCM,data:1YMh0sVk,iv:A1H6kaFgpAWKq7gPMalInrLKJthYEN1U7laf2nliq4w=,tag:BEXbt2Z5mpOS6IjhQx8vRg==,type:str]
        key-alias: ENC[AES256_GCM,data:34jEK+faOrrvGw==,iv:cYwCc6cH01bcGk+2s+XAoIVfJNuLi/Qs3JgnX5DmDI8=,tag:m3gWMsBFz4utFd4BT/laNw==,type:str]
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:fSsZefILfzdimcsnrKqVeucI/3z1I85H7Q9cogWdXuaEGmMuEeELQWGeKgxzRAMWmDO7xgBSGGM=,iv:KAb1Bl+A6QCFYoUkgYsQevA5JJ53eYp4P613mQoX6sg=,tag:aU5ig8moWDrj+dSfHmKEoQ==,type:str]
        username: ENC[AES256_GCM,data:43XmI/mY,iv:letqdxuxcM8bJFV7agq6yaYGBu9rBN7w9096dQbONUk=,tag:oK7RMnCrhCfVSju9CViZWg==,type:str]
        password: ENC[AES256_GCM,data:eBjG04VR5Nn1tso=,iv:cVQ95FiA78rrfHu4dYx22LcQWenkbv3dbGygVV1XdKg=,tag:S21ipfCgV7Z1lZwyB7TfNg==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:sey/KqfGiOELy1AaFFt5fbx8L/tb,iv:tNIzFUd0JIdhq4Zl+GbcxEWq5pX/73ULnJ2YyHSM5RU=,tag:dIuI4tAU9WQwgnUb866Hfw==,type:str]
            password: ENC[AES256_GCM,data:C2/XFunSH0VcY54=,iv:zVHfaIJVXS3P17WT2VueKWKPx6vIRz7qPENxgluukgU=,tag:l1X8BNhogNWbIJEXLuApEQ==,type:str]
logging:
    level:
        org.springframework.security: ENC[AES256_GCM,data:6cX0MuE=,iv:KBEZ8o2C/UmfwSHuzFDOmsR1kesubRSBpkQxBe/uok0=,tag:Vx9AyQiDe32N3XhKpsqhpQ==,type:str]
        org.springframework.security.web: ENC[AES256_GCM,data:wj8s9Jw=,iv:241YNq0Fug2izVcoODU2Gx6vkt5eOnKN3wKjlaebKLs=,tag:n4QTbP39RUHpT2DkadorfQ==,type:str]
        org.springframework.security.oauth2: ENC[AES256_GCM,data:yamukds=,iv:oNzB7j38rb5IJui/ogfnfs7tv5KxUJ9mNiMPwFMBjZc=,tag:lUsAs3JC7I56xpHmTtTLEw==,type:str]
app:
    domain:
        frontend: ENC[AES256_GCM,data:ku4DBWKiduCtj1f1pe7SrMYLldsy,iv:xyh5Zt4etNodzxcdJiNM8bcs2ALPswgAecU7GDu31TI=,tag:juY3pX31N2ekACJ92lb6nw==,type:str]
        cookie: ENC[AES256_GCM,data:2hsuOJoHXVEG,iv:/JU+tSV9agLT3wLGasEZ3Woe92kfdKKiCo+7odsVbmE=,tag:lPk/DiHuBKYdJkwbJlX9xg==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:flDil0hIDzHfw27neH6HjC2on4/JkzkMySnphmbAmU9skYzOaBH+5Zb+jENASCoHBjxx3kTuEIpgkKs=,iv:0KWHqvxBVpEttRSgyGtMm0Bnt9iOUTsi36J3JJKdJ7s=,tag:WhR8OofvJAnDs5sWrTI1rQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:foLfpDq4JeRLI197GS9b4HJzVw5QxLzi3+epOEFCyQ52wRCS7gxX8a1EeyIisWs4qaH/QZ5soAAMmz9y,iv:OJ2Uqb6msdgTGHK9X95fz1bMMtzQRGuYe/36irYpOa0=,tag:V+/5tIBeYTzs7AuxPc2tdw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:5hUHLuHym7/Uqv6SRnFZVmtPFpDiKjdCvr1DekZz7xZF6mSnLBEzOrg8qEfHRBt1XlaGKr23N/s4TQw=,iv:gsvAaFPHEEvBAhYcnbKTKkN3Nw96SZqfxjblW9KSMmM=,tag:ZkHFXbuL5FlSRFfEPU7xpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-28T16:16:00Z"
    mac: ENC[AES256_GCM,data:qGEK7ZJkcmyvn+OVdEF0LUfBK+Kj3RztWEaPi1Qj71Gp4tEx7rvg9Z9TiQp1tEnEk8JZN77I6LHLYTzpkIODmJ0KIN7YsFVY/fJhunafuJnUcSPRDktJW27mEluDYq3djjTVhvYjIiCp+z1sdM3Kv5BBqoj6VjUITYM9wx1GWMM=,iv:hmrtulvyuZSnQpnNqhPWgQjKHtlNJpjI+4hDxFfecYI=,tag:En1znl4HPQb/DJqAKgyiJw==,type:str]
    pgp:
        - created_at: "2025-06-28T16:16:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//eJt+7wYnfoIdgYT6oOjwvdJEo+CX+HgJl/X/0+ekl8DB
            J2F1BAO1Wk+lHbV5wuCHiGbt1LksdFW++S3xZbYuX2qmQAXtndMyDaYB7n64OywB
            ldWxFJYLOaucWUxzkdqd/T54dA6sjy13y5aXz2H7zjvj+v6nqDC4gMyiQ27TGFHP
            foxwdt4676P3eyCZsjFJfpDKFTi6yK3axwu0FoVEkOJI78Ma67d1qdbDK6WtLVhA
            VI0E1QZ9IJqb0zUPKeyPQaYjxfx4cTzlbHFUtiJZF+9S7TRbTSfcXIDzjCuwlcn3
            +6vQpjIqQFe9nlyvBMMPibxTYubCWzssDDI88F4fnSBxGJIouHm6B1lXKC5NMQUx
            92+Iw5WTWNKHi3bReSyJNb6QfZozCV46ZyIXNq7rtgsdzzxvy32+xe/yr6SAfapj
            2u1hjI+pWrMaWZwksc77fUwCSqqtWIIojuAv3wJGis0QNGWCzpZCqZC0QGm2euTO
            rnkWunbZ7sj0VXEuLEHx2K0q72rnz/aVJsfGtZy7zW2O53M+QZkC8XSwWwJcg4fV
            WCSuLtpif6u7VSb8DJfcfIBYPVMDxplEjAgd3k0oI3sjzbDq5xNn+KFESMrCYJUx
            BBWXUyzTMOuGZlC6FEmPgZQwUCn5TC54K9JmfBGNWTvIT0LbWWmG2kwgJIMtQJnS
            XAHv/f9gUvhh6f6qdFXy5ESV8Iq3fdqv/G9XWOnqkbIk8JinVpMkTxV8Rm3NUAC4
            dYrLPJaoEjKxuZiWWG6Q/vkDSTmaNQXTAq/Kz9hl1S++RqyOnlk+wi+934s0
            =pGGF
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
