spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:937ceT2OHXWeutUWKKiANo6Su/QZkFCztQ6sUjxK8HpNQYCaowaZ4/geJg==,iv:2favfP+V99Z9zpSNByO+2sahJxryQ2PhMNiis4ns74g=,tag:PUNI7l6yfHeNQXJWKzcbaQ==,type:str]
        username: ENC[AES256_GCM,data:iP+OzqvA,iv:ItTLWrDxlainLqndMI30xz7sJpkiJX92MJHG3Wc+S+4=,tag:d/a1C47hkg8nAkwxbcyDcQ==,type:str]
        password: ENC[AES256_GCM,data:Y8Qx6ppPwkzSF/k=,iv:tkmiGmAl0069WBSdnI5fHpQ6u3cfwVrfyAaSgxhUITE=,tag:jvBQXTByr+LJQs/o64KwZw==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:5qZx8zlEFQ/34PjdXQxlnASQdhQ=,iv:dk21fCLT1tpNkqLVBENLI5aaLljJgwEvcqtgTwhl8iU=,tag:EkML14sGphOmPEugrxzABg==,type:str]
            password: ENC[AES256_GCM,data:nKBPlXgmzKSYm9Y=,iv:Ei9jFwfUScjcq37h5J19fB+GbqLkHKYEWB4yByTBu7A=,tag:srvgtFSdTlNjPYGG0XXLeQ==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:ZiQlKI4=,iv:4HA0w3f6/l1Yq0NJuHsXCwaSbboI1qgN8Mue1HgVBks=,tag:kl963CFFutbaam8kyhhJXA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:k0AgQ3AQ8CLcUfDi4Fk1EAxR/ZYPM7idYIinA1AJ,iv:Sn853ay1gZ3pLhQCJfDUN8ZqIgJ075I/vWoEpCkcvM8=,tag:PrEwbD/34W3oko2I6JiWTw==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:IgePnRMQeTm/mx+fhAGgYHf6+v6yhOXdXkRFngSO,iv:FIDWT0PUzPQtpG2E7R2FggsyqBbSeP6Sejm+FxwCqqc=,tag:cM1PK4TKgAj2SAWPdrcpZw==,type:str]
        cookie: ENC[AES256_GCM,data:TKVqtbdMURNTIGt5wTZyCA==,iv:2ehsnpy78+BezahAJsNlwY9iXh/SaD0XCtLQiJ/uDik=,tag:/uGWm18L0IGbanUCVCQl0w==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:4rmQVaUYxC/XecnlLmJBttww8drJQwAPowzF4zQco6XvuU3IVv3h7jDykmTxLtoiUxqzlYFz1Wxt,iv:+NFsBAM/ZdSrXnhWRmf88IC6bEVQOKD1YumZwJBS8n4=,tag:2CLb+VPgGTlV6wiNt6gP/A==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:ND3aPj5GL0aKC7sSsQWry+assA+W3e1BDW74HjcwhWv6Fm5KWxbKITE4q7y06mMgIpbqH+D/rKmPQg==,iv:4X3CsXWyOlIND/royEWtS3By+Dj/pXAe3k/nuORfAtE=,tag:+LhMeyqDlclJKfE7+0Xa5w==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:DLAN9h2WgmGnU6uJ2PwlFAiC6ouLcyJYh/09w9Yl3vXlpSqFP9R0Ad0nhYlGFOoe+hJoLea2I1ze,iv:pHG1FUrti7S41pwADHDRywyaBz1aQ1wonlbvbei/b2w=,tag:uQ99AtwpZZQ35Tzaut4yAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-11T11:50:15Z"
    mac: ENC[AES256_GCM,data:kcFkrkJXvltxVWCARTQ0MqGTjjgbRfFPbzvxKzXAUA03kZClPKcIg44YNtZG6ZbOBp1OAZjX8KA9HNACZ2YReeAmpwdOrMl1xw4KnB2G0upYyF2Nn5u8xNGPDtUxpf++YrnKcmuo0RRF/M4+JOLP20UAczHPgzJZLQ3Pfoyu8X0=,iv:WHgS3phY31bkhvP6bGiPaNumNCpDzDtqdHVhCqH/rX0=,tag:aKMn4bE23uHihmdiBxe7Yw==,type:str]
    pgp:
        - created_at: "2025-05-11T11:50:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//dY5aaTLFozIzQ3XSazmzxg4yyL4yeqKZ8mdIBFU2pldR
            hxzaVXNdVYxvB89eZ0qrNTWVCRUOG7jlcYFtLONdQtZ+cAkC6uG0wj0c9N/UbTdG
            ZMJjEC6lvE0jQucGU+gdydqurkZFeG/9D4Jkw1/uM62PYLWSfQrF9HBowHtC16rZ
            /vTFqfIiPeznt3q/63LDAXZIA6zJBVdEVAhAiQm31TIq7aFZR8bm7dFR1iy4o9lr
            BhBOn6fQPjQCKYAijLk85hUuWjDbLcMXLekbfDTP5YAA5DkgvjPpQVQWIhNFlzYc
            EfCnwlFIahQHxaKILbnW++9Sv14EFPAGGKjq5OnK/0RFyVF3RXgfq6fZMRYymMiH
            aqdgxSyECVzgWCulPmexbGffV68aTDnfABIQre1kbvVol9FAWEBhfYrYmwjlxC+y
            7og4cETMQTKhFSjrCebAFyF6iyH35UN9zgFwL6bRhAVJ9nFxFmy2srKk4CrmHSzm
            YIe85G73ATI0fxnoqj3lsSdbmjZvsPm69gE96L+6YVJL29ULjjguLs9vrbQGWWVf
            HBLaaR4ue7dERZEsCArlyYhJRCj+8cEYNIISVNseuIWuGV/zmSA72/D8f9NJSLWG
            CM5xPbrc2YcarZnn/3TmcD6cULaMo+k7Hp3DXpzE7nyAnAqvgCy4U/gugYaHOnfS
            XgFTYE+ZV/cSetMMJH8d9ubwdjJWBa2Dpz948Fr9LjhwfFT5EEwuSYYA3UbUZumD
            4rOX5P1p3PIlJX+kFBFo6VUcx14eVJIHKO58o4om47mB7d+7CvDv7TJDdgZJzSg=
            =neKy
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
