server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:8Mff1kw/g7iYyLMMQWN5iZDwGA==,iv:lm+p8VKI0eFkehFowNFNDAswb84sEQkDcv1xgXYx9bs=,tag:oqRy9TfxzhluK8axUt8M1g==,type:str]
        key-store-password: ENC[AES256_GCM,data:LKSYTKYIzMhBQo0=,iv:hFH+NCa8vBzA/cXZeqSA3h/iVBYSSgu/XM9xyiQ3Q8k=,tag:T0U+8/WEDVUOGh1hOAa/dQ==,type:str]
        key-store-type: ENC[AES256_GCM,data:/hGx7Rsk,iv:1umALbYHKH+JsQlzh9vMWc7O1mobDFxaZxwflAP03tQ=,tag:LldCvtyvL5awuEobAjd8DA==,type:str]
        key-alias: ENC[AES256_GCM,data:8wYLF2/J4b0JSQ==,iv:iGnbqa0aXBEmkGo/7dNU3SaQzVn89RKU/EWJ1vUOVWc=,tag:x2YilrMjyMramvWIcd/dhQ==,type:str]
spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    datasource:
        driver-class-name: org.h2.Driver
        url: ENC[AES256_GCM,data:veHsHod+2QMZb53au8+KSg==,iv:S6rHf0KeaLvgMBaOh6/wHwwsmoVlvDQPbABSToCEAoQ=,tag:xIG9hLnQpT8g+jKa7naRHw==,type:str]
        username: ENC[AES256_GCM,data:PCjwu45q,iv:XRCkBaDAZI/OPIChyiq+c+JCOeW2PQtBnlEN75nLkbA=,tag:flD9gV4Jf868KWBnVJpIgw==,type:str]
        password: ENC[AES256_GCM,data:PS5MKLyukQz/btY=,iv:2cHcnJ/KEq7wevwqQmeVHswocZYi/yO+xtKF+UvY52s=,tag:B+DTzJu0/D1uKdQu0+0GDg==,type:str]
    h2:
        console:
            enabled: true
    data:
        redis:
            host: ENC[AES256_GCM,data:aZGMwYsugKG3Genvq535EeRcRYTC,iv:FQF/P/rAZ1rt8Chqt0uB1SFzksi008fwJF5kslRV+TA=,tag:OSpvxhJbEV+3ztZJnHhm1w==,type:str]
            password: ENC[AES256_GCM,data:hStY6F1N2BiEwrQ=,iv:Sm/P1ixTlzhveqegudR6xgPX/uO+8wIh3hTj/3P5XjI=,tag:rt7DYNIFoQ8clCQ62vl58w==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    flyway:
        locations: classpath:db/migration/h2
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:ESv4sV8=,iv:UfF5I8hOQZ+mJWdfefu26VSTqTKwlLRrSaiOhL8ClFw=,tag:UpWR7+BOy3pXP6cPlX3r+A==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:+N+itqkDa+KbTLp1YnyIxN3sT0UJPUC0VU9838ds,iv:u/KRHdrpnBwiLmlf/5tEdCprG7XYHLl8pfqfYlviDjo=,tag:3lQp3io5BOoJoaZB+8OcQA==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:/CbqtVz66l5h48xC+laQIoDrriE5,iv:IN2nbfzOS2XG6lwGAD+VEb1F3R/zVgAtWZMRALev4Q8=,tag:Jc0h9rHoR85A5/UuFX6QTw==,type:str]
        cookie: ENC[AES256_GCM,data:MoKs3uMH6GDP,iv:xJgrbAEH4c0JAiNxSh4b6pcCMTKy1sYuugCGiGOR4bk=,tag:4BJXdM0NKxySPgbHz43kUw==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:10txteGyFtYSSTZDq+Gt+tEXzk/oKzvju4LdRWl3498eEnYlYoFSGfDTLDmWjXQPm0Ro0ltt,iv:uPw8PrCbJCUc1aYfJTje0MgXf0PWOjCiiUnC48HvuRM=,tag:6JGXmaPAjxM1J0jvFyl6EQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:kXCHkeEikJFGfwF+n+VDnURd9bERXI0iCly8nKRJA+EGGcchOL1AXOIMIUrfarfXxI1U9fq0uw==,iv:UQHA0L69B90OdVrir39AB1inQPNt8Rz9+O8TwJSQeeo=,tag:Zvvj+pgtCcVKWMITkHF4rg==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:SNtlxITZKrTnHkoTDAeTMvoSctpZSMX7CNriQjhuVskJbfDH+nhTG1ZROk0MRoSPr6z9gd7u,iv:Hs5y2F2IVyv+ZaMhw9wcvfkE7OYpt7yRbc4UqVgMGcc=,tag:c9ao5TH7kigcG4zqOAb+zw==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:tTtUxJxbYkefsZSt9DWWBpwS9W5vZElFnD5As9GZlmvq,iv:lzjOi+DSGmkzd3IVgRZ7QehabMHsQyCjcpQARFdgQDg=,tag:7BqDPQBXuzhBUslN7O7CPQ==,type:str]
    access-key: ENC[AES256_GCM,data:1e9qmq8DN8N1pwyWGkpHO5fR0Qk=,iv:mVXnD9bt9U+4jk53SRuKZYZIveG/OGAyHH+91xl5+pE=,tag:9IjUQPW0JI7+pSN2ITrj7Q==,type:str]
    secret-key: ENC[AES256_GCM,data:86Od15Dx6tz0GVMqeswxXt5SCt7uShcma9M8rWGMvPV9rnvzScXmkg==,iv:GqDcrSJTK3F1N4l9exEERaQsTt697UjllfJsGSKLPgw=,tag:X5FYSV64uw99baDTM72ZSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-08T14:23:10Z"
    mac: ENC[AES256_GCM,data:T7vo75olq/imVOnoi22gvnj8dJpM2QKzX3YmCu1Fmtc8KFuanMld4bkwifI0ZtK+3MGw2SpIWpWbGaUSM90mWzOTmaGStTSisMct24MNMgUe8Keq3gYbBG0k9vzzq9iUOiPIjhkwM1Wz4gxKFvL34G1AkJmm5iBz1iO0GyqnnoI=,iv:YpMZB+Jr70AiOHyn+UGi7oa/OI7PpoCi66rZ5jMXh9c=,tag:jhFc+O+PozT6MQa7ZJZKVg==,type:str]
    pgp:
        - created_at: "2025-05-08T14:23:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//e7GY8BgH6jpMuuSjWo0Ebxam13eDHeop985OVcpm1nx4
            OMt31yc4cqrNEA755FKfajK0f/JYQrdPet2u/y4RxoM5M6aA+PgU3CLRg0W0xdUG
            lt6Noz7Bu7yOEFFHsmZCT5zEIpRkM5O824oE4bkBxMYD6IUybG7n/S57BJwFY1DM
            UajU3VNUl3YNUS8zY5NhTzfvIWn5xLNNZnR+iIghJwc1JLstCWaDLkbVlN9bqoEl
            f+RSh7Zj17reJpbPkRsHxSOg4Cc7whQa4cxEKC6h9xoHQLRTElCW++OoHuQDq18A
            zAkfnizE/+GkD0vnxVRA6X3rXloTPqGFl6xxmqOokQRXtDrUg9Q0cFcRZhP9kyJU
            0qyWxEXHpJzJO3vb1vfQiazFHJQs6t9FZWFuc8gIYpoC1asg/hU8+Y790E+cI4Ne
            ptxyZvoWn1HOklhOxRULeIQA9T/wPlwQYqK1ZiM+t8JoYosTt6nl13RUfPo/2FxA
            yAYceuSkb+qtJBn5cEvhQXHlGXKfzouYujVG5vcIWrd6mphP4w6YR8T5LGkSJ7Vr
            GikbA5w51Rl5RZ3gnehPLVhGTMEx692wry7LYG4jM61WYwmlICx/99V2YCPw+qlC
            2WyWSric2iAnrTNKPMSJ6zO++OsJWzz5UTyE08GdocjWxnNHWBNK4m3Ag4JvkMrS
            XgGADickOS3Eh6USyX5Ny1Zmh7zVzclhp0TJuMVBH/ck/KLWvYKt1SfuH0EKhZUy
            OGv3Ic+7Ooey9Nlm4+RL6oKxaGaB/ZEeLwrs5kghJmRtJo2QYcvdlP7DaLcOcNw=
            =Insy
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
