spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:NY9B3SeiogQDOZgq4b/oWr6No0n+WAaUSuWYJi5zxyLu1OEy2pTw4ypX+A==,iv:1Pw3gG4Jw4SzF5nhq/X+T3QrxiytNr3lAuDNt/tzEU0=,tag:3u04ZPE9+KG9Jy9a0S1ztw==,type:str]
        username: ENC[AES256_GCM,data:AwwBE+tW,iv:ZufJdMUA/sBPfYdM9ia4fA1RO5Hac6mWID9RPtv1vy0=,tag:SMBcB8ZVYaOnbXfw7e7MQQ==,type:str]
        password: ENC[AES256_GCM,data:KkGVRzla/0ecrPc=,iv:SIdKNQShAPjjyciCkQ3c1SeMP005dSHUvkYIfl8MROg=,tag:hJ0b3ZJNUFHBZAwLkIP9Cg==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:sXyQYg0epNYfRoG6no9vI5RfowQ=,iv:d8aHIYwZ2aFIk/EMpS9zRRGl6hgCOfFvmfE75MshAWw=,tag:4XI2r0w6OqiIYBCSoNyGpA==,type:str]
            password: ENC[AES256_GCM,data:tFIyv2g9f2HkFYY=,iv:6xODp2PEBNYebsszw7upMq7+Wme68pvXKbiRCtx5lr4=,tag:QIF4xsgIkwNdaz7sGd3qPA==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:SFxBy4Q=,iv:04A884z1dEO8E9HWwcOvNwnlGwI8yxITKs5/vJ+sIF4=,tag:5UYLZZIaZrV9bbfnPM8LkA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:mMOpgvujEu11e3a3Rt9ksNPVsanbr9Yz17Iouf+W,iv:I/gP/qtfS917BkG+TeyudxJAox0DDy2K05F0qp5Mpfk=,tag:kSIV5O0WbobeL9R1mRgJjA==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:IEDk0qrRf7io2+ENhF8BHTTEk7coFFClkDFroAXY,iv:o10YFtg8wfTmFOBZhpCXEpiz7wgXtYvQaiQQlNqjQR8=,tag:t7Z3eyGjTm09I3HbnRe1zQ==,type:str]
        cookie: ENC[AES256_GCM,data:r6mf0utIsN+8lsARteD/Sg==,iv:/M5wPmh+7rbXo2gsEnx9LU/nSGOIfqk8BR1RkY/qGZI=,tag:TDkNZYqM1/uJrTg7fqMi7A==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:mKcYOTSC3GtxO61r33K7h/aEn/BKuDRbRrJb+KCecpyTMUUeD75RZdZTKClzQ8OlOb1RpVqXqxmF,iv:tiBRwHoletsLnY55sV4f5MxHUgZCgkr9RIRy16TLEVQ=,tag:rERAvSSJFxcG54w0gFAk6Q==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:fbOrRG1L/kdseBHrFoz1/a9ZImKAPdaYK1NfFWxot9V901Mxll5OMIibs1XdNgey/f7x2W9uWW39EA==,iv:nHVuNfNTx/5uxhXSIAP8lv8MmDh9nF8JT/oGZiEGHeY=,tag:tfIyU9I1Z6KUS5PTM+IBuQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:8bsRjfnKf5y0sODNWU4JQoJJIvF/CNJUgqPhOKS4rbBWnhSQva4OU3IYXzRSgxgyKVewG5K/BzRB,iv:34Yjln00IjZ5H4cOU6HiGVAVvGjxBWPY2VeJxPeXyQU=,tag:iS0cgGuZvjGN2wktWVXGSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-11T12:34:28Z"
    mac: ENC[AES256_GCM,data:6HiFjBIkdct+kIzjg+TwyC4e/huHVFZVLK4LT7/YVyzbMoUOun3+DUA8Pp1t+f2VSoYpl2Qq9Wvk1bvraLGkRPa/pk5y1Tn8krCTF5NwLnTdzy6C2VsfOlAht/Cr7uLiYaomkaymo19a+z52wf4NY/CX7IoiuB06w7MM5SnpppY=,iv:ZmSAUR/yghZinP+oLp9k/ucI3K62ZYIRfAKtWkmhKQc=,tag:IPz4GeFQf8KTtZWDGJXQpw==,type:str]
    pgp:
        - created_at: "2025-05-11T12:34:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAn8r+x9j0RWRIRn44i+qQKpc035A1Ruw2nuc9LbtJTvbG
            QsfVooaMoDvm/L2xHNggBf2rucSumpjyUrY3DlW9GPWPzOVmJfYgH9gjXnOB9PGE
            SeKtd/yMvZVUb7Ipeg+rXVDFdVLYAIDTS4I6nkgSCWhRN1PlsvxRlkzvm3gG2FYR
            ZWQSc0wkBC9Yn5I1gyKOCcGYD6McgcGPz0zTl+xUtorInSqDIKdxhRqURDCbj/rm
            t1Bkdaol1FEInqP62KhslyvQvbjHR0zFeOLv8AALY4ZRVyLhMU1MnTaxKJPwv2Ec
            IPgz4k+cErzN6n51X6YH3UvPM+YIo38CDCUI0efgrbTotYhodvVV/pQtdAJeLQof
            NSAHmVcxdzamKlUIPLEEcx1BH+WTeW0BEBfZ45BcTwAYapv3422vc1Axu8es/+s4
            9E9mLTc6TDzkQun9RbQstS/lEsUGTcT+Qnp5jgkJe2Ea0ItaQula+Ps27SrajTHh
            l21L1JB20pD1M+OSl8hHCKNsucXZAJMtYyNXMlt6Xh6qlQjNQlIlMhyMu0wCqK1D
            InF4NaKWS7LCNTZBvt3C/dvLtxOD9zFNQwPeU2XdrsQpoBhnWukocCgjEiSehBTJ
            lBpUHQ8ZIgSzPoLYZO9f+tAan7lnqUtKgTz51LzVYF47A23bsZ8CruGk541k4LHS
            XgGxHKLlLUfWyZlw+FhbMmuZp2Y/wiq7dHg6X2nr2E7ZApzbPdHccmmDVLpZsM6W
            bOKyd3oRnk57ttBRP3d5Wvsn7fKR6H0HVeQ/22VfSceH8rKaRc4V0wjVexxsF+I=
            =7H+P
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
