server:
    ssl:
        enabled: false
        key-store: ENC[AES256_GCM,data:YOsmAvpFGNgtJuAPvhlac/+erg==,iv:1eY07wd/I5/BmLanT3gFmvPJkWsa/OGavTk2229By74=,tag:2Nu3tCyFv+VhuLYkBJfuTw==,type:str]
        key-store-password: ENC[AES256_GCM,data:NgraU4LIrUXMx48=,iv:DRnj71Eed8sgW92StAxM7qjTXGxkpqko9Hu6BY5J+u0=,tag:Vyu3tCTWPC3SCcAWGCCr5g==,type:str]
        key-store-type: ENC[AES256_GCM,data:qerxKxBM,iv:3Lw+qEhLW3OQYpAgnGFAhlDBPVd7x03q9yszxuRO/cs=,tag:BS4YXJeHciEGndE75mgzpg==,type:str]
        key-alias: ENC[AES256_GCM,data:VoTt+VYairKkGw==,iv:6OAZNlW45z8WHFgAol3eOZJolyWJqJGRcONwxYP7r5U=,tag:6x1ijdyUe29j0IYXS+KjQA==,type:str]
spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:tuYdbTRAgXNb+QTp9ZGIhT6cZyxS6Zunj4XustDGA5nF00V51VovWQ1iJA==,iv:hFLLJ5YGwTG3+GEkGB+7QYJUi5KxLQqUkUw/SMb/Y+k=,tag:BN4Jius07QQKJV5YE+8e2g==,type:str]
        username: ENC[AES256_GCM,data:CvGwTS9K,iv:ceGjiraANKLPP4PehzkOxVjj5cmrpoE7bGhNgbDOTSY=,tag:rKKS/y0Oz/9JucMLAJ+T/A==,type:str]
        password: ENC[AES256_GCM,data:d8vORxS117nGdSA=,iv:eyYryLpL1gtFALhD6G0FmxcBwS3gc13cYwvFn8A3t0E=,tag:fpumXVAQfDk4EBRaN6T+9Q==,type:str]
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:jKUZR0ilFVYodYU9cErDXWRR85o=,iv:JFDVoeZCmrzP6feN4kN6KKSzBhi9JOzH3b254peOaSk=,tag:30eUB7ZfSsXidqSHPXT9Ig==,type:str]
            password: ENC[AES256_GCM,data:pON3G6xZqF1JzwM=,iv:36D3joRLRuAt4IfZ2e+XfENQHeIe0boGSi9JZQ+hqDM=,tag:+3aSeI6UCsEgfFLZW2/2qg==,type:str]
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:rBBXUMQ=,iv:/aXgRN1fCeRAymEx29c9sbbX9xpMe9bFa0CPZGfvw/8=,tag:VZly3xUwglylprhyKvk0ig==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:G9g5ReTMO54tZGyTE3yQ1m2QUNMlUc3NXfVB1aHB,iv:S+Prs7IWsOwybbl78DYaYcm1eJDWBR2IlHlJ+KU3axM=,tag:1wwwSWS8qKtUNE5Skjsodg==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:92+N1w8BLsZQgz9Fz6+tsRuOzmul,iv:pE3Lb3Jt6WasKAdCPXmYEGvU7Dq7lASL1V5CzgCIpX4=,tag:1FC4/jmyUZemLxFc8hwcvA==,type:str]
        cookie: ENC[AES256_GCM,data:JvczzTwiwmf/,iv:vzVlVq+m37CbdM3s2HO8FsElFoAn+2MntaFIXq2xmWc=,tag:BywFRQvwiHkH1cMQeEpr7A==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:RYoK4sDUex9osfLcv4UxPrOibuLXFUBwDJNkkdFpSOM+9+lzPzhN1AW2LFW5xmZs7OA8EW1zH8LDeUBrhshZVw==,iv:M7O+c3UtAjBDignWVot483xsxRi/EODNbpIBBmq9z9s=,tag:7gGoMx2bKZ4ZNY7KMfqR8A==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:ismdxNj7ma1f/hqz7RY1eaQ42AzieQcyiZzncJGoZKke1T7naGjHVYG6eSHQIbf/N06scxczwwiiEtyEpS/ixvM=,iv:DSjVwqOK76SW2Wj3kRmxAy3yQxkbI/4QYhjJKfjfX0o=,tag:FuiIs7kGZux+YVyq5DZ7Kw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:Yi88SS3ZXj49zqJP7UNOL2uWlUnYPO+wwpCls0KJ57vlLPwnEnHQYbdNMs+0NoBnusp//CNXxWBkRcmSND64IA==,iv:p+4Zz83lSgV2qYLaQNhTMNvpN/Gon0KwVkwsjeC491Y=,tag:5NZD4An2vCz5Q2GJZHhxuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-11T12:34:28Z"
    mac: ENC[AES256_GCM,data:Lf32LgFvTfvXBHaUggZxHWZxZOE3gL5GWFYaKgacr7bey1aBcMZFVMbhelqlgPtv1S4At5APOiza9vuN5Jjr+voWVNru2fW94DVKxcnFo7AKBQg95PvuI8ZdOWyQVkpTpkF1PRA/PcMP8ivNr9N8Ty7IX3CQh65W3bs92wWZj1Q=,iv:7hGxXa+gRCn2Y/63qhWXsaQO3hffA3jI7fP1nkJvrcw=,tag:Vr/URj1VMUUf7X4uRAQohA==,type:str]
    pgp:
        - created_at: "2025-05-11T12:34:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+KDrPJDLw3tFgWo+VUT3KKwVmcWIvrsX91z7TRfC3o+Ze
            kRLWYTGnlZPdCvAN5GPJt87fFL27ZujQhkfz8JIjoLtnzCXXczEmRw2pv5ovxWab
            lj2zwkMyIl2YSRN2Ne2zEG79yQ3gpONB8h5Z22raJvPOJsm0FaonRjsc/89mnDvX
            Ms9ghrqZzGqAYyOWtAdcfXKo0ItfckeJv1AfQzGlpGq1eyHOTXiDjHE14THtnSjl
            5G2Ja9kc8I4eHDSTHXMqKmNLCMs7+6BVyuAjUstlbHHtCVdE3hGzg8RJZSRUpG9i
            69g3nlTA3HwljFDVZwhP+KlMMh8J7JJ3HFDHn8Qx9rWkwP+pbQ05ukXCsfpK79Nz
            9kqdOCwMgR5GH3sUtBiMq4yCvAajKo79G+ywCgiaWFwv7kLDuMcP+Ohixjs1FUVO
            QAQv4/VyKOJd2rzVmIxmNmRHtWMWSNIP0KkX9CRvLo0reKRGPGY2rxXEZ52tkJHa
            LlRGdwTVYDgSOBQR9GbU9HeSTvYqnZXcjxnHW5k3hjbPKANz4g1dhQbd/RFaH2Qt
            k36r6abwreRMtb0v6wUXirEABLG4PkLWp0zcKqsv5aEurYOyiwiIeDLTBxM5HQil
            EDl30YzzKRh42S1XugHSzXzTOeiGb+LeScDSDu4y0ddxuS4svY9GGyYOYUmVBC3S
            XgFQDWpZIkBaAmXP+k3R0wgxuHJoIxpoo8wX0Hs00IsMzspHa3E3EkU+DEBFRqWw
            k4gnUl8b6nh4gAeGJD044Um9Afv48G0vYG17bk6rd3cmahXI67rtzTNTK3JQ0ZA=
            =9kIW
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
