spring:
    application:
        name: Replay
    profiles:
        active: local
    jackson:
        serialization:
            write-dates-as-timestamps: false
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: |
        phanes.replay.gathering.dto,
        phanes.replay.theme.dto,
        phanes.replay.user.dto
jwt:
    secret: ENC[AES256_GCM,data:vx7C4xeIkb2EvWrpu9Hj419o/3r0kE3jNvHrye1Lc0byQn9maQjwuuva8Og=,iv:ytHYHj/kV/KJXZnv3mBs6vZne0LOW5B4yFd6blL2TDQ=,tag:ZrEKfLvyeqXFmplCpnWrrA==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:6X+w,iv:FD86iY8OOe99mzbKb59icA7k5VOcrncdX9FTqLeZrrI=,tag:IDaU/EHtg75UiJnxDkeKUw==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:7Wk=,iv:kohqMVyZSCC/jBzzILr8F2RZxWIx9j+lQL5tjhhRCco=,tag:nI8H8U4HDA6dkfLvYUpCog==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:ti/xY7n9izst87KTSgKaDq2+M5A=,iv:W9c9ZzjJbUGDu6CLDvm4UkheFsbjvb01eYEDGoeG9GE=,tag:BrtRN4Q67KpLXw/UJMYE2w==,type:str]
        client-secret: ENC[AES256_GCM,data:i877U3qqjJwWVw==,iv:jx5eXm4FlroFNsZj9xHpmHNkd/ukm5yYBO+6GxTqtXI=,tag:Pz8yCM5f2jiircmlBUpU5Q==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:97ywl3/BKNsCnZmpkoacTKeIC7NWLSR7Ks9snptSJyHyfBDsdgsz2qa0Re8kE3qyOasX9KwBJIujgQixz7U4G7CWSukVxxDI,iv:fsjtj6/YENYlrVk2k4lwhmFPIT+2j5f+30wAZmzOkcc=,tag:xZ6mUlGEtm4V/Z2pvlP3Vg==,type:str]
        client-secret: ENC[AES256_GCM,data:fy8WJNIgXyyN9kAcOHWAsEEr9RHh1rFny5mBfh1yam+LYqQ=,iv:mGBdFgQ2iSjWIEyJzO88SNUr8XArocUf/h2GPHWo0Pw=,tag:hjXk7x4E+ohhQ3p1c00c2w==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:cPkyFzq3qFcDVCXviJES1lLsLm7R/KhpEOitWMjuKsY=,iv:y1BZ/tTrZDu249pqRoeXt0b2fnn3/OpLHkv4nJ9MKYs=,tag:d0o5hlRd4Nb9bjBmf1v8kw==,type:str]
        client-secret: ENC[AES256_GCM,data:NuzUCnU1eSGHJXnDL0ik+eZZdxfzRJO43Da39cuhg84=,iv:aAzMC1qJjWAr+HkY4jjcuMr+iBKPFrh3ZlfWtl/5hG4=,tag:lnZFyKFcYnOexH8sed/SDQ==,type:str]
s3:
    bucket: replay
    endpoint: ENC[AES256_GCM,data:8yTUWBvxeu5vBXeVSeOkEsTjvVih/RdK2NCew5Sn8l97,iv:p96yQLW8bkhxYv0UQSU0SjghHZphB4NobM2BTPhgXR4=,tag:Mdlp2/iAHGyKRGKxT7ripA==,type:str]
    access-key: ENC[AES256_GCM,data:6k6vG658WV2O6Ai+bSIVoIxct40=,iv:IGvDL0F4zpSclc3bEtCrCuDXQYtwKIJiXnj1jSkPl4w=,tag:sjHvH4vCEJEZXmmR2n0W4A==,type:str]
    secret-key: ENC[AES256_GCM,data:fdmbUd0CtFklgKPJyGqcUUF7wG+ygS4Z0JVsVCJ+xoSfAE8U1t5hBg==,iv:LSJ+cmii+w18G1DwDZW2RJzEPlJtjMspaFIsJAJd5Yc=,tag:In4MJ3OWl2OWshNTNc07TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T04:52:34Z"
    mac: ENC[AES256_GCM,data:1w8JEmDLim3vWv9AakwCDdBPNNamY88q5yLo+zE43HorwtBsWspWgfAfRWK7+8OxXzaCKqobWR39DylmjIGS0eDguI3RGTPPEsXKh0HPEM3uXfvP+9FhHmACLONxzRYhx1PlP0XnYv7KVmvQVNVzL4zF8mj0VR08zctX7G/DzCQ=,iv:J2ad8tmoDldt1ohYkbGqK7WamTFiLL9RAoavUcGXjWY=,tag:AUwPvPJZrGU1autxKzTe2g==,type:str]
    pgp:
        - created_at: "2025-05-18T04:52:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA8Rw5zCwK2ZwBetda/dY23ygFSQTQSZDKRb4L2gpzF1sl
            5mKLmHG6CUuJzx9tpQolSxwC8lIh8/ubXtZLPtXYnzRxAzhsPExE7kd5EzxRM35U
            pqgcyL/zF23agtR0lfPqUV8eojKsDjDwDaeGe6b7So3FSnPwVX1u3sXji6neh9Q8
            /T8xejem3WS7APF6+QE26j5GXYezqfbY6CYh505uiz7oyiQgX5LOa+y2TYZh7TVN
            V0gX8BwwS2y8ebsDzzfXoleCzLudSIUmseZuMKMxeBjST4KfXn9wu7Ex6vimnNQg
            qZ7iwQJGg4R3SbMWN8U8gxt6yE32TsmrxR+wrciBZky/FDfU6/kF3kugJ9s0/Soj
            IbOTtxi3RySPANHeBlYXj7Tch0L5mBP8Mks/BbUMTCVmOyp5M2bJ+FGuo2WyLUHP
            v+yIzRfYi+tAkJ8+Yhdo79wJzju2rgmVNtbHNjDnupssXgmgFm1gdI5gTmvyI18l
            ZPNWTxq9BorfmKLwBGjBune0ftuL9FBVduqc4QnZWpDuW5yYUCh5w0rRFpk3XkNn
            M8NtldcEn1bqOusuChHxWHN8PWPza3kjUbWvlXBuGGXas2E8utt8+T5jJG3tnfHA
            TYRJRvGzZfiJpcU6GBbNExDWLLcEUW0pw00Ro1KjMzJBJytiqwRkz8LViuWRzK3S
            XAEqlNKw/f0ETA3MdK5YzNlMXR93rk/53MNtceBxdgviYpRuwi4IxwZ7EeJ6/5Xx
            PfiPUmiSKsAyAWueN7JaIwYvva7/5n+60cCZIoq0uKOUP4wIxOiEjKcGAAQe
            =ONX8
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
