server:
    ssl:
        key-store: ENC[AES256_GCM,data:88PKTQ76sVTU/QII0MzyO8HMcljJUEA=,iv:mLGD/0ImtfHSO64YNaumhKaWo/bP03MyL0pSFdaUww0=,tag:gzwnAPeXTLfS/Ie+lh6q3Q==,type:str]
        key-store-password: ENC[AES256_GCM,data:5b6+ePl6I2HxJI+xwFkDAyCko2w=,iv:6v1LV6/eoXZm/whRytyUdtPV1zbO+QmKL14eqzv80mQ=,tag:LN/DT3XiZ7OcultVkLHvkA==,type:str]
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:VBUyoix3lEmA9S1ayfpUqOjbTqL0lIFe6fEyBPZ5aD8F/KW7NxPP,iv:7RxkvUoJu/+6aMKfzMbX4jIkl1eU1UQwvqWEDjBzWvM=,tag:SxVNGsxly9Ecdp7/BNfEhA==,type:str]
        username: ENC[AES256_GCM,data:EkDVLE7l,iv:iI7YGB9lJqdaDAhmZ46CFu8WvVV6RvduwEcQw1pbwsA=,tag:9bCFu3RFDpg/IZ4I6grP5A==,type:str]
        password: ENC[AES256_GCM,data:Qmk83u0g7V+cxGg=,iv:ga5m6wtra0KpaC3MXF1MwJqeVh30FeqMNhbakr/uJZY=,tag:8zzZkMG+pS4mk+pjJio7TA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
    data:
        redis:
            sentinel:
                master: ENC[AES256_GCM,data:oB+YJz4O,iv:dgewOA7DUjHpzKRIHGs8A5McH/v8KaIbNxK6bbuUCc0=,tag:tVJnB0l6KF2BK+IfQwY14Q==,type:str]
                nodes:
                    - ENC[AES256_GCM,data:ytzV4tIBkvGlShwus/EOmY+SwjM5d9nESBK7bxkSGR6w/JANP/W4bjr4/o0aVet/4nM=,iv:bvFynRvNGAiZ1zzjp4b8cfzsY9HpXrhAoiA9lRnG0Jg=,tag:9dZ4DEkJZcsnedXWDZ8G3g==,type:str]
                    - ENC[AES256_GCM,data:i9GtaAxlbsT5ej+t0z411KfWO4MfxI+QXm9URcEpXVi2ZYAHtsKfHR54Gwx5OKmNij4=,iv:Z78i9rQmFm0N6SgvSt3guWtFtSRY37lIds3k4kUHZxI=,tag:96BTDwcAHo2oxtn/FvQY8g==,type:str]
                    - ENC[AES256_GCM,data:/Lf0Dxl2QLnxXoqc2oFW3YIKzWZOsS+1hdGiTo9SgesyDRliznN/dgkxxbvsBlA1XNw=,iv:s9uzqiIxN7lk2UUuHe09u5B9roAWSf57bgyWpTSecWI=,tag:QnF/E9u433IKI33PoD1zXA==,type:str]
                password: ENC[AES256_GCM,data:8u/1abUWqzz5Uck=,iv:GTodec65gI3b3IriDAVuEKXjRRsXUvhdXikZdlPFHwc=,tag:5Cw7gbLVzDYZp6nq6wRhgA==,type:str]
                username: ENC[AES256_GCM,data:kProq2f2uQ==,iv:h5xL5RgHfpuqDs08XDND8z82D862bunPY/fKApZR6lg=,tag:6OpQQl6mGHBZQ+nD01cH4w==,type:str]
            username: ENC[AES256_GCM,data:MM2pBjDHQg==,iv:C+lxJU0TTEMWEwa6+9xAER7vqOLnd1hgL8ffSJtv68U=,tag:fX/xsr3A7PxxvQrRzEuwBw==,type:str]
            password: ENC[AES256_GCM,data:BTnp+CeLkZ7hDr0=,iv:GG8Obycc5mh0g/xVPjPSh7mN5aHsh5qg3GtaJxxNZ0c=,tag:IzBdPt+DdRMUArEiT63p9A==,type:str]
app:
    domain:
        frontend: ENC[AES256_GCM,data:03hyAwAUHLIXo9wKOTWvV19hsE3kfdzzdGb3Rsgm,iv:TEGS5REXcG4KM9j3/zBNyaSaugbNI4ivhEC3hWqse1o=,tag:Lj7kRnp9SIFsdBJR4iDWLQ==,type:str]
        cookie: ENC[AES256_GCM,data:w+IKcQcgv/qqW4H80Ljm7A==,iv:ZqTHpi3fBSPnAF8wFgq1jhL6JkyCREX3bp4mQmO2ddQ=,tag:yk4BvkxVO9ZdPm4SIVNuXQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:QDL5MAeDc7kHO8d7KTeKaKLqva/I8U9G6c8/3aPB1qKSdOFE8Yx82afU/2huJzZ38BBrb/XM+doJ,iv:O6rovIP2XHABNwZvmlJMolY1JNlhrTVaDertCfjxi8Q=,tag:H3968j6S1aYKrzmgObEcsA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:2Yqm3yDRGFeqJ68CbipIDoypVILQWVkU+yVdy2J0seuRIXDB3fwJDaroVwtrqDjbHSvjMukSkHjw2Q==,iv:LiQonUuORDthe9ciPW6YYq+mbYeElwf/WVPYcEVbDWA=,tag:hkmNqMLW/tJe1EPFYbB1Mg==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:QsbwZ9nwjmDcBw5VvmOZlEKjHAtUZGtHoN1RZWrOQuIy6ah7LR+7WBmA/NKLW/1toIyusj3+14IZ,iv:USXDYuCesNl3UuNJYDNQ7x9oWJ2t/EdKm1b7A5fw050=,tag:fEj++NPrZ2yTYSQQ6kkkKA==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:nnb2QdYxj7M4ql5CeqHg7HDQtJCyxVynJLU=,iv:2Vu/q/2juI3GAeN5JBSvozXYw4zhkdKq9unfXic/kJ4=,tag:UMkYdvNNIG0SX2w51yyniw==,type:str]
opensearch:
    host: ENC[AES256_GCM,data:z9HJLBV3gzSCRJXT1aI4hCelXdg86vXNeDHA0qPGZtYN,iv:om4QMkCksmpVqq7ZoyYH3UzrbvqeKABtwzM26LRMF9M=,tag:WDX/pGADPOZbv+r0oFk/uQ==,type:str]
    port: 9200
    username: ENC[AES256_GCM,data:cR6zY3Q=,iv:eEoYkQRdWnBP+Q+z6qXTi28hRyDr2Cta0Ic3N/2AqCA=,tag:XBaX8Zx0VXjn7swFXoFMUA==,type:str]
    password: ENC[AES256_GCM,data:uy0QDntC0iVYwlE=,iv:Z8D56hiS7f1Xc0J4qUw9uQZPKJl3mErfagM37Jmeq60=,tag:Rdkb/s3ZTGS8uBfdGZWmTg==,type:str]
    truststore:
        path: /certs/truststore.jks
        password: ENC[AES256_GCM,data:VwMOoZ5aZQBCVCyjem7MAtjzW/Cj3Q==,iv:b25VzlBpPLQYBP9oiD+UondmzFOTujVP4oEmz8jc914=,tag:CJSfL4Aak/5e77yGMRvStQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-08T11:39:24Z"
    mac: ENC[AES256_GCM,data:RtjmAm203n0alU5FAPohxnZezRMDztFDryCwYe8nQaN1T1Yyteco+3J20xn+r/CuXjl8coX8VKV6h+01locHe0vKBGmmSUnF4UFRF4v7zF4YAs2i3D+aEeQ92XAqzINwrXNAzI/qzAg233E3zyoyeT6mU+aFJkTJD5MJQCN3w4A=,iv:RcduY49a1vlKdQue2jokPnWW864V+opIj7k/8CYbKvU=,tag:iXNPRppBjVpTcEFCOzM8wA==,type:str]
    pgp:
        - created_at: "2026-01-08T11:39:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA5c2sN/iiSYpepnc/fTJ0nNk5EkA9O0UXqKDTvZdK065f
            ZcdVrutmem+LT4YmoBXZcqcgTteq8B6/Xa8lW/4kcpCYAzPjXChzzEq/7Lzv/wbK
            sZSArZO6YF+hh546LDvVRNG39wR//LvKmVRDxK+wmj9BWpoE2IKTmCyx6uFL/7dZ
            aeosHrBrSmQ82TnaOLiHdUT6FywqxkQCWR4X6lm5EjzXtaqtBHRFIMj6rwxcZHvk
            uPcSpBnI7nqdbTf8TOF2S1TVwm0CaKQHI77S1yT1HhR9P/yqsV8l76z3Bc2/kg47
            L8GQ260rYY8dlJ8XrrglWTtEQm2EHpYFzxIYZT+BxKEMI4wcW4vLh27t+FxAkJ3w
            d8IBlS9T/0Ma+S2gqIpVw/rAvbuS893i7PLICUiU/SZLpj+6JF7PiunVAJ1etIbj
            SgDKM9hoZoJ+Gn1qHY9JXgdKmWtqWBtz/dRf7WS2MBr4DPHpfUDIzlJoc1oZgEyD
            rracqAQpuM0DFv4cTGLTpKMzoLj8SW8ixt4zxJhxkFgqXop26NzotkHo9Pc0Fclz
            4Tb4NYvPvYwjydz7C6HbjDSZrUZvbM8M3JtsqVdcPbFCbICUfah4GJnCMAOmIybF
            irPstlBd0XVdbkfhURbkXom+Trc/KJmG4k9FE49S5v9MqzhQqpCYGXF2z4mZ3JnS
            XgFD+4oj977Blzqx+RfGhBhgS0z+EPf1B/eVOlG7noEt4qBrJjZWpTPeGB8sYZLX
            z3RHTxEBWTBHc415yYgHecyTiaL9nW7HnkveXxQCDjeYQLGTYFO8GVw41BEaZ/E=
            =PGv1
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain|master|node).*)$
    version: 3.9.3
