server:
    ssl:
        enabled: false
        key-store: ENC[AES256_GCM,data:iAxr4y/MG3X69o8S9cvRuJprKQ==,iv:2YbPqDx+CywuhQl0pB8TlnKscpB+qyeu+i+G2LkzEZA=,tag:I1MvpZ/wXLi89rfN+kBV0g==,type:str]
        key-store-password: ENC[AES256_GCM,data:5KNPf2QZBRStYsM=,iv:4JBJ6ZSeNFeQ+6zg4Wo0y+Wmwn0cVePfo3gpGhgrfhM=,tag:UQ3qb2HVfG04w5y3aF8TxA==,type:str]
        key-store-type: ENC[AES256_GCM,data:B4xA9cTw,iv:GQ15hZ2Yn5oLPuNWT1E7dJfXKD9wfjqsNwRe2vzA/oA=,tag:urK5xvxMG7dBBM4TjbaeoA==,type:str]
        key-alias: ENC[AES256_GCM,data:3+ytnDFAv+y18Q==,iv:J0kpHYpahP4nsLBh45YBKyMn34b8XwTxNOHeASfPpcc=,tag:MgZTCipXaeKrY/v5s8NMaA==,type:str]
    servlet:
        encoding:
            force-response: true
spring:
    application:
        name: Replay

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:x3oRtv9/yRBhW9AM2NxeAYPXzy83bNrhPUfwg+aUIpsSjXlenRpeC7yJjTNg2q4FmkY=,iv:z3MIezoME628H+Wr0TwrPIF8hSKIkIpKSiuIzlRZwcE=,tag:XO0mCnkasErE4e6UQuFS6g==,type:str]
        username: ENC[AES256_GCM,data:oBoZz5XD,iv:ijH3n12dILH5hN7zIuikeR3BPbBw3ubw8FbzJny8PHs=,tag:Ir4fKu+UKCgvNpXpwrtbEg==,type:str]
        password: ENC[AES256_GCM,data:rszAFGoQYLHBiMQ=,iv:y7fszj4gYqkzGKV8/2uunYBDiP0JMOpi7KN6XuzH4qY=,tag:J9NC1jS4Epe8N3b7FQVckQ==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:tGxe9NCr6obJbH5o8xuhy3sRkRcz,iv:D37aV6LkD73ZEPwxAwjCBNQ2HAS22NXsXtFKNuUSCHU=,tag:EDBfZWj6R2TXL+s2MQHy8Q==,type:str]
            password: ENC[AES256_GCM,data:NKh+JVLkO9nV8mg=,iv:JcPuuOy69LHlDrHcWvTnmhfNEWyhNStbH4oYIbFyWAk=,tag:Ws5IV2JEl0H1z1Br1JLB7Q==,type:str]
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:hqvRHSo=,iv:YmJwqXCVf3D3PZHQzs+3pCkMh6ElNGCLq9Usv3JP5IU=,tag:jDf4R52faOdfzAUdm2S/Pw==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:FXsD6wEu+VaeL49AmEAmEJNB/BbE,iv:g/9H+ZW1p/VqhhF6k6METN3xGl3IuG5tya1xBIWgDP8=,tag:mJCAal8dsz7W3DW2VQXNSw==,type:str]
        cookie: ENC[AES256_GCM,data:sBL/FTGaVHUW,iv:1geKfnC7RrkXLxFlRvSzbWUnLMTW9FF1oDSZN75r+w8=,tag:2q9ZhHd5ADpwB0Ov5m9mMQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:KhYIVPOKp5uwaiwNkAZ45dF0Bqh47n8cgC6Llobsy92vqv8NcxPpllBawxtqH+J/s+zB/lqE,iv:BSOvnrmNMXLOC5aQxFwpn3d7jh68bVJaJrur9RmRn7E=,tag:0oLXEVZvgL0vHnqmKZx5Hg==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:OCp34nU3B5K6bp5mKJo0wYBkEWofJ87u80QlRSQbMneP6y7P/4o0Bkw3H0n9bT+Z0NnkueGuzA==,iv:jNhfEoCUvwbjOHEdc2T8Tgi5PodOUOCSaF/htmKK4jg=,tag:4qXFfa/V8bSxpin7cr7PbQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:nVFiUPyl9vE5LsnnxS48fDXxn32x8M97jSf5zWYAvG8dYkUeBdnqdwrUEqZr7oxlS3XkHNNH,iv:2MzH3xFnWFhxXwgkMRJJ2bTRa5H8Fox21KnnTkBFkis=,tag:+XRr8010aghp3hh3zcuHqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-29T06:06:22Z"
    mac: ENC[AES256_GCM,data:oXpnygYJ6eAOMVNt+06gOS8mwCUZDTrkWKq830L1xz8UUVRUVkkAMLNaJMjbvfOgI32sqotSBZbdgTu6MXyBpQNn4MSjtCY3CHI51ACjoWeAYCBuL7FUUHfG/O7ypd3yIUiSsekvehPJKNTV3ICukUoJ8OFmAyMr7B5YKavXNNU=,iv:5H6O2jSlxNl0hlDI3aOhk1xRR6lsFyBH3Zn3TI0tZto=,tag:pChBJnl/MADtKv3nCEYW/A==,type:str]
    pgp:
        - created_at: "2025-04-29T06:06:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ//Qf5E1zamM83bLNhS5q1kZ0rqNkkhQUogZXckCZM2Q2dd
            jTUkrNv/vb+H8eTbivsPZATA18ciR3Urpi/v0owb5LW4cjSamfQ9qzcJRzqbcVjJ
            drbWJnjuXT/TpRFNWJdFLSx6GTFp+h7UjUPBDO7XPlWke6SRIr08ahJkZUtsAyuG
            5StFva12iLM9CALpR5xTAS4nnjV3TBhmEhAnwnfvHeF3vkIroVkjte1Q6O/Zn30n
            24N8vLlQM9TYpR3jG5ksjgM7nc0khCyzawZQvIlcMrOFOJKIeGGGbNMkzQImoZuw
            hIK0HI46nf3VY6JD6NThRaQmpYB+XGPFWoftM+bjAmP9fdGpcMboBvolYHICwluT
            RrjmgGxwvLMPUE7ABZP1lrIHx6S4LEVelJzeYbNfwijY2mFS3+y2xl8W0o+Cm1yF
            Tcgz3/9KHaDGdGK85X5M1Aydveu+zVgSQso31irZmgHUSwSrK6T3YFAu7769Bi8n
            +kgFI3RM/Nt4rIqcLm4il0DkzNbhfpCL3PeJzmtehKGYWJ/LYfpBDLl2SJPUpIzE
            eZ7J77SAVYiMBteinly6gb08EJ1GMDIcgVlDDrlzvxBQPOySkgf8wj+hcg8jVcHW
            c085fnZw1ngs4ULjnnOXpXDV+4dnkL4LYPVXBBoT0rl8mLCotVDfWA/PlzRrV/bU
            aAEJAhDheWDPP6YjgC7pd5hdePiFE2mIYd4NsbBYC4lsER9axQotsG6ccvn70dQd
            3zYlT+7KqL7UV+vblFKvo7Qq5M3kYGBvlTv7/YCsmxgKJ3X1YocgYNxcnVrf2q0r
            hTBvcJDyAgYw
            =lRqz
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
