server:
    ssl:
        enabled: false
        key-store: ENC[AES256_GCM,data:KBHmxGaL8BZaEPJkuV2PiyifoA==,iv:zWucENhPyM6WcvUAxG1Mr4902FsiExoKVVswT/8fFl0=,tag:ZMWM+WUaIiVqp2lJtMyZSg==,type:str]
        key-store-password: ENC[AES256_GCM,data:5Cg7V362ANZgAqE=,iv:YjBV2WWq/DvaBWRIXLNMy3YHe8OhibOXo6GdhF3LENI=,tag:VYhKM7jzkjLFM4IwhxmLLA==,type:str]
        key-store-type: ENC[AES256_GCM,data:H4NeeU4W,iv:Jq9rp6Q1QmCVL6nxxVgLmCyxioaLv2pEQl+6kcDqIPY=,tag:ImeG2EZX1znZCGDIl+1fBg==,type:str]
        key-alias: ENC[AES256_GCM,data:EAWLzsr29ugJgA==,iv:jxvpd+GK19TqumqX73jR2XoBSQNyPJ6hXrLIAAtJBGw=,tag:yVVvIf5zltZz5nWcliCG4w==,type:str]
spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/h2
    datasource:
        driver-class-name: org.h2.Driver
        url: ENC[AES256_GCM,data:24SyAQKw4wO2g0oWU8zFdg==,iv:5r3zv/oxQWprHQ/uYsqWI6SJljNBcO65bOI5QbHoBbA=,tag:Y/BbMYpypdjAoGIFc7fZZw==,type:str]
        username: ENC[AES256_GCM,data:WyFdoqQB,iv:eaBqQ5fz7Eg1JiTNez1krx2M5BkDI/onxDCXcaAWuA4=,tag:jGr/mW0zAlpsnLsyfcqGaA==,type:str]
        password: ENC[AES256_GCM,data:M3aukYGcF9EmPls=,iv:WHmpeomwKmJTvEWc2GNoIK08WsAR1lDvbuo45BAEXFY=,tag:dto3XuLAr2RTq9ckYlcJEA==,type:str]
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:LOcXGs6bgoJudNCoqMQrmLJmF57n,iv:DSnxdscViPXCs9hO5jEZUSFmTIWmvxj/JiWF/SKsdHA=,tag:e7gdd9/RuFvbGwzwcR74+Q==,type:str]
            password: ENC[AES256_GCM,data:mMBsQlobBJhNkjk=,iv:C3S640Tbt1VF2NCHh/9iD3vGEFFhu8YneXaqy/0cOIE=,tag:wbFzOs4nPil+IfIHVmUY2w==,type:str]
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:rjD/r6Q=,iv:SXkF9+PedMDrqIyQQroTdAbmaC/V4lQj8UflFvIm3m4=,tag:QZDbh3W+1+Okksw6pZnyLA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:cArMRkZQouD96oBc5XPHDTVDQfRqQl3R8NWDcuZi,iv:R4+feOBPEKz/iHyfqQc5OPorIUk83k5IAo9ho8HGPh8=,tag:U8vmBtvvS+2nKRA3XJusvg==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:8Pt/TI1H1DSjSQatcXkq2SkhsF2Q,iv:PTnr0zw7Sq6ZCF/lF354Fy/qVQqLKTtHLuOfK4Z4Iys=,tag:NLjYTCtgO5ER0bAFuFkjrg==,type:str]
        cookie: ENC[AES256_GCM,data:MHH7KMZYMuuX,iv:AdVdUQIYWpFTYQWIDb8IDV0T49jJLQI7KQGeFVU0/5E=,tag:g1YZiIIBgDMvzmRGPqPBfQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:uRmfvhE7xFV6wERGVbYo/M7Sr4RbgDDtD5ULgNFVkFUL7HcoK/jf8fxj3Ha5qGmvWQ/0WHF9,iv:sFBZuMCmQce8ECYFMZk84vqZ/TjyW4tI2zuY0ekBfIk=,tag:QgekuwyRXSgfvB5kxAd2bw==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:2cGSMHVXpRgBYQjDO6Jrbxm2Z5ZoBv3WcYQxm5IN1t2+fYkRi8zW6z+TasjFmf4eKKAIWYqZxw==,iv:1wc0M7kmldO0Ikff3xmRS3D5lxxqMpCt7W6DPDEjdqU=,tag:2XJUd8Ba9dmp4ZUo3sJFmQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:j3PQvuMcGepHmE0J3D5fEXe4zwM2OL1EoUnPkvKuXdJA4Wugh4HuuaFMcrPXkmC1ktm/3Txs,iv:eeFYEDpf/DYR+nefe2wYf1tvIp5UcYlQTE8Qipq3+fs=,tag:OPLaVOSU+fUD9YhYl+79SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T14:02:23Z"
    mac: ENC[AES256_GCM,data:E3M+DbEn1G5f+9wG1n7lvCgnXUK3WnnbfgLCZrvVs5e1Ce3f64WloScubTO3rgJ+weGHrCLxkOoXqtP8g10ypz+J4i5PZKZcmvMm2T/zM7tWbFFkMnDvJTuSWhcbZRbnDwWe/pYU1Fq7sl4nUpbMSGa90XByWrDxZqICnFakr6Q=,iv:ytlhANv7+RNFqsbVRm7FaXGxG9d1rKCHaWyeRM6XqGo=,tag:iaPfkpcHyKXtDKPQKHkC/g==,type:str]
    pgp:
        - created_at: "2025-05-09T14:02:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAl+DP4ckjlhzIcFnzkDX41nkdVP5ixdQtDH+s0ZCB9f/J
            KLTN/nIskFzlSjgxBYpC91QuqfSFIScAx8aiEJeIT9v0tksGhJ+n+eMr2KAVxiXZ
            RQZUFrhQFHAYhJCe+AuAgakbZB/o22RhAMiiaLLPgqTFO3M7hcFzAdyB0LsnYCx3
            Apde5yznnNMidadfMiySOByQuZ7aOc0fWYjOR9xIF/zgxvctnfqtYWkD4pa38LNY
            7hecgQOeg5/Rd617pppuaJHdl35gMmwZoicjfYQsWza3VjG5sI2gDcAc/rymWAAS
            zcJIEd1E391amegD5skDXi9xAj2KBGzmzEo9WViyDI6KKMl2utKU3fUbKRRuiOuP
            yZfpKN2aSN3oV1LVhSpOtK0cuHsHDDX5oFs6fOrxr9g+hgMV2g3WY6Ul9N5RFfLn
            FooaB6i1j/XFjgJgaPYufg49L0G0sCtqD5MkAy8RaccQ70zDx7Ah5WQvGsDYcvZ0
            vwnon3+nW4Tfcx2+yP82i/CKC5DMOMs7kyzLH7szhkbewiOZIcIp//Kd5+Q6Xrcj
            OSWZWFc6ERj+4wMVkvhJ6VLPJQ68k5SfPT8XlFO488ghqQubiF++XlajGf6smRtw
            QbYe9An2zcJ6cCdYUX5IyrODt/oOaVlrnZkb228SfhCjNQcn654FlXW9P0aPkiLS
            XAGKyme/Z1RC7IZCT/lwd4EWgnoyu/OYIHTdjjuWn8PmUTZdQYEMUWydQnKA25tk
            MfcI3UMszUtlp7FVzZWHVsIBRX/cFoqPwhVycFmpd4vrpD7WSd47yYTLp7bh
            =U6MJ
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
