spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:NS5s7hsBqvSJFMK5hRNVV/XtklEbxCntIHA+Qtl7MVRcjW5pPje/ursoMw==,iv:vYXj3TcSJ4D13A936ofsiIxfzfb0R1FgVXAmIu4M1wg=,tag:/GIdhpPISXGrIyXaA3LQwA==,type:str]
        username: ENC[AES256_GCM,data:RQvmpIAm,iv:T07LYresAdEAks2iNGLMsiJd7IYbXWMJbDMiLdBVRnI=,tag:DR4bbOc1ClrsX09gG7XT+w==,type:str]
        password: ENC[AES256_GCM,data:4L7Nreah5RNPRXU=,iv:nSKiAYEPeB8h0NzytzVPy/9exPQvUtP1ZK2Pdb0gPTs=,tag:hkxAuhAgNkZqNPbyuwBYzQ==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:6SIvCUq2mWazT4NgUpzLkCtCG24=,iv:qsRD6GHFVP9mjr7hA4ExKyjav9eJSCNewZolcl9beME=,tag:oA+I3ZtI9ORi+S7apmQPBw==,type:str]
            password: ENC[AES256_GCM,data:faYcF3VmQHFR+FM=,iv:laPUTFUgVJpTuG2A5CIWUGTFd+eP3T1xVGwP3aMZ6/w=,tag:nUMuU04KUGsfZKeCLRUhdQ==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:xNNlCiI=,iv:J/eOFq+U2JbocGO7TCQW6r4mxmDMoEU8holuWIQ+jIo=,tag:RYt8w01zNmLPD6rvnuD1nQ==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:f6KeMGVkjFNk7vKbzkqgsTe3OcFeZQA+AB2CwQSb,iv:T+Tl8D37wGaknyIykpeA4LwzGL78CmhYDGlx+fcJyg4=,tag:FCbp2tsantmkKTrA7B5z0w==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:IDsKwzw1zi3Hgo7KohIEGXGnTc4EyzDqxW4y2tOM,iv:bthSlsaiS/PYvKW9JFCsxZ6Ru3VF/QqnysbUVSUrup8=,tag:emATLa85GgrI8XEVHe19vw==,type:str]
        cookie: ENC[AES256_GCM,data:JmrozC9nIZeF0fPWBPAjBw==,iv:ZzHPpaFJGiI6BQSFDJY0SwD/kJ/5l8QfsYGb9uOYRkc=,tag:5OCsEBvsqqlVctadUf/3JQ==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:nd/Q5SRMTrLd1g32tWgRMH20Wm/zC3FjazWRu4Z4UeqAbMF7gtl72WQLo6xswLa34v429S4=,iv:OOsrNLJ74jDU5rZvEqv/qYh3fxEGW8VEDBQDJoi2qmg=,tag:L5nHYukYOegIlcWTm5vgVQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:CAOuKhdOBoIT9jU+tR0DB+0zZKeCV9/OicMpI3FdGusVQeEV5Fa0loKKIT26nyh0FrKlsS1W,iv:no3nsRoeyonpUJtgL3BHsPHcCt2Duf/EowQk7d+aW14=,tag:mdrEyIQERQFJynH/0uZGtg==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:0c60/bOHqizV2movZA/UYaD7HCGS900YJfpJ8ixGIhhOt+F2fFnG7sWTJRtS69UXqVCFnzw=,iv:3Z2irz38Ky4K2d+76ze8AgDvwJ6JSuz3ZBYYyYm+ckg=,tag:4IkSVFcRpUEnqwJ53vpTJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T14:01:10Z"
    mac: ENC[AES256_GCM,data:DhRkx2s8VDGCBV4KpzxkHP7qcRTm1pz4V1xi0JPBOKl5WnMR/x/pxGiSXpl2CxZIbNcURYLSr5egBjJ+wBt7jTXsCbCMa8ZzrMhfX2v82nW6Bjk/K8RqVKCuLyBnOAky2s0E5URKZ6mCWroasv2Q0BYvrSJUrBlqiNpls62AkUo=,iv:9ihwvdUt/dtYNeI+aafeRr9K0BoaPg0npXaKuISkxVs=,tag:B52hYZdJwmdElG+pDct+Hg==,type:str]
    pgp:
        - created_at: "2025-05-09T14:01:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/9Ef1qUadqz8Aav6x/xNaIhzsiaK4AgzQWBoHiU+Cfa2Yu
            GfqaC5Dsj43vptbkybCx568fjwtHjGx1yDyZinUd5FY7ev6sbmpgjlT2TpFZ8/kn
            el/QouBXYF/yGjpa8H82RlIQsCm7bIuOHnhadrMut0FfXgXH3+TqvgLmRAB48Cuz
            gxWAwmk319K2XWGscRGtqifCQGh5PW0nQOH5+j47LbDEVau6gYxZBsd9/OjUODaP
            s0y9rcfHyQaL3rkUXbMFYf1eDFclwNuXtI76CVuS/xNSS9eT3aGBLzSrIGSuauBs
            hYBtLECchOW3mV5knCLO1JhXcmKKuFUi0+LDdTJhdhlm6qCcBSrHuc/eewfnXC55
            Kz5W6NqnadmF31jNjzwcFmFkAXbL0RrJk0+ua4L3H/AdhwXxfpZH/gTHgpItlw1g
            cRQAO/aSMWaklVIDacSVnE3MEaWIkmCsMXofsUfCByWCT0PIzFjAGp5pzJUoRXM2
            aYf9ca0G0FHVGE9fSut+QF5h80fq4JrMZmvsYkwhqizVDv1hcuchC3ZZeDzT3Kk9
            FeruKUym9BDEgh8k3FWRkraOMNm7okm2UABi7lY+e5peQcsc8uWm+y/jdiRzHZ9Y
            uhNYinpAJNkqMM0HwKKI4fOCjkrVMFWmFmBHDjYyk/kRS6P/aQwgsqD0ekYQ1vDS
            XgHoCktasU5QIs/Knrln4LnBUefCIAnTDVL7VharxflyWqyqVmLepzd2T4+45kJO
            EbIgmOoxEgfE6OxjYvTonjWCcPrkk2w1fifPTSaRvWbA0lT6rpoePxfzWCA875U=
            =Hdt5
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
