spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:H0NPmXn2YjVT530/3J6YU+YcCabSMlQ+UdP4A2GNEKj8RLkZCg==,iv:BVN0OH5kOMZMuK5fX0XzBWDkEAD81LxbB3WXc+tOCfY=,tag:IN4HGi0J5pEpQInorZGTbg==,type:str]
        username: ENC[AES256_GCM,data:xt5gj697,iv:qXHkW0mc9hKbHlAkIDRASz/hzGUjA8Q5xx16Pud8BsM=,tag:PgJz2TmBSaoPq1KRgFnCPQ==,type:str]
        password: ENC[AES256_GCM,data:Z4TQ1V4Fce7Rn50=,iv:ovjNVeU0BuHKyBnu0rwTbT05yorIFcrTct05VAYFmBY=,tag:Ns/X2hPl9avdcklH7WVXoQ==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:eKPd37c+MHdutx5yZwKCvnlC2oU=,iv:PAu63mIQ9YcwlI/SrtRmjdolobKmwdqkCFOo2d0OTYg=,tag:e2OlRhi38/37NHyTIUUJlQ==,type:str]
            password: ENC[AES256_GCM,data:Qs6WuJpO5F/zGTo=,iv:TlE0GskxW/dJ0R+hCKGQpepenXmLI3ZjEQ8PxBRhADM=,tag:hhz/6VZL+xGYa4lZV+/gCQ==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:ndmL37U=,iv:rB6qbmdFasN+fgNoHLZve/448QSbdRmtarfXuR8XuIA=,tag:IgPf1/WKUA51ZSH/EsW9pg==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:uIk0s/H6pPz7zLvAUjaLn5SF95BPN7/FNsJZYRMc,iv:yWiPeeutDP0rF8FDSxKExQMEbXLqr7Czb2aeghaYB60=,tag:OjkDOUPOx2Y4DlJjRzc8tA==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:qAUWuCku8Wpl5noqh7gnVGvZsJIXfCtForTI+iIA,iv:c9VLv7ut9YUpw8PXwufVOjT1qxNO3dIJyb4TPEYq1Tw=,tag:y+7DMBYW4h6RwCF6YyJwvA==,type:str]
        cookie: ENC[AES256_GCM,data:QicAmvt5IIwcvZxY1EJtzA==,iv:klEWtTJzA7L0QmqRe1eQQnBBjTJTRwnmznq/mB7OFvY=,tag:B4Di1H3jO8B2IRMxE5dMXw==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:KlOPYWG9Cg/H2csMLscOkIhJVP1zAK8oW8cm93KHoi68L0RgU3N7qDfa99oSINHRvnqRA8o=,iv:7BeKHM0CaAE+dR1JTE50c7Mxfhjems1Ycr5urI7aMUc=,tag:1WqsgD+oiOcxlIRiRaKSGw==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:ZthlZtOS5dN4Tyj3Z1L2f/wGwFDvH3GpR3ZTw0TMGyistK9HtD4zCn2OghVK+FCKcuyb0z8C,iv:D5dwNx/yr2t83m6Urojdyk9HBgIXHk9qeH5Lu0Cusvk=,tag:wfXlZ+2bGbDo61VM/byQQA==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:C5nLEBmIq++pNXHg2+r0bzenh0KJrO4TO8G6STrhbJSh3Nv4zD94uwW4KSd+F75ekSa0zMQ=,iv:ujNWPqt5v/u79d3MbhM+D0NbH4u7o8I2C+prufZ/PGs=,tag:KtjBNcL1Lv6//n1nKs8/qQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:gjU8C9Kq/Hr9mmSLqHu0XXjDLEEBceJ5ofMtRJJ5+GqL,iv:Y9yT6rXWx32Y4PgfBieKn1hEbtDAXpjZ9E3jW1umq0Y=,tag:qI/c7bTOytOaO51KIIJlmA==,type:str]
    access-key: ENC[AES256_GCM,data:UhysrkNHvsm2pkNIeL+E1Nll84w=,iv:LZ79pAwe8EqJwbzsSgD6CmVb+OyL8mvXOvakR16tGuM=,tag:vxNBLySM2BB2ovCVXtvIOw==,type:str]
    secret-key: ENC[AES256_GCM,data:kn6KNK8iN6o8BoycorXhoFXXCyOaM4EOaFgPNWH61UW2Zru0u4pvYw==,iv:lUAtYUQU123M4l9jdExy3UkGxs6BPwl49TGJWOS+4Qg=,tag:HsM3dc6ynORtpXywcIhwng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-30T11:14:48Z"
    mac: ENC[AES256_GCM,data:tfm2q2SWsNHD4EDHVFhRjGsiiin7Ft/rM7GBg3X2ZtU+VkkpVBeelEFW8dg+E/Kjtbt/qN1x1s5gyu5TwEkMPxAQRWZGdtVJp5eXUBBFEgGgGyguONLm0rhXePvWVhIliDd2WOyAWp+Sq0O7pnnC995c50qg1hRR26ziooFDhhM=,iv:/z6C8OK05KVIRi3GaFIXeRrBuQ2MOosqIOYVKWjtS+M=,tag:+irTdV3XcasL1IYxTpUemA==,type:str]
    pgp:
        - created_at: "2025-04-30T11:14:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAoF2WMnKA8T4bLjnY0WAPDALlL7mHTKZzRG8RJelfXRbh
            hvprk74bcYudHkZLXQI0dCUoSzxwWH9xeQIMMBzD4Rc35YsiaY6EyeWsJFSaj738
            lQp6jh3eWEQ/ZYMYv+TrziPhn+UGWENPelqzleDeYCQC96xWhu++0y6L9YDakDaw
            TkOP39xhK68DtXPgDhhsDnTMLm2807LoJMaq81+6HM6EXNsLid2SSQ8QOdwa/TBV
            2XOhNhrkNNTwtFoFb8V+Yr8TLfxeb51XXcDuoC6vPnyTQ7cMVOZ7XDiZnlqfDpPp
            CdbkKf3D3fqC+FwG/j4e3VEuGn5yjaM1bs/VId0+d+eVVJtIdNi4PsIPkl1kucCL
            6hSEr0wSBodFKlubR95CgaP50q1oz2ZV9sAc1r5gYtJswu0HazCfGDmoPH2h5Esn
            wXiyr9JNgRb0CoYl/k0wb6yFTlS946borru2/f/A5B9sFBUZXOW5Q0Pk7hd/r+zh
            ZRrw3uaTlG4XOSc/c9vfq/Cog+71vD9gk7KMdE2UIPm+xHA5cWZjG7nWEYxZN3Ym
            J34cGdo2/qd1WRd4PI29wP26B4AnbaqOYlrCJ6TNo3rXNEbUSmdz/pFTa/jQ6X+A
            aKfJ15bES5R9ngB0mRUPbru25Jl2qT0KbnoTCBkxB3p81ZfcarToVRoa5xoAcbzS
            XgFglUvuK3vi9qfP2wL2bEoM+7n2S20+OkunLcY2PLEQk8YwIYsZOktQfHXnz3k1
            jtbEYhbpKFcRlpl1Gp5bsnrrWW/w6fzk0TvDzpeR7tCtFjm+ft7RXHVMzn1C8Lc=
            =/6ef
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
