spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:EIHjiz6dWBcCVbEEYgqAEhYhgykasINZV7uCvcAiA4YP4nUFRB3p+K1lfQ==,iv:Evs8FGT92wsZ693X3AvQPYq1VnvgvqQZXeAg13k+ThE=,tag:Iq2ei8jYIuuLhLF1ZMxhHw==,type:str]
        username: ENC[AES256_GCM,data:5NhAoNo1,iv:Y1wyX3bC+V9zRrt8E6ZDoUWswYUdOsaAE1j1+4/bVEg=,tag:/d2j449e4feMexG0HMHQYQ==,type:str]
        password: ENC[AES256_GCM,data:0uysUvbzlJLSQwg=,iv:2A/Rwq2JNVNZJ+yhR2QQEsLxp/7wU+vZ/HN+SspalAs=,tag:VpXukFeYzx1Qj3WOz4urIA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:N6pgaNcVkzz5ewe8/nOYbod/BPE=,iv:WnVfEKuZeeyJ1TgkxGk9j+/A62/GuK20I1CWe+li5Zk=,tag:Xbzb+tr+EpvzJFf7jppnFQ==,type:str]
            password: ENC[AES256_GCM,data:/JFJcTb/T7rTK4Q=,iv:i+O3kIna7PmZItxkYvXzTYeuVJ4YeL7jJbk+9JuyJ2s=,tag:etzurMUwWIRAEhSK8HVR0g==,type:str]
    flyway:
        locations: classpath:db/migration/postgresql
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:ABmtYlM=,iv:9ps2FlKXm15S4j1JFGFkiSKhqBJ2lOk7mUPl0fRBjg4=,tag:SXHfmI+OU9daaec7x8dQnA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:oh3+FsIvVfIpEeje95D1GFWpcmHuSCPlA2+tVyFO,iv:apYFq7KKD18gYte92lq+9H3MXeuMNWxUznscOIvipGY=,tag:m4U3xT3dE6slO2yGkdRI7A==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:gX0SjE58ovQIYMM7i9DpyPbGCPSUWkd6Gga02Bue,iv:NbSylmnAtDTZcsrE+XNGdGs1qPHCwvAoWz1bwsj4tE8=,tag:MzVP32UGLLSK0gmvf6LlhA==,type:str]
        cookie: ENC[AES256_GCM,data:hyQhzMxWnHAzGBtRq4OTsQ==,iv:NRgXX2W8usIPtIeLYlE3tf6B8HVkH4qK01OIIpGTGPw=,tag:iXo1l6BEL6Arwjsg8OlH6Q==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:AKe6qnxPdXKBakyg1pOhgSwRZ+fbxm3ebYBBTbAUS7cJbq2K/J5uPGRBR0u8UcqSkmICJiw=,iv:n6rjtX2F3s96OJcBV7wpoX53onIF6Yj5Pn9iNgvRobQ=,tag:X2J/4ibplglKkeu+yQ5flQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:RuAiM6/vpmbapKu8XdLiIspkYX5Vt/8WoVjtW5oedk3ypjAxiTjroVfN8JITPMrC49oGT6OA,iv:7kWYJBgOEQlSW282OJBAvui7KYnLzX5+k1XHsU62TKI=,tag:P8fC4LGYi5KItefpZp1YCQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:skvcoOH9C7LZKhVu0YgHTHWtL8DPjEy8eY5MiUh6lVL79lzSNRdCpKW02KiojhrNl9KWGck=,iv:bpF1GaPVNCl3xaK8SLKWyEIbeAYAu1rmQN1ZLYgpMSw=,tag:Go3AgzbHXqDbz4GoRYzFTw==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:H+yHXlehYMpUbrCE6iaSpxPefDxhhMQjLXj25KFBEtUc,iv:EIChYbs8tcaFFXc/wMWoKw6P98NR+raUOQb0bzvg5g8=,tag:C7bTNkJdOrNippMhQTHD3Q==,type:str]
    access-key: ENC[AES256_GCM,data:5xf82nWLiwqQ7FCmg4YV/a41alc=,iv:fpbSoILP3SwQr0Wxh+jJo/7XandhT7uu9al98Xcn4C8=,tag:JxttnhugMBhC8mOzh/jDdQ==,type:str]
    secret-key: ENC[AES256_GCM,data:hdDMgaN8UWtVT+zVHaPKksFK/Xx1U86Ptw8WForhawohigWKmZp9CQ==,iv:2wV3EBNcZvICIWeCtgzRO+3ofANXutk2CPLvtDu7wE4=,tag:39jTU6esUS+S/7udcklO/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-09T13:15:34Z"
    mac: ENC[AES256_GCM,data:R0fGcgh5pFIBxSgU0vrCeFCYNs0sEKB5kxvENJ5gE6P6GQtslbFi0qtiwp7z/K08R/8b09Mt/ffOntFU4maOReaPC/OujNyII5H28kX/uPv8CRbSgBj5tVqB3jqLtrrHWBGZJOh/TlA7muePVvCDgyZ+63UErbL23wvQsKBkjR4=,iv:kKneJwx/GqMNrOYjMszKPuFsibsAzN3z3G5K7Ynx8XY=,tag:5UjrNyGCqK6F+YpV4+Wbew==,type:str]
    pgp:
        - created_at: "2025-05-09T13:15:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAx1yBXELMAwVO4L6EG0kUll2Xg3D9ymkfOUPTNyDFJs5z
            CGvQTvHVeGf85sC3hKfYZDnIfY7YRvtuzd1R98A0XTA8kbsyXxywoexylmDVFz+G
            lymuRb/dcKr7KGBw59LQZOza5vHs5+jC91Cjh6IQ5T4nc1HmCR46xunAvuDxZvx6
            xboax5kFqjtD79UCvKzL/9TnBoxrlallPBWpYyEO+jH36I6L8IX5EOljv03GYbqh
            PmPuvrp3f2iuuxyq5z8aZLmhX8Q9sOOt0+5xBGWJiLPYuXK2IhT51W17icgAtKM9
            QOn88YM/6SNCjkIkRy6WrRFAvhNmEAiH5JJkpddg07Pj7lZrpkrtP/9ppHKINCcB
            zZJtR4cpnwx61Ymlyzi7qrnV6mx+/SYpOJQT9nGr7lo2E1i//k4VUxkBMm1Y3XVa
            Khy64errVGb7Yxr9aavrqWE+fzaY/nexE9rIk0PUpedIkUlNKV+aT2kvdv2NRi5c
            QR8+rUJkJXVBdheWSCOzYgHJxfhcNyEH3cmszCu5flmSMPK4UsPe03fcSjcLGZ/k
            uqkBA/5JN8JMMDqEe1BVX0d3cAHmq3X+hHQcRURvdU5bQzW6iskNsWJtmpjacfDq
            RwWqFqVkJm2PzqR79QKSW+x/y1Yk49trNtWP3kKCExIvdaP2jSccjR4Rlg/aPDjS
            XgF9YZ1ULijsSkfR/c4KfQOmarkcE4eX6ObgEWNxHeg7PafbXVwD8RpICJwavLtS
            VIFQzSl7zmdqe48L6II6VbX96C4zMiTxzSRJOpaODjHE2u/ACbMcugmhwl/SarI=
            =s3TK
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
