spring:
    server:
        servlet:
            encoding:
                force-response: true
    flyway:
        locations: classpath:db/migration/postgresql
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:UlJQNCQwVWHnE2rPok5T4qDDUVm3W3nmpEAXv14vrTbqC4vuQL5bFn9UZw==,iv:ufc2/Lb71wvpR8r3b3adCegKZh1rrHGoa60HnPmiIXU=,tag:ol0h3tNruWEpJuw6cQNBmw==,type:str]
        username: ENC[AES256_GCM,data:YPZ/9lTK,iv:2agFPBY3ITB5qHQwk8bJPaQNbs97phO1xsWwCvE1e/8=,tag:MUjiFDSHuZA7WA1lvALOZg==,type:str]
        password: ENC[AES256_GCM,data:A2RTXlFs/OLsYhc=,iv:hEzsKVg/bMBAc6aHWAEIoSOmB/o6GE3oilux1/7f430=,tag:C9ZH4zN0UjUhBJwq73Pu8Q==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:mEhxRsEjDrb7SOSyqutKfztmBAc=,iv:/MN7KMVtlJAkV7wxd3s4KwQ3dCwsX50BqDrUh6n5W+w=,tag:T8s6HM0pYLfzJ7NIGkiZiQ==,type:str]
            password: ENC[AES256_GCM,data:dzUX/HZn2dFnlvo=,iv:+Vq54vM7feNdrGyG7OYpbLbEgRPg2JmxptB7F51O5vU=,tag:o6UWEuJwXwxPG6ZEAjkodQ==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:LV91+qk=,iv:P5STTxlRh5JrNsniOn64RdadIFCED4RxWut9RbO2xh8=,tag:GwPC4oBaKM1HP7Z0P0GIOQ==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:6GZAD7QmcRHgtiZ1q5FceJSRwJ9OyUlb1KShBVpI,iv:4EZ+0xIPLgIzrWD8l+yupPDIg3p7+M7dQzDMIs+nAn0=,tag:Gr2Dp/DwdB1h9oOQmJa60Q==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:kQM/c9pGh/W0CSPmZx1m2TKVfMntZcJffhYCtEC7,iv:mG+nPbWgC/mC+kyljxFXXVWMAchJyZ9kNQPhN9oGInk=,tag:Vur6EWQfl38V1mCOXeVmbg==,type:str]
        cookie: ENC[AES256_GCM,data:2meP95Dh0kSII+VyNkI5nA==,iv:B9ZQLG/DWtQgIU4f+4XcJrlk743sKfk92QVei/ppcn8=,tag:KuPcINVWwuZupFOoWzv/Ow==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:MO+oEea1/cP2kPOfX79x9IdcG6KPPilVIFUzvQhdMhh1QsyRE8k9Wri6yvpi5hOWZTqpijnpQiKC,iv:Jk7K7XXvyml6/H4vHLsqI+Zst38zJVSvJapjQXKKA24=,tag:h3P43vOd8tfTBCA9j14FrA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:NX9pDFGZl7gJKv475Oz6scRA/aExLTt3oGKBq/Nbt8eKbm5rrdZzYKMUna7N5YTDaQx6fLcV8OwPqQ==,iv:w6QzxCymgl1nC1/C9gySZaeVIY7qHbMZ6M3YjPIhhzI=,tag:fK697j84Dmx9rCu6gp9sYw==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:I8mMs7mbE+/F22dPdNIUS8yjSn0IYgcVUkFfvn/6s3XN88/Crf88du6D7dYCgsao4nBO8XvdYMg2,iv:cVafdRmgtgYW/lIkACvGhWvU2tXtRUWLWSMre/laC1E=,tag:gFZI1v0xzjQqgPwv6C1l9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-11T11:37:04Z"
    mac: ENC[AES256_GCM,data:oPYh9M28J+nK0ANkHiHccTOa6shfDQsz51MJgAUGSt26dwyRts0s8EiNMot+qKCqhWrGnln+AKoh7+NdrKbg+s/pgpvHaHn7lIJO8A5Ho8o/2HdRYnTZlg/IlQsqaJEglqaLVF4yFu5RESgGTh+F0DiPCr5OzoWvJAmyWYCp6Ug=,iv:G61sUbGzcGDqc0tc7OJR/YlfafRLbHCp+JhldjkvdfM=,tag:6p0GvdofpQXWzL/S2RS0Sg==,type:str]
    pgp:
        - created_at: "2025-05-11T11:37:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA4ilVwCGRafYFZXki7DBVQAg8ibSGPXJCb3Cy5ORIg+gq
            MJKJ12I9Ml4dzQZouUVQYveQH3mKGoWlka6c+uftq6EYyFpi6qebjadnjFVB5nDZ
            mVvPcWd5dCjPm7mOEiz40gySVPN3f2xWTs3hbYESuXXs3f1B7XiFX1NbitUuIXln
            CBAxrJGJhx3GS9S432RYUnM8705Z3lNCC4mb7Vmp+cAf4qrjWdfZhtp3+5mFEObg
            Dt3x/Kx3VrSXkcBuFu4PJVlhXB9MWgPKks16az2sTTzT3Yipzs7BTt167a3q2JjG
            XdB92VRxHgEsSpzDuLE8dOci8+qZmt1tl/s+P6FgJs6p2meLxQIJonz9R/N4zSf9
            9Q3iaVrz+i2+ofMBaJxZ1CNM9RY4FOYvpg1uaFSmhUQ1unYL9ySfZCkI0CVNoPsW
            hYFKxTBu7BbtmQ4w+F+cARDpBZfhk+KzdpyogmxfBzakHn1zVoo9fykhoNf+CVMo
            TJvqStlOF3kD0F4s7LzNixDCm5xQHXUC2pK/+5s0+ylLtgelMautcn0GUrlvU6zd
            NvZ++OyzKAfZQkSRE08K8g8w5TlCfIcpDhTNhIq9l2MP7hEVFgdfz9bUu2fMQq+S
            d63kyTfS5AA+hCRLtLLnLGgMPR1GOoVLgSWEjUR/FrGYnpXVkMtl0iYJ2LhaKn/S
            XAHaNjXj9gzQFreg7kyVURPQu6jX1xVsfauauNjK7Pv80t0K9KK6k/qEIDcAhGki
            xJknV0aMr5L+DObVqpQtrfoxXHMrhd2/XX3k6DA/EbpeBhm134jkKeT0GeG9
            =6C36
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
