spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:+53U4POg1EAWvfMAMSZhMlhxe6QWM+qAy7T8P2Kl83X76eFNoQ==,iv:dr55goACf/YWSaWhOCRf6+JO5+GA2rKuj0QMzqEvQNw=,tag:E2R0DLGGZCwdrdR76UXLSA==,type:str]
        username: ENC[AES256_GCM,data:2M0lMywv,iv:2I6TP6MOJm0TqIaNL8We8w8EeQYqn6zNtRLBobb76pc=,tag:+V9eyFiwWAoFs18OW29zsQ==,type:str]
        password: ENC[AES256_GCM,data:8cpWIzwzl0N8nLs=,iv:fBCcKVnYwjidkodi5hA3imav5Y+2RdTxIuo9ESUqKmU=,tag:w/FWEQT2T5ffpzPEZlP2xA==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:KzRQXUEJMuGlAd5mqFyH50+uq4E=,iv:+gEI1Ij/8IVga9KqBctqwnqlgYrN3phkds1LoSaQt8k=,tag:O4v+QzeLxbxR2FJydpR9Kg==,type:str]
            password: ENC[AES256_GCM,data:7tMTFKEMRF0fmIc=,iv:rKvt1vtL8ia7Krw4PYlDq0GzCG2AVyvSRftM0w1rLHA=,tag:ORHejoEAGToPz/yIK3gCWA==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:tbX9Q3U=,iv:k0vgpFGoqQyFsF4npVOhD/Qr/348YdhLQs/kzEg9++E=,tag:c64Fte/4jTKt8JZ50qENcA==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
server:
    port: 8080
app:
    domain:
        frontend: ENC[AES256_GCM,data:PkveegfTaf9fvrtw9nBTFkowT2PpB+JUQBye1Wet,iv:LmtEfM1aOSn4dlMSPbcM8FhbbpwRsBnww3qSwi+jpSA=,tag:YxtEqbfpRG9ajgw9fRsUVQ==,type:str]
        cookie: ENC[AES256_GCM,data:dlLDo/WtS+tAZkagrpUKYw==,iv:jNDjXvdnk+YsNr+FD+ZqbdyouTu6JOAi7MtO7O2fUY8=,tag:a3gXnIV0sg5NIZDV3Ohy2g==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:Z37XjMKtxMKzSseNl6geEhgZ+lwOO5CSEwCZJIcQsnv7Ex8tpWIDcTXI9e+oH5f0Sn0TP4s=,iv:PAnzLU3+5tKWbFvkcOiLJr6UFvcD0L0TAuzliBtuPH0=,tag:jnMs5DudkAGojRwY+w3yKQ==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:Igknn+I4zbqAk1L7Cr24Q48BXTgJl+MVkoHgBjxvZ2faEtfpMRLgR4UGpqAX4fSbgLGkzNar,iv:CzvOMJHSGhGHp83BRedJDHLPaQ/zBtCVYLncy/SBFF0=,tag:P3CNeMdiqoZMrxSZ1m5cpQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:hH1qMs2b7DyN8TbRpEDbL3bSBTv7VebUnKw0tLgDT1YVBW2cBr1l/27pprs0DjouWMnZCoA=,iv:rgORRNjKMDsIxcY2v5Af/XxXGsLTxRi0K3e1VmB3CCo=,tag:qCfbNIqMgTAHyBa5urzwOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-28T10:19:00Z"
    mac: ENC[AES256_GCM,data:MAGPQOPGFuH9dRUMA9eGap5QYyM5eG8whlUlCsn7Frycm1A5NapR20K/sWqsdQjsl6NrjW6+b4Tisd+jqXOPZ/pxjLY+lBYueJnC7KmRZAxU3EjVy3RCYcecaAZ3XylftsDWpSHIzCa5zLUGuicfwnqhX9JbUU++ApudruN5Nik=,iv:G9dwhnivSFhMGBqOKqME4p+NfWEVNgrjZGf2u/hvdDY=,tag:eZAYWj+aW2+3tLBvQeghIA==,type:str]
    pgp:
        - created_at: "2025-04-28T10:19:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA0940EXynD4KPrvF4jGEu2okM104QpQC2DBxqFdP44XsX
            6yxeuS1ETSqkf/ba8KuQrtIn+1lx43DlzJJ8cnvq7Anzp+QUq70VZBUg7s1z3LT7
            LOziBBYvVItaC0Kf0Y/qX7J3MMy+zvFX3fUlD2oRbCOQw7GbR2OJ7+ycaOViDqF1
            D9TDziyOCdTcHoHRPN3NZYc7vVecqZrL5dR06edWnMZFnLanMOvHONPDVlo4hvyu
            SpV1lEaiuZND99+4Czf098rz+8LYdg/ry0p6uzPJYbM4RuKVydJ+jlUWkq6T/UIt
            WCOhBeC/cx3SSB/wsjHBUROA5nF0CI3YytCXqM3D1SW/2rJ5Ay7hd1GwPahxxp2/
            0z4U7Kveono0LIsGknt6lrLSvyOkOByp38XQSzNd90MpwB1uOrvm+Y69M/lMPAcC
            srlFk5gTJszaMxmvYKV8zHqBQmZZWGP7Lzfwo4S/A7k3pfqnVyurp6xDHGnaMlZf
            KfXk1TOd4+utug0Z9ZwdKHfDai+YIcowPRKaPkoPeG+2KtMmfF0ePD5sBmTSu++u
            h/G1sXHwKY9yYIjkXV71VKfpiuNORpLnXaKT4yZtnLwmO06QZtEv9do/Qo6BH5q/
            xLgef/Z/cXOeVUhE13ELaATFasZwRamnMuhu6mb9++JNV2Nxj/qKnmPUZMdX1AjS
            XgHXz5TmeZKv5YQf8fulY8dvuByk1Rxba1PcWp6mItMz5QF4z5jvG/drZWC4PKYD
            vXzjkPzm1LzPE08TS9JCo/cYhch8N2+MhtC8dd/OASSqLMbsifU4H2qdRQcboLA=
            =8sCs
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
