spring:
    # 데이터베이스 설정
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:ZRp4WulVczHYqh1+8/QVG7zPFVBqpNDR9u/cxPzHntzfS676U8fMArG59Q==,iv:PqUMy6TzjLH3nVqvilR7eT5LhEZMITImA/wN/B+37v4=,tag:Tzarw0R3KL2/QH7YfEFM2g==,type:str]
        username: ENC[AES256_GCM,data:Pf95xjjp,iv:VGDIuCVkRufbLZrEHRdVa59FR3cXjcGf38EHdoWq7a8=,tag:U9FPJRPe969cJQ5sLTEUsg==,type:str]
        password: ENC[AES256_GCM,data:tf++rsRF1soZRJw=,iv:usA7/z2iMP499T9UFBEvE8ULzeOs2z6VR/H9fyFRsHs=,tag:8uaTvihdnPrNONgfEzBuwQ==,type:str]
    # JPA 설정
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            # 운영환경에서는 꺼야함
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:82GHccaU9SjIhawOk/Mfz8J87Ec=,iv:ZKcdRh4QEAO4E5R0nsgkg4iJM2FcjkW9mtdLUX47Z8g=,tag:dxkTD4oR4Ee8t8tKqLq08g==,type:str]
            password: ENC[AES256_GCM,data:lOyxG7b7URsG+2s=,iv:WiNACOoom6oDxTtQ0Qxv2/0zcL44g3EpM/LHfoUl9pA=,tag:NZso5kKDF9ee33Q1Bwzgzg==,type:str]
# 로깅 설정
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:hYJbI6s=,iv:l5mfy/yA8vCs895UTpbuH3X+mleaw02EHoxfReeVg7A=,tag:7ZZYJjbcih5fnf4hbOqyhg==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
# 액추에이터 설정
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:aLmqLXNtRITveK5JXfMlMNb33SjQse2ZmTQeFyQJ,iv:P9yw61VjCsIPN19lXuvon4JrwdaYVUPHD9hBQtxPTqQ=,tag:uZvXllvmXfqk/qD2rzgwWg==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:0Cn56EGBW7WKvRIj2xJqrSWc9JKDB0gB74jc6yGy,iv:kUPun2iUrEDqd7wsWOK3PrrrIB1M3Ta9ms6S+YnFp94=,tag:y+BZGxLxdxGfouv7ueSuig==,type:str]
        cookie: ENC[AES256_GCM,data:/dpqO71aJamGrOfQjUB7TQ==,iv:V735o21TLqfgvv/d5FwhCUdWf4niClF0+eyXeggnJtQ=,tag:+B20lqCqqQDuzhOeh1UJag==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:9LQd0+QVRElT/jV3QBI8p8MDijCDRd6nOOdVBAc52cPL8YA54+EhT5Tdl3rR0HeZgtNVeStONhda,iv:tbMc+D+ZfkGHEvsS3QCi/fBU1lAK0QkkfEXnaX2lh3c=,tag:G749N6YLtyshh26XjpoYyg==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:QTzG3aNhAv4DFCC6HBLp5bTApipZL/i7iUmU5c1uQle4wXFG313bT0olHQBaXRA+W3LPixBzDC7t+w==,iv:NE7W3B9u4+3uxmVsnoMHry5iIx0qi8z4beL2ckp9lcA=,tag:JEZzryrJLcxz/o4Aw76Ztg==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:ZSmhZkc0j1/QCHmzNAX0+6M3EoMXbeclcS/Qg6whSGQ2EzFdnsCmeCfud4/9LSHwRnV8slZYfhHU,iv:Zsw031mHu3qdaC7d+KJO8Rur2ZSkYOaQPTJF2nw+t3A=,tag:5k70HW5wXxLyk/PTzBJdAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T12:28:35Z"
    mac: ENC[AES256_GCM,data:3v2W5dA6h24PmUSogekBcXfaV2th4lOQZ7lFBvDbqJLdIT4hgiVU89Ux++Kb3tZIbwwtU+ALWXUoTbLVGKrVbeyqLbGsosSCvqiB+S4CJrFpKdsITXyMvzjOfP4FVPuurLbLbd4aOhLRCuO64Aa2kPrcRnpcwLleRgSBIOhpCiA=,iv:+EpZw9FVMp08/pk9DkP+7R4O/2lmbOMI8ZO44vEf4X8=,tag:7ruBrSz2Ot5X9gLJ5vwh1g==,type:str]
    pgp:
        - created_at: "2025-05-18T12:28:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAArITQH3Lp8ZTo2EIsV3KMwlXNHrmsbahPMuEWwJ/qMOmm
            r2qlbQ7B6jYVyw0w9jVLXSxGewFxMz30Hd/K1IlblAq+AaumGnWfooWIhmRXrv34
            KwxgHNeqFWpSBUb8SBrTV3xC6nh//hEkSajjfSD43pIdze0hN6RLiDPjIYdn9bMR
            pX1fQcmdQk97fReQCVD7ZDJgEmPEEQ0zvdzZ1pkhXoOmW8ovqD1j4ZkQ1CFZI6OW
            rS719vNl8hiThan5I+X2XPRd0lHJ1UJH5tji2iatGVkJ3CnpyuIn8ICDPGrfTB6M
            GSTk/xFJgfMs2A5PF65qZmkHSKe0iddjOj96kWKyyT8vyNrYG0r26XwsmrIzSVJk
            3lBbCe4x2PrFaQpua+I+YNZOz+VHNl6sGfi/v1o0BQ0pDnHSbnoeRIW9ESpddZjv
            xdNG0vFQounfQSa6mkT9Rwn4H45hNK0YPIChmu/Q9fdv8UFzL87xFaJx41CDPp++
            iBIy+ZBHEu1ujwIua/2srU94nBWdbr7Ab3BFyW+Cc06QKCNF1Yq4v+Y3e6lpx0KM
            Qhj+09Jb8fXAsSKoln/1M8oH4nAZxY55Ks6L7LxztC41b/lIv5Lj3UBP4hG9kQyR
            KHyyzRqWK+A+n2PZQ0woebeibgsW214h5ayq6iPo65vwdqWznwhiCLlwqFBCndbS
            XAH9VxDJHdeibauCDupyJzydfbBd5cI2Fsi9Os/mupLfBEouzWEA9VZzjOZZk8AK
            t/MQeM87/9lgdHuqF7HjIo0yAL504ubGh1EFWINiJHw2oVqkK9fR8LwdoXzG
            =Cuxv
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
