server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:PanVtjAtcYM477pVmF2K+80V0Q==,iv:VMSDCgbuBUmD5c6yNeRXWVfvnwKus9NfEWyhEJpc71Q=,tag:iGuv8YcdgAW4zYaZBACjLA==,type:str]
        key-store-password: ENC[AES256_GCM,data:xMVQM6u3RqjY/Dg=,iv:M6e0lwDfEGu/pNd7bVIju/U3l+Ib893tw5svZKn3vbI=,tag:7R5d01G1iQBvZMXRHOEl8g==,type:str]
        key-store-type: ENC[AES256_GCM,data:EQZb/B34,iv:9udALShe3tzumsDgHeIED6QI1ud6Od32ibnt4ZR7NVc=,tag:bwryb+G+6rps5exwAhe/OQ==,type:str]
        key-alias: ENC[AES256_GCM,data:2OuuBI+bJGAabg==,iv:Kz3OjazRqQBGzNXppf4lBQRR2IV166w+G835WUyc/2I=,tag:zh4d4eiJhB2YMAGz2IksaA==,type:str]
spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    datasource:
        driver-class-name: org.h2.Driver
        url: ENC[AES256_GCM,data:vIYbVZm6Hf3GfutD5gQeRbpN6oQ3ytRUYcK3,iv:j102pp22wPctUsZ60YWtnsZL/9sFf9m636T5g4QOT9g=,tag:TE0rI3jMwXswqzEh541Vmg==,type:str]
        username: ENC[AES256_GCM,data:D5SrcN3c,iv:meRaap5HTrDB+BLndZY5JAuCg3pjNuhRoko7LNhl9Hc=,tag:dKnzWOhLXUB8G2FeguosLA==,type:str]
        password: ENC[AES256_GCM,data:oneKmhMp5RYYjBw=,iv:TS97XZhFIREU6PCI86eurFgO+SAwwzWlnM0frXrzyfw=,tag:eb1R/fE5VnYheLymdIcf4w==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:V87KkMdRr24UxdbIqh0RGRpTxieH,iv:kzi/DbjKFtGRdctJEAoclEMx+98VYTaZL7KFY9Oc5Uo=,tag:WK8XuqxwAR/Qs9UV1eXiWw==,type:str]
            password: ENC[AES256_GCM,data:FRzeQWqp4q3oG6w=,iv:AQ95FojxMVWFIBl4vPRmM68ldOwob0ZIsPAdGvuCdJw=,tag:3X0d3Mv//NXpcgrQGkH24g==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:CnlwJ3U=,iv:68/VJHxVrZMpwYEiXrE8Y9YfNCDsy0f7/nxR3SvULP4=,tag:aV1Yq67sJvyBPqhCadv4tg==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: ENC[AES256_GCM,data:FgeCkrRpa6aeaOAyy2ZbPUEzwuIIrAgRZoXEgdSA,iv:CmoNQUl75ZXpaTGOB0lNPQZBbMkYMYbUwep5UfLvbH0=,tag:X+uzjo9dCHpEsCZCb4deVg==,type:str]
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:oS89V3OE/ZSjB2M9X+07fK4A5aIp,iv:oc7ji3i2xCPtVti3UANREiIhsU8fmrduXnFYGO1oR94=,tag:kEeSkDx8edNR2i7cmxbAwg==,type:str]
        cookie: ENC[AES256_GCM,data:zpAqrEOwVV4d,iv:4QhleRJg44SD0voHFMm2/a5CFz1XTrOL4lELWaqMkJM=,tag:PlVY+Hl4m+NoRBJ6RmhT7w==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:iC2B0YKodFXqCEsxtvnqXobmqJkO53IitlZKvuItDacBq4LpWxvCYN1YSfCeicGJm272KdjJ,iv:wdFiULP/VPijCJpMWPDFuLJBt0/eM3LE0BsdrJGg/us=,tag:vyDryN9FVYo5QWa1uOGotA==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:nMetnYUdzyCWrz5jzJj+7V4RI2r4tuj3DQFj/573R8jooa1hLwg4Gbis83cIKr9cBzn4yJRr1w==,iv:CTv3I3OH/LrZUtNSexa/IvRQTm7sP9S30JpWnr9gYYo=,tag:TMXeOK4xKixH4AQTigmQ9Q==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:5TPAhGS/R+GzNGaYu5blWeJAhYFylrf8L7O/UNxSPC8f9zs1IK57evLIlcrx3NMvS0DXF44x,iv:TkqeqlD5VcKJ2NRaxm1OK29IaWd6jAsgAwN4eGHVZuI=,tag:lxv34tJ5pWOOVerXCFlvAQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:qjeFDLD++89vX9vnlAdEkceVcjcF3egZGvvnJFxgS3T5,iv:FKKax88rCTDOSrprElPvjW2FO2XqJqUOSCx0eEk3TZI=,tag:JdQeZFXmoqR+4bJvSeZPWA==,type:str]
    access-key: ENC[AES256_GCM,data:QLQwo5GPhSdVtVvTU1d6PSH7vDM=,iv:NJKlETuZ41lJs+WFLs9MPjWRHKlsM73RzIfvm13I0eY=,tag:dYIDPNCUQkkJikGN6BEzgw==,type:str]
    secret-key: ENC[AES256_GCM,data:GwlGskfSwUJGMG+ShqvQlT2ppThfSqdDheKxBIQxnK6o1QsfY4OLWQ==,iv:DHH2ioDxamUtK29COFT9UVFqyGScF6H5B9soG3BMCa0=,tag:qhwu8wRD8Rynzz2tPZ1R6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-30T10:43:29Z"
    mac: ENC[AES256_GCM,data:MwQcgt2ply8Zdt33lJy21P4FMPI6Y1xxLnWMgDJljrzLlmjE287dfQLSy8IJ2CIAdL+j9vCNb542szv+USrQADLC3Ow1HfPNL+eacH99FGomHli502XWQiDffsdTms1M2euebw8ZIpoT64jBbGDcTE/62qX54Ygp5VJOSrz2eII=,iv:aXaA3lxsx4j+bVpA8K1tp6dEONWipcAhp+CQlEGrLHM=,tag:e8J9GmADEw4yBSkXJwrbpA==,type:str]
    pgp:
        - created_at: "2025-04-30T10:43:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+LMHmKf4oXLZyZYSilD+tuu0Ie0+mBXzLymAXc4IDCQzZ
            otO4LPpJuM6dd9y+TPpyBiChWs/LRsmOcsayPOIHyUKOYMELBUe8noZks1bykbie
            tJkOfsA1FAEViRfCTf+gA8EXf9qCGWXn5zFueU6KnO1qo18oDjEH/Msy8aJMVEla
            psTBqSWZHsU5NvSXRniMoQNFU4R6ZpzZq+52qeLHDthJCYxDcPXmlKvVzh9IMvdG
            W8eQh/Al3QQfStzdPOEOZ0w1XDp1lwTDhbmOFlCcH7ZzstbQeMhcSus/v106VtMU
            YEKRxx1rVhM8TeBLIIgqCUwmNsz1/fmUF1cqy5mpVRQzjMI+pgkEZ8jdnfNOjGRv
            HGU+NhHgA4z3mtAg2LOMMTdvSXfz+thkK+OUW6vYaag+4MYSWE03pkmhTYJMGBnt
            YLZ8ia7+BBUf1enCIEqNauvo9P7gvTIR6KUvOEt8Qi7rZ/4G0qIdf1jPpEf+V+ds
            OmVq/bIiFKXBsFlttUJznhM8VR88ZDAzvMllg1iWphvUdNz2sOkAAZaWi8/d2V+t
            +VMYMeiEw89Wc2Ijsdgrd+RSegfKG26sGpVuDhCERUGJXzgJ+FmGy0LeQWcIZLI5
            esprStWTLBToOluGqcbbxpNdmCPHf43YxQoD6uXctS1toIf12JCtbOa247GTUUXS
            XgF3fzR1sIxvNgCZS8mQrk0ei1mEPD/kKoDiIZ0A2Gw3wJUzi9kMbg36tZ81b8pl
            NTnyNHzRbUeq3XA96nUN4YG3HaHhNdbpOMVl0JZfzzLUw6ArXLYwpUUchlGDzM8=
            =Epe7
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
