server:
    ssl:
        enabled: true
        key-store-type: ENC[AES256_GCM,data:SC2D9lvd,iv:0P92TEaVZHuKCRgmrSlYULUnAls47k//M+PpoXK2AEk=,tag:gFHLqQ/lWM3EmLv0oKUqcw==,type:str]
    port: 8443
spring:
    application:
        name: Replay
    profiles:
        active: local
    jackson:
        time-zone: Asia/Seoul
        serialization:
            write-dates-as-timestamps: false
    sql:
        init:
            schema-locations: classpath:sql/schema.sql
            mode: always
    data:
        redis:
            repositories:
                enabled: false
    jpa:
        open-in-view: false
jwt:
    secret: ENC[AES256_GCM,data:m2XcQYnuy4KxDiYTCqnYJ7trsiHfiUYdpnifgzLM4Idbt0U6p0v65cSenu0=,iv:yMoQsxONq6NR0OtcZZEYv0SPDB8FHsE1lLPDRBO7xgM=,tag:ZFukdU+lVZS76mjU9PN8Pg==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:pceI,iv:hwFrwQZTYGdX5Ipo9IEGNQ9rNJtQqtQuWdCwPvPLncY=,tag:BxL1dnHbY9of8kp0gpNbBw==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:kyk=,iv:BfzlLOgJGpVXk+A5rue95jEkdtv11Deir9fyN7dvgZc=,tag:0SY3ZJ6DJBwV6xOQboYIXQ==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:dfSsU89tXkltE9jxRmbvOQMNZgA=,iv:Gg9sam1FdaFyKxZSNuqWrEq/sIlqlwzmuj3qpFzIKqA=,tag:xIWTDDuvvXeed1lVy39ddA==,type:str]
        client-secret: ENC[AES256_GCM,data:FnQ10GO4kyvNCg==,iv:RWqqlucOOTUvcc02+9K9P/2uwoOH9XYcoyHQz7ty58g=,tag:Bd3fKRi1PGh0PcWBukj2og==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:vKN9Cf9P2mEaM7cjG55SCXTNifDmsn+SgLlZf6WnRPiiXQK6h8zufvzdeGnGadeBjXQy3rqqTZHx3YJJRyoW+6iB4kZQY8ar,iv:LYEHbKfCCs2R/tqSGArlPQUn/KYlO7wSh4/+whHXWWA=,tag:QMQwN6AVjM8FbUIdrqSD0A==,type:str]
        client-secret: ENC[AES256_GCM,data:/u6sVr1u6N6tKBsjswy+TGLxUjQhsxzv0jtG5yvRF56Fazg=,iv:myAbC+8Ot9W/mJ0RbfwLObTMnZGIafNNp/eTAXnjFHw=,tag:NWnDxdJ0FD5sYpn26hadQg==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:u2oDvNjei/jcIniqmuE6qmc4DNFFF8J/0rIN8vSx9xA=,iv:KHA9Q9HOvPAXYwewZ2hTIiexjjIUPagOQW4qqHl/B3c=,tag:Z71ouIRskbaEJDT9hSCtJw==,type:str]
        client-secret: ENC[AES256_GCM,data:wUcn3ZgBU6vvgALHzEsCmmjDy2SsR7ngk+QM7ImtwS8=,iv:6FlNzRKb3QebSsi4uiQWl7LfVVVsSSZ6xMyHH4H+eBg=,tag:wBWVnBGn0szodEt46aGyQQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:ensVn4rbjb9SFStamsbEccBXUBRsBXYJdQ6YI4JB2Kyt,iv:u+1GzIWFgdWah9kDFUnWtsZ1j854JhPOa7UkYK4GQFo=,tag:RZnphoX3fZEcZHrsvfGx8A==,type:str]
    bucket: replay
    access-key: ENC[AES256_GCM,data:37prZK0t+DQnTyhxePW4cjj5lok=,iv:K8xmR769txVxX4xrdMQiTgoErsRa1iBzPOAr4JDrt/E=,tag:0reJ5Stul9dBiW1R7EhS7Q==,type:str]
    secret-key: ENC[AES256_GCM,data:eHGQiiAZf8v+riXajBtg4H8VDSt+V8q3UOVHhK/BG+73nCUUXVzhBA==,iv:q2nUuXyDrMhk1V4+C2hYnmWPh67QNSxKFt+vrCjXFvU=,tag:vR4Sr79fmCzKJF4v4riwwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-11T13:53:18Z"
    mac: ENC[AES256_GCM,data:gVASKhB5ASuCgQ9uJnu4NDzkAW5ZtfiPJ+4BizdY0o2I9nZsK++qJjFjWmUe1DRJcT8rGhNqfu1ljkveKEWt3xluQwZgFQhFXL15w1Hrw3vaCCIlO3oVQZ8htRTrtJWaCpeo6VQBv0ZkcPLo4ZDLG6Wxtz0wDJA8c3kkjEIyoxo=,iv:J/15lbbnxfeVwCFgz6l4hSDVIlqcgTkBZdLPmzbsJ0M=,tag:vJCyRSZ4vd9QQHhkeSnAEQ==,type:str]
    pgp:
        - created_at: "2025-12-11T13:53:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAtXCiHBhexjVFi/7oCr/cgIwF5J+I4gFgfXOthnemXC1j
            Z7Ab0OHsvfmfInIXk6koASO3VcpduU6+rv33qmBjemFbth2ctw8xsW72i8QhRaYi
            K9cw2Gne3W4PEczWKBGnKKE9k3MDx2HCuN8bWQ7k2GtA//V87N/hsJFEWSIm8knz
            LIcmOh+7F+zuYmgipJ9zkhY6+AvfzANcOoxddGUFXrEZqrvS1Bi1uZ7K3zGCnpht
            /54Iw3u/Y19hUyu0noslJiM1Ep19SVINEIt8zQ7gXaHRiGmlTn5RrzUTahQszVo9
            5/qHX9WheKM5uAWqlhM3UvQ9wEiQNU7w6t6CMtxnSVUhotxtRMFne5yYs87mm3/k
            835YiEe92OTN2H4218Pjjqo8CiJ1Zj5gplfPXlhAW5VQ9owboHRHWhjT/o12gvPC
            jeQI16kPDkLjdZrPxTdzFvfG5o1zAsD4sm7Enk3thTEyWc/ti6/W/z1ZK9xoDeUc
            5rbLn4RnU1GM9wiCf2UM7Ehcy2bG1k9kCPUYkebM2bDnkBNAfRxjE7O1aC3YImcM
            O1MPudzxInbY1lFgDrQdRLDQc1RwWkDpywB+LGwKOLZ7Ujl8TBA7bk+ounvmSBq6
            arbPQIdc3TcCLjUuEthV7YKOzuo+V+B/SEDHQViaHS6phOWM0SOUnKrz5qXlFU7S
            XgFk41R8wmeso6NzE3kAtjfeMTMwX28Fr9c23NLeOyPtWYI9yX8dtYK8W3mzZdyk
            rbtdAIQZC+JRNWD37dk5t3C7qdYKAixF/keUwtTGeIMpLPaGPadxGFP1thY24oE=
            =oMg7
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain|master|node).*)$
    version: 3.9.3
