server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:umXB7naRNlRerdknWTpok9RO/g==,iv:c6GduQdiEpqGHvkX2LwPV4Sm9qZJKPHxWyfFk2ETjmA=,tag:M0tmX6fNic6Sfn+IH28nkQ==,type:str]
        key-store-password: ENC[AES256_GCM,data:KKVnUnaf1dKnLGI=,iv:knkFZrgND/t31ixkybxEYb6N+QoXB3kfWsntgxQD/Pg=,tag:ntV61ITgMzWYG+8acXb4rQ==,type:str]
        key-store-type: ENC[AES256_GCM,data:0nySjSt+,iv:VBSUADnCiMRhq5uUDxvB44nXjTHNoehkapDf35pYyfc=,tag:VGA9+KH77116IpPwmtQCsw==,type:str]
        key-alias: ENC[AES256_GCM,data:2EvUnwbap3RnqQ==,iv:YVszK1AF9Imnr0THa6lvd63HRVvJvSaBGQZ8EjKA8lk=,tag:lmrwQrbQMDwaouV+TBNZvg==,type:str]
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC[AES256_GCM,data:ScThN95itKhNPVr4Xi6d1TrlYKvMgJhN1o8IwbaPNyW0X7ua2SspyqBs8cmS5dTvavbQzwd/2H8=,iv:9L6o43icRx2vK9oxYkuMZv7qK7X8Tdvyi4Jb15fRKus=,tag:iFiivRZAvpJYqnvzlFdCow==,type:str]
        username: ENC[AES256_GCM,data:vXpfGDq0,iv:ZzxCd0VWBPa3ghTrZ/0KYAXBDlwrWT3x/J5Ze+0gMUI=,tag:diGqj5YlzvScJlF3xh99wA==,type:str]
        password: ENC[AES256_GCM,data:oHZhioiQPzl4joo=,iv:9uzxzDrKLshrKWXBRfft4SYZi5nCoV/zrvz+Q3S2LFo=,tag:RI662z3cHzhmYcovfqECjA==,type:str]
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    data:
        redis:
            host: ENC[AES256_GCM,data:gExAV3XauN7ZKz6keU8wNQoScXhf,iv:yRlqC5HiHlECUMkmHGMH0ViFTXg8+mH/60M4JNOsM20=,tag:mc9H68xwWMuPqnBR5gg8hQ==,type:str]
            password: ENC[AES256_GCM,data:4gUdxB33wJPx8pA=,iv:lnq+L0f3CY2sd+NNPKlEYLXB5wAESNlJXiYm8YtxIA0=,tag:SQJ2pOG1UUiWtau07AMkyw==,type:str]
app:
    domain:
        frontend: ENC[AES256_GCM,data:IkgoZr2uNhBz2OyPGYqo9sDzYQiw,iv:NW7Csh+R5wuL2FsBYi+/EFdflH3DqId4I8DpQP9j/iw=,tag:alx6vRXgFA4vZ7zKD99qbQ==,type:str]
        cookie: ENC[AES256_GCM,data:ZB00xNMoR1vc,iv:HAj3WlZm1SOaWV3DiiwXIqDBKu/0enmumQK9Yivrw2g=,tag:AKzL36wWwuklI1Z3W5dkcg==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:iuGDnfH80FiOfdLROjK9g6JkwmqPiLwWGLlgBHjTuvU9hfLrqNfenqsXvbiTm6YalYjk8DwJZfYzRRM=,iv:FsaBJ8CSBS+j1fNOtuw3vbJ4zzIVAYo6BdJRb7F3uXc=,tag:lFvT8fUFzTbksbNqRypTjg==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:+nZjuVvEEkeRuC7y1KQRzWOpSPOjE025iNc/1hWyLL8JVt86PGg4RinKAJ99kcpCZZUMkq1MJhJuv0D5,iv:icjvskKNrC+SfDX1Gk+0IfCTY5mYhDpSZCqeDkgNnDI=,tag:nd2KDEZqbP4wEYc9U7aB7Q==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:LF1GQn/FWf5bqMEKFsWA/AwntA7FlJpnZU2VmmUtt4C91TZIHaAPoe2UlA3ywVjnG3YHsefFvC1rDNs=,iv:J7BPj25qlXPjHkg/OmAy7vc+xOGO15c0vpr/RMo7z5A=,tag:byZLMRHIh/qNuM7uLQ6zoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-11T14:16:42Z"
    mac: ENC[AES256_GCM,data:GJA17BX0Gjv59vdmlQw6f2RK+ED+5oqGUtqHgxh4L/DQC1lKiDLJ40kEmorRIuXuJKpQOD2K2IpzkwsGcBsyaBPQBSlwF8rhqNBttbPvYsX52P7a1rr0PaGK93StFjooX90HWos8TIwCB3fX01SjBg5rssDc37pTv0tkLeHk4Xs=,iv:VO8EjpeV/El+TD3bhknc9bDYYyg36TCHc4xNSQKUClI=,tag:SokrH4WgLrzAVNwXT4Kizg==,type:str]
    pgp:
        - created_at: "2025-06-11T14:16:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/8CezxC8VLNu3rpia4NHRhkpaP+ikvp6P8IIHj5pjIngey
            LrUJTx9cEsm6iYL0KhE1bf8eFdwiOvwJcDPKP/SQTPfj0+htT9OaLTJM7cXqQ5iG
            tN2LHrtpOjUSYIVKPWa6qfa4EIA4SSldqlxKs6KU2bYrAFneV/3UTgdSbWoRCIoL
            ZDBLCSTyJ837/6jqd/yuQvlpDffAFTDEx0uyjOwaFOgVm9eF0/Dtr3K0IKZ+gygn
            piV87H2o1e6DcJUKotNUBGUQGuRSoUeb1ibnwLxkFWTpRKJ5upJchSujCyEDaeMT
            BskkVRuKQa6KIFvxuE/WzhP20s1/mkMUVr59/hoc1CUPg3WIbnc1B5OPS4Rd8o33
            bk3tWN3eafTq6K/EyK+SB7C/unGjlCFGB0r5trFmC4tc4yScW82ePpkQzQVs2wO8
            dQoLYE6pIEJy8kZc6H3U9xMLsDA3UTYLBjUdTEBertWWI9w13TpBoW4Jo1nYCz5K
            EDUbz5RGVS+t27m+UbJa/bHQ2/xXatpCK8NxOYe20B6C6GRG6vY/jBrMnCc5X6l7
            Clz/dVdSzJGaRtTQwacATBHNC5a/DIeUIDbHfXaVl9hWhOTWKgK/02yjuMnYvtSC
            vCu9QvAZDyXGdZs8Y/G2W/2EpjTZwr7S/KupgqEcfgjgUHtZsr36NEy+hA7LQ5DS
            XgGl/M+m15zUVBpbcg7BqF8VmFmKGUbnrRAda5N62LBqRocTfX66EcNBzNbmn63k
            rOOjgSFseG6bzvTeo8ilNhH/NS0OpU2V6juE32U02uDjyGXFZNqUjjSWTDxT7Wg=
            =jtPM
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
