spring:
    application:
        name: Replay
    profiles:
        active: local
    flyway:
        enabled: true
    jackson:
        serialization:
            write-dates-as-timestamps: false
jwt:
    secret: ENC[AES256_GCM,data:Wtog7SVqn6z7+8JlNpkinWj0cxxmdmF7Gv4uXI/SL9JZ1kr1XBuIv3g0L1g=,iv:K+Yv6DaMiaI4vXCdJK/Z6eZh4192Z09++NV7qRv9vQ8=,tag:dHAvwcKS56ELqmPOXmtgWQ==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:gpXF,iv:CQ4605hvNMDMtgWftNvhWtmtM0iB/TClRprxeTEbL0U=,tag:WbCahxhcHEti9my3a4jH1w==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:ou4=,iv:YXj70+fD6NK7rBdcleYPj64c67nQoUGzPS9TtPt9aN4=,tag:1CaPB5E6NFDjXsb/IyKsHA==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:W8LBzxw7IOIO5HZ3kcyviuGXAXA=,iv:hjGMzinrDjAfL8P3YcLedxd2hOmHnKrGDLf1hZnRpuw=,tag:7tM6kotfFtaq8UDzkA70dQ==,type:str]
        client-secret: ENC[AES256_GCM,data:zMFCUm1C0rVjag==,iv:iXIQt5QWqprsOyh+Xv1/A0581Q2A119M6ciVRu6oeGs=,tag:QCblYXodilFyFPX9Fz9toQ==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:wbR3x0v1mZ5+KpF32I0ZAF86bMvcXeKaMYMowPHkxD2kVrIcHmons6x3F4AIImSewjn0cifK/F93N66ItQ3J1wu0tLcYwWhd,iv:NtF7Nz16AZDA41uL9YjpiY3UVcmIZ8hwgVlYV9IJct4=,tag:LDCJMWUSAsGBhBAxkyEiag==,type:str]
        client-secret: ENC[AES256_GCM,data:wbM8NS13NAewxBkyNTfi3ghDGYpIZqdd7a24gn4mRbc1OTQ=,iv:M/0W0FOqM8cthhKKfrQuMY8tUwwu3+Ha19nVjL6RW1Q=,tag:ZmR6/BIHxVUuhOixbmS/EA==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:jgl63wLU1BvrgPnxD40XXg4bri98IDHsiFxpcDORNIM=,iv:/5QjAOBeFwFRzcEJfDmltmxvXpsaWQY5VmUNxcjPH7M=,tag:IuK0+Y6y/l/a2yuDoDtupg==,type:str]
        client-secret: ENC[AES256_GCM,data:29J/+4gzAD+xWDsStV+gjLv6Hiq7nWXyB0+XsMDmB8o=,iv:NwRf6iKW+E+/W/rz4qpd80zwSe+9Ni8p7noDb8VJqTg=,tag:vQtI16DyVEun2Iv743cnOQ==,type:str]
s3:
    bucket: replay
    endpoint: ENC[AES256_GCM,data:KP0E6JhZoYja+XyZRXqqouUw6kmAVwVOrx922vPS/W8H,iv:w4qKSibY0rBzbUq+zBq289LodlQSznO3wN7XzLosrIg=,tag:knlex4YlR4eRcbM/HrYGxg==,type:str]
    access-key: ENC[AES256_GCM,data:+IyOysxlXRNDZG4UDykM8CyYiBg=,iv:TsPuXuXTl4wvZU7Av8TQy/fMPW7Brei0P68lhKdwoyM=,tag:TedvE4uhRzwh1KKpP15k3g==,type:str]
    secret-key: ENC[AES256_GCM,data:2KPTJ/JUFDBvFuM6pI38WLSHoph3Z4pIx1XxN+lgTRg7tRCtqFXgWA==,iv:HXO5iCpMRc6/Tkbeb7uxih7QbTDo8Pq0aRZ+nFeQan8=,tag:0+Tux9Khp7IPg625ixGwEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-11T12:34:28Z"
    mac: ENC[AES256_GCM,data:OxnN4iF46Klj48aNscE6fePVAJ9bbou3ZTOqwLhDI0j5qD86njtrurhDAUP8soOxH+AvypdanzJFVla4y2u3kEX4udqERWDvmUrI2ClZQrshAqiJ+4gQjL2y5+M1+bpUH1fRuV5TPyEQoa5D8Kls3vt+ANJKcZw8/vjjW00FBUM=,iv:b+Aiuu/ongX4zBFwWT3tR55fxhUdyg84TF4UAauFN7I=,tag:xcW6vT7UVV/FoRjlK5646w==,type:str]
    pgp:
        - created_at: "2025-05-11T12:34:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+IJ+wN4p4XYKaN6hmIjfTcXPkRx4vrkUkm1mmAR0hn2xG
            XZThzu4GW94Mth+LY1rqUnM072SUPsfRuweC7OHCZzwttdhUgaGx4teQrJqdTnR0
            xFZu1u/qbhmDnypq6qLNd1rBNvj56JeXAOZNKT1Je6e4gh+RBeE4wIs8te4ioGcM
            ql8fmP/gS2i3z23BgRV6U/vBvrMjQvIB/HR6w6BXrp11vLRD1hU3Dl5fUqidx8+l
            t/waRRar/8gjH2jlVwAuwMFxGYK817H/VintHEWI/D7+iUpoyU4UshHSbL3E728Y
            EEczcFEJmV6po+LbVbM8deq9K5gmBq6+TbcCbMGRVJZw1ZLKCJ2yJnYWCk3jsv1K
            EvMNXv5j6BcgAaEEWWSXjZOvMUUyNllAW5GkIT7BJfy+fh+jp7MSggVoN2+cL9UF
            J1VQMYRwqbXXkYONK0usr0GhzdFRhQo5rTxcAb6AlH56FFBToNZvLk0X7vbJG33d
            xDgzIs+lFd69Mkft6LGn8Md7RuuYJP9w40zFpo2U/cJIy3iQ6VWQUgAjlhsPAnGK
            gpBgCAtbb59dbpOiHD2IXtKZ0ILKzaS/xVwEeW4dn07XvllUHLprDb2Y4TnT1pqz
            dUvTy+p9qBhZ6MPn3lQ9wnhxckNSvnkoncZbiq72uXKbBLioiNWQAYbvEL1UnxbS
            XgG9jKjsQMjGDq5/F8W6JSw/ON4LYMCUTirJVrPRb9WIdVlPWC7xmtJPDbfgrthI
            351HDTdvMNUpuRL/k3wCV1Hme8TpaqJxVTnLkxYgNxoRUYfskwYQs+1RAety/kA=
            =Im55
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
