server:
    ssl:
        enabled: true
        key-store: ENC[AES256_GCM,data:iO6Ac2h9VgKE9p9yUhOd7oKFMw==,iv:urlc9U5VQuaBLzAAsTN5AOgwuIRmg+lfHu7hX3GCKns=,tag:5P7giEPFzVGOK9bn2EydoQ==,type:str]
        key-store-password: ENC[AES256_GCM,data:65BJVKAPc0Ik0Ek=,iv:Fwspc5/6SMHeqiW45eUf74EotGxCvP0kUXtD4Fr7DMI=,tag:CeWbTQeIRCduq1+dlTYDTA==,type:str]
        key-store-type: ENC[AES256_GCM,data:m13Mrwn2,iv:/HJMIOsWTfj91Ns4kAncatHp/NzfoaroE0sYFAtX1sY=,tag:g95GbBwfV4YU7hl/QQQhUw==,type:str]
        key-alias: ENC[AES256_GCM,data:nKu7eE2IcxKWBQ==,iv:qK5ZhSjb/UTNlvfsX7otw7Kyv9oB7luzIx4QXWUzQxo=,tag:24Sj2v84t3R5fhceyapc1A==,type:str]
spring:
    application:
        name: Replay
    server:
        servlet:
            encoding:
                force-response: true
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC[AES256_GCM,data:S3JdHCyKa8IaZ+LUfjPln6jdm+eyBUllSOIaVCzAkuMQgRHpdftNcotVATLxSpWtQKQ=,iv:5jboxvfgBGu1zqACg2PEOzAwuF18preoLXVRo/Ax3BQ=,tag:rA/yVPiB6jv+HQhqOalGeg==,type:str]
        username: ENC[AES256_GCM,data:U1W0K4hr,iv:xTtTWBeFQmJ3h+ZfBmNGPgb8WV7+e63dWjgGll/ttE0=,tag:5B/Ph3cJqaRxHpMJwelchQ==,type:str]
        password: ENC[AES256_GCM,data:vUkmXnPAWHg6GHs=,iv:sYQAH+LriJYImqQlXLY1k5AfmsCaG1QzepsBf5ueIUY=,tag:XUSY9fBcQ7AiiKqj3g5m+A==,type:str]
    data:
        redis:
            host: ENC[AES256_GCM,data:FLJxIORQmSDrTzYGCW81SlosTH5e,iv:mGWm+RfSQK646Y/SYaoUxE0sJfrXlPngJ/eQJn0gK74=,tag:cO78uRTuTqyqmA7katpEmg==,type:str]
            password: ENC[AES256_GCM,data:KlcCAxQ1c7rAee8=,iv:8KjsUEN/WbGxMz8mob8ztWeb9cuZ7/tIuzrxbCxVraM=,tag:XcVwglmJIoNahxkxdyGbmQ==,type:str]
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    level:
        org.hibernate.SQL: debug
        root: info
        org.springframework.web: info
        org.springframework.security: ENC[AES256_GCM,data:48fptow=,iv:h0j4TBHZggJiziRCcJw0JuEQ9WhS5J5uKQvD+p9TBQo=,tag:Jx4t6+wAm/hzooj65ssjOg==,type:str]
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        org.hibernate.tool.hbm2ddl: debug
management:
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus,info
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
    info:
        git:
            mode: simple
        java:
            enabled: true
app:
    domain:
        frontend: ENC[AES256_GCM,data:yeOHjmCjKSl+6X9W/9nYqf6AmewT7OvkCBIp,iv:vfMVFrBuG7gG6gxasBSJ9ozaC2iEc+eQ6LawZ5EafeU=,tag:+sh18Ki5T4nD+GAYM++I2A==,type:str]
oauth:
    naver:
        redirect-uri: ENC[AES256_GCM,data:Bay1VJ5rV7GuSE193KALqyB/oSxf+H3D9FcQ1JETaYwhVGe+BmidLa0qDtL7yn4HypsRsPIt,iv:9/Ng3j6J8SOCAOaNbsdf0KweO3NNSc60enRwEk8oVL0=,tag:JswiX6+RpvmyEgdv2bcOig==,type:str]
    google:
        redirect-uri: ENC[AES256_GCM,data:IVsPJKxdjxqFpTw0GTaILsCbsV7cKKeAEJNh+/s2ixpRSVlnD+tQykDjRXamR2O3oqXDQYrJZA==,iv:eOnqeX/lZ1oWw+63bFUeyfAdOvO9Vmw91OCi0uTfmSc=,tag:vwmxQ/pdhEl3NsDPSJQGoQ==,type:str]
    kakao:
        redirect-uri: ENC[AES256_GCM,data:q0HLsCrrcqXhwaTqLA+gXkWDA50IPLdGv3w1orTf2Cr3sjK+eZGplsMaMnJ2gG2IqzjJYhRJ,iv:bxlCUs9FYRnDjfPwrQdKwdHz9rbK6FxfCTwybpwdF0Q=,tag:arX6WNehbaI+vpoyMvVxgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-26T16:18:58Z"
    mac: ENC[AES256_GCM,data:StnfsAx7/GOLJQY+FunILL3xJ5fO0QpTOzMJ6hBXuN1J7J15fotM9Gy5RRLAIX+KAgBEi80KywLIeWcos5SHgiUHINIUo75LrsGXoGaOd7pwwnKhsvI6//5fwXDJRkQfRcHZVAhNkpo5HoCF0JzapZdf7i4aEQ4fYX8toNzxldQ=,iv:3qG0O0oM0/OdKzDH61xHkRfZ6/YtXfHtHefZlAQ9FzY=,tag:Necq5oEU43kV5E8qmuJfKQ==,type:str]
    pgp:
        - created_at: "2025-04-26T16:18:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAAkfcwRdHqE7tVt4tEh3kpisNLjpQkycvKtbuQ0rGlQN4o
            KQJSGDMhjqAA68qDjG+Vyde0xRYBr7LVJFyHvWgi6/prUJXv+v4pUEo2nrRtbvgi
            LK0PnQndHHL1JK7yllTo+rymmVIDRXd1aT1nY6t1wUauVOt15dKfurppk+zfP9MW
            G8Hmx/VtGU22R/dllcVSt/4S8IP1EnDi2zxEklNYAhySJctSEdY2zJL/4FsbjRrH
            Bk7Cc5Bysj0k/FZT4tbse/38kz86illSySmhdQ/rGdc0kDKeKsMl+uyFNY276H05
            E3kSXXBBnyNwGRy8gFElkiDCnv5EJSZm77tcWreW0THuCub29y0HS1+vJszBhpBE
            6n3otngbQFOq3ZFPOxfKapEI5gXJEpsUfpogVSIJtGVxjTgNRsThVn2/mxGIU+yS
            8oKfJL46Xk+Hbkcm84Akzs3c1z9I7uCkR7j3KGwJadhl+bESm1uz36NX971lvEgx
            NWrUdrYDFL1cvCP4yC6dUnCP8tqZJq4DdOWZbdDcgZM+VSe7JFrgBBwN65BbFmmi
            WMB2J4a7VcBqJ05ZlskpQ46LIE6YQbjuLf7d+4lNrPQRNcQYhe0pROX7WHAiHOIu
            Olj4cCWEUKZ7a4SjVAQ9itTdXJ7zu3NdqY2euBnaSCjdqgGCFaNk02P9FrB2tafS
            XgE/WhqFaYN1Mfs9JnN6YWgmoOwTkPd49YsnTLD2BTMNWhLe5dfws0hA8uY58Oi1
            WDeLp+RhQCdfKGAFxyi61uiSxDtsv+uNom/KPTDRoCag+7a+FwnfHtmD9IgRGJw=
            =0ZsM
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
