spring:
    profiles:
        active: local
jwt:
    secret: ENC[AES256_GCM,data:w+qmrmiQMxWwBGzlPokQKBLqMhCtkuDX0Y+o0CZ1BNK3pmRsmOGExMSNedQ=,iv:kxIPkT23dMARqzfX5UTw1NAQvPLSdL852M/o1n5/Q7Y=,tag:YwHVkQfl2AVJtqOI5MlmVA==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:Dv0l,iv:IQeIfFKivLeUZeM1QqunMhLB7rYgshA5C1eUXm4pZAA=,tag:4VLG/Tuvaj1VVd+SF5KJaA==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:RRg=,iv:hppj4K5v509HjfvTEQJ2moY+dHJ/iyXNH19H1n7Y+BY=,tag:FEaJYpbctGcjKOQsXPUHRA==,type:str]
app:
    domain:
        cookie: ENC[AES256_GCM,data:ltAEDEPXuG/vjeKjFRunzQ==,iv:Aj2CI/G8pG8F3jmEoqartb7UCF2m/uv9yK+zqAk1nrI=,tag:PiPoclHOmKcMthYR2n/xmQ==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:tBo/oheXr1kdSsUhIPrf3YXbXdw=,iv:6RSGhv5RE6xDeTjpJ4Jn2XeFhuRL1XUooHWHahdTncw=,tag:iZBRydmFW0s7bA9q3e2RHQ==,type:str]
        client-secret: ENC[AES256_GCM,data:dyuMz+5jWKwrQg==,iv:71xcYWApmtkxLEdPp6BEXDiVm++JOSAs0clmWO9zsA0=,tag:x6amJQekayTGH1WqlPFWrA==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:i2w/GiUp6V4GKVzUKFMLgwOVpzNxBbbYGs6pIeXVTyFxk6qud19FPqDmNT02rLWOpWSXclBeUClBvkorpCdaPJCxWv7mpuhS,iv:o2uaqJW6jon/TaG3EHHHgXA/+YTH7No8mpxo3MefFRo=,tag:2hI4eD/1zXtcZl5PH66u8w==,type:str]
        client-secret: ENC[AES256_GCM,data:o8UGhtccq9ak1BlgqIhStqo4VHE7rJVCD4sdEMgucME3lgI=,iv:sb4DXyc0RAzBMTWTU0VAM9k/OxSpz+mUh6VsLTTTTUU=,tag:X0rcJt2lIqeN15pJ11QKVQ==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:IFOUFeug+EF6CHRV1gcrsxiNgxrkLpbO28DfilIFEds=,iv:VyH7MfkWCMlp/7CxV8ZwKn5Z+2qqBorsHDeW0n+orHY=,tag:qUvF0lGTvSitL97RupYImw==,type:str]
        client-secret: ENC[AES256_GCM,data:b6o0w+GpRTKfKJIDClCy2DoByeAHWqqk9SeJMqX0+Xw=,iv:MSS+TLMu0MEEOcMdI5T5W0bPkK3N/hFZgvEBmk1T6ZI=,tag:fIhmofJ8fr3ncxHRv0N2sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-26T16:18:58Z"
    mac: ENC[AES256_GCM,data:OndyuIimct2hkiAiWsJZ+gHVHDsYmVnyCIzjdahsV+32ucWY8Mf8t/Y4m2d+b9bSYyklSEY5duH9XDylRTQ906z+k61RIS4pn5/u7ooepVyUF3EOp5IlmyQRh8kjzaf3UPzXeN00eL3dXMqq6oGUItul9uEoG/s6ZwpLIzkysok=,iv:p0uiyaXXQdIJl4kj5glGyMgfYxsECTU4zBhd/XetJKY=,tag:VJByq0HOMc6lPIQjcDLRKQ==,type:str]
    pgp:
        - created_at: "2025-04-26T16:18:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRARAA8T7+O3iAIUd78nTu0wuHFg4TEfM7ts4nY3u/BnTFlqR4
            RJ1gbgZZwGy+b/cqECuBOWC7hrF8QTUtqsRlh0NqVOZ04cfkx9SIf1SOR2GQ4d5V
            lZVsBW90ajtP+LLtlmOBcJrInq1XiGo4CtMEfjbDZz2O1z4ifiuJ4EyBow9atVB4
            jgM+v6oTOV9+RSJ2BwLsi51kaJtX6WbUlXnTwIZOiOsuCENA2XY46QvXl7BSqiyp
            MGIC1dq7LXwMOw+MsevO2ZBV6IZPvZb5PQoXoYQilNCkYJpmo9hurJgfLPuDD6lM
            q9NkIVMGycwfuoZXcFDZktem+iC14ZMzPdZKPrgeCX84uW6y9/K+u34kLlUzjWGd
            Is4KUTA7l/rx26shGGk62vkH+JK47XFqWkNrSUk+bbeeOFKFxlIxyHfT8zJbPAr9
            Kl9G7ZVZet+rwSBLPWYRbXFKIzmszY99ZVeZpano/M6x6cS+HtbzYx374mMbhENJ
            Ma+7CGOeUGR2nGg7NEezj9Qtp3DRWxzygFhGRcMOVx7glRDsYT604z9Vc44dQPF4
            8rPcKPJJbm2BbW13PYWHJbCzZ13gIsKlpK5Crjeh/5wSuAgL2uM2DsrK0AFVNNfv
            job1b5uLIRxvMQidRMuhrg3eoX4AZRj5+N2mXZTIgydfl8++eYVl4C7Edtmc5bfS
            XAGGNEPfITcAAVtZzS80YTJV40DeHNo+Sel+r+kwUINIObspgz6PhaYL0qwUCmRM
            Z+BR7mIz2atq2k2sSF4yiVdloV2D5LLm51qdQcWtnNfRaaybDeACgXGFx9pb
            =VpKa
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
