spring:
    application:
        name: Replay
    profiles:
        active: local
    jackson:
        serialization:
            write-dates-as-timestamps: false
    sql:
        init:
            mode: always
            schema-locations:
                - classpath:db/migration/postgresql/V1__create_table.sql
                - classpath:db/migration/postgresql/V2__create_view.sql
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: phanes.replay.user.dto.user.query
jwt:
    secret: ENC[AES256_GCM,data:sXI+aQ2TsANSxSR8fn2k/WwUUy7mTiRvPGz5UTC1TeYXhggwEC4b6hHBCTg=,iv:xJQDEZKud/xJMu0a0W64ImGoKLbFH9TJkuq8gorR884=,tag:Isd5IxJMxOu6ntV62KcrCQ==,type:str]
    access-token:
        expire-time: ENC[AES256_GCM,data:Ggec,iv:C5N2yavYqw4Z7oe5uIm3adlTE9QZdgrhYLqYqlAxf6Q=,tag:givWUEUzfD7zGFHZKgu8AQ==,type:str]
    refresh-token:
        expire-time: ENC[AES256_GCM,data:Kg4=,iv:GCMQwkJ6e/HGZUqTJogEAQx762ms9QIZkScRhLSwEws=,tag:mNO4FR91YOMsri4GoJ5MCQ==,type:str]
oauth:
    naver:
        client-id: ENC[AES256_GCM,data:hYvSLO0WtFZKzzgM8qMc1j3rilU=,iv:1C9UMJPM/7K/p+wqdDo6jt3ES9M23m2mwJZZD7GNV3s=,tag:ec/3EGHhZuM+iw4U5WL47w==,type:str]
        client-secret: ENC[AES256_GCM,data:JoITFL5QiVIJMA==,iv:eiRxnze/Xxn6AA2fO0Q9pBpowpF7LNiTjpDPYkQTSJw=,tag:G2cbmnwrYd7Wb+KPfAJv1g==,type:str]
    google:
        client-id: ENC[AES256_GCM,data:08hYXMyoKzMEQYi2of6AYjIF1//YVuVz7cWfZvoFZO0bEb+pxLM3ChlnvJk9LxXPc1D8ZbcdEQieBa5OetqqBEOqynQyV5L5,iv:RGQ+k85LQTwEKqrhTtyxrJRgL6puilpm7e1woV/Y+Cs=,tag:EGNX/l5YmDOt0nhqQXG5Bg==,type:str]
        client-secret: ENC[AES256_GCM,data:TL6e2mJdKrevFpPgh21NpY0bwQfhPunI9pljgkcBzgGjdp8=,iv:PmgXrKamN2PyCBEDL7d/3VujpuL2h0ft7tYXOQ4/3pY=,tag:69Dagsh2i69z1E4rj/PHhQ==,type:str]
    kakao:
        client-id: ENC[AES256_GCM,data:xu3LBlI8kCvLmFN4BnnWAVbrlI1LW0Q7J6QPyf6Jfc4=,iv:9V5JhNHUfQJ3Sll0SNMHfSms8b0s29lzuuS5Qu5+Kr0=,tag:/PPI3FGHVRrKf8qvUuoQVw==,type:str]
        client-secret: ENC[AES256_GCM,data:T4a30tN4TFVch+4t5ZchpJSsyAG/bfjQtw1XYl20Aiw=,iv:+ZoXlYz5jCqmT3+MpO/bzQe3JhmqqUq12eV8j+T7W2w=,tag:A+aY2gB93Ffs1S2yXJZhvA==,type:str]
s3:
    bucket: replay
    endpoint: ENC[AES256_GCM,data:pvx655pfdJI+YMQ2yeNNdXi7o/6iIMtPtsJXQy54stB5,iv:Vvpo8CC4G8mr0lSFoCrND1ocQnt9ktNjfgcYNy5ZOJc=,tag:NP9NIs+3rzhIVt0ZCTLTvQ==,type:str]
    access-key: ENC[AES256_GCM,data:if/ULU7WYmO25F0YhUG9KNukz8I=,iv:7i67I0+fwXBMeSQQXHqIQ9JRQE+s+zo11hSbrf4MPLE=,tag:xN4D8bGH9LQTXKpTvjTorg==,type:str]
    secret-key: ENC[AES256_GCM,data:24toYdGaYraFiTEv6/L4uGbF7l8Bm5jCuqw343Vr10TjdRawdgJQzQ==,iv:U0Gb0NkAuDmokYuK5kPcZathDxYhco2Cx+CrcEWtfVw=,tag:RGVt/FTrkTejOwzGTPmlww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-18T12:28:35Z"
    mac: ENC[AES256_GCM,data:tR0bof69R9em4BQxTQiTjrSCOZwxfPZCdAAT4n9ZH7HzKPzeHjB0+wCscXzmP/gPeR9gpbfkQWMitzXNNdJbcCgmg9gScQoT/5teSox+Dmp3TdmFpruklZqrpfU3IviN1fwP1wqUQ8WlgF+JOZJKW5I019/BrACxQ+PVpRmDd9I=,iv:sNs+mwpyr6YpL24I62ymOz8JHyefienu1FzuCbd2YMc=,tag:gwvdsu+HwwjDpW+7q6vyXQ==,type:str]
    pgp:
        - created_at: "2025-05-18T12:28:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0pEQ+ak5/eRAQ/+Lyul+ThhaHyd1suTiqTqt6LZpghciQStJkymcee7TI41
            PUroO4I0RFpsqP+taDz+subyyGugrbXGzZTYLDiHP6RH1gcwg+1sug+upcTfpeuA
            ff2DtGDZZYa/8Bm56PUUcbJURppDtGhmoqqyYyc6DaUF8XbMbM0ggVBdL6R8gP5L
            Q90nTGzQ2knsuoxVBdxwnMJ5X20D+b58dnb9gRPJbZ74IJW2O+WQ8x4ZWIEkzVhY
            IxMJ1BGFw4z4CkIcoGT6+KMFV/oe3awqc8ej410hL3seV2/L8do+zOZRSD74Si2F
            QeUPeWe03draCMgSIkkpQQZbU3sqQnBlRhDyivZ5DIja+AMetTG8aOGvxbsnFy/A
            4+tkuY48lmw9mWjTiIKvjU+Y/GREeD0mqodU7PHXg+3uZoXKwj8+mG/GdU2qoiTm
            BAEFoQ9579nDvMvg3WUAB1cudk99qcmIGM0RKMaIjlFTfInDI69OH/2TDq4cm1iq
            4hvQOJMUz0kE9bXdDLjBXxTG51Fpna66GZfouSM7hTpOkHRpUq42ahnFcqZusV7P
            5KVM+79nbKfbA3c2vsqwHCxygZs0KKJlfWJV7e1d5IKkVBYnAE9i1d1y2hjtweOc
            xi+bAmKT7gtYJ0zbiuQyk9MnNhKfrH8gEgL140hEpqycc0VFUO9r/fJtzDWj4ubS
            XgF9qpPBBiu1UXU8yyYPtACsP/psHEYaUKGAj2Xrkgy+is190RiFwRYZurfu+u5A
            6L6dR3v6h33CMA+in9kY2KEDl+eYnO9Ne7pLR4zyJDv3xVyMFh2q+ge0MyUzOP8=
            =9kc6
            -----END PGP MESSAGE-----
          fp: B57822CEBBF7C27C196DB7D3D9DF0BD2C91CBE98
    encrypted_regex: ^(?i)(.*(_)?(password|secret|token|endpoint|key|client.?id|uri|url|username|host|domain).*)$
    version: 3.9.3
